""" Introduction
K-means is a widely used unsupervised machine learning algorithm for clustering datasets, which works by dividing the data into k clusters based on their similarities.

How K-means Works 123
K-means clustering starts by initializing k cluster centers, called centroids, which can be selected from the data points or generated randomly. Each data point is then assigned to the nearest centroid based on a distance metric, such as Euclidean distance. The algorithm iterates between assigning each data point to the closest cluster center and setting each cluster center as the mean of the data points assigned to it. This process is repeated until the centroids become relatively stable.
 """
from sklearn.cluster import KMeans
import numpy as np

# Initialize k-means with 3 clusters
kmeans = KMeans(n_clusters=3)

# Generate some sample data
data = np.random.rand(100, 2)

# Fit the model to the data
kmeans.fit(data)

""" Code sample generated by AI. Please double-check responses.

Advantages and Limitations 145
K-means clustering has several advantages, including its simplicity and efficiency. However, it also has some limitations, such as requiring the number of clusters to be predefined. Additionally, k-means may not work well with complex shapes or noise in the data.
 """
# Example of k-means clustering with scikit-learn
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Generate some sample data
data, _ = make_blobs(n_samples=200, centers=4, n_features=2, random_state=1)

# Initialize k-means with 4 clusters
kmeans = KMeans(n_clusters=4)

# Fit the model to the data
kmeans.fit(data)

# Plot the clusters
plt.scatter(data[:, 0], data[:, 1], c=kmeans.labels_)
plt.show()
# Code sample generated by AI. Please double-check responses.

# Real-World Applications 25
# K-means clustering has many real-world applications, including customer segmentation, image compression, and gene expression analysis. For example, Netflix uses k-means clustering to recommend movies and shows to users based on their viewing history.

# Example of using k-means for customer segmentation
from sklearn.cluster import KMeans
import pandas as pd

# Load the customer data
data = pd.read_csv('customer_data.csv')

# Select the relevant features
features = data[['age', 'income', 'spending']]

# Initialize k-means with 3 clusters
kmeans = KMeans(n_clusters=3)

# Fit the model to the data
kmeans.fit(features)
