-- customer order line iteration 2026-01-21
-- template parameters
DECLARE @StartDate DATE = '2026-01-01';     

WITH CTE_BASE AS
	(	SELECT A.*
		, SHIPPED_QTY * UNIT_PRICE AS SHIPPED_AMOUNT
		, UNSHIPPEDQTY * UNIT_PRICE AS UNSHIPPED_AMOUNT
		, CONVERT(DATE, DATEADD(DD, REASONING, DESIRED_SHIP_DATE)) AS ADJUSTED_DUE_DATE
		, CASE
			WHEN DSL.SUPPLY_TYPE = 'CP' THEN 'CP'
			ELSE 'WO'
		END AS SUPPLY_TYPE
		, WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID
		, CASE
			-- tt20210125 
			WHEN CO_STATUS = 'H' AND TOTAL_SHIPPED_QTY = 0 AND UNSHIPPEDQTY = 0 THEN 'ON HOLD???'   --> 436527/10 SHIPSHORT BUT 0 SHIPPED
			WHEN CO_STATUS = 'X' THEN 'CANCELLED'
			WHEN ORDER_QTY = '0' THEN 'CANCELLED'
			WHEN CO_STATUS = 'C' AND TOTAL_SHIPPED_QTY = 0 AND UNSHIPPEDQTY = 0 THEN 'CANCELLED'
			WHEN SHIP_SHORT = 'C' AND TOTAL_SHIPPED_QTY = 0 AND UNSHIPPEDQTY = 0 THEN 'CANCELLED'
			WHEN SHIP_SHORT = 'C' AND TOTAL_SHIPPED_QTY > 0 AND UNSHIPPEDQTY = 0 THEN 'COMPLETED'
			WHEN (TOTAL_SHIPPED_QTY - ORDER_QTY >= 0) AND (UNSHIPPEDQTY = 0) THEN 'COMPLETED'
			WHEN UNSHIPPEDQTY > 0 THEN 'INCOMPLETE'
			ELSE 'INCOMPLETE'
		END AS ORDER_STATUS
		FROM 
		(	SELECT CO.CUSTOMER_ID 
			, CO.ID AS CUST_ORDER_ID
			, COL.LINE_NO AS COL_LINE_NO
			, CONVERT(DATE, CO.ORDER_DATE) AS ORDER_DATE
			, CONVERT(DATE, CO.CREATE_DATE) AS CREATE_DATE
			, CONVERT(DATE, ISNULL(COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE)) AS DESIRED_SHIP_DATE
			, CASE
				--> tt20210125: handle COL with 0 qty that were not deleted, cancelled, or shipped
				WHEN COL.ORDER_QTY = 0 THEN 'COL.ORDER_QTY = 0'
				WHEN CO.[STATUS] = 'C' THEN 'CO.[STATUS] = C'
				WHEN COL.ORDER_QTY - COL.TOTAL_SHIPPED_QTY > 0 THEN 'COL.ORDER_QTY - COL.TOTAL_SHIPPED_QTY > 0'
				WHEN COL.TOTAL_SHIPPED_QTY > 0 THEN 'COL.TOTAL_SHIPPED_QTY > 0'
				WHEN S.SHIPPED_DATE IS NOT NULL THEN 'S.SHIPPED_DATE IS NOT NULL'
				WHEN COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) <= GETDATE() THEN '<= GETDATE()'
				ELSE 'ELSE'
			END AS FILTER_CASE
			, CONVERT(DATE, CASE
				--> tt20210125: handle COL with 0 qty that were not deleted, cancelled, or shipped
				WHEN COL.ORDER_QTY = 0 THEN COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE)
				WHEN CO.[STATUS] = 'C' THEN COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE)
				WHEN COL.ORDER_QTY - COL.TOTAL_SHIPPED_QTY > 0 THEN COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE)
				WHEN COL.TOTAL_SHIPPED_QTY > 0 THEN COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE)
				WHEN S.SHIPPED_DATE IS NOT NULL THEN S.SHIPPED_DATE
				WHEN COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) <=  GETDATE() THEN GETDATE()
				ELSE COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE)
			END) AS FILTER_DATE
			, CO.[STATUS] AS CO_STATUS
				--	, COL.SERVICE_CHARGE_ID
			, CASE
				WHEN COL.SERVICE_CHARGE_ID IS NOT NULL THEN '' 
				WHEN COL.PART_ID IS NULL AND COL.MISC_REFERENCE IS NOT NULL AND P2.ID IS NOT NULL THEN 'PART UPDATE'
				WHEN CHARINDEX('PROGRAMMING', COL.MISC_REFERENCE) > 0 THEN 'CHARGE UPDATE'
				WHEN CHARINDEX('NRE PROIGRAMMING', COL.MISC_REFERENCE) > 0 THEN 'CHARGE UPDATE'
				WHEN CHARINDEX('NRE PROFGRAMMING', COL.MISC_REFERENCE) > 0 THEN 'CHARGE UPDATE'
				WHEN CHARINDEX('NRE VOI', COL.MISC_REFERENCE) > 0 THEN 'CHARGE UPDATE'
				WHEN CHARINDEX('SHIPPING CHARGE', COL.MISC_REFERENCE) > 0 THEN 'CHARGE UPDATE'
				WHEN CHARINDEX('EXPEDITE', COL.MISC_REFERENCE) > 0 THEN 'CHARGE UPDATE'
				WHEN CHARINDEX('SHIPPING CHARGE', COL.MISC_REFERENCE) > 0 THEN 'CHARGE UPDATE'
				WHEN CHARINDEX('WA State Sales Tax', COL.MISC_REFERENCE) > 0 THEN 'CHARGE UPDATE'
				WHEN CHARINDEX('FAI CHARGE', COL.MISC_REFERENCE) > 0 THEN 'CHARGE UPDATE'
				WHEN CHARINDEX('FAI COST', COL.MISC_REFERENCE) > 0 THEN 'CHARGE UPDATE'
				WHEN CHARINDEX('DELIVERY FEE', COL.MISC_REFERENCE) > 0 THEN 'CHARGE UPDATE'
				ELSE ''
			END AS UPDATE_USING_MISC_REF
			, CASE
				WHEN COL.SERVICE_CHARGE_ID IS NOT NULL THEN COL.SERVICE_CHARGE_ID 
				WHEN CHARINDEX('PROGRAMMING', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('NRE PROIGRAMMING', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('NRE PROFGRAMMING', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('NRE VOI', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('SHIPPING CHARGE', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('EXPEDITE', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('SHIPPING CHARGE', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('WA State Sales Tax', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('FAI CHARGE', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('FAI COST', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('DELIVERY FEE', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				ELSE ''
			END AS SERVICE_CHARGE_ID
			, CASE
				WHEN COL.SERVICE_CHARGE_ID IS NOT NULL THEN 'SERVICE CHARGE'
				--> tt20210201
				WHEN CHARINDEX('NRE PROGRAMMING', COL.MISC_REFERENCE) > 0 THEN 'SERVICE CHARGE'
				WHEN CHARINDEX('PROGRAMMING', COL.MISC_REFERENCE) > 0 THEN 'SERVICE CHARGE'
				WHEN CHARINDEX('NRE PROIGRAMMING', COL.MISC_REFERENCE) > 0 THEN 'SERVICE CHARGE'
				WHEN CHARINDEX('NRE PROFGRAMMING', COL.MISC_REFERENCE) > 0 THEN 'SERVICE CHARGE'
				WHEN CHARINDEX('NRE VOI', COL.MISC_REFERENCE) > 0 THEN 'SERVICE CHARGE'
				WHEN CHARINDEX('SHIPPING CHARGE', COL.MISC_REFERENCE) > 0 THEN 'SERVICE CHARGE'
				WHEN CHARINDEX('EXPEDITE', COL.MISC_REFERENCE) > 0 THEN 'SERVICE CHARGE'
				WHEN CHARINDEX('SHIPPING CHARGE', COL.MISC_REFERENCE) > 0 THEN 'SERVICE CHARGE'
				WHEN CHARINDEX('WA State Sales Tax', COL.MISC_REFERENCE) > 0 THEN 'SERVICE CHARGE'
				WHEN CHARINDEX('FAI CHARGE', COL.MISC_REFERENCE) > 0 THEN 'SERVICE CHARGE'
				WHEN CHARINDEX('FAI COST', COL.MISC_REFERENCE) > 0 THEN 'SERVICE CHARGE'
				WHEN CHARINDEX('DELIVERY FEE', COL.MISC_REFERENCE) > 0 THEN 'SERVICE CHARGE'
				WHEN COL.PART_ID IS NOT NULL THEN 'PART PROCESSING'
				--> TT20210201: WHEN PARTS ENTERED INTO COL.MISC_REFERENCE BUT NOT COL.PART_ID
				WHEN COL.PART_ID IS NULL AND COL.MISC_REFERENCE IS NOT NULL AND P2.ID IS NOT NULL THEN 'PART PROCESSING'
				ELSE 'OTHER'
			END AS LINE_TYPE
			, CASE
				WHEN COL.SERVICE_CHARGE_ID IS NOT NULL THEN COL.SERVICE_CHARGE_ID
				WHEN CHARINDEX('PROGRAMMING', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('NRE PROIGRAMMING', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('NRE PROFGRAMMING', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('NRE VOI', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('SHIPPING CHARGE', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('EXPEDITE', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('SHIPPING CHARGE', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('WA State Sales Tax', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('FAI CHARGE', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('FAI COST', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('DELIVERY FEE', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				--> TT20210201: WHEN PARTS ENTERED INTO COL.MISC_REFERENCE BUT NOT COL.PART_ID
				WHEN COL.PART_ID IS NULL AND COL.MISC_REFERENCE IS NOT NULL AND P2.ID IS NOT NULL THEN P2.ID
				ELSE COL.PART_ID
			END AS LINE_ITEM
			, CASE
				WHEN COL.SERVICE_CHARGE_ID IS NOT NULL THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('PROGRAMMING', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('NRE PROIGRAMMING', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('NRE PROFGRAMMING', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('NRE VOI', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('SHIPPING CHARGE', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('EXPEDITE', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('SHIPPING CHARGE', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('WA State Sales Tax', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('FAI CHARGE', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('FAI COST', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				WHEN CHARINDEX('DELIVERY FEE', COL.MISC_REFERENCE) > 0 THEN COL.MISC_REFERENCE
				ELSE ''
			END AS CHARGE_TYPE
			, CASE
				WHEN COL.SERVICE_CHARGE_ID IS NULL THEN COL.MISC_REFERENCE
				ELSE ''
			END AS CUST_PART_DESC
			, COL.PART_ID AS 'COL_PARTID'
			, P2.ID AS 'P2ID'
			--> TT20210201: WHEN PARTS ENTERED INTO COL.MISC_REFERENCE BUT NOT COL.PART_ID
			, CASE
				WHEN COL.PART_ID IS NULL AND COL.MISC_REFERENCE IS NOT NULL AND P2.ID IS NOT NULL THEN P2.ID
				ELSE COL.PART_ID
			END AS 'PART_ID'
			, P.[DESCRIPTION]
			, P.PRODUCT_CODE AS 'PART_PROD_CODE'
			, P.COMMODITY_CODE AS 'PART_COMM_CODE'
			, P.PLANNER_USER_ID
			, P.BUYER_USER_ID
			, CASE
				WHEN P.PLANNER_USER_ID = 'FIN' THEN 1
				WHEN CO.CUSTOMER_ID != 'BOE609' THEN 0
				WHEN LEFT(P.BUYER_USER_ID,2) = '59' THEN 10
				WHEN LEFT(P.BUYER_USER_ID,2) = '09' THEN 30
				WHEN RTRIM(LTRIM(P.PLANNER_USER_ID)) = 'FIN-HOURLY' THEN 10
				WHEN P.PLANNER_USER_ID LIKE 'MFG-HOURLY%' THEN 30
				ELSE 0 
			END AS 'REASONING'
			, COL.LINE_STATUS AS SHIP_SHORT
			, COL.ORDER_QTY
			, COL.TOTAL_SHIPPED_QTY
			, COL.ORDER_QTY - COL.TOTAL_SHIPPED_QTY AS REMQTY
			, CASE
				WHEN COL.LINE_STATUS = 'C' THEN 0
				WHEN CO.[STATUS] = 'C' THEN 0
				WHEN COL.ORDER_QTY < COL.TOTAL_SHIPPED_QTY THEN 0
				ELSE COL.ORDER_QTY - COL.TOTAL_SHIPPED_QTY
			END AS UNSHIPPEDQTY
			, COL.UNIT_PRICE
			, CASE
				WHEN CO.CUSTOMER_ID != 'BOE609' THEN UDF.STRING_VAL
				WHEN LEFT(P.BUYER_USER_ID,2) = '59' THEN 'CMP-FIN'
				WHEN LEFT(P.BUYER_USER_ID,2) = '09' THEN  'CMP-MFG'
				WHEN P.PLANNER_USER_ID IN ('FIN', 'MFG', 'BUSSOL') THEN P.PLANNER_USER_ID
				WHEN P.PLANNER_USER_ID = 'FIN-HOURLY' THEN 'CMP-FIN'
				WHEN P.PLANNER_USER_ID LIKE 'MFG-HOURLY%' THEN  'CMP-MFG'
				WHEN LEFT(P.PLANNER_USER_ID,3) IN ('MFG') THEN 'CMP-MFG'
				WHEN COL.SERVICE_CHARGE_ID IS NOT NULL THEN 'SERVICE CHARGE'
				ELSE 'UNKNOWN'	END AS 'BUS_STREAM'
			, UDF1.STRING_VAL AS 'MATERIAL_TYPE'
			, S.PACKLIST_ID
			, SL.LINE_NO AS 'PACKLIST_LINE_NO'
			, CASE
				WHEN LTRIM(RTRIM(RIGHT(R.INVOICE_ID,1))) = 'M' THEN 0
				ELSE SHIPPED_QTY
			END AS 'SHIPPED_QTY'
			, CONVERT(DATE, S.SHIPPED_DATE) AS 'SHIPPED_DATE'
			, CONVERT(DATE, R.INVOICE_DATE) AS 'INVOICE_DATE'
			, ISNULL(RL.INVOICE_ID, '') AS 'INVOICE_ID'
			, ISNULL(RL.LINE_NO, 0) AS 'INVOICE_LINE'
			, ISNULL(RL.AMOUNT, 0) AS 'INVOICE_AMT'
			, CASE
				WHEN LTRIM(RTRIM(RIGHT(R.INVOICE_ID,1))) = 'M' THEN 0
				ELSE RL.QTY
			END AS 'INVOICE_QTY'
		FROM CUST_ORDER_LINE COL
		INNER JOIN CUSTOMER_ORDER CO WITH (NOLOCK)	ON CO.ID = COL.CUST_ORDER_ID
		LEFT OUTER JOIN PART P WITH (NOLOCK)		ON COL.PART_ID = P.ID
		LEFT OUTER JOIN PART P2 WITH (NOLOCK)		ON COL.MISC_REFERENCE = P2.ID
		LEFT OUTER JOIN SHIPPER_LINE SL WITH (NOLOCK)	ON COL.CUST_ORDER_ID = SL.CUST_ORDER_ID
			AND COL.LINE_NO = SL.CUST_ORDER_LINE_NO	AND SL.SHIPPED_QTY <> 0
		LEFT OUTER JOIN SHIPPER S WITH (NOLOCK)	ON SL.PACKLIST_ID = S.PACKLIST_ID
		LEFT OUTER JOIN RECEIVABLE_LINE RL WITH (NOLOCK)	
			ON SL.PACKLIST_ID = RL.PACKLIST_ID	AND SL.LINE_NO = RL.PACKLIST_LINE_NO
		LEFT OUTER JOIN RECEIVABLE R WITH (NOLOCK)	ON RL.INVOICE_ID = R.INVOICE_ID
		LEFT OUTER JOIN USER_DEF_FIELDS UDF WITH (NOLOCK)
			ON UDF.DOCUMENT_ID = CO.CUSTOMER_ID	AND PROGRAM_ID = 'VMCUSMNT'	AND UDF.ID = 'UDF-0000072'
		LEFT OUTER JOIN USER_DEF_FIELDS UDF1 WITH (NOLOCK)
			ON UDF1.DOCUMENT_ID = P.ID	AND UDF1.PROGRAM_ID = 'VMPRTMNT'	AND UDF1.ID = 'UDF-0000035'
		WHERE COALESCE(R.INVOICE_DATE, S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) >= @StartDate
		--	AND COL.ORDER_QTY != '0'
		--	AND CO.[STATUS] IN ('H', 'R', 'C')
	) A
	
	LEFT OUTER  JOIN DEMAND_SUPPLY_LINK DSL WITH (NOLOCK) ON DSL.DEMAND_TYPE = 'CO'
		AND DSL.DEMAND_BASE_ID = A.CUST_ORDER_ID AND DSL.DEMAND_SEQ_NO = A.COL_LINE_NO
	LEFT OUTER JOIN WORK_ORDER WO WITH (NOLOCK) ON DSL.SUPPLY_TYPE = 'WO' AND WO.[TYPE] = 'W'
		AND DSL.SUPPLY_BASE_ID = WO.BASE_ID AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
		AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
	
)	--CTE_BASE

--SELECT * FROM CTE_BASE 

, CTE_PIVOT AS
	(	SELECT BASE_ID, LOT_ID, SPLIT_ID, SUB_ID
			, [M] AS MFG_COUNT, [A] AS FIN_COUNT
			, [O] AS O_COUNT, [NULL] AS NULL_COUNT
		FROM (	SELECT WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID, 
					CASE
						WHEN ISNULL(SR.USER_1, '') = '' THEN 'NULL'
						WHEN ISNULL(SR.USER_1, '') = 'B' OR ISNULL(SR.SKILLS_TYPE, '') = 'A' THEN 'A'
						WHEN ISNULL(SR.USER_1, '') = 'ARCHIVED' THEN ISNULL(SR.SKILLS_TYPE, '')
						ELSE ISNULL(SR.USER_1, '')
					END AS SKILLS_TYPE
				FROM CTE_BASE WO WITH (NOLOCK)
				LEFT OUTER JOIN OPERATION O WITH (NOLOCK) ON WO.BASE_ID = O.WORKORDER_BASE_ID AND 
					WO.LOT_ID = O.WORKORDER_LOT_ID AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID AND WO.SUB_ID = O.WORKORDER_SUB_ID
				LEFT OUTER JOIN SHOP_RESOURCE SR WITH (NOLOCK) ON O.RESOURCE_ID = SR.ID
			) AS SOURCE PIVOT (COUNT(SKILLS_TYPE) FOR SKILLS_TYPE IN ([M], [A], [O], [NULL]) ) AS PIVOTTABLE
	)	--CTE_PIVOT

--SELECT * FROM CTE_PIVOT 

, CTE_BS AS
	(	SELECT B.*, P.MFG_COUNT, P.FIN_COUNT, P.O_COUNT, P.NULL_COUNT, 
			CASE
				WHEN B.BUS_STREAM = 'CMP-MFG' AND FIN_COUNT > 2 THEN 'CMP-MFGFIN'
				WHEN B.BUS_STREAM = 'CMP-FIN' AND MFG_COUNT > 2 THEN 'CMP-FINMFG'
				WHEN B.BUS_STREAM = 'MFG' AND FIN_COUNT > 2 THEN 'MFGFIN'
				WHEN B.BUS_STREAM = 'FIN' AND MFG_COUNT > 2 THEN 'FINMFG'
				ELSE B.BUS_STREAM
			END AS UPD_BUS_STREAM
		FROM CTE_BASE B WITH (NOLOCK)
		LEFT OUTER JOIN CTE_PIVOT P WITH (NOLOCK) ON B.BASE_ID = P.BASE_ID AND 
			B.LOT_ID = P.LOT_ID AND B.SPLIT_ID = P.SPLIT_ID AND B.SUB_ID = P.SUB_ID
	)	--CTE_BS

--SELECT * FROM CTE_BS

, CTE_REMAINING AS
	(	SELECT * FROM CTE_BS WITH (NOLOCK)
		where CO_STATUS = 'R' AND SHIP_SHORT <> 'C'
			AND ORDER_QTY > TOTAL_SHIPPED_QTY
			AND TOTAL_SHIPPED_QTY > 0
	)

, CTE_FULL AS 
	(	SELECT 'BASE' AS CTE, *
		FROM CTE_BS
		UNION ALL
		SELECT 'REMAINING' AS CTE , CUSTOMER_ID
			, CUST_ORDER_ID , COL_LINE_NO , ORDER_DATE, CREATE_DATE
			, DESIRED_SHIP_DATE, [FILTER_CASE], DESIRED_SHIP_DATE AS FILTER_DATE
			, CO_STATUS, [UPDATE_USING_MISC_REF], SERVICE_CHARGE_ID, LINE_TYPE
			, LINE_ITEM, CHARGE_TYPE, CUST_PART_DESC, COL_PARTID, P2ID, PART_ID
			, [DESCRIPTION], PART_PROD_CODE, PART_COMM_CODE, PLANNER_USER_ID
			, BUYER_USER_ID, REASONING, SHIP_SHORT, ORDER_QTY, TOTAL_SHIPPED_QTY
			, UNSHIPPEDQTY, REMQTY, UNIT_PRICE, BUS_STREAM, MATERIAL_TYPE
			, NULL AS 'PACKLIST_ID', NULL AS 'PACKLIST_LINE_NO'
			, NULL AS 'SHIPPED_QTY', NULL AS 'SHIPPED_DATE'
			, NULL AS 'INVOICE_DATE', NULL AS 'INVOICE_ID'
			, NULL AS 'INVOICE_LINE', NULL AS 'INVOICE_AMT'
			, NULL AS 'INVOICE_QTY'
			, SHIPPED_AMOUNT, UNSHIPPED_AMOUNT, ADJUSTED_DUE_DATE
			, SUPPLY_TYPE, BASE_ID, LOT_ID, SPLIT_ID, SUB_ID, ORDER_STATUS
			, MFG_COUNT, FIN_COUNT, O_COUNT, NULL_COUNT, UPD_BUS_STREAM
		FROM CTE_REMAINING
	)	--CTE_FULL

--, CTE_FINAL AS

	SELECT A.* 
		, MAX(DATEADD(DD,-(DAY(FILTER_DATE)-1), FILTER_DATE)) AS 'FILTER_PERIOD'
		, PSF.[Target] AS 'TARGET_GOALS'
	INTO #CTE_FINAL
	FROM CTE_FULL A
	LEFT OUTER JOIN [SQL-Bi-1].[LIVESupplemental].[dbo].[Plant_Shipment_Forecast] PSF WITH (NOLOCK)
		ON PSF.BusStream = A.BUS_STREAM AND PSF.[Date] = DATEADD(DD,-(DAY(A.FILTER_DATE)-1), A.FILTER_DATE)
	GROUP BY CTE, CUSTOMER_ID, CUST_ORDER_ID, COL_LINE_NO
	, ORDER_DATE, CREATE_DATE, DESIRED_SHIP_DATE
	, [FILTER_CASE], FILTER_DATE, CO_STATUS
	, [UPDATE_USING_MISC_REF], SERVICE_CHARGE_ID
	, LINE_TYPE, LINE_ITEM, CHARGE_TYPE
	, CUST_PART_DESC, COL_PARTID, P2ID
	, PART_ID, [DESCRIPTION], PART_PROD_CODE
	, PART_COMM_CODE, PLANNER_USER_ID, BUYER_USER_ID
	, REASONING, SHIP_SHORT, ORDER_QTY
	, TOTAL_SHIPPED_QTY, UNSHIPPEDQTY, REMQTY
	, UNIT_PRICE, BUS_STREAM, MATERIAL_TYPE
	, PACKLIST_ID, PACKLIST_LINE_NO, SHIPPED_QTY
	, SHIPPED_DATE, INVOICE_DATE, INVOICE_ID
	, INVOICE_LINE, INVOICE_AMT, INVOICE_QTY
	, SHIPPED_AMOUNT, UNSHIPPED_AMOUNT
	, ADJUSTED_DUE_DATE, SUPPLY_TYPE, BASE_ID
	, LOT_ID, SPLIT_ID, SUB_ID, ORDER_STATUS
	, MFG_COUNT, FIN_COUNT, O_COUNT, NULL_COUNT
	, UPD_BUS_STREAM, PSF.[Target]

    select * from #CTE_FINAL
