		/****** SEE:  UserDefinedFunction [dbo].[ufn_demand_supply]   
        
        
         ******/
        
        SELECT DISTINCT ISNULL(DSL.SUPPLY_TYPE,'CO') AS SUPPLY_TYPE, ISNULL(DSL.DEMAND_TYPE,'WO') AS DEMAND_TYPE,
		CL.CUST_ORDER_ID, CL.LINE_NO, CL.ORDER_QTY, CL.TOTAL_SHIPPED_QTY, CL.PART_ID, CL.UNIT_PRICE, 
		CL.LAST_SHIPPED_DATE, ISNULL(W2.BASE_ID,W.BASE_ID)+'/'+ISNULL(W2.LOT_ID,W.LOT_ID)+'/'+
		CAST(ISNULL(W2.SPLIT_ID,W.SPLIT_ID)AS VARCHAR) AS WORK_ORDER, ISNULL(W2.BASE_ID,W.BASE_ID) AS WO_BASE,
		ISNULL(W2.LOT_ID,W.LOT_ID) AS WO_LOT, ISNULL(W2.SPLIT_ID, W.SPLIT_ID) AS WO_SPLIT, CAST (0 AS INT) AS WO_SUB,
		CASE WHEN DSL.SUPPLY_TYPE IS NOT NULL THEN 'Y' ELSE 'N' END AS ALLOCATED, TRT.TRACE_ID, DSL.ALLOCATED_QTY, 
		DSL.RECEIVED_QTY, DSL.ISSUED_QTY, DSL.CREATE_DATE, DSL.[USER_ID]  
		FROM (CUST_ORDER_LINE CL 
        INNER JOIN CUSTOMER_ORDER CO ON CL.CUST_ORDER_ID = CO.ID)
		LEFT OUTER JOIN (
            --- Why does the structure of this sql not have a select statement before the from clause? It appears to be joining demand supply link to work order and then joining that to the main query. Is this a common structure for queries that need to pull from demand supply link?
                        DEMAND_SUPPLY_LINK DSL 
                        INNER JOIN WORK_ORDER W ON DSL.SUPPLY_BASE_ID = W.BASE_ID 
                        AND DSL.SUPPLY_LOT_ID = W.LOT_ID AND DSL.SUPPLY_SPLIT_ID = W.SPLIT_ID AND DSL.SUPPLY_SUB_ID = W.SUB_ID
                        AND DSL.SUPPLY_TYPE IN ('WO','CP')
                        ) 
        
        ON CL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID AND CL.LINE_NO = DSL.DEMAND_SEQ_NO 
		AND DSL.DEMAND_TYPE = 'CO'
		LEFT OUTER JOIN (SHIPPER_LINE SL INNER JOIN TRACE_INV_TRANS TRT ON SL.TRANSACTION_ID = TRT.TRANSACTION_ID
		INNER JOIN WORK_ORDER W2 ON TRT.TRACE_ID = W2.BASE_ID+'/'+W2.LOT_ID+'/'+CAST(W2.SPLIT_ID AS VARCHAR) 
		AND W2.SUB_ID = 0) ON CL.CUST_ORDER_ID = SL.CUST_ORDER_ID AND CL.LINE_NO = SL.CUST_ORDER_LINE_NO