Use
Live
go



Select 
S.PACKLIST_ID
,SL.LINE_NO
,CO.CUSTOMER_ID
,CO.ID
,COL.PART_ID
,format(S.SHIPPED_DATE,'MM/dd/yyyy') AS SHIPPED_DATE
,SL.SHIPPED_QTY
,COL.TOTAL_AMT_SHIPPED
,COl.UNIT_PRICE
,CO.TOTAL_AMT_SHIPPED
,C.NAME
,C.ADDR_1
,C.ADDR_2
,C.ADDR_3
,C.CITY
,C.STATE
,C.COUNTRY
,C.BILL_TO_ADDR_1
,C.BILL_TO_ADDR_2
,C.BILL_TO_ADDR_3


From 
	Shipper_line SL
		Left Outer Join Shipper S
			on S.PACKLIST_ID = SL.PACKLIST_ID
		Left Outer join CUST_ORDER_LINE COL
			on COL.CUST_ORDER_ID = SL.CUST_ORDER_ID
			and COL.LINE_NO = SL.LINE_NO
		left Outer jOin CUSTOMER_ORDER CO
			on CO.ID = COL.CUST_ORDER_ID
		Left Outer JOin CUSTOMER C
			on C.ID = CO.CUSTOMER_ID

Where 

S.SHIPPED_DATE >= '12/15/2025'
and S.SHIPPED_DATE <= '1/15/2026'

