
declare @PACKLIST_ID nvarchar(50) = NULL;
declare @TOPPER int = 1; --1000000

/**********************************************************************************************
Description:
Sample:
Date      Modified By      Change Description
---------- ------------------ ------------------------------------------------------------
1447859 test
**********************************************************************************************/
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DEADLOCK_PRIORITY LOW
IF OBJECT_ID('tempdb..#Results') IS NOT NULL DROP TABLE #Results

-- wpould you create a create table for #tmpShipper and use the correct table ddl to create the table and insert the data into it.
IF OBJECT_ID('tempdb..#ShipperContents') IS NOT NULL DROP TABLE #ShipperContents
CREATE TABLE #ShipperContents (
    PACKLIST_ID NVARCHAR(15) NOT NULL,
    SUPPLY_BASE_ID NVARCHAR(30) NOT NULL,
    SUPPLY_LOT_ID NVARCHAR(15) NULL,
    SUPPLY_SUB_ID NVARCHAR(3) NULL,
    SUPPLY_SPLIT_ID NVARCHAR(3) NULL,
    TRANSACTION_ID INT NULL,
    TRACE_ID NVARCHAR(30) NULL,
    PART_ID NVARCHAR(30) NULL,
    USER_1 NVARCHAR(80) NULL,
    USER_2 NVARCHAR(80) NULL,
    USER_3 NVARCHAR(80) NULL,
    USER_4 NVARCHAR(80) NULL,
    USER_5 NVARCHAR(80) NULL,
    USER_6 NVARCHAR(80) NULL,
    USER_7 NVARCHAR(80) NULL,
    USER_8 NVARCHAR(80) NULL,
    USER_9 NVARCHAR(80) NULL,
    USER_10 NVARCHAR(80) NULL,
    CUST_ORDER_ID NVARCHAR(15) NOT NULL,
    CUST_ORDER_LINE_NO SMALLINT NULL,
    CUSTOMER_PART_ID NVARCHAR(30) NULL,
    CUSTOMER_PO_REF NVARCHAR(40) NULL,
    CUSTOMER_ID NVARCHAR(15) NOT NULL,
    SHIP_TO_ADDR_NO INT NULL,
    CUST_POLN_PRINT NCHAR(1) NOT NULL,
    CUST_PO_LN NVARCHAR(80) NULL,
    WO_SHIPPED_QTY DECIMAL(20,8) NOT NULL
)

INSERT INTO #ShipperContents (
    PACKLIST_ID,
    SUPPLY_BASE_ID,
    SUPPLY_LOT_ID,
    SUPPLY_SUB_ID,
    SUPPLY_SPLIT_ID,
    TRANSACTION_ID,
    TRACE_ID,
    PART_ID,
    USER_1,
    USER_2,
    USER_3,
    USER_4,
    USER_5,
    USER_6,
    USER_7,
    USER_8,
    USER_9,
    USER_10,
    CUST_ORDER_ID,
    CUST_ORDER_LINE_NO,
    CUSTOMER_PART_ID,
    CUSTOMER_PO_REF,
    CUSTOMER_ID,
    SHIP_TO_ADDR_NO,
    CUST_POLN_PRINT,
    CUST_PO_LN,
    WO_SHIPPED_QTY
)
SELECT TOP (@TOPPER)
    SL.PACKLIST_ID,
    DSL.SUPPLY_BASE_ID,
    DSL.SUPPLY_LOT_ID,
    DSL.SUPPLY_SUB_ID,
    DSL.SUPPLY_SPLIT_ID,
    TRT.TRANSACTION_ID,
    TRT.TRACE_ID,
    COL.PART_ID,
    S.USER_1,
    S.USER_2,
    S.USER_3,
    S.USER_4,
    S.USER_5,
    S.USER_6,
    S.USER_7,
    S.USER_8,
    S.USER_9,
    S.USER_10,
    SL.CUST_ORDER_ID,
    SL.CUST_ORDER_LINE_NO,
    COL.CUSTOMER_PART_ID,
    CO.CUSTOMER_PO_REF,
    CO.CUSTOMER_ID,
    CO.SHIP_TO_ADDR_NO,
    CASE WHEN COL.USER_2 IS NOT NULL THEN 'Y' ELSE 'N' END AS CUST_POLN_PRINT,
    COL.USER_2 AS CUST_PO_LN,
    ISNULL(ABS(TRT.QTY), SL.SHIPPED_QTY) AS WO_SHIPPED_QTY
FROM SHIPPER_LINE SL
JOIN CUST_ORDER_LINE COL
    ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
    AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
LEFT JOIN DEMAND_SUPPLY_LINK DSL
    ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
    AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
JOIN CUSTOMER_ORDER CO
    ON COL.CUST_ORDER_ID = CO.ID
LEFT JOIN TRACE_INV_TRANS TRT
    ON TRT.TRANSACTION_ID = SL.TRANSACTION_ID
JOIN SHIPPER S
    ON SL.PACKLIST_ID = S.PACKLIST_ID
WHERE (SL.PACKLIST_ID = @PACKLIST_ID OR @PACKLIST_ID IS NULL)
    AND ISNULL(ABS(TRT.QTY), SL.SHIPPED_QTY) > 0

SELECT *
FROM #ShipperContents