USE [LIVE]
GO

/****** Object:  View [dbo].[vw_PART_DATA]    Script Date: 1/30/2026 12:10:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

----CREATE VIEW [dbo].[vw_PART_DATA] AS 

declare @PART_ID NVARCHAR(50) = 'BACB30FM6-7';

WITH CTE_PART AS
(SELECT ID FROM PART 
WHERE 1=1 
-- --  AND PURCHASED = 'Y' AND (STATUS != 'O' OR STATUS IS NULL)
AND ID = @PART_ID
and commodity_code in ('Standards','details')
)

-- , CTE_RCVD AS 
-- (SELECT P.ID AS PART_ID
-- 	, MAX(PO.ORDER_DATE) AS ORDER_DATE
-- 	, MAX(R.RECEIVED_DATE) AS RECEIVED_DATE
-- FROM PURC_ORDER_LINE POL
-- INNER JOIN PURCHASE_ORDER PO
-- 	ON POL.PURC_ORDER_ID = PO.ID
-- 	AND PO.[STATUS] != 'X'
-- INNER JOIN CTE_PART P
-- 	ON POL.PART_ID = P.ID
-- LEFT OUTER JOIN RECEIVER_LINE RL
-- 	ON RL.PURC_ORDER_ID = POL.PURC_ORDER_ID
-- 	AND RL.PURC_ORDER_LINE_NO = POL.LINE_NO
-- LEFT OUTER JOIN RECEIVER R
-- 	ON RL.RECEIVER_ID = R.ID
-- --WHERE P.ID = '.256T3652-1'
-- GROUP BY P.ID
-- )
-- --SELECT * FROM CTE_PARTS

-- , CTE_WO AS
-- (SELECT PART_ID
-- 	, MAX(CLOSE_DATE) AS LAST_WO_DATE
-- FROM WORK_ORDER WO
-- WHERE WO.[STATUS] = 'C' 
-- GROUP BY PART_ID
-- )

SELECT P.ID AS PART_ID
	, P.[DESCRIPTION]
	, P.[STATUS]
	, P.STOCK_UM AS UM
	, P.[PRODUCT_CODE]
	, P.[COMMODITY_CODE]
	, P.[FABRICATED]
	, P.[PURCHASED]
	, P.[STOCKED]
	, P.[TOOL_OR_FIXTURE]
	, P.[PLANNER_USER_ID]
	, P.[BUYER_USER_ID]
	, P.CONSUMABLE
	, P.INSPECTION_REQD AS INSP_REQD
--> PART_SITE JOIN FOR UNIT COSTS
	, PS.[UNIT_PRICE]
	, PS.[UNIT_MATERIAL_COST]
	, PS.[UNIT_LABOR_COST]
	, PS.[UNIT_SERVICE_COST]
--> PART SPECIFICATIONS AS DEFINED BY CUSTOMER
	, CAST(CAST(PB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS PART_SPECS
--> DOCUMENTATION OF PART SPECIFICATIONS
	, STUFF((SELECT ', ' + d.id +' REV '+ d.REVISION_ID 
		FROM DOCUMENT D
		INNER JOIN DOCUMENT_REFERENCE DF
			ON DF.DOCUMENT_ID = D.ID
			AND D.CATEGORY_ID = 'SPECIFICATION'
		WHERE P.ID = DF.ID
		FOR XML PATH('')), 1, 1, ''
	) AS SPEC_LIST
	, P.USER_1 AS TBD1
	, P.USER_2 AS MFG_PROCESS
	, P.USER_3 AS FIN_PROCESS
	, P.USER_4 AS MFG_EST_UNIT_PRICE
	, P.USER_5 AS FIN_EST_UNIT_PRICE
	, P.USER_6 AS TBD2
	, P.USER_7 AS AIRPLANE_MODEL
	, P.USER_8 AS TBD3
	, P.USER_9 AS GEN_PROCESS
	, P.USER_10 AS CUSTOMER_ROLT
	, CASE
		WHEN ISNULL(P.QTY_ON_HAND, 0.00000000) != 0.00000000 THEN P.QTY_ON_HAND
		ELSE 0.00000000
	END AS INVENTORY
	, ISNULL(UDF26.STRING_VAL, UDF26.NUMBER_VAL) AS [Surface Area]
	, ISNULL(UDF35.STRING_VAL, UDF35.NUMBER_VAL) AS [Material Type]
	, ISNULL(UDF36.STRING_VAL, UDF36.NUMBER_VAL) AS [Alloy]
	, ISNULL(UDF37.STRING_VAL, UDF37.NUMBER_VAL) AS [Length]
	, ISNULL(UDF38.STRING_VAL, UDF38.NUMBER_VAL) AS [Width]
	, ISNULL(UDF39.STRING_VAL, UDF39.NUMBER_VAL) AS [Thickness]
	, CASE
		WHEN UDF40.BOOL_VAL = 1 THEN 'ITAR'
		ELSE ''
	END AS [ITAR]
	, ISNULL(UDF82.STRING_VAL, UDF82.NUMBER_VAL) AS [SK-PUR CONTROLLED]
	, ISNULL(UDF84.STRING_VAL, UDF84.NUMBER_VAL) AS [SK-PUR Cert Needed]
	, ISNULL(UDF85.STRING_VAL, UDF85.NUMBER_VAL) AS [Used on Part ID]
	, ISNULL(UDF91.STRING_VAL, UDF91.NUMBER_VAL) AS [Limited Scope]
	, ISNULL(UDF92.STRING_VAL, UDF92.NUMBER_VAL) AS [SK-FIN Primer]
	, ISNULL(UDF98.STRING_VAL, UDF98.NUMBER_VAL) AS [SK-FIN Topcoat]
	, ISNULL(UDF99.STRING_VAL, UDF99.NUMBER_VAL) AS [SK-FIN Topcoat 2]
	-- , CTE.ORDER_DATE AS LAST_ORDER_DATE
	-- , CTE.RECEIVED_DATE AS LAST_RECEIVED_DATE
	-- , WO.LAST_WO_DATE
FROM CTE_PART CP
join PART P
	ON P.ID = CP.ID	
LEFT OUTER JOIN PART_SITE PS
	ON P.ID = PS.PART_ID
LEFT OUTER JOIN PART_BINARY PB
	ON P.ID = PB.PART_ID
	AND PB.[TYPE] = 'D'
LEFT OUTER JOIN USER_DEF_FIELDS UDF26
	ON P.ID = UDF26.DOCUMENT_ID
	AND UDF26.PROGRAM_ID = 'VMPRTMNT' 
	AND UDF26.ID = 'UDF-0000026' 
LEFT OUTER JOIN USER_DEF_FIELDS UDF35
	ON P.ID = UDF35.DOCUMENT_ID
	AND UDF35.PROGRAM_ID = 'VMPRTMNT' 
	AND UDF35.ID = 'UDF-0000035' 
LEFT OUTER JOIN USER_DEF_FIELDS UDF36
	ON P.ID = UDF36.DOCUMENT_ID
	AND UDF36.PROGRAM_ID = 'VMPRTMNT' 
	AND UDF36.ID = 'UDF-0000036' 
LEFT OUTER JOIN USER_DEF_FIELDS UDF37
	ON P.ID = UDF37.DOCUMENT_ID
	AND UDF37.PROGRAM_ID = 'VMPRTMNT' 
	AND UDF37.ID = 'UDF-0000037' 
LEFT OUTER JOIN USER_DEF_FIELDS UDF38
	ON P.ID = UDF38.DOCUMENT_ID
	AND UDF38.PROGRAM_ID = 'VMPRTMNT' 
	AND UDF38.ID = 'UDF-0000038' 
LEFT OUTER JOIN USER_DEF_FIELDS UDF39
	ON P.ID = UDF39.DOCUMENT_ID
	AND UDF39.PROGRAM_ID = 'VMPRTMNT' 
	AND UDF39.ID = 'UDF-0000039' 
LEFT OUTER JOIN USER_DEF_FIELDS UDF40
	ON P.ID = UDF40.DOCUMENT_ID
	AND UDF40.PROGRAM_ID = 'VMPRTMNT' 
	AND UDF40.ID = 'UDF-0000040' 
LEFT OUTER JOIN USER_DEF_FIELDS UDF82
	ON P.ID = UDF82.DOCUMENT_ID
	AND UDF82.PROGRAM_ID = 'VMPRTMNT' 
	AND UDF82.ID = 'UDF-0000082' 
LEFT OUTER JOIN USER_DEF_FIELDS UDF84
	ON P.ID = UDF84.DOCUMENT_ID
	AND UDF84.PROGRAM_ID = 'VMPRTMNT' 
	AND UDF84.ID = 'UDF-0000084' 
LEFT OUTER JOIN USER_DEF_FIELDS UDF85
	ON P.ID = UDF85.DOCUMENT_ID
	AND UDF85.PROGRAM_ID = 'VMPRTMNT' 
	AND UDF85.ID = 'UDF-0000085' 
LEFT OUTER JOIN USER_DEF_FIELDS UDF91
	ON P.ID = UDF91.DOCUMENT_ID
	AND UDF91.PROGRAM_ID = 'VMPRTMNT' 
	AND UDF91.ID = 'UDF-0000091' 
LEFT OUTER JOIN USER_DEF_FIELDS UDF92
	ON P.ID = UDF92.DOCUMENT_ID
	AND UDF92.PROGRAM_ID = 'VMPRTMNT' 
	AND UDF92.ID = 'UDF-0000092' 
LEFT OUTER JOIN USER_DEF_FIELDS UDF98
	ON P.ID = UDF98.DOCUMENT_ID
	AND UDF98.PROGRAM_ID = 'VMPRTMNT' 
	AND UDF98.ID = 'UDF-0000098' 
LEFT OUTER JOIN USER_DEF_FIELDS UDF99
	ON P.ID = UDF99.DOCUMENT_ID
	AND UDF99.PROGRAM_ID = 'VMPRTMNT' 
	AND UDF99.ID = 'UDF-0000099' 

-- MAX(CASE WHEN ID = 'UDF-0000101' THEN STRING_VAL ELSE NULL END) AS [qc_notes]
LEFT OUTER JOIN USER_DEF_FIELDS UDF101
	ON P.ID = UDF99.DOCUMENT_ID
	AND UDF99.PROGRAM_ID = 'VMPRTMNT' 
	AND UDF99.ID = 'UDF-0000101' 

----WHERE P.ID NOT LIKE '%REWORK%'
-- LEFT OUTER JOIN CTE_RCVD CTE
-- 	ON CTE.PART_ID = P.ID
-- LEFT OUTER JOIN CTE_WO WO
-- 	ON WO.PART_ID = P.ID
GO


