--> HOME > VISUAL ENTERPRISE REPORTS > PURCHASING REPORTS > PURCHASE_ORDER
/**********************************************************************************************
Date     Modified By	Change Description
-------- -------------  ------------------------------------------------------------
20210909 tt				new version
20220211 mp				correction on logic to get document reference from EM's (didn't pull when legs were involved).  Spice Works Help Desk Ticket #1630
20260202 wt				Add UDF115 to indicate Supplier Controlled Drawing
**********************************************************************************************/

declare @ORDER_ID NVARCHAR(15) = NULL -- '184341'  -- Purchase Order ID to report on
declare @vendor_ID NVARCHAR(15) = 'ATCMAN'  -- Purchase Order ID to report on

; WITH CTE_DOCS AS
--> MASTERS DOCS
(SELECT 'MASTERS' AS SRC 
	, DRW.WORKORDER_BASE_ID
	, DRW.WORKORDER_LOT_ID 
	, DRW.WORKORDER_SPLIT_ID
	, DRW.WORKORDER_SUB_ID
	, DRW.WORKORDER_TYPE
	, DRW.SEQUENCE_NO
	, (SELECT D.ID + CASE
			WHEN D.REVISION_ID IS NULL THEN ' / REV: '
			ELSE ' / REV: ' + D.REVISION_ID
		END + CASE
			WHEN U1.STRING_VAL IS NULL THEN ' / ADCN: '
			ELSE ' / ADCN: ' + U1.STRING_VAL
		END + CHAR(10)
	) AS DOCUMENT_ID
FROM DEMAND_SUPPLY_LINK DSL
--> GIVES ME THE PART TO THE MASTER
INNER JOIN WORK_ORDER WO
	ON DSL.DEMAND_BASE_ID = WO.BASE_ID
	AND DSL.DEMAND_LOT_ID = WO.LOT_ID
	AND WO.SUB_ID = '0'
INNER JOIN DOCUMENT_REF_WO DRW
	ON DRW.WORKORDER_BASE_ID = WO.PART_ID
	--DRW,WORKORDER_SUB_ID = DSL.DEMAND_SUB_ID)
	AND (DRW.WORKORDER_SUB_ID = DSL.DEMAND_SUB_ID OR (DRW.WORKORDER_SUB_ID = 0 AND DRW.SEQUENCE_NO = 0))
INNER JOIN DOCUMENT D
	ON DRW.DOCUMENT_ID = D.ID
LEFT JOIN USER_DEF_FIELDS U1  --> ADCN
	ON D.ID = U1.DOCUMENT_ID
	AND U1.PROGRAM_ID = 'VMDOCMNT'
	AND U1.ID = 'UDF-0000032'
LEFT JOIN USER_DEF_FIELDS UDF115  --> Supplier Controlled Drawing
	ON D.ID = UDF115.DOCUMENT_ID
	AND UDF115.PROGRAM_ID = 'VMDOCMNT'
	AND UDF115.ID = 'UDF-0000115'
WHERE DSL.SUPPLY_BASE_ID = @ORDER_ID
)
--SELECT * FROM CTE_DOCS
--select * from DEMAND_SUPPLY_LINK where SUPPLY_BASE_ID = 'PO'
--select * from DEMAND_SUPPLY_LINK where DEMAND_BASE_ID = 'WO' and SUPPLY_BASE_ID = 'PO'

, CTE_BASE AS
(SELECT PO.ID AS ORDER_ID
	, POL.LINE_NO
--> PO INFORMATION
	, PO.ORDER_DATE
	, PO.BUYER
	, PO.SHIP_VIA
	, PO.FREE_ON_BOARD
	, EE.EMAIL_ADDR AS BUYER_EMAIL
	, PO.TOTAL_AMT_ORDERED AS PO_TOTAL
	, CASE 
		WHEN ISNULL(PrePaidCC.BOOL_VAL,0) = 1 THEN 'Prepaid via CC' 
		ELSE T.[DESCRIPTION] 
	END AS TERMS
--> VENDOR INFORMATION
	, PO.VENDOR_ID
	, V.[NAME] AS VENDOR_NAME
	, V.ADDR_1 AS VENDOR_ADDR_1
	, V.ADDR_2 AS VENDOR_ADDR_2
	, V.ADDR_3 AS VENDOR_ADDR_3
	, CASE 
		WHEN V.COUNTRY IN ('US', 'USA', 'UNITED STATES') THEN V.CITY + ', ' + V.[STATE] + '  '+ V.ZIPCODE
		ELSE V.ADDR_3 + ' ' + V.COUNTRY + ' ' + V.ZIPCODE
	END AS VENDOR_CTSZ
	, PO.CONTACT_PHONE AS VENDOR_PHONE
	, PO.CONTACT_FAX AS VENDOR_FAX
	, UDF5.STRING_VAL AS VENDOR_QCNOTES
--> SHIP TO INFORMATION
	, STA.[NAME] AS SHIPTO_NAME
	, STA.ADDR_1 AS SHIPTO_ADDR_1
	, STA.CITY AS SHIPTO_CITY
	, STA.[STATE] AS SHIPTO_STATE
	, STA.ZIPCODE AS SHIPTO_ZIPCODE
	, STA.COUNTRY AS SHIPTO_COUNTRY
--> PO LINE INFORMATION
	, POL.PART_ID
	, POL.USER_1 AS POL_USER_1
	, P.[DESCRIPTION] AS PART_DESCRIPTION
	, DBO.SFNWONUMFORMAT(DSL.DEMAND_BASE_ID, DSL.DEMAND_LOT_ID, DSL.DEMAND_SPLIT_ID, DSL.DEMAND_SUB_ID) AS WORKORDER
	, POL.VENDOR_PART_ID
	, POL.USER_ORDER_QTY
	, POL.PURCHASE_UM
	, POL.UNIT_PRICE 
	, ISNULL(POL.DESIRED_RECV_DATE, PO.DESIRED_RECV_DATE) AS POL_DESIRED_RECV_DATE
	, POL.TOTAL_AMT_ORDERED
	, POL.MFG_NAME
	, POL.MFG_PART_ID
	, POL.USER_2 AS POL_USER_2
	, CASE
		WHEN POL.USER_2 = 'Y' THEN CASE
				WHEN POL.TOTAL_AMT_ORDERED IS NULL THEN 0
				ELSE POL.TOTAL_AMT_ORDERED * .1
			END
		ELSE 0
	END AS POL_TAX
	, UDF6.STRING_VAL AS PART_QCNOTES
	, UDF.BOOL_VAL AS ITAR_PART
	, CASE
		WHEN UDF.BOOL_VAL = 1 AND V.USER_1 = 'Y' AND ISNULL(V.USER_4, '') != '' THEN 'ITAR'
		ELSE NULL
	END AS ISITAR
	, CASE 
		WHEN UDF2.STRING_VAL IN ('SPECIFICATION CONTROLLED') THEN 'Product must be manufactured by an approved supplier listed in stated specification'
		WHEN UDF2.STRING_VAL = 'CONTROLLED' THEN 'Product is a Controlled Part'
		WHEN UDF2.STRING_VAL = 'QPL CONTROLLED' THEN 'Product must be from a QPL-approved manufacturer'
	ELSE NULL
	END AS CONTROLLED_TEXT
	, UDF3.STRING_VAL AS CERT_REQ
	, UDF4.STRING_VAL AS USED_ON
	, CASE 
		WHEN DR.DOCUMENT_ID = '3CXPhone for Windows.lnk' THEN '3CXPhone for Windows'
		ELSE DR.DOCUMENT_ID
	END AS DOCUMENT_ID
	, D.REVISION_ID
--> MESSAGES
	, CASE
		WHEN POL.VENDOR_PART_ID LIKE '%EXP%' THEN 1
		ELSE NULL
	END AS EXPEDITE
	, CASE
		WHEN V.ACTIVE_FLAG = 'Y' AND ISNULL(V.USER_1, '') = '' AND ISNULL(V.USER_2, '') = '' THEN NULL
		WHEN V.USER_1 = 'Y' AND ISNULL(V.USER_2, '') != '' THEN V.USER_2
		ELSE 'Not Approved Vendor'
	END AS SUPPLIER_APPROVAL
	, CASE
		WHEN V.ACTIVE_FLAG = 'Y' AND ISNULL(V.USER_1, '') = '' AND ISNULL(V.USER_2, '') = '' THEN NULL
		WHEN V.USER_1 = 'Y' AND ISNULL(V.USER_4, '') != '' THEN V.USER_4
		ELSE 'Not ITAR Approved'
	END AS ITAR_APPROVAL
	, CASE
		WHEN V.ACTIVE_FLAG = 'Y' AND ISNULL(V.USER_1, '') = '' AND ISNULL(V.USER_2, '') = '' THEN NULL
		WHEN V.USER_1 = 'Y' AND ISNULL(V.USER_5, '') != '' THEN V.USER_5
		ELSE 'Not DPD Approved'
	END AS DPD_APPROVAL
	, HasPrtLimited = ISNULL(HasPrtLimited.Bool_Val, 0) 
	, HasVndLimited = ISNULL(HasVndLimited.Bool_Val, 0)
	, IsFlaggedLimited = IIF(ISNULL(HasVndLimited.Bool_Val, 0) = 1 AND ISNULL(HasPrtLimited.Bool_Val, 0) = 0, 1, 0) 
	, CASE
		WHEN UDF2.STRING_VAL IN ('SPECIFICATION CONTROLLED') AND ISNULL(V.USER_2, '') = '' THEN 'Product must be manufactured by an approved supplier listed in stated specification'
		WHEN UDF2.STRING_VAL IN ('CONTROLLED', 'QPL CONTROLLED') AND ISNULL(V.USER_2, '') = '' THEN 'Controlled Products must be from an approved manufacturer'
		WHEN P.FABRICATED = 'Y' AND ISNULL(V.USER_2, '') = '' THEN 'Fabricated Products must be from an approved manufacturer'
		WHEN V.USER_2 = 'Disapproved' THEN 'Check Vendor ASL information'
		WHEN ISNULL(HasVndLimited.Bool_Val, 0) = 1 AND ISNULL(HasPrtLimited.Bool_Val, 0) = 0 THEN 'Not a Limited Scope Part'
		WHEN UDF.BOOL_VAL = 1 AND ISNULL(V.USER_4, '') = '' THEN 'Not ITAR Approved'
		WHEN V.ACTIVE_FLAG = 'Y' AND V.USER_1 = 'Y' AND V.USER_2 = 'Approved' AND ISNULL(CAST(V.USER_3 AS DATE), GETDATE() + 1) <= GETDATE() THEN 'Check Vendor ASL information'
		WHEN V.ACTIVE_FLAG = 'Y' AND V.USER_1 = 'Y' AND V.USER_2 = 'Approved' AND ISNULL(CAST(V.USER_4 AS DATE), GETDATE() + 1) <= GETDATE() THEN 'Check Vendor ASL information'
		WHEN V.ACTIVE_FLAG = 'Y' AND V.USER_1 = 'Y' AND V.USER_2 = 'Approved' AND ISNULL(CAST(V.USER_5 AS DATE), GETDATE() + 1) <= GETDATE() THEN 'Check Vendor ASL information'
		WHEN V.USER_2 = 'Pending' THEN NULL
		ELSE NULL
	END AS PRINTMESSAGE
	, CASE
		WHEN PO.VENDOR_ID = 'TMXDIV'
			THEN 'The INCOTERMS™ 2000 for all orders from Buyer will be Free on Board (FOB) if by ocean and Delivery Duty Unpaid (DDU); otherwise, Boeing will pay for freight per Boeing''s standard routing instructions.  When Buyer''s order requests delivery outside the United States of America, the Import of Record will be the Buyer placing the order.  Title and risk of loss shall pass at place of shipment (i.e. for orders shipped directly from a mill, title and risk of loss shall pass when Boeing, or it''s designee, assume control of the Material; for orders shipped from Boeing, or Boeing''s service provider, title and risk of loss shall pass at Boeing, or Boeing''s service provider''s, shipping dock and Buyer will maintain adequate insurance to cover shipments at the time of risk of loss of transfer to Buyer.)'
		ELSE NULL
	END AS TMXMESSAGE
	, STUFF((SELECT CHAR(032) + T.DOCUMENT_ID
		FROM (SELECT WORKORDER_BASE_ID
				, WORKORDER_SUB_ID
				, SEQUENCE_NO
				, DOCUMENT_ID 
			FROM CTE_DOCS 
			GROUP BY WORKORDER_BASE_ID
				, WORKORDER_SUB_ID
				, SEQUENCE_NO
				, DOCUMENT_ID
		) T
		WHERE (T.WORKORDER_BASE_ID = POL.PART_ID)
			--AND (T.WORKORDER_SUB_ID = DSL.DEMAND_SUB_ID)
			AND (T.WORKORDER_SUB_ID = DSL.DEMAND_SUB_ID OR (T.WORKORDER_SUB_ID = 0 AND T.SEQUENCE_NO = 0))
			AND (T.SEQUENCE_NO = '0' OR T.SEQUENCE_NO = DSL.DEMAND_SEQ_NO)
		FOR XML PATH('')), 1, 1, '') AS DOCUMENT
	, CASE
		WHEN VB.BITS_LENGTH <= 6 THEN NULL
		WHEN CHAR(13) + CHAR(10) = LEFT(LTRIM(RTRIM(REPLACE(CAST(CAST(VB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10), CHAR(13) + CHAR(10)))), 2) 
			THEN SUBSTRING(LTRIM(RTRIM(REPLACE(CAST(CAST(VB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10), CHAR(13) + CHAR(10))))
				, 3, LEN(LTRIM(RTRIM(REPLACE(CAST(CAST(VB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10), CHAR(13) + CHAR(10))))))
		ELSE LTRIM(RTRIM(REPLACE(CAST(CAST(VB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10), CHAR(13) + CHAR(10)))) 
	END AS SPECTAB_VERBIAGE
	, CASE
		WHEN POB.BITS_LENGTH <= 6 THEN NULL
		WHEN CHAR(13) + CHAR(10) = LEFT(LTRIM(RTRIM(REPLACE(CAST(CAST(POB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10), CHAR(13) + CHAR(10)))), 2) 
			THEN SUBSTRING(LTRIM(RTRIM(REPLACE(CAST(CAST(POB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10), CHAR(13) + CHAR(10))))
				, 3, LEN(LTRIM(RTRIM(REPLACE(CAST(CAST(POB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10), CHAR(13) + CHAR(10))))))
		ELSE LTRIM(RTRIM(REPLACE(CAST(CAST(POB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10), CHAR(13) + CHAR(10)))) 
	END AS PO_LONG_DESCRIPTION
	, CASE
		WHEN PLB.BITS_LENGTH <= 6 THEN NULL
		WHEN CHAR(13) + CHAR(10) = LEFT(LTRIM(RTRIM(REPLACE(CAST(CAST(PLB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10), CHAR(13) + CHAR(10)))), 2) 
			THEN SUBSTRING(LTRIM(RTRIM(REPLACE(CAST(CAST(PLB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10), CHAR(13) + CHAR(10))))
				, 3, LEN(LTRIM(RTRIM(REPLACE(CAST(CAST(PLB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10), CHAR(13) + CHAR(10))))))
		ELSE LTRIM(RTRIM(REPLACE(CAST(CAST(PLB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10), CHAR(13) + CHAR(10)))) 
	END AS POL_LONG_DESCRIPTION
	, CASE
		WHEN PAB.BITS_LENGTH <= 6 THEN NULL
		WHEN CHAR(13) + CHAR(10) = LEFT(LTRIM(RTRIM(REPLACE(CAST(CAST(PAB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10), CHAR(13) + CHAR(10)))), 2) 
			THEN SUBSTRING(LTRIM(RTRIM(REPLACE(CAST(CAST(PAB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10), CHAR(13) + CHAR(10))))
				, 3, LEN(LTRIM(RTRIM(REPLACE(CAST(CAST(PAB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10), CHAR(13) + CHAR(10))))))
		ELSE LTRIM(RTRIM(REPLACE(CAST(CAST(PAB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10), CHAR(13) + CHAR(10)))) 
	END AS PAB_LONG_DESCRIPTION, UDF74.STRING_VAL as 'UDF_StringV_WO', DSL.UDF_WO, 
	CASE WHEN STOCKED = 'Y' AND CONSUMABLE = 'Y' THEN 'STOCKED and CONSUMABLE'
		WHEN STOCKED = 'Y' AND CONSUMABLE = 'N' THEN 'STOCKED'
		WHEN STOCKED = 'N' AND CONSUMABLE = 'Y' THEN 'CONSUMABLE'
	END AS 'Item'
	, V.USER_2 as 'Vendor_Approved'
	, CASE WHEN UDF2.STRING_VAL IS NULL THEN 0
		WHEN UDF2.STRING_VAL = 'Not Controlled' THEN 0
		WHEN UDF2.STRING_VAL = '' THEN 0
	ELSE 1 END AS 'Part_Controller_L'

		, CASE WHEN UDF115.BOOL_VAL IS NULL THEN 0
		WHEN UDF115.BOOL_VAL = 1 THEN 1
		else 0
	END AS 'Supplier_Controlled_Drawing'
FROM PURCHASE_ORDER PO
LEFT OUTER JOIN PURC_ORDER_LINE POL
	ON PO.ID = POL.PURC_ORDER_ID 
LEFT OUTER JOIN PART P
	ON POL.PART_ID = P.ID
LEFT OUTER JOIN EMPLOYEE EE
	ON PO.BUYER = EE.[USER_ID]
LEFT OUTER JOIN VENDOR V
	ON PO.VENDOR_ID = V.ID
LEFT OUTER JOIN TERMS T
	ON T.ID = V.DEF_TERMS_ID
LEFT OUTER JOIN SHIPTO_ADDRESS STA
	ON STA.ADDR_NO = PO.SHIPTO_ADDR_NO
LEFT OUTER JOIN ( SELECT ID, DEMAND_TYPE, DEMAND_BASE_ID, DEMAND_LOT_ID, DEMAND_SPLIT_ID, DEMAND_SUB_ID, DEMAND_SEQ_NO, DEMAND_NO, SUPPLY_TYPE, SUPPLY_BASE_ID, SUPPLY_SEQ_NO, 
SUPPLY_PART_ID, 'W~'+DEMAND_BASE_ID+'~'+cast(DEMAND_SPLIT_ID as varchar(12))+'~'+cast(DEMAND_LOT_ID as varchar(12))+'~'+cast(DEMAND_SUB_ID as  varchar(12))+'~'+cast(DEMAND_SEQ_NO as varchar(12)) as 'UDF_WO' 
FROM DEMAND_SUPPLY_LINK ) DSL --W~base~split~lot~sub~seq
	ON POL.PURC_ORDER_ID = DSL.SUPPLY_BASE_ID
	AND POL.LINE_NO = DSL.SUPPLY_SEQ_NO
	AND DSL.SUPPLY_TYPE = 'PO'
	AND DSL.DEMAND_TYPE = 'OP'
LEFT OUTER JOIN DOCUMENT_REFERENCE DR
	ON DR.ID = POL.PART_ID
LEFT OUTER JOIN DOCUMENT D
	ON D.ID = DR.DOCUMENT_ID
	AND DR.SOURCE_TYPE = 'P'
	AND D.SITE_ID = 'SK01'
--> ITAR INFO
LEFT OUTER JOIN USER_DEF_FIELDS UDF
	ON UDF.DOCUMENT_ID = POL.PART_ID
	AND UDF.PROGRAM_ID = 'VMPRTMNT'
	AND UDF.ID = 'UDF-0000040'
	AND BOOL_VAL = 1
--> CONTROLLED INFO
LEFT OUTER JOIN USER_DEF_FIELDS UDF2
	ON UDF2.DOCUMENT_ID = POL.PART_ID
	AND UDF2.PROGRAM_ID = 'VMPRTMNT'
	AND UDF2.ID = 'UDF-0000082'
--> CERT INFO
LEFT OUTER JOIN USER_DEF_FIELDS UDF3
	ON UDF3.DOCUMENT_ID = POL.PART_ID
	AND UDF3.PROGRAM_ID = 'VMPRTMNT'
	AND UDF3.ID = 'UDF-0000084'
--> USED ON INFO
LEFT OUTER JOIN USER_DEF_FIELDS UDF4
	ON UDF4.DOCUMENT_ID = POL.PART_ID
	AND UDF4.PROGRAM_ID = 'VMPRTMNT'
	AND UDF4.ID = 'UDF-0000085'
--> limited Scope; VMPRTMNT; HasPrtLimited
LEFT OUTER JOIN dbo.USER_DEF_FIELDS HasPrtLimited (nolock)
	ON HasPrtLimited.Document_ID = POL.PART_ID
	AND HasPrtLimited.program_id = 'VMPRTMNT'
	AND HasPrtLimited.DOCUMENT_ID is NOT null
	AND ISNULL(HasPrtLimited.BOOL_VAL, 0) = 1
	AND HasPrtLimited.ID = ('UDF-0000091') 
--> limited Scope; VMVNDMNT; HasVndLimited
LEFT OUTER JOIN [dbo].[USER_DEF_FIELDS] HasVndLimited (nolock)
	ON HasVndLimited.Document_ID = PO.VENDOR_ID
	AND HasVndLimited.program_id = 'VMVNDMNT'
	AND HasVndLimited.DOCUMENT_ID is NOT null
	AND HasVndLimited.ID ='UDF-0000090'  
	AND HasVndLimited.BOOL_VAL = 1
--> limited Scope; VMPURENT; PrePaidCC
LEFT OUTER JOIN [dbo].[USER_DEF_FIELDS] PrePaidCC (nolock)
	ON PrePaidCC.Document_ID = PO.ID
	AND PrePaidCC.program_id = 'VMPURENT'
	AND PrePaidCC.DOCUMENT_ID is NOT null
	AND PrePaidCC.ID ='UDF-0000100'  
--> tt20210512 : UDF VENDOR QC NOTES
LEFT OUTER JOIN USER_DEF_FIELDS UDF5
	ON UDF5.DOCUMENT_ID = PO.VENDOR_ID
	AND UDF5.PROGRAM_ID = 'VMVNDMNT'
	AND UDF5.ID = 'UDF-0000102'
--> tt20210512 : UDF PART QC NOTES
LEFT OUTER JOIN USER_DEF_FIELDS UDF6
	ON UDF6.DOCUMENT_ID = POL.PART_ID
	AND UDF6.PROGRAM_ID = 'VMPRTMNT'
	AND UDF6.ID = 'UDF-0000101'
LEFT OUTER JOIN PURC_ORDER_BINARY POB
	ON PO.ID = POB.PURC_ORDER_ID
	AND POB.[TYPE] = 'D'
LEFT OUTER JOIN VENDOR_BINARY VB
	ON V.ID = VB.VENDOR_ID
	AND VB.[TYPE] = 'D'
LEFT OUTER JOIN PURC_LINE_BINARY PLB
	ON POL.PURC_ORDER_ID = PLB.PURC_ORDER_ID
	AND POL.LINE_NO = PLB.PURC_ORDER_LINE_NO
	AND PLB.[TYPE] = 'D'
LEFT OUTER JOIN PART_BINARY PAB
	ON POL.PART_ID = PAB.PART_ID
	AND PAB.[TYPE] = 'D'
--> WO information  USER_DEF_FIELDS 
--DSL.DEMAND_BASE_ID, DSL.DEMAND_LOT_ID, DSL.DEMAND_SPLIT_ID, DSL.DEMAND_SUB_ID
LEFT OUTER JOIN USER_DEF_FIELDS UDF74
	ON UDF74.DOCUMENT_ID = DSL.UDF_WO
	AND UDF74.PROGRAM_ID = 'VMMFGWIN_OP'
	AND UDF74.ID = 'UDF-0000074'

LEFT JOIN [LIVE].[dbo].[USER_DEF_FIELDS] udf115 (nolock)
  	ON P.ID = udf115.DOCUMENT_ID
	and udf115.[PROGRAM_ID] = 'VMPRTMNT'
    and udf115.id like 'UDF-00115'

WHERE 
 (PO.ID = @ORDER_ID
  OR @ORDER_ID IS NULL
  )
  AND
  (V.ID = @VENDOR_ID
  OR @VENDOR_ID IS NULL)
)

SELECT ORDER_ID
	, LINE_NO
	, ORDER_DATE
	, BUYER
	, SHIP_VIA
	, FREE_ON_BOARD
	, BUYER_EMAIL
	, PO_TOTAL
	, TERMS
	, VENDOR_ID
	, VENDOR_NAME
	, VENDOR_ADDR_1
	, VENDOR_ADDR_2
	, VENDOR_ADDR_3
	, VENDOR_CTSZ
	, VENDOR_PHONE
	, VENDOR_FAX
	, SHIPTO_NAME
	, SHIPTO_ADDR_1
	, SHIPTO_CITY
	, SHIPTO_STATE
	, SHIPTO_ZIPCODE
	, SHIPTO_COUNTRY
	, PART_ID
	, PART_DESCRIPTION
	, POL_USER_1
	, WORKORDER
	, VENDOR_PART_ID
	, USER_ORDER_QTY
	, PURCHASE_UM
	, UNIT_PRICE 
	, POL_DESIRED_RECV_DATE
	, TOTAL_AMT_ORDERED
	, MFG_NAME
	, MFG_PART_ID
	, POL_USER_2
	, POL_TAX
	, ITAR_PART
	, ISITAR
	, CONTROLLED_TEXT
	, CERT_REQ
	, USED_ON
	, DOCUMENT_ID
	, REVISION_ID
	, EXPEDITE
	, SUPPLIER_APPROVAL
	, ITAR_APPROVAL
	, DPD_APPROVAL
	, CASE WHEN SUPPLIER_APPROVAL = 'APPROVED' THEN '' 
		--WHEN SUPPLIER_APPROVAL = 'approved' THEN ''
		--WHEN Vendor_Approved = 'approved' THEN ''
	ELSE '*** DO NOT SEND TO VENDOR ***' END  AS 'WaterMark'
	, HasPrtLimited
	, HasVndLimited
	, IsFlaggedLimited
	, PRINTMESSAGE
	, TMXMESSAGE
	, DOCUMENT
--> tt20220120: REMOVE DUPLICATION BETWEEN SPECIFICATION LINES
	, PART_QCNOTES
--> QC NOTES; REMOVE DUPLICATION BETWEEN PART AND VENDOR QCNOTES
	, CASE	
		WHEN VENDOR_QCNOTES = PART_QCNOTES THEN NULL
		ELSE VENDOR_QCNOTES 
	END AS VENDOR_QCNOTES
--> VENDOR SPECIFICATIONS; REMOVE DUPLICATION BETWEEN VENDOR SPECS AND VENDOR QCNOTES
	, CASE
		WHEN REPLACE(REPLACE(SPECTAB_VERBIAGE, CHAR(13), ''), CHAR(10), '') = VENDOR_QCNOTES THEN NULL
		ELSE SPECTAB_VERBIAGE
	END AS SPECTAB_VERBIAGE
--> PART SPECIFICATIONS: KEEP PART OVER PO AND POL
	, PAB_LONG_DESCRIPTION
--> PO SPECIFICATIONS: KEEP VENDOR OVER POL
	, CASE
		WHEN REPLACE(REPLACE(PO_LONG_DESCRIPTION, CHAR(13), ''), CHAR(10), '') = REPLACE(REPLACE(PAB_LONG_DESCRIPTION, CHAR(13), ''), CHAR(10), '') THEN NULL
		WHEN REPLACE(REPLACE(PO_LONG_DESCRIPTION, CHAR(13), ''), CHAR(10), '') = REPLACE(REPLACE(SPECTAB_VERBIAGE, CHAR(13), ''), CHAR(10), '') THEN NULL
		ELSE PO_LONG_DESCRIPTION
	END AS PO_LONG_DESCRIPTION
--> POL SPECIFICATIONS: KEEP PO OVER POL
	, POL_LONG_DESCRIPTION AS B4_POL
	, CASE
		WHEN REPLACE(REPLACE(POL_LONG_DESCRIPTION, CHAR(13), ''), CHAR(10), '') = REPLACE(REPLACE(PO_LONG_DESCRIPTION, CHAR(13), ''), CHAR(10), '') THEN NULL
		WHEN REPLACE(REPLACE(POL_LONG_DESCRIPTION, CHAR(13), ''), CHAR(10), '') = REPLACE(REPLACE(PAB_LONG_DESCRIPTION, CHAR(13), ''), CHAR(10), '') THEN NULL
		ELSE POL_LONG_DESCRIPTION
	END AS POL_LONG_DESCRIPTION, UDF_StringV_WO, UDF_WO, Item, Part_Controller_L
	,Supplier_Controlled_Drawing
	, case when Supplier_Controlled_Drawing = 1 then 'Supplier Controlled Drawing' else null end Supplier_Controlled_Drawing_desc
FROM CTE_BASE