-- Report Purchasing Reports > Outside Services Inspection

; WITH CTE_BASE AS
(SELECT PL.PURC_ORDER_ID AS POID
    , PL.LINE_NO AS POLN
    , PO.VENDOR_ID AS VENDORID
    , V.NAME AS VENDORNAME
    , RL.RECEIVER_ID AS RECVRID
    , RL.LINE_NO AS RECVRLINE
    , R.RECEIVED_DATE AS RECVRDATE
    , PL.PART_ID AS PARTID
    , PL.SERVICE_ID AS SERVICEID
    , COALESCE(P.DESCRIPTION, PL.USER_1) AS DESCRIPTION
    , S.DESCRIPTION AS SERV_DESC
    , WO.BASE_ID + '/' + WO.LOT_ID + CASE WHEN WO.SPLIT_ID = '0' THEN '' ELSE '.' + CAST(WO.SPLIT_ID AS VARCHAR) END AS JOBID
    , WO.DESIRED_WANT_DATE AS JOBWANTDATE
    , DSL.DEMAND_SEQ_NO AS OPNO
    , DSL.DEMAND_SUB_ID AS OPSUB
    , (SELECT TOP 1 SO.STATUS FROM OPERATION SO (NOLOCK) JOIN SHOP_RESOURCE SR (NOLOCK) ON SO.RESOURCE_ID = SR.ID AND CHARINDEX('RECEIVING',SR.DESCRIPTION) = 0 
        WHERE SO.WORKORDER_TYPE = WO.TYPE AND SO.WORKORDER_BASE_ID = DSL.DEMAND_BASE_ID 
        AND SO.WORKORDER_LOT_ID = DSL.DEMAND_LOT_ID AND SO.WORKORDER_SPLIT_ID = DSL.DEMAND_SPLIT_ID AND SO.WORKORDER_SUB_ID = DSL.DEMAND_SUB_ID 
        AND SO.SEQUENCE_NO > DSL.DEMAND_SEQ_NO ORDER BY SO.SEQUENCE_NO) 
    AS NEXTOPSTATUS
    , (SELECT TOP 1 SO.RESOURCE_ID FROM OPERATION SO (NOLOCK) JOIN SHOP_RESOURCE SR (NOLOCK) ON SO.RESOURCE_ID = SR.ID AND CHARINDEX('RECEIVING',SR.DESCRIPTION) = 0 
        WHERE SO.WORKORDER_TYPE = WO.TYPE AND SO.WORKORDER_BASE_ID = DSL.DEMAND_BASE_ID 
        AND SO.WORKORDER_LOT_ID = DSL.DEMAND_LOT_ID AND SO.WORKORDER_SPLIT_ID = DSL.DEMAND_SPLIT_ID AND SO.WORKORDER_SUB_ID = DSL.DEMAND_SUB_ID 
        AND SO.SEQUENCE_NO > DSL.DEMAND_SEQ_NO ORDER BY SO.SEQUENCE_NO) 
    AS NEXTOPRESOURCEID
    , (SELECT TOP 1 SR.[DESCRIPTION] FROM OPERATION SO (NOLOCK) JOIN SHOP_RESOURCE SR (NOLOCK) ON SO.RESOURCE_ID = SR.ID AND CHARINDEX('RECEIVING',SR.DESCRIPTION) = 0 
        WHERE SO.WORKORDER_TYPE = WO.TYPE AND SO.WORKORDER_BASE_ID = DSL.DEMAND_BASE_ID 
        AND SO.WORKORDER_LOT_ID = DSL.DEMAND_LOT_ID AND SO.WORKORDER_SPLIT_ID = DSL.DEMAND_SPLIT_ID AND SO.WORKORDER_SUB_ID = DSL.DEMAND_SUB_ID 
        AND SO.SEQUENCE_NO > DSL.DEMAND_SEQ_NO ORDER BY SO.SEQUENCE_NO) 
    AS NEXTOPRESDESC
    , RL.USER_RECEIVED_QTY 
    , (SELECT TOP 1 SO.COMPLETED_QTY FROM OPERATION SO (NOLOCK) JOIN SHOP_RESOURCE SR (NOLOCK) ON SO.RESOURCE_ID = SR.ID AND CHARINDEX('RECEIVING',SR.DESCRIPTION) = 0 
        WHERE SO.WORKORDER_TYPE = WO.TYPE AND SO.WORKORDER_BASE_ID = DSL.DEMAND_BASE_ID 
        AND SO.WORKORDER_LOT_ID = DSL.DEMAND_LOT_ID AND SO.WORKORDER_SPLIT_ID = DSL.DEMAND_SPLIT_ID AND SO.WORKORDER_SUB_ID = DSL.DEMAND_SUB_ID 
        AND SO.SEQUENCE_NO > DSL.DEMAND_SEQ_NO ORDER BY SO.SEQUENCE_NO) 
    AS OP_INSP_QTY
FROM PURC_ORDER_LINE PL (NOLOCK)
JOIN PURCHASE_ORDER PO (NOLOCK) 
    ON PL.PURC_ORDER_ID = PO.ID 
JOIN VENDOR V (NOLOCK) 
    ON PO.VENDOR_ID = V.ID 
LEFT JOIN PART P (NOLOCK) 
    ON PL.PART_ID = P.ID 
LEFT JOIN SERVICE S (NOLOCK) 
    ON PL.SERVICE_ID = S.ID 
LEFT JOIN DEMAND_SUPPLY_LINK (NOLOCK) DSL 
    ON PL.PURC_ORDER_ID = DSL.SUPPLY_BASE_ID 
    AND PL.LINE_NO = DSL.SUPPLY_SEQ_NO 
    AND DSL.SUPPLY_TYPE = 'PO' 
    AND DSL.DEMAND_TYPE IN ('OP','RQ')
LEFT JOIN WORK_ORDER (NOLOCK) WO 
    ON DSL.DEMAND_BASE_ID = WO.BASE_ID 
    AND DSL.DEMAND_LOT_ID = WO.LOT_ID 
    AND DSL.DEMAND_SPLIT_ID = WO.SPLIT_ID 
    AND WO.SUB_ID = 0 
    AND WO.TYPE = 'W'
LEFT JOIN RECEIVER_LINE RL (NOLOCK) 
    ON PL.PURC_ORDER_ID = RL.PURC_ORDER_ID 
    AND PL.LINE_NO = RL.PURC_ORDER_LINE_NO
LEFT JOIN SERVICE_RECEIPT SR (NOLOCK) 
    ON RL.SERV_TRANS_ID = SR.TRANSACTION_ID 
LEFT JOIN RECEIVER R (NOLOCK) 
    ON RL.RECEIVER_ID = R.ID
LEFT JOIN PAYABLE_LINE APL (NOLOCK) 
    ON RL.RECEIVER_ID = APL.RECEIVER_ID 
    AND RL.LINE_NO = APL.RECEIVER_LINE_NO        
LEFT JOIN PAYABLE AP (NOLOCK) 
    ON APL.VOUCHER_ID = AP.VOUCHER_ID 
WHERE (R.RECEIVED_DATE IS NOT NULL AND R.RECEIVED_DATE >= '1/1/2019')
    AND PL.SERVICE_ID IS NOT NULL 
    AND WO.BASE_ID IS NOT NULL
    AND APL.VOUCHER_ID IS NULL
    AND PL.PART_ID IS NOT NULL
)


SELECT * 
FROM CTE_BASE
WHERE CASE 
        WHEN RECVRDATE IS NOT NULL AND SERVICEID IS NOT NULL 
            AND (CHARINDEX('RECEIV', NEXTOPRESDESC) > 0 OR CHARINDEX('INSP', NEXTOPRESDESC) > 0) 
            AND NEXTOPSTATUS IN ('F', 'R') 
            THEN 'YES' 
        WHEN RECVRDATE IS NOT NULL AND SERVICEID IS NOT NULL 
            AND (CHARINDEX('INSP', NEXTOPRESDESC) = 0 OR CHARINDEX('RECEIV', NEXTOPRESDESC) = 0)
            AND NEXTOPSTATUS IN ('C') 
            AND OP_INSP_QTY < USER_RECEIVED_QTY
            THEN 'YES' 
        ELSE '' 
        END = 'YES'


