#!/usr/bin/env python3
"""
013_Entry_Point_Manufacturing_Assistant.py
Direct adaptation of LangChain Academy email assistant pattern for Manufacturing Intelligence
Replacing 'email' with 'Manufacturing' following the exact structure from the tutorial
"""

import os
from typing import Literal, Dict, Any, List, Optional
from dataclasses import dataclass
from langchain_core.tools import tool
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage, BaseMessage
from langchain_openai import ChatOpenAI
import json
import uuid
from datetime import datetime

# Manufacturing Assistant Tools - Direct adaptation of email assistant tools
@tool
def write_manufacturing_report(
    recipient: str, 
    subject: str, 
    content: str,
    report_type: str = "standard"
) -> str:
    """Write and generate a manufacturing intelligence report."""
    report_id = str(uuid.uuid4())[:8]
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report = f"""
Manufacturing Intelligence Report #{report_id}
Generated: {timestamp}
Recipient: {recipient}
Subject: {subject}
Type: {report_type}

{content}

---
Report generated by Manufacturing Intelligence Assistant
    """.strip()
    
    return f"Manufacturing report #{report_id} generated for {recipient} with subject '{subject}'"

@tool
def analyze_production_metrics(
    equipment_id: str = "MAIN-LINE-001",
    metric_type: str = "oee",
    time_period: str = "last_week"
) -> str:
    """Analyze production metrics for manufacturing intelligence."""
    
    if metric_type == "oee":
        analysis = {
            "equipment_id": equipment_id,
            "metric_type": "Overall Equipment Effectiveness",
            "time_period": time_period,
            "availability": 0.85,
            "performance": 0.92,
            "quality": 0.97,
            "overall_oee": 0.759,
            "world_class_benchmark": 0.85,
            "status": "Improvement Needed",
            "recommendations": [
                "Reduce unplanned downtime by 5%",
                "Optimize cycle times for 3% performance gain",
                "Implement quality controls for 2% improvement"
            ]
        }
    elif metric_type == "defect_rate":
        analysis = {
            "equipment_id": equipment_id,
            "metric_type": "Defect Rate Analysis",
            "time_period": time_period,
            "current_defect_rate": "3.2%",
            "target_defect_rate": "2.0%",
            "trend": "increasing",
            "root_causes": ["Material inconsistency", "Equipment drift", "Process variation"],
            "recommendations": [
                "Implement statistical process control",
                "Enhanced material inspection",
                "Equipment calibration schedule"
            ]
        }
    else:
        analysis = {
            "equipment_id": equipment_id,
            "metric_type": metric_type,
            "status": "Metric analysis completed",
            "recommendations": ["Review metric parameters"]
        }
    
    return json.dumps(analysis, indent=2)

@tool
def schedule_manufacturing_task(
    task_type: str,
    equipment_id: str = "MAIN-LINE-001",
    priority: str = "medium",
    scheduled_date: str = "2024-02-15"
) -> str:
    """Schedule manufacturing tasks like maintenance, inspection, or calibration."""
    
    task_id = str(uuid.uuid4())[:8]
    
    task_details = {
        "task_id": task_id,
        "task_type": task_type,
        "equipment_id": equipment_id,
        "priority": priority,
        "scheduled_date": scheduled_date,
        "estimated_duration": "4 hours" if task_type == "maintenance" else "2 hours",
        "required_resources": {
            "technicians": 2 if priority == "high" else 1,
            "spare_parts": ["filters", "seals"] if task_type == "maintenance" else [],
            "tools": ["calibration_kit", "inspection_tools"]
        },
        "pre_task_checklist": [
            "Verify spare parts availability",
            "Assign qualified technicians",
            "Notify production planning"
        ]
    }
    
    return f"Manufacturing task #{task_id} scheduled: {task_type} for {equipment_id} on {scheduled_date}"

@tool
def assess_manufacturing_risk(
    risk_category: str = "operational",
    assessment_scope: str = "facility"
) -> str:
    """Assess manufacturing risks including supply chain, equipment, and operational risks."""
    
    risk_id = str(uuid.uuid4())[:8]
    
    if risk_category == "supply_chain":
        assessment = {
            "assessment_id": risk_id,
            "category": "Supply Chain Risk",
            "scope": assessment_scope,
            "overall_risk_level": "Medium",
            "critical_suppliers": 3,
            "risk_factors": [
                "Geographic concentration",
                "Single source dependencies", 
                "Financial stability concerns"
            ],
            "mitigation_strategies": [
                "Diversify supplier base",
                "Implement supplier monitoring",
                "Develop contingency plans"
            ]
        }
    elif risk_category == "equipment":
        assessment = {
            "assessment_id": risk_id,
            "category": "Equipment Risk",
            "scope": assessment_scope,
            "overall_risk_level": "Low",
            "critical_equipment": ["CNC-001", "PRESS-002"],
            "failure_probabilities": {"CNC-001": 0.15, "PRESS-002": 0.25},
            "mitigation_strategies": [
                "Predictive maintenance implementation",
                "Spare parts inventory optimization",
                "Technician training programs"
            ]
        }
    else:
        assessment = {
            "assessment_id": risk_id,
            "category": "Operational Risk",
            "scope": assessment_scope,
            "overall_risk_level": "Medium",
            "risk_areas": ["Quality control", "Production scheduling", "Resource allocation"],
            "mitigation_strategies": [
                "Process standardization",
                "Real-time monitoring implementation",
                "Cross-training initiatives"
            ]
        }
    
    return json.dumps(assessment, indent=2)

# Manufacturing Assistant Prompt Templates - Direct adaptation of email assistant prompts
class ManufacturingPromptTemplates:
    """Prompt templates for manufacturing assistant following email assistant pattern"""
    
    TRIAGE_SYSTEM_PROMPT = """
    You are a manufacturing intelligence triage assistant. Your job is to analyze manufacturing requests and route them appropriately.
    
    Available categories:
    - PRODUCTION_ANALYSIS: OEE calculation, defect analysis, performance metrics
    - MAINTENANCE_SCHEDULING: Preventive maintenance, repairs, calibration tasks
    - RISK_ASSESSMENT: Supply chain risks, equipment risks, operational risks
    - REPORT_GENERATION: Manufacturing reports, intelligence summaries
    - GENERAL: General manufacturing inquiries
    
    Analyze the user's request and categorize it appropriately.
    """
    
    AGENT_SYSTEM_PROMPT = """
    You are a manufacturing intelligence assistant with access to specialized tools for:
    
    1. Production Analysis: Calculate OEE, analyze defect rates, performance metrics
    2. Task Scheduling: Schedule maintenance, inspections, calibration tasks
    3. Risk Assessment: Evaluate supply chain, equipment, and operational risks
    4. Report Generation: Create comprehensive manufacturing intelligence reports
    
    Always use the appropriate tools to provide data-driven manufacturing insights.
    Focus on actionable recommendations and practical solutions.
    """
    
    MANUFACTURING_TOOLS_PROMPT = """
    Available Manufacturing Intelligence Tools:
    
    - analyze_production_metrics: Calculate OEE, defect rates, performance analysis
    - schedule_manufacturing_task: Schedule maintenance, inspections, calibration
    - assess_manufacturing_risk: Evaluate risks across supply chain, equipment, operations
    - write_manufacturing_report: Generate comprehensive intelligence reports
    
    Use these tools to provide comprehensive manufacturing intelligence.
    """

# Manufacturing State Schema - Following email assistant state pattern
@dataclass
class ManufacturingState:
    """State management for manufacturing intelligence requests"""
    request: str = ""
    category: str = ""
    analysis_results: Dict[str, Any] = None
    scheduled_tasks: List[str] = None
    risk_assessments: List[str] = None
    reports_generated: List[str] = None
    recommendations: List[str] = None
    
    def __post_init__(self):
        if self.analysis_results is None:
            self.analysis_results = {}
        if self.scheduled_tasks is None:
            self.scheduled_tasks = []
        if self.risk_assessments is None:
            self.risk_assessments = []
        if self.reports_generated is None:
            self.reports_generated = []
        if self.recommendations is None:
            self.recommendations = []

class ManufacturingRouterSchema:
    """Router schema for manufacturing request classification"""
    
    @staticmethod
    def classify_request(request: str) -> str:
        """Classify manufacturing request into appropriate category"""
        request_lower = request.lower()
        
        if any(term in request_lower for term in ["oee", "defect", "performance", "analysis", "metrics"]):
            return "PRODUCTION_ANALYSIS"
        elif any(term in request_lower for term in ["maintenance", "schedule", "repair", "calibration"]):
            return "MAINTENANCE_SCHEDULING"
        elif any(term in request_lower for term in ["risk", "supplier", "supply chain", "assessment"]):
            return "RISK_ASSESSMENT"
        elif any(term in request_lower for term in ["report", "summary", "intelligence", "generate"]):
            return "REPORT_GENERATION"
        else:
            return "GENERAL"

class ManufacturingIntelligenceAssistant:
    """Manufacturing Intelligence Assistant following email assistant architecture"""
    
    def __init__(self, openai_api_key: str = None):
        self.api_key = openai_api_key or os.getenv("OPENAI_API_KEY")
        
        # Initialize LLM
        self.llm = ChatOpenAI(
            model="gpt-4",
            api_key=self.api_key,
            temperature=0.1
        )
        
        # Manufacturing tools
        self.manufacturing_tools = [
            write_manufacturing_report,
            analyze_production_metrics,
            schedule_manufacturing_task,
            assess_manufacturing_risk
        ]
        
        # Bind tools to model
        self.model_with_tools = self.llm.bind_tools(
            self.manufacturing_tools,
            tool_choice="auto"
        )
        
        # Prompt templates
        self.prompts = ManufacturingPromptTemplates()
        
        # Router
        self.router = ManufacturingRouterSchema()
    
    def process_manufacturing_request(self, request: str, context: Dict[str, Any] = None) -> Dict[str, Any]:
        """Main method to process manufacturing intelligence requests"""
        
        print(f"🏭 Manufacturing Intelligence Request Processing")
        print(f"Request: {request}")
        print("-" * 60)
        
        # Initialize state
        state = ManufacturingState(request=request)
        
        # Step 1: Triage and classify request
        category = self.router.classify_request(request)
        state.category = category
        print(f"📊 Request Category: {category}")
        
        # Step 2: Process with appropriate agent
        if category == "PRODUCTION_ANALYSIS":
            result = self._handle_production_analysis(state)
        elif category == "MAINTENANCE_SCHEDULING":
            result = self._handle_maintenance_scheduling(state)
        elif category == "RISK_ASSESSMENT":
            result = self._handle_risk_assessment(state)
        elif category == "REPORT_GENERATION":
            result = self._handle_report_generation(state)
        else:
            result = self._handle_general_request(state)
        
        return result
    
    def _handle_production_analysis(self, state: ManufacturingState) -> Dict[str, Any]:
        """Handle production analysis requests"""
        print("🔧 Processing production analysis request...")
        
        # Use tools to analyze production metrics
        try:
            if "oee" in state.request.lower():
                analysis = analyze_production_metrics.invoke({
                    "metric_type": "oee",
                    "equipment_id": "MAIN-LINE-001"
                })
            else:
                analysis = analyze_production_metrics.invoke({
                    "metric_type": "defect_rate",
                    "equipment_id": "MAIN-LINE-001"
                })
            
            state.analysis_results["production_metrics"] = analysis
            state.recommendations.append("Review production metrics analysis")
            
            print("✅ Production analysis completed")
            
        except Exception as e:
            print(f"❌ Production analysis failed: {str(e)}")
        
        return self._format_response(state)
    
    def _handle_maintenance_scheduling(self, state: ManufacturingState) -> Dict[str, Any]:
        """Handle maintenance scheduling requests"""
        print("🔧 Processing maintenance scheduling request...")
        
        try:
            task_result = schedule_manufacturing_task.invoke({
                "task_type": "maintenance",
                "equipment_id": "MAIN-LINE-001",
                "priority": "medium"
            })
            
            state.scheduled_tasks.append(task_result)
            state.recommendations.append("Review scheduled maintenance tasks")
            
            print("✅ Maintenance scheduling completed")
            
        except Exception as e:
            print(f"❌ Maintenance scheduling failed: {str(e)}")
        
        return self._format_response(state)
    
    def _handle_risk_assessment(self, state: ManufacturingState) -> Dict[str, Any]:
        """Handle risk assessment requests"""
        print("🔧 Processing risk assessment request...")
        
        try:
            if "supply" in state.request.lower():
                risk_assessment = assess_manufacturing_risk.invoke({
                    "risk_category": "supply_chain"
                })
            else:
                risk_assessment = assess_manufacturing_risk.invoke({
                    "risk_category": "operational"
                })
            
            state.risk_assessments.append(risk_assessment)
            state.recommendations.append("Review risk assessment findings")
            
            print("✅ Risk assessment completed")
            
        except Exception as e:
            print(f"❌ Risk assessment failed: {str(e)}")
        
        return self._format_response(state)
    
    def _handle_report_generation(self, state: ManufacturingState) -> Dict[str, Any]:
        """Handle report generation requests"""
        print("🔧 Processing report generation request...")
        
        try:
            report_result = write_manufacturing_report.invoke({
                "recipient": "Manufacturing Manager",
                "subject": "Manufacturing Intelligence Summary",
                "content": f"Analysis of request: {state.request}",
                "report_type": "intelligence_summary"
            })
            
            state.reports_generated.append(report_result)
            state.recommendations.append("Review generated manufacturing report")
            
            print("✅ Report generation completed")
            
        except Exception as e:
            print(f"❌ Report generation failed: {str(e)}")
        
        return self._format_response(state)
    
    def _handle_general_request(self, state: ManufacturingState) -> Dict[str, Any]:
        """Handle general manufacturing requests"""
        print("🔧 Processing general manufacturing request...")
        
        # Default to production analysis for general requests
        try:
            analysis = analyze_production_metrics.invoke({
                "metric_type": "oee",
                "equipment_id": "MAIN-LINE-001"
            })
            
            state.analysis_results["general_analysis"] = analysis
            state.recommendations.append("General manufacturing analysis completed")
            
            print("✅ General request processed")
            
        except Exception as e:
            print(f"❌ General request processing failed: {str(e)}")
        
        return self._format_response(state)
    
    def _format_response(self, state: ManufacturingState) -> Dict[str, Any]:
        """Format the final response"""
        return {
            "request": state.request,
            "category": state.category,
            "analysis_results": state.analysis_results,
            "scheduled_tasks": state.scheduled_tasks,
            "risk_assessments": state.risk_assessments,
            "reports_generated": state.reports_generated,
            "recommendations": state.recommendations,
            "status": "completed"
        }

def demo_manufacturing_assistant():
    """Demonstrate the Manufacturing Intelligence Assistant"""
    print("🧪 Manufacturing Intelligence Assistant Demo")
    print("Direct adaptation of LangChain Academy email assistant pattern")
    print("=" * 70)
    
    # Initialize assistant
    assistant = ManufacturingIntelligenceAssistant()
    
    # Test different types of manufacturing requests
    test_requests = [
        "Calculate OEE for our main production line and provide improvement recommendations",
        "Schedule preventive maintenance for our critical equipment",
        "Assess supply chain risks for our key suppliers",
        "Generate a comprehensive manufacturing intelligence report",
        "What are our current defect rates and quality metrics?"
    ]
    
    for i, request in enumerate(test_requests, 1):
        print(f"\n🧪 Test {i}: Manufacturing Request")
        print("-" * 40)
        
        try:
            result = assistant.process_manufacturing_request(request)
            
            print(f"✅ Request processed successfully")
            print(f"Category: {result['category']}")
            print(f"Status: {result['status']}")
            print(f"Recommendations: {len(result['recommendations'])} items")
            
        except Exception as e:
            print(f"❌ Request processing failed: {str(e)}")
        
        print("-" * 40)
    
    print(f"\n" + "=" * 70)
    print("🎯 Manufacturing Intelligence Assistant successfully implemented!")
    print("📧➡️🏭 Email assistant pattern adapted for manufacturing intelligence")
    print("🔧 Ready for Berkeley Haas capstone integration")
    
    return True

if __name__ == "__main__":
    # Run the manufacturing assistant demo
    demo_manufacturing_assistant()