CREATE TABLE [dbo].[RECEIVABLE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [INVOICE_DATE] datetime DEFAULT  NOT NULL,
    [TOTAL_AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [PAID_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [DISCOUNT_GIVEN] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [LAST_PAID_DATE] datetime DEFAULT  NULL,
    [ZERO_DATE] datetime DEFAULT  NULL,
    [TERMS_NET_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [TERMS_NET_DAYS] smallint DEFAULT  NULL,
    [TERMS_NET_DATE] datetime DEFAULT  NULL,
    [TERMS_DISC_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [TERMS_DISC_DAYS] smallint DEFAULT  NULL,
    [TERMS_DISC_DATE] datetime DEFAULT  NULL,
    [TERMS_DISC_PERCENT] DECIMAL(5,3) DEFAULT  NULL,
    [TERMS_DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [FREIGHT_TERMS] NCHAR(1) DEFAULT ('') NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [PREPAY_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [PREPAY_INVOICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT  NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RECV_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [MARKED_FOR_PURGE] NCHAR(1) DEFAULT ('') NOT NULL,
    [NEW_SELL_RATE] DECIMAL(15,8) DEFAULT  NULL,
    [NEW_BUY_RATE] DECIMAL(15,8) DEFAULT  NULL,
    [PRINTED_DATE] datetime DEFAULT  NULL,
    [VAT_BOOK_CODE] NVARCHAR(5) DEFAULT  NULL,
    [VAT_REPORT_NO] int DEFAULT  NULL,
    [VAT_FILENAME] NVARCHAR(15) DEFAULT  NULL,
    [RCR_INVOICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_EXCH_RATE] NCHAR(1) DEFAULT ('') NOT NULL,
    [SALESREP_ID] NVARCHAR(15) DEFAULT  NULL,
    [COMM_PAID_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [VOID_DATE] datetime DEFAULT  NULL,
    [PREPAY_APPLIED_AMT] DECIMAL(23,8) DEFAULT  NULL,
    [LAST_PREPAY_INVOICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [TERMS_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [DISTRIBUTION_METHOD] NVARCHAR(15) DEFAULT  NULL,
    [DISTRIBUTED_DATE] datetime DEFAULT  NULL,
    [DOC_FILE_PATH] NVARCHAR(255) DEFAULT  NULL,
    [DOCUMENT_ID] NVARCHAR(128) DEFAULT  NULL,
    [DIST_DOC_FILE_TYPE] NVARCHAR(4) DEFAULT  NULL,
    [TERMS_DISC_BASIS] NVARCHAR(32) DEFAULT  NULL
)

ALTER TABLE [dbo].[RECEIVABLE] ADD CONSTRAINT [PK_RECEIVABLE] PRIMARY KEY ([INVOICE_ID]);

ALTER TABLE [dbo].[RECEIVABLE] ADD CONSTRAINT [FKEY0025] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[RECEIVABLE] ADD CONSTRAINT [FKEY0067] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);

ALTER TABLE [dbo].[RECEIVABLE] ADD CONSTRAINT [FKEY9390] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[RECEIVABLE] ADD CONSTRAINT [FKEY9588] FOREIGN KEY ([SALESREP_ID]) REFERENCES [dbo].[SALES_REP]([ID]);

ALTER TABLE [dbo].[RECEIVABLE] ADD CONSTRAINT [FKEY9626] FOREIGN KEY ([TERMS_ID]) REFERENCES [dbo].[TERMS]([ID]);
