LEFT JOIN LIVESupplemental.dbo.buyer_assn b
	ON LEFT(w.BUYER_USER_ID,2) = b.Account_ID


SELECT wo.BASE_ID

	, p.QTY_ON_HAND QTY_ON_HAND
	, p.QTY_IN_DEMAND QTY_IN_DEMAND
	, P.BUYER_USER_ID BUYER_USER_ID
	, RTRIM(p.PLANNER_USER_ID) PLANNER_USER_ID
	, p.COMMODITY_CODE
	, p.[DESCRIPTION]
	, ISNULL(wo.DESIRED_WANT_DATE
	, (SELECT MIN(DESIRED_WANT_DATE) FROM WORK_ORDER w WHERE wo.[TYPE] = w.[TYPE] AND wo.BASE_ID = w.BASE_ID AND wo.LOT_ID = w.LOT_ID AND wo.SPLIT_ID = w.SPLIT_ID AND wo.SUB_ID <> w.SUB_ID)) AS DESIRED_WANT_DATE
	, (SELECT TOP 1 STRING_VAL 
		FROM USER_DEF_FIELDS ud
		WHERE ud.PROGRAM_ID = N'VMMFGWIN_WO'
			AND ud.ID = N'UDF-0000070' 
			AND ISNULL(ud.LABEL, '') = ''
			AND wo.[TYPE] + N'~' + wo.BASE_ID + N'~' + N'0' + N'~' + wo.LOT_ID + N'~' + wo.SPLIT_ID = ud.DOCUMENT_ID
	) AS [EXP/FLT]
	, col.user_10 
	, col.USER_1 AS col_user_1
	, CASE 
		WHEN wo.PART_ID = N'REWORK MFG' THEN (SELECT PART_ID 
			FROM WORK_ORDER w 
			WHERE w.[TYPE] = wo.[TYPE] 
				AND w.BASE_ID = wo.BASE_ID 
				AND w.LOT_ID = wo.LOT_ID 
				AND w.SPLIT_ID = wo.SPLIT_ID 
				AND w.SUB_ID = '0'
				AND w.PART_ID <> N'REWORK MFG'
			)
		ELSE wo.PART_ID 
	END AS RWPart
	, co.CUSTOMER_PO_REF
	, CONVERT(NVARCHAR(MAX), CONVERT(VARBINARY(MAX), wb.BITS)) AS WORK_ORDER_NOTES
	, n.NOTE AS CUST_ORDER_NOTATION
	, co.CREATE_DATE AS CUST_ORD_CREATEDATE
	, ISNULL(nullif(material.material, ''), '_blank') AS PartMaterialType
	, ISNULL(NULLIF(alloy.alloy, ''), '_blank') AS Alloy
	, CASE 
		WHEN Material.Material IS NULL and alloy.alloy IS NULL then'_blank'
		ELSE ISNULL(Material.Material, '') + IIF(Material.Material IS NOT NULL, IIF(alloy.alloy IS NOT NULL, ' ', ''), '') + ISNULL(alloy.Alloy, '') 
	END AS MaterialType
	, CO.TOTAL_AMT_ORDERED AS CO_AMOUNT
	, COL.UNIT_PRICE
	, COL.TOTAL_AMT_SHIPPED
	, COL.TOTAL_AMT_ORDERED AS COL_AMOUNT
INTO #cte_wo
FROM WORK_ORDER wo2
JOIN WORK_ORDER wo
	ON wo2.[TYPE] = wo.[TYPE]
	AND wo2.[BASE_ID] = wo.[BASE_ID]
	AND wo2.[LOT_ID] = wo.[LOT_ID]
	AND wo2.[SPLIT_ID] = wo.[SPLIT_ID]
	AND wo2.[SUB_ID] = wo.[SUB_ID]
LEFT JOIN WORK_ORDER EndItem
	ON EndItem.[TYPE] = wo.[TYPE]
	AND EndItem.[BASE_ID] = wo.[BASE_ID]
	AND EndItem.[LOT_ID] = wo.[LOT_ID]
	AND EndItem.[SPLIT_ID] = wo.[SPLIT_ID]
	AND EndItem.[SUB_ID] = '0'
LEFT JOIN WORKORDER_BINARY wb
	ON wb.WORKORDER_BASE_ID = wo.BASE_ID
	AND wb.WORKORDER_LOT_ID = wo.LOT_ID
	AND wb.WORKORDER_SPLIT_ID = wo.SPLIT_ID
	AND wb.WORKORDER_SUB_ID = wo.SUB_ID
	AND wb.WORKORDER_TYPE = wo.[TYPE] 
LEFT JOIN DEMAND_SUPPLY_LINK dsl
	ON dsl.SUPPLY_BASE_ID = wo.BASE_ID
	AND dsl.SUPPLY_LOT_ID = wo.LOT_ID
	AND dsl.SUPPLY_SPLIT_ID = wo.SPLIT_ID