MODEL (
  name staging.stg_operation_sched,
  kind FULL,
  cron '@daily',
  columns (
    schedule_id TEXT,
    workorder_type TEXT,
    workorder_base_id TEXT,
    workorder_lot_id TEXT,
    workorder_split_id TEXT,
    workorder_sub_id TEXT,
    sequence_no INT,
    resource_id TEXT,
    unit_assigned INT,
    start_date TIMESTAMP,
    could_start_date TIMESTAMP,
    finish_date TIMESTAMP,
    could_finish_date TIMESTAMP,
    isdeterminant TEXT,
    direction TEXT,
    delay_reason TEXT,
    user_start_date TIMESTAMP,
    user_finish_date TIMESTAMP,
    sched_resource_id TEXT,
    is_concurrent TEXT,
    group_resource_id TEXT,
    org_resource_id TEXT,
    setup_hours DOUBLE,
    run_hours DOUBLE,
    problem_code INT,
    dispatch_sequence INT
  ),
  grain (
    schedule_id,
    workorder_type,
    workorder_base_id,
    workorder_lot_id,
    workorder_split_id,
    workorder_sub_id,
    sequence_no,
    resource_id,
    unit_assigned
  ),
  audits (
    NOT_NULL(columns = (schedule_id, workorder_base_id))
  )
);

SELECT
  SCHEDULE_ID::TEXT AS schedule_id,
  WORKORDER_TYPE::TEXT AS workorder_type,
  WORKORDER_BASE_ID::TEXT AS workorder_base_id,
  WORKORDER_LOT_ID::TEXT AS workorder_lot_id,
  WORKORDER_SPLIT_ID::TEXT AS workorder_split_id,
  WORKORDER_SUB_ID::TEXT AS workorder_sub_id,
  SEQUENCE_NO::INT AS sequence_no,
  RESOURCE_ID::TEXT AS resource_id,
  UNIT_ASSIGNED::INT AS unit_assigned,
  START_DATE::TIMESTAMP AS start_date,
  COULD_START_DATE::TIMESTAMP AS could_start_date,
  FINISH_DATE::TIMESTAMP AS finish_date,
  COULD_FINISH_DATE::TIMESTAMP AS could_finish_date,
  ISDETERMINANT::TEXT AS isdeterminant,
  DIRECTION::TEXT AS direction,
  DELAY_REASON::TEXT AS delay_reason,
  USER_START_DATE::TIMESTAMP AS user_start_date,
  USER_FINISH_DATE::TIMESTAMP AS user_finish_date,
  SCHED_RESOURCE_ID::TEXT AS sched_resource_id,
  IS_CONCURRENT::TEXT AS is_concurrent,
  GROUP_RESOURCE_ID::TEXT AS group_resource_id,
  ORG_RESOURCE_ID::TEXT AS org_resource_id,
  SETUP_HOURS::DOUBLE AS setup_hours,
  RUN_HOURS::DOUBLE AS run_hours,
  PROBLEM_CODE::INT AS problem_code,
  DISPATCH_SEQUENCE::INT AS dispatch_sequence
FROM raw.operation_sched