MODEL (
  name staging.stg_operation_audit,
  kind FULL,
  cron '@daily',
  columns (
    schedule_id TEXT,
    attempt_no INT,
    resource_id TEXT,
    unit_no INT,
    workorder_type TEXT,
    workorder_base_id TEXT,
    workorder_lot_id TEXT,
    workorder_split_id TEXT,
    workorder_sub_id TEXT,
    sequence_no INT,
    workorder_pass_no INT,
    direction TEXT,
    result TEXT,
    start_date TIMESTAMP,
    finish_date TIMESTAMP,
    could_start_finish TIMESTAMP,
    result_detail TEXT,
    supply_type TEXT,
    supply_base_id TEXT,
    supply_lot_id TEXT,
    supply_split_id TEXT,
    supply_sub_id TEXT,
    supply_seq_no INT,
    supply_no INT,
    part_id TEXT
  ),
  grain (schedule_id, attempt_no, resource_id, unit_no),
  audits (
    NOT_NULL(columns = (schedule_id, attempt_no))
  )
);

SELECT
  SCHEDULE_ID::TEXT AS schedule_id,
  ATTEMPT_NO::INT AS attempt_no,
  RESOURCE_ID::TEXT AS resource_id,
  UNIT_NO::INT AS unit_no,
  WORKORDER_TYPE::TEXT AS workorder_type,
  WORKORDER_BASE_ID::TEXT AS workorder_base_id,
  WORKORDER_LOT_ID::TEXT AS workorder_lot_id,
  WORKORDER_SPLIT_ID::TEXT AS workorder_split_id,
  WORKORDER_SUB_ID::TEXT AS workorder_sub_id,
  SEQUENCE_NO::INT AS sequence_no,
  WORKORDER_PASS_NO::INT AS workorder_pass_no,
  DIRECTION::TEXT AS direction,
  RESULT::TEXT AS result,
  START_DATE::TIMESTAMP AS start_date,
  FINISH_DATE::TIMESTAMP AS finish_date,
  COULD_START_FINISH::TIMESTAMP AS could_start_finish,
  RESULT_DETAIL::TEXT AS result_detail,
  SUPPLY_TYPE::TEXT AS supply_type,
  SUPPLY_BASE_ID::TEXT AS supply_base_id,
  SUPPLY_LOT_ID::TEXT AS supply_lot_id,
  SUPPLY_SPLIT_ID::TEXT AS supply_split_id,
  SUPPLY_SUB_ID::TEXT AS supply_sub_id,
  SUPPLY_SEQ_NO::INT AS supply_seq_no,
  SUPPLY_NO::INT AS supply_no,
  PART_ID::TEXT AS part_id
FROM raw.operation_audit