MODEL (
  name staging.stg_operation_type,
  kind FULL,
  cron '@daily',
  columns (
    id TEXT,
    site_id TEXT,
    description TEXT,
    resource_id TEXT,
    setup_hrs DOUBLE,
    run DOUBLE,
    run_type TEXT,
    load_size_qty DOUBLE,
    move_hrs DOUBLE,
    service_id TEXT,
    transit_days DOUBLE,
    scrap_yield_pct DOUBLE,
    scrap_yield_type TEXT,
    fixed_scrap_units DOUBLE,
    minimum_move_qty DOUBLE,
    override_qtys TEXT,
    begin_traceability TEXT,
    test_id TEXT,
    setup_cost_per_hr DOUBLE,
    run_cost_per_hr DOUBLE,
    run_cost_per_unit DOUBLE,
    bur_per_hr_setup DOUBLE,
    bur_per_hr_run DOUBLE,
    bur_per_unit_run DOUBLE,
    service_base_chg DOUBLE,
    bur_percent_setup DOUBLE,
    bur_percent_run DOUBLE,
    bur_per_operation DOUBLE,
    capacity_usage_max INT,
    capacity_usage_min INT,
    schedule_type INT,
    min_segment_size DOUBLE,
    service_min_chg DOUBLE,
    vendor_id TEXT,
    vendor_service_id TEXT,
    service_part_id TEXT
  ),
  grain (id, site_id),
  audits (UNIQUE_VALUES(columns = (id, site_id)), NOT_NULL(columns = (id, site_id)))
);

SELECT
  ID::TEXT AS id,
  SITE_ID::TEXT AS site_id,
  DESCRIPTION::TEXT AS description,
  RESOURCE_ID::TEXT AS resource_id,
  SETUP_HRS::DOUBLE AS setup_hrs,
  RUN::DOUBLE AS run,
  RUN_TYPE::TEXT AS run_type,
  LOAD_SIZE_QTY::DOUBLE AS load_size_qty,
  MOVE_HRS::DOUBLE AS move_hrs,
  SERVICE_ID::TEXT AS service_id,
  TRANSIT_DAYS::DOUBLE AS transit_days,
  SCRAP_YIELD_PCT::DOUBLE AS scrap_yield_pct,
  SCRAP_YIELD_TYPE::TEXT AS scrap_yield_type,
  FIXED_SCRAP_UNITS::DOUBLE AS fixed_scrap_units,
  MINIMUM_MOVE_QTY::DOUBLE AS minimum_move_qty,
  OVERRIDE_QTYS::TEXT AS override_qtys,
  BEGIN_TRACEABILITY::TEXT AS begin_traceability,
  TEST_ID::TEXT AS test_id,
  SETUP_COST_PER_HR::DOUBLE AS setup_cost_per_hr,
  RUN_COST_PER_HR::DOUBLE AS run_cost_per_hr,
  RUN_COST_PER_UNIT::DOUBLE AS run_cost_per_unit,
  BUR_PER_HR_SETUP::DOUBLE AS bur_per_hr_setup,
  BUR_PER_HR_RUN::DOUBLE AS bur_per_hr_run,
  BUR_PER_UNIT_RUN::DOUBLE AS bur_per_unit_run,
  SERVICE_BASE_CHG::DOUBLE AS service_base_chg,
  BUR_PERCENT_SETUP::DOUBLE AS bur_percent_setup,
  BUR_PERCENT_RUN::DOUBLE AS bur_percent_run,
  BUR_PER_OPERATION::DOUBLE AS bur_per_operation,
  CAPACITY_USAGE_MAX::INT AS capacity_usage_max,
  CAPACITY_USAGE_MIN::INT AS capacity_usage_min,
  SCHEDULE_TYPE::INT AS schedule_type,
  MIN_SEGMENT_SIZE::DOUBLE AS min_segment_size,
  SERVICE_MIN_CHG::DOUBLE AS service_min_chg,
  VENDOR_ID::TEXT AS vendor_id,
  VENDOR_SERVICE_ID::TEXT AS vendor_service_id,
  SERVICE_PART_ID::TEXT AS service_part_id
FROM raw.operation_type