MODEL (
  name staging.stg_operation_sched,
  kind FULL,
  cron '@daily',
  columns (
    schedule_id          TEXT,
    workorder_type       TEXT,
    workorder_base_id    TEXT,
    workorder_lot_id     TEXT,
    workorder_split_id   TEXT,
    workorder_sub_id     TEXT,
    sequence_no          INTEGER,
    resource_id          TEXT,
    unit_assigned        INTEGER,
    start_date           TIMESTAMP,
    could_start_date     TIMESTAMP,
    finish_date          TIMESTAMP,
    could_finish_date    TIMESTAMP,
    isdeterminant        TEXT,
    direction            TEXT,
    delay_reason         TEXT,
    user_start_date      TIMESTAMP,
    user_finish_date     TIMESTAMP,
    sched_resource_id    TEXT,
    is_concurrent        TEXT,
    group_resource_id    TEXT,
    org_resource_id      TEXT,
    setup_hours          DOUBLE,
    run_hours            DOUBLE,
    problem_code         INTEGER,
    dispatch_sequence    INTEGER
  ),
  grain (schedule_id, workorder_type, workorder_base_id, workorder_lot_id, workorder_split_id, workorder_sub_id, sequence_no, resource_id, unit_assigned),
  audits (
    NOT_NULL(columns = (schedule_id, workorder_base_id))
  )
);

SELECT
  CAST(SCHEDULE_ID        AS TEXT)      AS schedule_id,
  CAST(WORKORDER_TYPE     AS TEXT)      AS workorder_type,
  CAST(WORKORDER_BASE_ID  AS TEXT)      AS workorder_base_id,
  CAST(WORKORDER_LOT_ID   AS TEXT)      AS workorder_lot_id,
  CAST(WORKORDER_SPLIT_ID AS TEXT)      AS workorder_split_id,
  CAST(WORKORDER_SUB_ID   AS TEXT)      AS workorder_sub_id,
  CAST(SEQUENCE_NO        AS INTEGER)   AS sequence_no,
  CAST(RESOURCE_ID        AS TEXT)      AS resource_id,
  CAST(UNIT_ASSIGNED      AS INTEGER)   AS unit_assigned,
  CAST(START_DATE         AS TIMESTAMP) AS start_date,
  CAST(COULD_START_DATE   AS TIMESTAMP) AS could_start_date,
  CAST(FINISH_DATE        AS TIMESTAMP) AS finish_date,
  CAST(COULD_FINISH_DATE  AS TIMESTAMP) AS could_finish_date,
  CAST(ISDETERMINANT      AS TEXT)      AS isdeterminant,
  CAST(DIRECTION          AS TEXT)      AS direction,
  CAST(DELAY_REASON       AS TEXT)      AS delay_reason,
  CAST(USER_START_DATE    AS TIMESTAMP) AS user_start_date,
  CAST(USER_FINISH_DATE   AS TIMESTAMP) AS user_finish_date,
  CAST(SCHED_RESOURCE_ID  AS TEXT)      AS sched_resource_id,
  CAST(IS_CONCURRENT      AS TEXT)      AS is_concurrent,
  CAST(GROUP_RESOURCE_ID  AS TEXT)      AS group_resource_id,
  CAST(ORG_RESOURCE_ID    AS TEXT)      AS org_resource_id,
  CAST(SETUP_HOURS        AS DOUBLE)    AS setup_hours,
  CAST(RUN_HOURS          AS DOUBLE)    AS run_hours,
  CAST(PROBLEM_CODE       AS INTEGER)   AS problem_code,
  CAST(DISPATCH_SEQUENCE  AS INTEGER)   AS dispatch_sequence
FROM raw.operation_sched;
