MODEL (
  name staging.stg_operation_type,
  kind FULL,
  cron '@daily',
  columns (
    id                   TEXT,
    site_id              TEXT,
    description          TEXT,
    resource_id          TEXT,
    setup_hrs            DOUBLE,
    run                  DOUBLE,
    run_type             TEXT,
    load_size_qty        DOUBLE,
    move_hrs             DOUBLE,
    service_id           TEXT,
    transit_days         DOUBLE,
    scrap_yield_pct      DOUBLE,
    scrap_yield_type     TEXT,
    fixed_scrap_units    DOUBLE,
    minimum_move_qty     DOUBLE,
    override_qtys        TEXT,
    begin_traceability   TEXT,
    test_id              TEXT,
    setup_cost_per_hr    DOUBLE,
    run_cost_per_hr      DOUBLE,
    run_cost_per_unit    DOUBLE,
    bur_per_hr_setup     DOUBLE,
    bur_per_hr_run       DOUBLE,
    bur_per_unit_run     DOUBLE,
    service_base_chg     DOUBLE,
    bur_percent_setup    DOUBLE,
    bur_percent_run      DOUBLE,
    bur_per_operation    DOUBLE,
    capacity_usage_max   INTEGER,
    capacity_usage_min   INTEGER,
    schedule_type        INTEGER,
    min_segment_size     DOUBLE,
    service_min_chg      DOUBLE,
    vendor_id            TEXT,
    vendor_service_id    TEXT,
    service_part_id      TEXT
  ),
  grain (id, site_id),
  audits (
    UNIQUE_VALUES(columns = (id, site_id)),
    NOT_NULL(columns = (id, site_id))
  )
);

SELECT
  CAST(ID                 AS TEXT)   AS id,
  CAST(SITE_ID            AS TEXT)   AS site_id,
  CAST(DESCRIPTION        AS TEXT)   AS description,
  CAST(RESOURCE_ID        AS TEXT)   AS resource_id,
  CAST(SETUP_HRS          AS DOUBLE) AS setup_hrs,
  CAST(RUN                AS DOUBLE) AS run,
  CAST(RUN_TYPE           AS TEXT)   AS run_type,
  CAST(LOAD_SIZE_QTY      AS DOUBLE) AS load_size_qty,
  CAST(MOVE_HRS           AS DOUBLE) AS move_hrs,
  CAST(SERVICE_ID         AS TEXT)   AS service_id,
  CAST(TRANSIT_DAYS       AS DOUBLE) AS transit_days,
  CAST(SCRAP_YIELD_PCT    AS DOUBLE) AS scrap_yield_pct,
  CAST(SCRAP_YIELD_TYPE   AS TEXT)   AS scrap_yield_type,
  CAST(FIXED_SCRAP_UNITS  AS DOUBLE) AS fixed_scrap_units,
  CAST(MINIMUM_MOVE_QTY   AS DOUBLE) AS minimum_move_qty,
  CAST(OVERRIDE_QTYS      AS TEXT)   AS override_qtys,
  CAST(BEGIN_TRACEABILITY AS TEXT)   AS begin_traceability,
  CAST(TEST_ID            AS TEXT)   AS test_id,
  CAST(SETUP_COST_PER_HR  AS DOUBLE) AS setup_cost_per_hr,
  CAST(RUN_COST_PER_HR    AS DOUBLE) AS run_cost_per_hr,
  CAST(RUN_COST_PER_UNIT  AS DOUBLE) AS run_cost_per_unit,
  CAST(BUR_PER_HR_SETUP   AS DOUBLE) AS bur_per_hr_setup,
  CAST(BUR_PER_HR_RUN     AS DOUBLE) AS bur_per_hr_run,
  CAST(BUR_PER_UNIT_RUN   AS DOUBLE) AS bur_per_unit_run,
  CAST(SERVICE_BASE_CHG   AS DOUBLE) AS service_base_chg,
  CAST(BUR_PERCENT_SETUP  AS DOUBLE) AS bur_percent_setup,
  CAST(BUR_PERCENT_RUN    AS DOUBLE) AS bur_percent_run,
  CAST(BUR_PER_OPERATION  AS DOUBLE) AS bur_per_operation,
  CAST(CAPACITY_USAGE_MAX AS INTEGER) AS capacity_usage_max,
  CAST(CAPACITY_USAGE_MIN AS INTEGER) AS capacity_usage_min,
  CAST(SCHEDULE_TYPE      AS INTEGER) AS schedule_type,
  CAST(MIN_SEGMENT_SIZE   AS DOUBLE)  AS min_segment_size,
  CAST(SERVICE_MIN_CHG    AS DOUBLE)  AS service_min_chg,
  CAST(VENDOR_ID          AS TEXT)    AS vendor_id,
  CAST(VENDOR_SERVICE_ID  AS TEXT)    AS vendor_service_id,
  CAST(SERVICE_PART_ID    AS TEXT)    AS service_part_id
FROM raw.operation_type;
