MODEL (
  name staging.stg_operation_audit,
  kind FULL,
  cron '@daily',
  columns (
    schedule_id          TEXT,
    attempt_no           INTEGER,
    resource_id          TEXT,
    unit_no              INTEGER,
    workorder_type       TEXT,
    workorder_base_id    TEXT,
    workorder_lot_id     TEXT,
    workorder_split_id   TEXT,
    workorder_sub_id     TEXT,
    sequence_no          INTEGER,
    workorder_pass_no    INTEGER,
    direction            TEXT,
    result               TEXT,
    start_date           TIMESTAMP,
    finish_date          TIMESTAMP,
    could_start_finish   TIMESTAMP,
    result_detail        TEXT,
    supply_type          TEXT,
    supply_base_id       TEXT,
    supply_lot_id        TEXT,
    supply_split_id      TEXT,
    supply_sub_id        TEXT,
    supply_seq_no        INTEGER,
    supply_no            INTEGER,
    part_id              TEXT
  ),
  grain (schedule_id, attempt_no, resource_id, unit_no),
  audits (
    NOT_NULL(columns = (schedule_id, attempt_no))
  )
);

SELECT
  CAST(SCHEDULE_ID         AS TEXT)      AS schedule_id,
  CAST(ATTEMPT_NO          AS INTEGER)   AS attempt_no,
  CAST(RESOURCE_ID         AS TEXT)      AS resource_id,
  CAST(UNIT_NO             AS INTEGER)   AS unit_no,
  CAST(WORKORDER_TYPE      AS TEXT)      AS workorder_type,
  CAST(WORKORDER_BASE_ID   AS TEXT)      AS workorder_base_id,
  CAST(WORKORDER_LOT_ID    AS TEXT)      AS workorder_lot_id,
  CAST(WORKORDER_SPLIT_ID  AS TEXT)      AS workorder_split_id,
  CAST(WORKORDER_SUB_ID    AS TEXT)      AS workorder_sub_id,
  CAST(SEQUENCE_NO         AS INTEGER)   AS sequence_no,
  CAST(WORKORDER_PASS_NO   AS INTEGER)   AS workorder_pass_no,
  CAST(DIRECTION           AS TEXT)      AS direction,
  CAST(RESULT              AS TEXT)      AS result,
  CAST(START_DATE          AS TIMESTAMP) AS start_date,
  CAST(FINISH_DATE         AS TIMESTAMP) AS finish_date,
  CAST(COULD_START_FINISH  AS TIMESTAMP) AS could_start_finish,
  CAST(RESULT_DETAIL       AS TEXT)      AS result_detail,
  CAST(SUPPLY_TYPE         AS TEXT)      AS supply_type,
  CAST(SUPPLY_BASE_ID      AS TEXT)      AS supply_base_id,
  CAST(SUPPLY_LOT_ID       AS TEXT)      AS supply_lot_id,
  CAST(SUPPLY_SPLIT_ID     AS TEXT)      AS supply_split_id,
  CAST(SUPPLY_SUB_ID       AS TEXT)      AS supply_sub_id,
  CAST(SUPPLY_SEQ_NO       AS INTEGER)   AS supply_seq_no,
  CAST(SUPPLY_NO           AS INTEGER)   AS supply_no,
  CAST(PART_ID             AS TEXT)      AS part_id
FROM raw.operation_audit;
