MODEL (
  name staging.stg_operation,
  kind FULL,
  cron '@daily',
  columns (
    workorder_type TEXT,
    workorder_base_id TEXT,
    workorder_lot_id TEXT,
    workorder_split_id TEXT,
    workorder_sub_id TEXT,
    sequence_no INT,
    resource_id TEXT,
    setup_hrs DOUBLE,
    run DOUBLE,
    run_type TEXT,
    load_size_qty DOUBLE,
    run_hrs DOUBLE,
    move_hrs DOUBLE,
    transit_days DOUBLE,
    service_id TEXT,
    scrap_yield_pct DOUBLE,
    scrap_yield_type TEXT,
    fixed_scrap_units DOUBLE,
    minimum_move_qty DOUBLE,
    calc_start_qty DOUBLE,
    calc_end_qty DOUBLE,
    completed_qty DOUBLE,
    deviated_qty DOUBLE,
    act_setup_hrs DOUBLE,
    act_run_hrs DOUBLE,
    status TEXT,
    setup_completed TEXT,
    service_begin_date TIMESTAMP,
    close_date TIMESTAMP,
    operation_type TEXT,
    drawing_id TEXT,
    drawing_rev_no TEXT,
    sched_start_date TIMESTAMP,
    sched_finish_date TIMESTAMP,
    could_finish_date TIMESTAMP,
    setup_cost_per_hr DOUBLE,
    run_cost_per_hr DOUBLE,
    run_cost_per_unit DOUBLE,
    bur_per_hr_setup DOUBLE,
    bur_per_hr_run DOUBLE,
    bur_per_unit_run DOUBLE,
    est_ttl_lab_cost DOUBLE,
    est_ttl_bur_cost DOUBLE,
    est_ttl_ser_cost DOUBLE,
    act_ttl_lab_cost DOUBLE,
    act_ttl_bur_cost DOUBLE,
    act_ttl_ser_cost DOUBLE,
    percent_compl TEXT,
    dispatched_qty DOUBLE,
    vendor_id TEXT,
    site_id TEXT
  ),
  grain (
    workorder_type,
    workorder_base_id,
    workorder_lot_id,
    workorder_split_id,
    workorder_sub_id,
    sequence_no
  ),
  audits (
    NOT_NULL(columns = (workorder_base_id, sequence_no))
  )
);

SELECT
  WORKORDER_TYPE::TEXT AS workorder_type,
  WORKORDER_BASE_ID::TEXT AS workorder_base_id,
  WORKORDER_LOT_ID::TEXT AS workorder_lot_id,
  WORKORDER_SPLIT_ID::TEXT AS workorder_split_id,
  WORKORDER_SUB_ID::TEXT AS workorder_sub_id,
  SEQUENCE_NO::INT AS sequence_no,
  RESOURCE_ID::TEXT AS resource_id,
  SETUP_HRS::DOUBLE AS setup_hrs,
  RUN::DOUBLE AS run,
  RUN_TYPE::TEXT AS run_type,
  LOAD_SIZE_QTY::DOUBLE AS load_size_qty,
  RUN_HRS::DOUBLE AS run_hrs,
  MOVE_HRS::DOUBLE AS move_hrs,
  TRANSIT_DAYS::DOUBLE AS transit_days,
  SERVICE_ID::TEXT AS service_id,
  SCRAP_YIELD_PCT::DOUBLE AS scrap_yield_pct,
  SCRAP_YIELD_TYPE::TEXT AS scrap_yield_type,
  FIXED_SCRAP_UNITS::DOUBLE AS fixed_scrap_units,
  MINIMUM_MOVE_QTY::DOUBLE AS minimum_move_qty,
  CALC_START_QTY::DOUBLE AS calc_start_qty,
  CALC_END_QTY::DOUBLE AS calc_end_qty,
  COMPLETED_QTY::DOUBLE AS completed_qty,
  DEVIATED_QTY::DOUBLE AS deviated_qty,
  ACT_SETUP_HRS::DOUBLE AS act_setup_hrs,
  ACT_RUN_HRS::DOUBLE AS act_run_hrs,
  STATUS::TEXT AS status,
  SETUP_COMPLETED::TEXT AS setup_completed,
  SERVICE_BEGIN_DATE::TIMESTAMP AS service_begin_date,
  CLOSE_DATE::TIMESTAMP AS close_date,
  OPERATION_TYPE::TEXT AS operation_type,
  DRAWING_ID::TEXT AS drawing_id,
  DRAWING_REV_NO::TEXT AS drawing_rev_no,
  SCHED_START_DATE::TIMESTAMP AS sched_start_date,
  SCHED_FINISH_DATE::TIMESTAMP AS sched_finish_date,
  COULD_FINISH_DATE::TIMESTAMP AS could_finish_date,
  SETUP_COST_PER_HR::DOUBLE AS setup_cost_per_hr,
  RUN_COST_PER_HR::DOUBLE AS run_cost_per_hr,
  RUN_COST_PER_UNIT::DOUBLE AS run_cost_per_unit,
  BUR_PER_HR_SETUP::DOUBLE AS bur_per_hr_setup,
  BUR_PER_HR_RUN::DOUBLE AS bur_per_hr_run,
  BUR_PER_UNIT_RUN::DOUBLE AS bur_per_unit_run,
  EST_TTL_LAB_COST::DOUBLE AS est_ttl_lab_cost,
  EST_TTL_BUR_COST::DOUBLE AS est_ttl_bur_cost,
  EST_TTL_SER_COST::DOUBLE AS est_ttl_ser_cost,
  ACT_TTL_LAB_COST::DOUBLE AS act_ttl_lab_cost,
  ACT_TTL_BUR_COST::DOUBLE AS act_ttl_bur_cost,
  ACT_TTL_SER_COST::DOUBLE AS act_ttl_ser_cost,
  PERCENT_COMPL::TEXT AS percent_compl,
  DISPATCHED_QTY::DOUBLE AS dispatched_qty,
  VENDOR_ID::TEXT AS vendor_id,
  SITE_ID::TEXT AS site_id
FROM raw.operation