MODEL (
  name staging.stg_operation,
  kind FULL,
  cron '@daily',
  columns (
    workorder_type          TEXT,
    workorder_base_id       TEXT,
    workorder_lot_id        TEXT,
    workorder_split_id      TEXT,
    workorder_sub_id        TEXT,
    sequence_no             INTEGER,
    resource_id             TEXT,
    setup_hrs               DOUBLE,
    run                     DOUBLE,
    run_type                TEXT,
    load_size_qty           DOUBLE,
    run_hrs                 DOUBLE,
    move_hrs                DOUBLE,
    transit_days            DOUBLE,
    service_id              TEXT,
    scrap_yield_pct         DOUBLE,
    scrap_yield_type        TEXT,
    fixed_scrap_units       DOUBLE,
    minimum_move_qty        DOUBLE,
    calc_start_qty          DOUBLE,
    calc_end_qty            DOUBLE,
    completed_qty           DOUBLE,
    deviated_qty            DOUBLE,
    act_setup_hrs           DOUBLE,
    act_run_hrs             DOUBLE,
    status                  TEXT,
    setup_completed         TEXT,
    service_begin_date      TIMESTAMP,
    close_date              TIMESTAMP,
    operation_type          TEXT,
    drawing_id              TEXT,
    drawing_rev_no          TEXT,
    sched_start_date        TIMESTAMP,
    sched_finish_date       TIMESTAMP,
    could_finish_date       TIMESTAMP,
    setup_cost_per_hr       DOUBLE,
    run_cost_per_hr         DOUBLE,
    run_cost_per_unit       DOUBLE,
    bur_per_hr_setup        DOUBLE,
    bur_per_hr_run          DOUBLE,
    bur_per_unit_run        DOUBLE,
    est_ttl_lab_cost        DOUBLE,
    est_ttl_bur_cost        DOUBLE,
    est_ttl_ser_cost        DOUBLE,
    act_ttl_lab_cost        DOUBLE,
    act_ttl_bur_cost        DOUBLE,
    act_ttl_ser_cost        DOUBLE,
    percent_compl           TEXT,
    dispatched_qty          DOUBLE,
    vendor_id               TEXT,
    site_id                 TEXT
  ),
  grain (workorder_type, workorder_base_id, workorder_lot_id, workorder_split_id, workorder_sub_id, sequence_no),
  audits (
    NOT_NULL(columns = (workorder_base_id, sequence_no))
  )
);

SELECT
  CAST(WORKORDER_TYPE       AS TEXT)      AS workorder_type,
  CAST(WORKORDER_BASE_ID    AS TEXT)      AS workorder_base_id,
  CAST(WORKORDER_LOT_ID     AS TEXT)      AS workorder_lot_id,
  CAST(WORKORDER_SPLIT_ID   AS TEXT)      AS workorder_split_id,
  CAST(WORKORDER_SUB_ID     AS TEXT)      AS workorder_sub_id,
  CAST(SEQUENCE_NO          AS INTEGER)   AS sequence_no,
  CAST(RESOURCE_ID          AS TEXT)      AS resource_id,
  CAST(SETUP_HRS            AS DOUBLE)    AS setup_hrs,
  CAST(RUN                  AS DOUBLE)    AS run,
  CAST(RUN_TYPE             AS TEXT)      AS run_type,
  CAST(LOAD_SIZE_QTY        AS DOUBLE)    AS load_size_qty,
  CAST(RUN_HRS              AS DOUBLE)    AS run_hrs,
  CAST(MOVE_HRS             AS DOUBLE)    AS move_hrs,
  CAST(TRANSIT_DAYS         AS DOUBLE)    AS transit_days,
  CAST(SERVICE_ID           AS TEXT)      AS service_id,
  CAST(SCRAP_YIELD_PCT      AS DOUBLE)    AS scrap_yield_pct,
  CAST(SCRAP_YIELD_TYPE     AS TEXT)      AS scrap_yield_type,
  CAST(FIXED_SCRAP_UNITS    AS DOUBLE)    AS fixed_scrap_units,
  CAST(MINIMUM_MOVE_QTY     AS DOUBLE)    AS minimum_move_qty,
  CAST(CALC_START_QTY       AS DOUBLE)    AS calc_start_qty,
  CAST(CALC_END_QTY         AS DOUBLE)    AS calc_end_qty,
  CAST(COMPLETED_QTY        AS DOUBLE)    AS completed_qty,
  CAST(DEVIATED_QTY         AS DOUBLE)    AS deviated_qty,
  CAST(ACT_SETUP_HRS        AS DOUBLE)    AS act_setup_hrs,
  CAST(ACT_RUN_HRS          AS DOUBLE)    AS act_run_hrs,
  CAST(STATUS               AS TEXT)      AS status,
  CAST(SETUP_COMPLETED      AS TEXT)      AS setup_completed,
  CAST(SERVICE_BEGIN_DATE   AS TIMESTAMP) AS service_begin_date,
  CAST(CLOSE_DATE           AS TIMESTAMP) AS close_date,
  CAST(OPERATION_TYPE       AS TEXT)      AS operation_type,
  CAST(DRAWING_ID           AS TEXT)      AS drawing_id,
  CAST(DRAWING_REV_NO       AS TEXT)      AS drawing_rev_no,
  CAST(SCHED_START_DATE     AS TIMESTAMP) AS sched_start_date,
  CAST(SCHED_FINISH_DATE    AS TIMESTAMP) AS sched_finish_date,
  CAST(COULD_FINISH_DATE    AS TIMESTAMP) AS could_finish_date,
  CAST(SETUP_COST_PER_HR    AS DOUBLE)    AS setup_cost_per_hr,
  CAST(RUN_COST_PER_HR      AS DOUBLE)    AS run_cost_per_hr,
  CAST(RUN_COST_PER_UNIT    AS DOUBLE)    AS run_cost_per_unit,
  CAST(BUR_PER_HR_SETUP     AS DOUBLE)    AS bur_per_hr_setup,
  CAST(BUR_PER_HR_RUN       AS DOUBLE)    AS bur_per_hr_run,
  CAST(BUR_PER_UNIT_RUN     AS DOUBLE)    AS bur_per_unit_run,
  CAST(EST_TTL_LAB_COST     AS DOUBLE)    AS est_ttl_lab_cost,
  CAST(EST_TTL_BUR_COST     AS DOUBLE)    AS est_ttl_bur_cost,
  CAST(EST_TTL_SER_COST     AS DOUBLE)    AS est_ttl_ser_cost,
  CAST(ACT_TTL_LAB_COST     AS DOUBLE)    AS act_ttl_lab_cost,
  CAST(ACT_TTL_BUR_COST     AS DOUBLE)    AS act_ttl_bur_cost,
  CAST(ACT_TTL_SER_COST     AS DOUBLE)    AS act_ttl_ser_cost,
  CAST(PERCENT_COMPL        AS TEXT)      AS percent_compl,
  CAST(DISPATCHED_QTY       AS DOUBLE)    AS dispatched_qty,
  CAST(VENDOR_ID            AS TEXT)      AS vendor_id,
  CAST(SITE_ID              AS TEXT)      AS site_id
FROM raw.operation;
