#!/usr/bin/env python3

"""
networkx_build.py: Optional Python NetworkX exporter
Reads from the CSV files generated by build_graph_node.js and creates a NetworkX graph
"""

import csv
import json
import os
import networkx as nx
import matplotlib.pyplot as plt

NODES_CSV = os.path.join(os.path.dirname(__file__), '..', 'graph_nodes.csv')
EDGES_CSV = os.path.join(os.path.dirname(__file__), '..', 'graph_edges.csv')
OUTPUT_PNG = os.path.join(os.path.dirname(__file__), '..', 'supply_chain_graph.png')

def load_graph():
    """Load graph from CSV files into NetworkX DiGraph"""
    print('🔨 Building NetworkX graph from CSV files...')
    
    G = nx.DiGraph()
    
    # Load nodes
    if not os.path.exists(NODES_CSV):
        print(f'❌ Error: {NODES_CSV} not found. Run "npm run build-graph-node" first.')
        return None
        
    print(f'📦 Loading nodes from {NODES_CSV}...')
    with open(NODES_CSV, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            node_id = row['NODE_ID']
            node_type = row['TYPE']
            label = row['LABEL']
            try:
                data = json.loads(row['DATA_JSON'])
            except json.JSONDecodeError:
                data = {}
            
            # Avoid conflict with NetworkX's internal 'type' attribute
            # NetworkX reserves 'type' for internal use, so we use 'node_type' instead
            attrs = {'node_type': node_type, 'label': label}
            attrs.update(data)
            G.add_node(node_id, **attrs)
    
    print(f'  ✅ Loaded {G.number_of_nodes()} nodes')
    
    # Load edges
    if not os.path.exists(EDGES_CSV):
        print(f'❌ Error: {EDGES_CSV} not found.')
        return None
        
    print(f'🔗 Loading edges from {EDGES_CSV}...')
    with open(EDGES_CSV, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            source = row['SOURCE']
            target = row['TARGET']
            relationship = row['RELATIONSHIP']
            try:
                data = json.loads(row['DATA_JSON'])
            except json.JSONDecodeError:
                data = {}
            
            # Merge relationship with data attributes
            attrs = {'edge_relationship': relationship}
            attrs.update(data)
            G.add_edge(source, target, **attrs)
    
    print(f'  ✅ Loaded {G.number_of_edges()} edges')
    
    return G

def analyze_graph(G):
    """Print graph analytics"""
    print('')
    print('📊 NetworkX Graph Analytics:')
    print(f'  Nodes: {G.number_of_nodes()}')
    print(f'  Edges: {G.number_of_edges()}')
    print(f'  Is DAG: {nx.is_directed_acyclic_graph(G)}')
    
    # Node types breakdown
    node_types = {}
    for node, data in G.nodes(data=True):
        node_type = data.get('node_type', 'unknown')
        node_types[node_type] = node_types.get(node_type, 0) + 1
    
    print('  Node types:')
    for node_type, count in sorted(node_types.items()):
        print(f'    - {node_type}: {count}')
    
    # Check connectivity
    if G.number_of_nodes() > 0:
        weakly_connected = nx.number_weakly_connected_components(G)
        print(f'  Weakly connected components: {weakly_connected}')

def visualize_graph(G):
    """Create a simple visualization of the graph"""
    print('')
    print('🎨 Creating visualization...')
    
    plt.figure(figsize=(14, 10))
    
    # Use hierarchical layout
    pos = nx.spring_layout(G, k=1, iterations=50)
    
    # Color nodes by type
    color_map = {
        'supplier': '#FF6B6B',
        'part': '#4ECDC4',
        'assembly': '#45B7D1',
        'product': '#96CEB4',
    }
    
    node_colors = [color_map.get(G.nodes[node].get('node_type', 'unknown'), '#95A5A6') for node in G.nodes()]
    node_labels = {node: G.nodes[node].get('label', node) for node in G.nodes()}
    
    # Draw graph
    nx.draw_networkx_nodes(G, pos, node_color=node_colors, node_size=500, alpha=0.9)
    nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=8, font_weight='bold')
    nx.draw_networkx_edges(G, pos, edge_color='#7F8C8D', arrows=True, arrowsize=15, alpha=0.5)
    
    plt.title('Supply Chain Network', fontsize=16, fontweight='bold')
    plt.axis('off')
    plt.tight_layout()
    
    plt.savefig(OUTPUT_PNG, dpi=150, bbox_inches='tight')
    print(f'✅ Visualization saved to {OUTPUT_PNG}')

def main():
    print('🐍 Python NetworkX Supply Chain Graph Builder')
    print('')
    
    G = load_graph()
    if G is None:
        return
    
    analyze_graph(G)
    visualize_graph(G)
    
    print('')
    print('🎉 NetworkX graph analysis complete!')
    print('')
    print('You can now:')
    print('  - View the visualization in supply_chain_graph.png')
    print('  - Use the NetworkX graph object for further analysis')
    print('  - Run graph algorithms (shortest path, centrality, etc.)')

if __name__ == '__main__':
    main()
