CREATE TABLE [dbo].[OPERATION_RESOURCE_DISPATCH] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [SEQUENCE_NO] smallint DEFAULT  NOT NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DISPATCH_SEQUENCE] int DEFAULT ((99999)) NOT NULL
)

ALTER TABLE [dbo].[OPERATION_RESOURCE_DISPATCH] ADD CONSTRAINT [PK_OPERATION_RESOURCE_DISPATCH] PRIMARY KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [SEQUENCE_NO], [RESOURCE_ID]);

ALTER TABLE [dbo].[OPERATION_RESOURCE_DISPATCH] ADD CONSTRAINT [FK_OPER_RES_DISP_OPER] FOREIGN KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [SEQUENCE_NO]) REFERENCES [dbo].[OPERATION]([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [SEQUENCE_NO]);
