CREATE TABLE [dbo].[BUFFER_STATUS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] int DEFAULT  NOT NULL,
    [BUFFER_ID] int DEFAULT  NOT NULL,
    [STATUS_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [BUFFER_STATUS] DECIMAL(5,1) DEFAULT  NOT NULL,
    [PROBLEM_CLASS] NVARCHAR(15) DEFAULT  NULL,
    [PROBLEM_DESCR] image DEFAULT  NULL,
    [EMERGENCY_ZONE] int DEFAULT  NULL,
    [YELLOW_ZONE] int DEFAULT  NULL
)

ALTER TABLE [dbo].[BUFFER_STATUS] ADD CONSTRAINT [PK_BUFFER_STATUS] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[BUFFER_STATUS] ADD CONSTRAINT [FKEY_BUFSTAT_BUF] FOREIGN KEY ([BUFFER_ID]) REFERENCES [dbo].[BUFFER]([ID]);
