CREATE TABLE [dbo].[INTRA_RECEIVR_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RECEIVER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RECEIVER_LINE_NO] smallint DEFAULT  NOT NULL,
    [ARRIVAL_CODE] NVARCHAR(25) DEFAULT  NULL,
    [TRANS_CODE] NVARCHAR(25) DEFAULT  NULL,
    [TO_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [FROM_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [ORIG_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [REGION_ID] NVARCHAR(2) DEFAULT  NULL,
    [NATURE_OF_TRANS] int DEFAULT  NULL,
    [MODE_OF_TRANSPORT] int DEFAULT  NULL,
    [EXCISE_PRICE] DECIMAL(23,8) DEFAULT  NULL,
    [TARIFF_CODE] NVARCHAR(15) DEFAULT  NULL,
    [INTRA_REPORT_NO] int DEFAULT  NULL,
    [INTRA_FILENAME] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[INTRA_RECEIVR_LINE] ADD CONSTRAINT [PK_INTRA_RECEIVR_LINE] PRIMARY KEY ([RECEIVER_ID], [RECEIVER_LINE_NO]);

ALTER TABLE [dbo].[INTRA_RECEIVR_LINE] ADD CONSTRAINT [FK_INTREC_FROM_CTRY] FOREIGN KEY ([FROM_COUNTRY_ID]) REFERENCES [dbo].[COUNTRY]([ID]);

ALTER TABLE [dbo].[INTRA_RECEIVR_LINE] ADD CONSTRAINT [FK_INTREC_ORIG_CTRY] FOREIGN KEY ([ORIG_COUNTRY_ID]) REFERENCES [dbo].[COUNTRY]([ID]);

ALTER TABLE [dbo].[INTRA_RECEIVR_LINE] ADD CONSTRAINT [FK_INTREC_TO_CTRY] FOREIGN KEY ([TO_COUNTRY_ID]) REFERENCES [dbo].[COUNTRY]([ID]);

ALTER TABLE [dbo].[INTRA_RECEIVR_LINE] ADD CONSTRAINT [FKEY9341] FOREIGN KEY ([RECEIVER_ID], [RECEIVER_LINE_NO]) REFERENCES [dbo].[RECEIVER_LINE]([RECEIVER_ID], [LINE_NO]);

ALTER TABLE [dbo].[INTRA_RECEIVR_LINE] ADD CONSTRAINT [FKEY9342] FOREIGN KEY ([ARRIVAL_CODE]) REFERENCES [dbo].[PORT_OF_ARRIVAL]([CODE]);

ALTER TABLE [dbo].[INTRA_RECEIVR_LINE] ADD CONSTRAINT [FKEY9343] FOREIGN KEY ([TRANS_CODE]) REFERENCES [dbo].[PORT_OF_TRANS]([CODE]);

ALTER TABLE [dbo].[INTRA_RECEIVR_LINE] ADD CONSTRAINT [FKEY9347] FOREIGN KEY ([REGION_ID]) REFERENCES [dbo].[REGION]([ID]);

ALTER TABLE [dbo].[INTRA_RECEIVR_LINE] ADD CONSTRAINT [FKEY9348] FOREIGN KEY ([NATURE_OF_TRANS]) REFERENCES [dbo].[NATURE_OF_TRANS]([CODE]);

ALTER TABLE [dbo].[INTRA_RECEIVR_LINE] ADD CONSTRAINT [FKEY9349] FOREIGN KEY ([MODE_OF_TRANSPORT]) REFERENCES [dbo].[MODE_OF_TRANSPORT]([CODE]);

ALTER TABLE [dbo].[INTRA_RECEIVR_LINE] ADD CONSTRAINT [FKEY9350] FOREIGN KEY ([TARIFF_CODE]) REFERENCES [dbo].[TARIFF]([CODE]);
