CREATE TABLE [dbo].[COMMODITY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [UNIV_PLAN_MATERIAL] NVARCHAR(1) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [ACTIVE_FLAG] NCHAR(1) DEFAULT ('Y') NOT NULL
)

ALTER TABLE [dbo].[COMMODITY] ADD CONSTRAINT [PK_COMMODITY] PRIMARY KEY ([CODE]);
