CREATE TABLE [dbo].[APS_TABLE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [LAYOUT_KEY] NCHAR(3) DEFAULT  NOT NULL,
    [SEGMENT_TYPE] NCHAR(3) DEFAULT  NOT NULL,
    [TABLE_NAME] NVARCHAR(18) DEFAULT  NOT NULL,
    [JOIN] image DEFAULT  NULL,
    [PRIMARY_KEY] NVARCHAR(250) DEFAULT  NULL
)

ALTER TABLE [dbo].[APS_TABLE] ADD CONSTRAINT [PK_APS_TABLE] PRIMARY KEY ([LAYOUT_KEY], [SEGMENT_TYPE], [TABLE_NAME]);
