CREATE TABLE [dbo].[INV_TRANS_DIST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [IN_TRANS_ID] int DEFAULT  NOT NULL,
    [OUT_TRANS_ID] int DEFAULT  NOT NULL,
    [DIST_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [ACT_MATERIAL_COST] DECIMAL(23,8) DEFAULT  NOT NULL,
    [ACT_LABOR_COST] DECIMAL(23,8) DEFAULT  NOT NULL,
    [ACT_BURDEN_COST] DECIMAL(23,8) DEFAULT  NOT NULL,
    [ACT_SERVICE_COST] DECIMAL(23,8) DEFAULT  NOT NULL,
    [DEMAND_SUPPLY_ID] int DEFAULT  NULL
)

ALTER TABLE [dbo].[INV_TRANS_DIST] ADD CONSTRAINT [PK_INV_TRANS_DIST] PRIMARY KEY ([IN_TRANS_ID], [OUT_TRANS_ID]);

ALTER TABLE [dbo].[INV_TRANS_DIST] ADD CONSTRAINT [FKEY0173] FOREIGN KEY ([IN_TRANS_ID]) REFERENCES [dbo].[INVENTORY_TRANS]([TRANSACTION_ID]);

ALTER TABLE [dbo].[INV_TRANS_DIST] ADD CONSTRAINT [FKEY0174] FOREIGN KEY ([OUT_TRANS_ID]) REFERENCES [dbo].[INVENTORY_TRANS]([TRANSACTION_ID]);
