CREATE TABLE [dbo].[RECEIVABLE_CURR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[RECEIVABLE_CURR] ADD CONSTRAINT [PK_RECEIVABLE_CURR] PRIMARY KEY ([INVOICE_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[RECEIVABLE_CURR] ADD CONSTRAINT [FKEY9391] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[RECEIVABLE_CURR] ADD CONSTRAINT [FKEY9392] FOREIGN KEY ([INVOICE_ID]) REFERENCES [dbo].[RECEIVABLE]([INVOICE_ID]);
