CREATE TABLE [dbo].[WIP_TRANSACTION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TRANSACTION_ID] int DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TRANSACTION_DATE] datetime DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [TRANSFER_TRANS_ID] int DEFAULT  NULL,
    [MOVE_REQUEST_ID] NVARCHAR(15) DEFAULT  NULL,
    [MOVE_REQUEST_LINE_NO] int DEFAULT  NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [OPERATION_SEQ_NO] smallint DEFAULT  NULL,
    [PIECE_NO] smallint DEFAULT  NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(255) DEFAULT  NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NULL,
    [DEPARTMENT_ID] NVARCHAR(15) DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [LOCATION_ID] NVARCHAR(15) DEFAULT  NULL,
    [QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [PIECE_COUNT] DECIMAL(20,8) DEFAULT  NULL,
    [LENGTH] DECIMAL(14,4) DEFAULT  NULL,
    [WIDTH] DECIMAL(14,4) DEFAULT  NULL,
    [HEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [DIMENSIONS_UM] NVARCHAR(15) DEFAULT  NULL,
    [EMPLOYEE_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[WIP_TRANSACTION] ADD CONSTRAINT [PK_WIP_TRANSACTION] PRIMARY KEY ([TRANSACTION_ID]);

ALTER TABLE [dbo].[WIP_TRANSACTION] ADD CONSTRAINT [FK_WIP_TRANS_MOVE_REQUEST_LINE] FOREIGN KEY ([MOVE_REQUEST_ID], [MOVE_REQUEST_LINE_NO]) REFERENCES [dbo].[MOVE_REQUEST_LINE]([MOVE_REQUEST_ID], [LINE_NO]);

ALTER TABLE [dbo].[WIP_TRANSACTION] ADD CONSTRAINT [FK_WIP_TRANS_TO_DEPARTMENT] FOREIGN KEY ([DEPARTMENT_ID]) REFERENCES [dbo].[DEPARTMENT]([ID]);

ALTER TABLE [dbo].[WIP_TRANSACTION] ADD CONSTRAINT [FK_WIP_TRANS_TO_EMPLOYEE] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [dbo].[EMPLOYEE]([ID]);

ALTER TABLE [dbo].[WIP_TRANSACTION] ADD CONSTRAINT [FK_WIP_TRANS_TO_PART] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);

ALTER TABLE [dbo].[WIP_TRANSACTION] ADD CONSTRAINT [FK_WIP_TRANS_TO_SHOP_RESOURCE] FOREIGN KEY ([RESOURCE_ID]) REFERENCES [dbo].[SHOP_RESOURCE]([ID]);

ALTER TABLE [dbo].[WIP_TRANSACTION] ADD CONSTRAINT [FK_WIP_TRANS_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[WIP_TRANSACTION] ADD CONSTRAINT [FK_WIP_TRANS_TO_WIP_MAT_LOC] FOREIGN KEY ([WAREHOUSE_ID], [LOCATION_ID]) REFERENCES [dbo].[WIP_MAT_LOCATION]([WAREHOUSE_ID], [ID]);

ALTER TABLE [dbo].[WIP_TRANSACTION] ADD CONSTRAINT [FK_WIP_TRANS_TO_WORK_ORDER] FOREIGN KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID]) REFERENCES [dbo].[WORK_ORDER]([TYPE], [BASE_ID], [LOT_ID], [SPLIT_ID], [SUB_ID]);
