CREATE TABLE [dbo].[CASH_DISBURSE_CURR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BANK_ACCOUNT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CONTROL_NO] int DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[CASH_DISBURSE_CURR] ADD CONSTRAINT [PK_CSHD_CURR] PRIMARY KEY ([BANK_ACCOUNT_ID], [CONTROL_NO], [CURRENCY_ID]);

ALTER TABLE [dbo].[CASH_DISBURSE_CURR] ADD CONSTRAINT [FKEY9404] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[CASH_DISBURSE_CURR] ADD CONSTRAINT [FKEY9405] FOREIGN KEY ([BANK_ACCOUNT_ID], [CONTROL_NO]) REFERENCES [dbo].[CASH_DISBURSEMENT]([BANK_ACCOUNT_ID], [CONTROL_NO]);
