CREATE TABLE [dbo].[RECV_MEMO_APPLY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [MEMO_INVOICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [INV_INVOICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [APPLY_AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [APPLY_DATE] datetime DEFAULT  NULL,
    [INST_NO] smallint DEFAULT  NULL
)

ALTER TABLE [dbo].[RECV_MEMO_APPLY] ADD CONSTRAINT [FKEY0234] FOREIGN KEY ([INV_INVOICE_ID]) REFERENCES [dbo].[RECEIVABLE]([INVOICE_ID]);

ALTER TABLE [dbo].[RECV_MEMO_APPLY] ADD CONSTRAINT [FKEY0235] FOREIGN KEY ([MEMO_INVOICE_ID]) REFERENCES [dbo].[RECEIVABLE]([INVOICE_ID]);
