CREATE TABLE [dbo].[LANGUAGE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(2) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(20) DEFAULT  NULL
)

ALTER TABLE [dbo].[LANGUAGE] ADD CONSTRAINT [PK_LANGUAGE] PRIMARY KEY ([ID]);
