CREATE TABLE [dbo].[SUMMARY_TABLE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] int DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL,
    [TOTAL_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[SUMMARY_TABLE] ADD CONSTRAINT [PK_SUMMARY_TABLE] PRIMARY KEY ([ID]);
