CREATE TABLE [dbo].[CUST_SHIP_CHG_ACCT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SHIP_VIA] NVARCHAR(40) DEFAULT  NOT NULL,
    [ACCOUNT_NO] NVARCHAR(30) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CUST_SHIP_CHG_ACCT] ADD CONSTRAINT [PK_CUST_SHIP_CHG_ACCT] PRIMARY KEY ([CUSTOMER_ID], [SHIP_VIA]);

ALTER TABLE [dbo].[CUST_SHIP_CHG_ACCT] ADD CONSTRAINT [FK_CUST_SHIP_CHG_ACCT_CUST] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);
