CREATE TABLE [dbo].[ACCOUNT_BAL_SUM] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SPID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ACCT_YEAR] DECIMAL(4,0) DEFAULT  NOT NULL,
    [ACCT_PERIOD] DECIMAL(2,0) DEFAULT  NOT NULL,
    [O_DEBIT_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [O_CREDIT_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [O_DEBIT_BUDGET] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [O_CREDIT_BUDGET] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [N_DEBIT_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [N_CREDIT_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [N_DEBIT_BUDGET] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [N_CREDIT_BUDGET] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [FLAG] int DEFAULT ((0)) NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL
)

ALTER TABLE [dbo].[ACCOUNT_BAL_SUM] ADD CONSTRAINT [PK_ACCTBAL_SUM] PRIMARY KEY ([SPID], [ACCOUNT_ID], [SITE_ID], [ACCT_YEAR], [ACCT_PERIOD], [CURRENCY_ID]);
