CREATE TABLE [dbo].[ACCOUNT_PROFILE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ACCOUNT_TYPE] NVARCHAR(1) DEFAULT  NOT NULL,
    [PROFILE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [START_ACCOUNT] NVARCHAR(30) DEFAULT  NULL,
    [END_ACCOUNT] NVARCHAR(30) DEFAULT  NULL,
    [PROFILE_TYPE] NVARCHAR(1) DEFAULT  NOT NULL,
    [ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [PROFILE_AMOUNT] DECIMAL(23,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[ACCOUNT_PROFILE] ADD CONSTRAINT [PK_ACCT_PROFILE] PRIMARY KEY ([ACCOUNT_TYPE], [PROFILE_ID], [PROFILE_TYPE], [ACCOUNT_ID]);

ALTER TABLE [dbo].[ACCOUNT_PROFILE] ADD CONSTRAINT [FKEY9500] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);
