CREATE TABLE [dbo].[EQUIP_MODEL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL
)

ALTER TABLE [dbo].[EQUIP_MODEL] ADD CONSTRAINT [PK_EQUIP_MODEL] PRIMARY KEY ([TYPE_ID], [ID]);

ALTER TABLE [dbo].[EQUIP_MODEL] ADD CONSTRAINT [FKEY9506] FOREIGN KEY ([TYPE_ID]) REFERENCES [dbo].[EQUIP_TYPE]([ID]);
