CREATE TABLE [dbo].[HISTORY_DEFINITION] (
    [TBL_NAME] NVARCHAR(50) DEFAULT  NOT NULL,
    [COL_NAME] NVARCHAR(50) DEFAULT  NOT NULL,
    [COL_TYPE] NVARCHAR(15) DEFAULT  NULL,
    [FOR_INSERT] NCHAR(1) DEFAULT  NULL,
    [FOR_UPDATE] NCHAR(1) DEFAULT  NULL,
    [FOR_DELETE] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[HISTORY_DEFINITION] ADD CONSTRAINT [PK_HISTORY_DEFINITION] PRIMARY KEY ([TBL_NAME], [COL_NAME]);
