CREATE TABLE [dbo].[PHYS_TRACE_COUNT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PHYS_COUNT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TAG_NO] int DEFAULT  NOT NULL,
    [SUB_TAG_NO] int DEFAULT  NOT NULL,
    [TRACE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SUB_TAG_TOTAL_NO] int DEFAULT  NOT NULL,
    [SUB_COUNT_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [SUB_COUNT_USER] NVARCHAR(20) DEFAULT  NULL,
    [SUB_RECOUNT_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [SUB_RECOUNT_USER] NVARCHAR(20) DEFAULT  NULL,
    [SUB_COUNT_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[PHYS_TRACE_COUNT] ADD CONSTRAINT [PK_PHYS_TRACE_COUNT] PRIMARY KEY ([PHYS_COUNT_ID], [TAG_NO], [SUB_TAG_NO]);

ALTER TABLE [dbo].[PHYS_TRACE_COUNT] ADD CONSTRAINT [FKEY0177] FOREIGN KEY ([PHYS_COUNT_ID], [TAG_NO]) REFERENCES [dbo].[PHYS_COUNT_TAG]([PHYS_COUNT_ID], [TAG_NO]);
