CREATE TABLE [dbo].[WAREHOUSE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [NAME] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_1] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_2] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_3] NVARCHAR(50) DEFAULT  NULL,
    [CITY] NVARCHAR(30) DEFAULT  NULL,
    [STATE] NVARCHAR(10) DEFAULT  NULL,
    [ZIPCODE] NVARCHAR(10) DEFAULT  NULL,
    [COUNTRY] NVARCHAR(50) DEFAULT  NULL,
    [REGION_ID] NVARCHAR(2) DEFAULT  NULL,
    [COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [WAREHOUSE_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [VAT_REGISTRATION] NVARCHAR(25) DEFAULT  NULL,
    [WIP_VAS] NCHAR(1) DEFAULT  NULL,
    [DEF_LBL_FORMAT_ID] NVARCHAR(30) DEFAULT  NULL,
    [INDEPENDENT] NCHAR(1) DEFAULT ('') NOT NULL,
    [VDW_INSTALLED] NCHAR(1) DEFAULT  NULL,
    [INV_NOT_SHARED] NCHAR(1) DEFAULT  NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NULL,
    [CONSIGNED_TYPE] NCHAR(1) DEFAULT  NULL,
    [MRP_EXEMPT] NCHAR(1) DEFAULT ('N') NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DEF_WIP_LOC_ID] NVARCHAR(15) DEFAULT  NULL,
    [DEF_RECEIVING_WIP_LOC_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[WAREHOUSE] ADD CONSTRAINT [PK_WAREHOUSE] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[WAREHOUSE] ADD CONSTRAINT [FK_WAREHOUSE_CNTRY] FOREIGN KEY ([COUNTRY_ID]) REFERENCES [dbo].[COUNTRY]([ID]);

ALTER TABLE [dbo].[WAREHOUSE] ADD CONSTRAINT [FK_WAREHOUSE_RCV_WIP_MAT_LOC] FOREIGN KEY ([ID], [DEF_RECEIVING_WIP_LOC_ID]) REFERENCES [dbo].[WIP_MAT_LOCATION]([WAREHOUSE_ID], [ID]);

ALTER TABLE [dbo].[WAREHOUSE] ADD CONSTRAINT [FK_WAREHOUSE_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[WAREHOUSE] ADD CONSTRAINT [FK_WAREHOUSE_WIP_MAT_LOC] FOREIGN KEY ([ID], [DEF_WIP_LOC_ID]) REFERENCES [dbo].[WIP_MAT_LOCATION]([WAREHOUSE_ID], [ID]);

ALTER TABLE [dbo].[WAREHOUSE] ADD CONSTRAINT [FKEY9330] FOREIGN KEY ([REGION_ID]) REFERENCES [dbo].[REGION]([ID]);

ALTER TABLE [dbo].[WAREHOUSE] ADD CONSTRAINT [FKEY9467] FOREIGN KEY ([DEF_LBL_FORMAT_ID]) REFERENCES [dbo].[LABEL_FORMAT]([ID]);

ALTER TABLE [dbo].[WAREHOUSE] ADD CONSTRAINT [FKEY9611] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);

ALTER TABLE [dbo].[WAREHOUSE] ADD CONSTRAINT [FKEY9612] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);
