CREATE TABLE [dbo].[DOCUMENT_DEFLT_REF_TYPE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DOCUMENT_SRC_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [REFERENCE_TYPE] NVARCHAR(5) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[DOCUMENT_DEFLT_REF_TYPE] ADD CONSTRAINT [PK_DOCUMENT_DEFLT_REF_TYPE] PRIMARY KEY ([SITE_ID], [DOCUMENT_SRC_TYPE], [REFERENCE_TYPE]);
