CREATE TABLE [dbo].[EQUIP_MAINT_TYPE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL,
    [MAINT_PRICE] DECIMAL(23,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[EQUIP_MAINT_TYPE] ADD CONSTRAINT [PK_EQ_MAINT_TYPE] PRIMARY KEY ([ID]);
