CREATE TABLE [dbo].[LMC_MRP_LOGGING] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [LOG_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [LOG_USER] VARCHAR(80) DEFAULT (suser_sname()) NOT NULL,
    [CODE_LINE] VARCHAR(10) DEFAULT  NULL,
    [INFORMATION] VARCHAR(MAX) DEFAULT  NULL
)
