CREATE TABLE [dbo].[VMDI_ASSOC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [LAYOUT_KEY] NCHAR(3) DEFAULT  NOT NULL,
    [LAYOUT_VERSION] NCHAR(4) DEFAULT  NOT NULL,
    [LAYOUT_DIRECTION] NCHAR(1) DEFAULT  NOT NULL,
    [TABLE_NAME] NVARCHAR(18) DEFAULT  NOT NULL,
    [TABLE_KEY] NVARCHAR(60) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[VMDI_ASSOC] ADD CONSTRAINT [PK_VMDI_ASSOC] PRIMARY KEY ([LAYOUT_KEY], [LAYOUT_VERSION], [LAYOUT_DIRECTION], [TABLE_NAME], [TABLE_KEY]);

ALTER TABLE [dbo].[VMDI_ASSOC] ADD CONSTRAINT [FKEY9114] FOREIGN KEY ([LAYOUT_KEY], [LAYOUT_VERSION], [LAYOUT_DIRECTION]) REFERENCES [dbo].[VMDI_LAYOUT]([KEY], [VERSION], [DIRECTION]);
