CREATE TABLE [dbo].[EXTRA_JOIN] (
    [PARENT] NVARCHAR(20) DEFAULT  NOT NULL,
    [CHILD] NVARCHAR(20) DEFAULT  NOT NULL,
    [ADDTL_WHERE] NVARCHAR(2000) DEFAULT  NULL,
    [NAME] NVARCHAR(20) DEFAULT  NOT NULL,
    [CHILD_COLUMNS] NVARCHAR(2000) DEFAULT  NULL,
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[EXTRA_JOIN] ADD CONSTRAINT [PK_EXTRA_JOIN] PRIMARY KEY ([PARENT], [CHILD], [NAME]);
