CREATE TABLE [dbo].[INTRA_ARRIVAL_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ARRIVAL_DATE] datetime DEFAULT  NOT NULL,
    [TARIFF_CODE] NVARCHAR(15) DEFAULT  NULL,
    [EXCISE_PRICE] DECIMAL(23,8) DEFAULT  NULL,
    [DELIVERY_TERMS] NVARCHAR(25) DEFAULT  NULL,
    [NATURE_OF_TRANS] int DEFAULT  NULL,
    [NET_MASS] int DEFAULT  NULL,
    [SUPP_UNITS] int DEFAULT  NULL,
    [TO_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [FROM_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [ORIG_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [REGION_ID] NVARCHAR(2) DEFAULT  NULL,
    [ARRIVAL_CODE] NVARCHAR(25) DEFAULT  NULL,
    [TRANS_CODE] NVARCHAR(25) DEFAULT  NULL,
    [MODE_OF_TRANSPORT] int DEFAULT  NULL,
    [NO_OF_CONSIGN] int DEFAULT  NULL,
    [REFERENCE] NVARCHAR(15) DEFAULT  NULL,
    [INTRA_REPORT_NO] int DEFAULT  NULL,
    [INTRA_FILENAME] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[INTRA_ARRIVAL_LINE] ADD CONSTRAINT [PK_INTRA_ARRIVAL_LINE] PRIMARY KEY ([ID], [ARRIVAL_DATE]);

ALTER TABLE [dbo].[INTRA_ARRIVAL_LINE] ADD CONSTRAINT [FK_INTRA_ARRIVAL_LINE_00] FOREIGN KEY ([ARRIVAL_CODE]) REFERENCES [dbo].[PORT_OF_ARRIVAL]([CODE]);

ALTER TABLE [dbo].[INTRA_ARRIVAL_LINE] ADD CONSTRAINT [FK_INTRA_ARRIVAL_LINE_01] FOREIGN KEY ([TRANS_CODE]) REFERENCES [dbo].[PORT_OF_TRANS]([CODE]);

ALTER TABLE [dbo].[INTRA_ARRIVAL_LINE] ADD CONSTRAINT [FK_INTRA_ARRIVAL_LINE_02] FOREIGN KEY ([FROM_COUNTRY_ID]) REFERENCES [dbo].[COUNTRY]([ID]);

ALTER TABLE [dbo].[INTRA_ARRIVAL_LINE] ADD CONSTRAINT [FK_INTRA_ARRIVAL_LINE_03] FOREIGN KEY ([ORIG_COUNTRY_ID]) REFERENCES [dbo].[COUNTRY]([ID]);

ALTER TABLE [dbo].[INTRA_ARRIVAL_LINE] ADD CONSTRAINT [FK_INTRA_ARRIVAL_LINE_04] FOREIGN KEY ([TO_COUNTRY_ID]) REFERENCES [dbo].[COUNTRY]([ID]);

ALTER TABLE [dbo].[INTRA_ARRIVAL_LINE] ADD CONSTRAINT [FK_INTRA_ARRIVAL_LINE_05] FOREIGN KEY ([REGION_ID]) REFERENCES [dbo].[REGION]([ID]);

ALTER TABLE [dbo].[INTRA_ARRIVAL_LINE] ADD CONSTRAINT [FK_INTRA_ARRIVAL_LINE_06] FOREIGN KEY ([NATURE_OF_TRANS]) REFERENCES [dbo].[NATURE_OF_TRANS]([CODE]);

ALTER TABLE [dbo].[INTRA_ARRIVAL_LINE] ADD CONSTRAINT [FK_INTRA_ARRIVAL_LINE_07] FOREIGN KEY ([MODE_OF_TRANSPORT]) REFERENCES [dbo].[MODE_OF_TRANSPORT]([CODE]);

ALTER TABLE [dbo].[INTRA_ARRIVAL_LINE] ADD CONSTRAINT [FK_INTRA_ARRIVAL_LINE_08] FOREIGN KEY ([TARIFF_CODE]) REFERENCES [dbo].[TARIFF]([CODE]);
