CREATE TABLE [dbo].[BOL_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BOL_ID] NVARCHAR(20) DEFAULT  NULL,
    [NMFC_CODE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CARTON_COUNT] smallint DEFAULT  NOT NULL,
    [PACKAGE_TYPE] NVARCHAR(5) DEFAULT  NULL,
    [SHIPPING_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [WEIGHT_UM] NVARCHAR(15) DEFAULT  NULL,
    [TRUCK_LOAD] NCHAR(1) DEFAULT  NULL,
    [PALLET_COUNT] smallint DEFAULT  NULL,
    [SHIP_DIMENSIONS] NVARCHAR(50) DEFAULT  NULL,
    [TARE_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [NET_SHIP_WEIGHT] DECIMAL(14,4) DEFAULT  NULL
)
