CREATE TABLE [dbo].[SALES_TAX_PCT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SALES_TAX_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [EFFECTIVE_DATE] datetime DEFAULT  NOT NULL,
    [TAX_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [TAX_CEILING_AMOUNT] DECIMAL(23,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[SALES_TAX_PCT] ADD CONSTRAINT [PK_SALES_TAX_PCT] PRIMARY KEY ([SALES_TAX_ID], [EFFECTIVE_DATE]);

ALTER TABLE [dbo].[SALES_TAX_PCT] ADD CONSTRAINT [FKEY0047] FOREIGN KEY ([SALES_TAX_ID]) REFERENCES [dbo].[SALES_TAX]([ID]);
