CREATE TABLE [dbo].[OPER_TYPE_RESOURCE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [OPERATION_TYPE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [PERCENT_DURATION] smallint DEFAULT  NULL,
    [JUSTIFICATION] NCHAR(1) DEFAULT ('') NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[OPER_TYPE_RESOURCE] ADD CONSTRAINT [PK_OPER_TYPE_RESOURCE] PRIMARY KEY ([OPERATION_TYPE_ID], [SITE_ID], [RESOURCE_ID]);

ALTER TABLE [dbo].[OPER_TYPE_RESOURCE] ADD CONSTRAINT [FK_OPER_TYPE_RES_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[OPER_TYPE_RESOURCE] ADD CONSTRAINT [FKEY0053] FOREIGN KEY ([OPERATION_TYPE_ID], [SITE_ID]) REFERENCES [dbo].[OPERATION_TYPE]([ID], [SITE_ID]);

ALTER TABLE [dbo].[OPER_TYPE_RESOURCE] ADD CONSTRAINT [FKEY0122] FOREIGN KEY ([RESOURCE_ID]) REFERENCES [dbo].[SHOP_RESOURCE]([ID]);
