CREATE TABLE [dbo].[GJ_DIST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [GJ_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DIST_NO] smallint DEFAULT  NOT NULL,
    [ENTRY_NO] smallint DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [AMOUNT_TYPE] NCHAR(2) DEFAULT  NOT NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [NATIVE_AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [POSTING_STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [BATCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [NATIVE] NCHAR(1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[GJ_DIST] ADD CONSTRAINT [PK_GJ_DIST] PRIMARY KEY ([GJ_ID], [DIST_NO], [ENTRY_NO], [CURRENCY_ID]);

ALTER TABLE [dbo].[GJ_DIST] ADD CONSTRAINT [FKEY9438] FOREIGN KEY ([GJ_ID]) REFERENCES [dbo].[GJ]([ID]);

ALTER TABLE [dbo].[GJ_DIST] ADD CONSTRAINT [FKEY9439] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
