CREATE TABLE [dbo].[CUSTOMER_TYPE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TYPE] NVARCHAR(20) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [REALLOCATE] NCHAR(1) DEFAULT  NOT NULL,
    [ALLOCATION_FENCE] int DEFAULT  NULL,
    [PRIORITY] smallint DEFAULT  NULL,
    [AUTO_ALLOCATE] NCHAR(1) DEFAULT  NULL,
    [CO_ALLOC_LEVEL] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[CUSTOMER_TYPE] ADD CONSTRAINT [PK_CUSTOMER_TYPE] PRIMARY KEY ([TYPE]);
