CREATE TABLE [dbo].[QUOTED_OPTIONS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [QUOTE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [QUOTE_LINE_NO] smallint DEFAULT  NOT NULL,
    [SEQ_NO] smallint DEFAULT  NOT NULL,
    [TYPE] NCHAR(3) DEFAULT  NULL,
    [RQD_OPT] NCHAR(3) DEFAULT  NULL,
    [STD_OPT] NCHAR(3) DEFAULT  NULL,
    [SERIES_ID] NVARCHAR(15) DEFAULT  NULL,
    [SERIES_DESCR] NVARCHAR(40) DEFAULT  NULL,
    [MODEL_ID] NVARCHAR(15) DEFAULT  NULL,
    [MODEL_DESCR] NVARCHAR(40) DEFAULT  NULL,
    [SALES_CODE] NVARCHAR(30) DEFAULT  NULL,
    [SALES_CODE_DESCR] NVARCHAR(40) DEFAULT  NULL,
    [CATEGORY_ID] NVARCHAR(15) DEFAULT  NULL,
    [CATEGORY_DESCR] NVARCHAR(40) DEFAULT  NULL,
    [USER_TEXT] NVARCHAR(80) DEFAULT  NULL,
    [DIM_UM_0] NVARCHAR(15) DEFAULT  NULL,
    [DIM_VALUE_0] DECIMAL(23,8) DEFAULT  NULL,
    [DIM_UM_1] NVARCHAR(15) DEFAULT  NULL,
    [DIM_VALUE_1] DECIMAL(23,8) DEFAULT  NULL,
    [DIM_UM_2] NVARCHAR(15) DEFAULT  NULL,
    [DIM_VALUE_2] DECIMAL(23,8) DEFAULT  NULL,
    [DIM_UM_3] NVARCHAR(15) DEFAULT  NULL,
    [DIM_VALUE_3] DECIMAL(23,8) DEFAULT  NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NULL,
    [TRADE_DISCOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [DISCOUNT_TYPE] NCHAR(1) DEFAULT  NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [ENG_ID] NVARCHAR(3) DEFAULT  NULL,
    [COPY_SEQ_NO] smallint DEFAULT  NULL,
    [UNIT_PRICE] DECIMAL(22,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[QUOTED_OPTIONS] ADD CONSTRAINT [PK_QUOTED_OPTIONS] PRIMARY KEY ([QUOTE_ID], [QUOTE_LINE_NO], [SEQ_NO]);

ALTER TABLE [dbo].[QUOTED_OPTIONS] ADD CONSTRAINT [FKEY0183] FOREIGN KEY ([QUOTE_ID], [QUOTE_LINE_NO]) REFERENCES [dbo].[QUOTE_LINE]([QUOTE_ID], [LINE_NO]);

ALTER TABLE [dbo].[QUOTED_OPTIONS] ADD CONSTRAINT [FKEY0287] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);
