CREATE TABLE [dbo].[PROJECT_BASELINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PROJECT_BASELINE] ADD CONSTRAINT [PK_PROJECT_BASELINE] PRIMARY KEY ([WORKORDER_BASE_ID], [WORKORDER_SPLIT_ID]);
