CREATE TABLE [dbo].[HTS_DUTY_PERCENT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [HTS_CODE] NVARCHAR(20) DEFAULT  NOT NULL,
    [ORIG_COUNTRY_ID] NVARCHAR(50) DEFAULT  NOT NULL,
    [DUTY_PERCENT] DECIMAL(6,3) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[HTS_DUTY_PERCENT] ADD CONSTRAINT [PK_HTS_DUTY_PCT] PRIMARY KEY ([HTS_CODE], [ORIG_COUNTRY_ID]);
