CREATE TABLE [dbo].[SETTINGS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(50) DEFAULT  NOT NULL,
    [SETTING_VALUE] NVARCHAR(250) DEFAULT  NULL
)

ALTER TABLE [dbo].[SETTINGS] ADD CONSTRAINT [PK_SETTINGS] PRIMARY KEY ([NAME]);
