CREATE TABLE [dbo].[CUST_LINE_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUST_ORDER_LINE_NO] smallint DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CUST_LINE_BINARY] ADD CONSTRAINT [PK_CUST_LINE_BINARY] PRIMARY KEY ([CUST_ORDER_ID], [CUST_ORDER_LINE_NO], [TYPE]);
