CREATE TABLE [dbo].[TEMP_PACKLIST_TINAC] (
    [selected_packlist_id] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[TEMP_PACKLIST_TINAC] ADD CONSTRAINT [PK__TEMP_PAC__4ED8A34664726E7A] PRIMARY KEY ([selected_packlist_id]);
