CREATE TABLE [dbo].[PART_ALTERNATE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [ALTERNATE_PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [RANK] smallint DEFAULT  NULL
)

ALTER TABLE [dbo].[PART_ALTERNATE] ADD CONSTRAINT [PK_PART_ALTERNATE] PRIMARY KEY ([PART_ID], [ALTERNATE_PART_ID]);
