CREATE TABLE [dbo].[ECN_REQ_REF_DESIG] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ECN_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] int DEFAULT  NOT NULL,
    [ECN_ENTRY_NO] smallint DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [OPERATION_SEQ_NO] smallint DEFAULT  NOT NULL,
    [PIECE_NO] smallint DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [X_COORDINATE] NVARCHAR(15) DEFAULT  NULL,
    [Y_COORDINATE] NVARCHAR(15) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[ECN_REQ_REF_DESIG] ADD CONSTRAINT [PK_ECN_REQ_REF_DESIG] PRIMARY KEY ([ECN_ID], [LINE_NO], [ECN_ENTRY_NO], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO], [PIECE_NO], [ID]);

ALTER TABLE [dbo].[ECN_REQ_REF_DESIG] ADD CONSTRAINT [FK_ECN_REQ_REF_DESIG] FOREIGN KEY ([ECN_ID], [LINE_NO], [ECN_ENTRY_NO]) REFERENCES [dbo].[ECN_DETAIL]([ECN_ID], [LINE_NO], [ENTRY_NO]);
