CREATE TABLE [dbo].[RECEIVABLE_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [REFERENCE] NVARCHAR(120) DEFAULT  NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [VAT_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [VAT_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [VAT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [COMMISSION_PCT] DECIMAL(6,3) DEFAULT  NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [CUST_ORDER_LINE_NO] smallint DEFAULT  NULL,
    [PACKLIST_ID] NVARCHAR(15) DEFAULT  NULL,
    [PACKLIST_LINE_NO] smallint DEFAULT  NULL,
    [VAT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [HTS_CODE] NVARCHAR(20) DEFAULT  NULL,
    [ORIG_COUNTRY_ID] NVARCHAR(50) DEFAULT  NULL,
    [DUTY_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [DUTY_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [VAT_CATEGORY] NVARCHAR(15) DEFAULT  NULL,
    [FT_TYPE] NCHAR(1) DEFAULT  NULL,
    [PREPAY_APPLIED_AMT] DECIMAL(23,8) DEFAULT  NULL,
    [PREPAY_APPLIED_VAT] DECIMAL(23,8) DEFAULT  NULL,
    [PREPAY_INVOICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [PRODUCT_CODE] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[RECEIVABLE_LINE] ADD CONSTRAINT [PK_RECEIVABLE_LINE] PRIMARY KEY ([INVOICE_ID], [LINE_NO]);

ALTER TABLE [dbo].[RECEIVABLE_LINE] ADD CONSTRAINT [FKEY0231] FOREIGN KEY ([INVOICE_ID]) REFERENCES [dbo].[RECEIVABLE]([INVOICE_ID]);

ALTER TABLE [dbo].[RECEIVABLE_LINE] ADD CONSTRAINT [FKEY0281] FOREIGN KEY ([CUST_ORDER_ID], [CUST_ORDER_LINE_NO]) REFERENCES [dbo].[CUST_ORDER_LINE]([CUST_ORDER_ID], [LINE_NO]);

ALTER TABLE [dbo].[RECEIVABLE_LINE] ADD CONSTRAINT [FKEY9579] FOREIGN KEY ([VAT_CATEGORY]) REFERENCES [dbo].[VAT_CATEGORY]([ID]);
