CREATE TABLE [dbo].[CASH_RECEIPT_CURR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CHECK_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[CASH_RECEIPT_CURR] ADD CONSTRAINT [PK_CASH_RECEIPT_CURR] PRIMARY KEY ([CUSTOMER_ID], [CHECK_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[CASH_RECEIPT_CURR] ADD CONSTRAINT [FKEY9395] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[CASH_RECEIPT_CURR] ADD CONSTRAINT [FKEY9396] FOREIGN KEY ([CUSTOMER_ID], [CHECK_ID]) REFERENCES [dbo].[CASH_RECEIPT]([CUSTOMER_ID], [CHECK_ID]);
