CREATE TABLE [dbo].[QRP_CONTROL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [STD_QRP_NAME] NVARCHAR(15) DEFAULT  NOT NULL,
    [CONTEXT_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [CONTEXT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [USER_QRP_NAME] NVARCHAR(128) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[QRP_CONTROL] ADD CONSTRAINT [PK_QRP_CONTROL] PRIMARY KEY ([STD_QRP_NAME], [CONTEXT_TYPE], [CONTEXT_ID]);
