CREATE TABLE [dbo].[CUST_ORDER_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CUST_ORDER_BINARY] ADD CONSTRAINT [PK_CUST_ORDER_BINARY] PRIMARY KEY ([CUST_ORDER_ID], [TYPE]);

ALTER TABLE [dbo].[CUST_ORDER_BINARY] ADD CONSTRAINT [FKEY0155] FOREIGN KEY ([CUST_ORDER_ID]) REFERENCES [dbo].[CUSTOMER_ORDER]([ID]);
