CREATE TABLE [dbo].[CUSTOMER_SITE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PRIORITY_CODE] NVARCHAR(15) DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [CUSTOMER_TYPE] NVARCHAR(20) DEFAULT  NULL,
    [ORDER_FILL_RATE] DECIMAL(5,2) DEFAULT ((0)) NOT NULL,
    [FILL_RATE_TYPE] NCHAR(1) DEFAULT  NULL,
    [ALLOCATION_FENCE] int DEFAULT  NULL,
    [CO_ALLOC_LEVEL] NCHAR(1) DEFAULT  NULL,
    [REALLOCATE] NCHAR(1) DEFAULT  NULL,
    [CONSOLIDATE_ORDERS] NCHAR(1) DEFAULT  NULL,
    [COMPLIANCE_LABEL] NCHAR(1) DEFAULT  NULL,
    [AUTO_ALLOCATE] NCHAR(1) DEFAULT  NULL,
    [EMAIL_INVOICE] NCHAR(1) DEFAULT ('N') NOT NULL,
    [CREATED_BY] NVARCHAR(20) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [MODIFIED_BY] NVARCHAR(20) DEFAULT  NULL,
    [MODIFY_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[CUSTOMER_SITE] ADD CONSTRAINT [PK_CUSTOMER_SITE] PRIMARY KEY ([SITE_ID], [CUSTOMER_ID]);

ALTER TABLE [dbo].[CUSTOMER_SITE] ADD CONSTRAINT [FK_CUST_SITE_TO_CUST] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);

ALTER TABLE [dbo].[CUSTOMER_SITE] ADD CONSTRAINT [FK_CUST_SITE_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
