CREATE TABLE [dbo].[CUST_ORDER_TYPE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TYPE] NVARCHAR(20) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL
)

ALTER TABLE [dbo].[CUST_ORDER_TYPE] ADD CONSTRAINT [PK_CUST_ORD_TYPE] PRIMARY KEY ([TYPE]);
