CREATE TABLE [dbo].[VENDOR_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[VENDOR_BINARY] ADD CONSTRAINT [PK_VENDOR_BINARY] PRIMARY KEY ([VENDOR_ID], [TYPE]);

ALTER TABLE [dbo].[VENDOR_BINARY] ADD CONSTRAINT [FKEY0073] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);
