CREATE TABLE [dbo].[SK_PLANNER_USER_ID] (
    [PLANNER_USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [NOTES] NVARCHAR(255) DEFAULT  NULL
)

ALTER TABLE [dbo].[SK_PLANNER_USER_ID] ADD CONSTRAINT [PK_PlannerUserID] PRIMARY KEY ([PLANNER_USER_ID]);
