CREATE TABLE [dbo].[FINANCIAL_PERIOD] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CALENDAR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ACCT_YEAR] DECIMAL(4,0) DEFAULT  NOT NULL,
    [ACCT_PERIOD] DECIMAL(2,0) DEFAULT  NOT NULL,
    [BEGIN_DATE] datetime DEFAULT  NULL,
    [END_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[FINANCIAL_PERIOD] ADD CONSTRAINT [PK_FINANCIAL_PERIOD] PRIMARY KEY ([CALENDAR_ID], [ACCT_YEAR], [ACCT_PERIOD]);
