CREATE TABLE [dbo].[NEXT_NUM_GEN_EAC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROJECT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [NEXT_NUMBER] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[NEXT_NUM_GEN_EAC] ADD CONSTRAINT [PK_NEXT_NUM_GEN_EAC] PRIMARY KEY ([PROJECT_ID], [NEXT_NUMBER]);
