CREATE TABLE [dbo].[ECN_CO_PRODUCT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ECN_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] int DEFAULT  NOT NULL,
    [ECN_ENTRY_NO] smallint DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [MAT_COST_PERCENT] DECIMAL(6,3) DEFAULT  NOT NULL,
    [DESIRED_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [LAB_COST_PERCENT] DECIMAL(6,3) DEFAULT  NOT NULL,
    [BUR_COST_PERCENT] DECIMAL(6,3) DEFAULT  NOT NULL,
    [SER_COST_PERCENT] DECIMAL(6,3) DEFAULT  NOT NULL,
    [QTY_IS_RATIO] NCHAR(1) DEFAULT  NULL,
    [QTY_PER] DECIMAL(20,8) DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [WIP_VAS_REQUIRED] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[ECN_CO_PRODUCT] ADD CONSTRAINT [PK_ECN_CO_PRODUCT] PRIMARY KEY ([ECN_ID], [LINE_NO], [ECN_ENTRY_NO], [WORKORDER_SUB_ID], [PART_ID]);

ALTER TABLE [dbo].[ECN_CO_PRODUCT] ADD CONSTRAINT [FK_ECN_CO_PRODUCT] FOREIGN KEY ([ECN_ID], [LINE_NO], [ECN_ENTRY_NO]) REFERENCES [dbo].[ECN_DETAIL]([ECN_ID], [LINE_NO], [ENTRY_NO]);
