CREATE TABLE [dbo].[TASK] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TYPE] NVARCHAR(15) DEFAULT  NOT NULL,
    [TASK_NO] int DEFAULT  NOT NULL,
    [SEQ_NO] int DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [SUB_TYPE] NVARCHAR(15) DEFAULT  NOT NULL,
    [EC_ID] NVARCHAR(128) DEFAULT  NULL,
    [STATUS] NVARCHAR(5) DEFAULT  NOT NULL,
    [REJECT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [REJ_TASK_NO] int DEFAULT  NULL,
    [REJ_SEQ_NO] int DEFAULT  NULL,
    [COMPLETED_DATE] datetime DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [OL_ENTRY_ID] NVARCHAR(250) DEFAULT  NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[TASK] ADD CONSTRAINT [PK_TASK] PRIMARY KEY ([TYPE], [TASK_NO], [SEQ_NO]);

ALTER TABLE [dbo].[TASK] ADD CONSTRAINT [FK_TASK_REJ_CODE] FOREIGN KEY ([REJECT_CODE]) REFERENCES [dbo].[TASK_REJ_CODES]([CODE]);
