CREATE TABLE [dbo].[LOCATION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT ('A') NOT NULL
)

ALTER TABLE [dbo].[LOCATION] ADD CONSTRAINT [PK_LOCATION] PRIMARY KEY ([WAREHOUSE_ID], [ID]);

ALTER TABLE [dbo].[LOCATION] ADD CONSTRAINT [FKEY0117] FOREIGN KEY ([WAREHOUSE_ID]) REFERENCES [dbo].[WAREHOUSE]([ID]);

ALTER TABLE [dbo].[LOCATION] ADD CONSTRAINT [FKEY9607] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);

ALTER TABLE [dbo].[LOCATION] ADD CONSTRAINT [FKEY9608] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);
