CREATE TABLE [dbo].[USER_DIM_PROC_PRI] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DIMENSION] smallint DEFAULT  NOT NULL,
    [PROCESS_TYPE] NVARCHAR(5) DEFAULT  NOT NULL,
    [SOURCE_TYPE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DR_PROCESS_ORDER] smallint DEFAULT  NULL,
    [CR_PROCESS_ORDER] smallint DEFAULT  NULL
)

ALTER TABLE [dbo].[USER_DIM_PROC_PRI] ADD CONSTRAINT [PK_USR_DIM_PROC_PRI] PRIMARY KEY ([DIMENSION], [PROCESS_TYPE], [SOURCE_TYPE]);
