CREATE TABLE [dbo].[SKILLS_CERT_DESC] (
    [OP_TYPE] VARCHAR(15) DEFAULT  NOT NULL,
    [PRINT_] VARCHAR(1) DEFAULT  NOT NULL,
    [DESCRIPTION] VARCHAR(250) DEFAULT  NULL,
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUST_FILTER_APPLIED] CHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[SKILLS_CERT_DESC] ADD CONSTRAINT [PK_SKILLS_CERT_DESC] PRIMARY KEY ([OP_TYPE]);
