CREATE TABLE [dbo].[HOLD_REASON] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[HOLD_REASON] ADD CONSTRAINT [PK_HOLD_REASON] PRIMARY KEY ([ID]);
