CREATE TABLE [dbo].[ACCOUNT_BUDGET_SUM] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SPID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ACCT_YEAR] DECIMAL(4,0) DEFAULT  NOT NULL,
    [ACCT_PERIOD] DECIMAL(2,0) DEFAULT  NOT NULL,
    [BUDGET_TYPE] NVARCHAR(15) DEFAULT  NOT NULL,
    [BUDGET_CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [O_BUDGET_DR_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [O_BUDGET_CR_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [N_BUDGET_DR_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [N_BUDGET_CR_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [FLAG] int DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[ACCOUNT_BUDGET_SUM] ADD CONSTRAINT [PK_ACCOUNT_BUDGET_SUM] PRIMARY KEY ([SPID], [ACCOUNT_ID], [SITE_ID], [ACCT_YEAR], [ACCT_PERIOD], [BUDGET_TYPE], [BUDGET_CODE], [CURRENCY_ID]);
