CREATE TABLE [dbo].[TRACE_SERV_TRANS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [TRACE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [TRANSACTION_ID] int DEFAULT  NOT NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[TRACE_SERV_TRANS] ADD CONSTRAINT [PK_TRACE_SERV_TRANS] PRIMARY KEY ([PART_ID], [TRACE_ID], [TRANSACTION_ID]);
