CREATE TABLE [dbo].[TRANSIT_TIME] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [FROM_WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TO_WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DAYS] DECIMAL(14,4) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[TRANSIT_TIME] ADD CONSTRAINT [PK_TRANSIT_TIME] PRIMARY KEY ([FROM_WAREHOUSE_ID], [TO_WAREHOUSE_ID]);
