CREATE TABLE [dbo].[CUSTOMER_RELATION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [OWNER_CUST_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SELL_TO_CUST_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CUSTOMER_RELATION] ADD CONSTRAINT [PK_CUSTOMER_RELATION] PRIMARY KEY ([OWNER_CUST_ID], [SELL_TO_CUST_ID]);
