CREATE TABLE [dbo].[INBOX_ERROR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [C_ID] bigint DEFAULT  NOT NULL,
    [C_INBOX_ID] bigint DEFAULT  NOT NULL,
    [C_BOD_TYPE] NVARCHAR(100) DEFAULT  NULL,
    [C_DOCUMENT_ID] NVARCHAR(100) DEFAULT  NULL,
    [C_STATUS] NVARCHAR(30) DEFAULT  NULL,
    [C_FAILURE_CODE] int DEFAULT  NOT NULL,
    [C_FAILURE_MESSAGE] NVARCHAR(500) DEFAULT  NULL,
    [C_RETRY_TRIGGER] NVARCHAR(250) DEFAULT  NULL,
    [C_RETRY_KEY] NVARCHAR(100) DEFAULT  NULL,
    [C_CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[INBOX_ERROR] ADD CONSTRAINT [PK_INBOX_ERROR] PRIMARY KEY ([C_ID]);

ALTER TABLE [dbo].[INBOX_ERROR] ADD CONSTRAINT [FK_INBOX_ERROR_TO_INBOX] FOREIGN KEY ([C_INBOX_ID]) REFERENCES [dbo].[COR_INBOX_ENTRY]([C_ID]);
