CREATE TABLE [dbo].[NORMAL_DIST_AREA] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [Z] DECIMAL(4,3) DEFAULT  NOT NULL,
    [AREA_MEAN_TO_Z] DECIMAL(6,5) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[NORMAL_DIST_AREA] ADD CONSTRAINT [PK_NORMAL_DIST_AREA] PRIMARY KEY ([Z]);
