CREATE TABLE [dbo].[REQUEST_FOR_QUOTE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUSTOMER_QUOTE_ID] NVARCHAR(15) DEFAULT  NULL,
    [REQUEST_DATE] datetime DEFAULT  NOT NULL,
    [BUYER] NVARCHAR(20) DEFAULT  NULL,
    [SHIP_VIA] NVARCHAR(40) DEFAULT  NULL,
    [FREE_ON_BOARD] NVARCHAR(25) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [STATUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[REQUEST_FOR_QUOTE] ADD CONSTRAINT [PK_REQUEST_FOR_QUOTE] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[REQUEST_FOR_QUOTE] ADD CONSTRAINT [FKEY0292] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
