CREATE TABLE [dbo].[INVENTORY_BALANCE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [TRANSACTION_ID] int DEFAULT  NOT NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [FLAG] NCHAR(1) DEFAULT  NOT NULL,
    [MATERIAL_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [LABOR_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [BURDEN_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [SERVICE_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [MAT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [LAB_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [BUR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [SER_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[INVENTORY_BALANCE] ADD CONSTRAINT [PK_INVENTORY_BALANCE] PRIMARY KEY ([PART_ID], [POSTING_DATE], [TRANSACTION_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[INVENTORY_BALANCE] ADD CONSTRAINT [FK_INVBAL_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[INVENTORY_BALANCE] ADD CONSTRAINT [FKEY9119] FOREIGN KEY ([TRANSACTION_ID]) REFERENCES [dbo].[INVENTORY_TRANS]([TRANSACTION_ID]);

ALTER TABLE [dbo].[INVENTORY_BALANCE] ADD CONSTRAINT [FKEY9120] FOREIGN KEY ([MAT_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[INVENTORY_BALANCE] ADD CONSTRAINT [FKEY9121] FOREIGN KEY ([LAB_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[INVENTORY_BALANCE] ADD CONSTRAINT [FKEY9122] FOREIGN KEY ([BUR_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[INVENTORY_BALANCE] ADD CONSTRAINT [FKEY9123] FOREIGN KEY ([SER_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[INVENTORY_BALANCE] ADD CONSTRAINT [FKEY9417] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
