CREATE TABLE [dbo].[IBT_LINE_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [IBT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [IBT_LINE_NO] smallint DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[IBT_LINE_BINARY] ADD CONSTRAINT [PK_IBT_LINE_BINARY] PRIMARY KEY ([IBT_ID], [IBT_LINE_NO], [TYPE]);

ALTER TABLE [dbo].[IBT_LINE_BINARY] ADD CONSTRAINT [FKEY9546] FOREIGN KEY ([IBT_ID], [IBT_LINE_NO]) REFERENCES [dbo].[IBT_LINE]([IBT_ID], [LINE_NO]);
