CREATE TABLE [dbo].[BUFFER_STAT_MATL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BUFFER_STATUS_ID] int DEFAULT  NOT NULL,
    [SUPPLY_TYPE] NVARCHAR(2) DEFAULT  NOT NULL,
    [SUPPLY_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SUPPLY_SEQ_NO] smallint DEFAULT  NOT NULL,
    [SUPPLY_NO] smallint DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[BUFFER_STAT_MATL] ADD CONSTRAINT [PK_BUFFER_STAT_MATL] PRIMARY KEY ([BUFFER_STATUS_ID], [SUPPLY_TYPE], [SUPPLY_BASE_ID], [SUPPLY_SEQ_NO], [SUPPLY_NO]);

ALTER TABLE [dbo].[BUFFER_STAT_MATL] ADD CONSTRAINT [FKEY_BUFSTM_BUFST] FOREIGN KEY ([BUFFER_STATUS_ID]) REFERENCES [dbo].[BUFFER_STATUS]([ID]);
