CREATE TABLE [dbo].[COUNTRY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL,
    [INTRASTAT_REQD] NCHAR(1) DEFAULT ('') NOT NULL,
    [INTRA_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [ESL_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [ESL_COUNTRY] NVARCHAR(1) DEFAULT ('') NOT NULL
)

ALTER TABLE [dbo].[COUNTRY] ADD CONSTRAINT [PK_COUNTRY] PRIMARY KEY ([ID]);
