CREATE TABLE [dbo].[CUST_BOOK_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUST_ORDER_LINE_NO] smallint DEFAULT  NOT NULL,
    [BOOK_DATE] datetime DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [ORDER_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [USER_ORDER_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [DESIRED_SHIP_DATE] datetime DEFAULT  NULL,
    [TRADE_DISC_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [UNIT_PRICE] DECIMAL(22,8) DEFAULT  NULL,
    [EDI_BLANKET_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [EDI_RELEASE_NO] NVARCHAR(30) DEFAULT  NULL,
    [EDI_ACCUM_SHIP_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [EDI_ACCUM_FAB_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [EDI_ACCUM_RAW_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [EDI_ACCUM_SHIP_ADJ] DECIMAL(20,8) DEFAULT  NULL,
    [EDI_ACCUM_ORD_ADJ] DECIMAL(20,8) DEFAULT  NULL,
    [EDI_LAST_SHIPDATE] datetime DEFAULT  NULL,
    [TOTAL_SHIPPED_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [TOTAL_USR_SHIP_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [ACTUAL_SHIP_DATE] datetime DEFAULT  NULL,
    [REVISION_ID] NVARCHAR(8) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CUST_BOOK_LINE] ADD CONSTRAINT [PK_CUST_BOOK_LINE] PRIMARY KEY ([CUST_ORDER_ID], [CUST_ORDER_LINE_NO], [BOOK_DATE]);
