CREATE TABLE [dbo].[APPLICATION_FIELDS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [FIELD_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [FIELD_DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[APPLICATION_FIELDS] ADD CONSTRAINT [PK_APPLICATION_FIELDS] PRIMARY KEY ([PROGRAM_ID], [FIELD_ID]);
