CREATE TABLE [dbo].[OPER_TYPE_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [OPERATION_TYPE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[OPER_TYPE_BINARY] ADD CONSTRAINT [PK_OPER_TYPE_BINARY] PRIMARY KEY ([OPERATION_TYPE_ID], [SITE_ID], [TYPE]);

ALTER TABLE [dbo].[OPER_TYPE_BINARY] ADD CONSTRAINT [FK_OPER_TYPE_BIN_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[OPER_TYPE_BINARY] ADD CONSTRAINT [FKEY0054] FOREIGN KEY ([OPERATION_TYPE_ID], [SITE_ID]) REFERENCES [dbo].[OPERATION_TYPE]([ID], [SITE_ID]);
