CREATE TABLE [dbo].[SHIPPER_LINE_DEL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PACKLIST_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PACKLIST_LINE_NO] smallint DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [CUST_ORDER_LINE_NO] smallint DEFAULT  NULL,
    [CUST_DEL_LINE_NO] smallint DEFAULT  NULL,
    [USER_SHIPPED_QTY] DECIMAL(20,8) DEFAULT ((0)) NULL,
    [SHIPPED_QTY] DECIMAL(20,8) DEFAULT ((0)) NULL,
    [USER_1] NVARCHAR(80) DEFAULT  NULL,
    [USER_2] NVARCHAR(80) DEFAULT  NULL,
    [USER_3] NVARCHAR(80) DEFAULT  NULL,
    [USER_4] NVARCHAR(80) DEFAULT  NULL,
    [USER_5] NVARCHAR(80) DEFAULT  NULL,
    [USER_6] NVARCHAR(80) DEFAULT  NULL,
    [USER_7] NVARCHAR(80) DEFAULT  NULL,
    [USER_8] NVARCHAR(80) DEFAULT  NULL,
    [USER_9] NVARCHAR(80) DEFAULT  NULL,
    [USER_10] NVARCHAR(80) DEFAULT  NULL,
    [UDF_LAYOUT_ID] NVARCHAR(15) DEFAULT  NULL,
    [PIECE_COUNT] DECIMAL(20,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[SHIPPER_LINE_DEL] ADD CONSTRAINT [PK_SHIPPER_LINE_DEL] PRIMARY KEY ([PACKLIST_ID], [PACKLIST_LINE_NO], [LINE_NO]);

ALTER TABLE [dbo].[SHIPPER_LINE_DEL] ADD CONSTRAINT [FKEY9372] FOREIGN KEY ([CUST_ORDER_ID], [CUST_ORDER_LINE_NO]) REFERENCES [dbo].[CUST_ORDER_LINE]([CUST_ORDER_ID], [LINE_NO]);

ALTER TABLE [dbo].[SHIPPER_LINE_DEL] ADD CONSTRAINT [FKEY9373] FOREIGN KEY ([PACKLIST_ID], [PACKLIST_LINE_NO]) REFERENCES [dbo].[SHIPPER_LINE]([PACKLIST_ID], [LINE_NO]);
