CREATE TABLE [dbo].[CARTON_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CARTON_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CARTON_LINE] ADD CONSTRAINT [PK_CARTON_LINE] PRIMARY KEY ([CARTON_ID], [LINE_NO]);

ALTER TABLE [dbo].[CARTON_LINE] ADD CONSTRAINT [FKEY9569] FOREIGN KEY ([CARTON_ID]) REFERENCES [dbo].[CARTON]([ID]);
