CREATE TABLE [dbo].[RECEIVABLE_SHARE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SHARE_SALESREP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SHARE_PERCENT] DECIMAL(6,3) DEFAULT  NULL
)

ALTER TABLE [dbo].[RECEIVABLE_SHARE] ADD CONSTRAINT [PK_RECEIVABLE_SHARE] PRIMARY KEY ([INVOICE_ID], [SHARE_SALESREP_ID]);

ALTER TABLE [dbo].[RECEIVABLE_SHARE] ADD CONSTRAINT [FKEY9589] FOREIGN KEY ([INVOICE_ID]) REFERENCES [dbo].[RECEIVABLE]([INVOICE_ID]);

ALTER TABLE [dbo].[RECEIVABLE_SHARE] ADD CONSTRAINT [FKEY9590] FOREIGN KEY ([SHARE_SALESREP_ID]) REFERENCES [dbo].[SALES_REP]([ID]);
