CREATE TABLE [dbo].[CALENDAR_CHANGE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SCHEDULE_ID] NVARCHAR(15) DEFAULT  NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NULL,
    [START_DATE] datetime DEFAULT  NOT NULL,
    [END_DATE] datetime DEFAULT  NOT NULL,
    [START_OF_DAY] datetime DEFAULT  NOT NULL,
    [SHIFT_1] DECIMAL(5,3) DEFAULT  NOT NULL,
    [SHIFT_2] DECIMAL(5,3) DEFAULT  NOT NULL,
    [SHIFT_3] DECIMAL(5,3) DEFAULT  NOT NULL,
    [SHIFT_1_CAPACITY] smallint DEFAULT  NULL,
    [SHIFT_2_CAPACITY] smallint DEFAULT  NULL,
    [SHIFT_3_CAPACITY] smallint DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL,
    [ORIGINAL_START_OF_DAY] datetime DEFAULT  NULL,
    [ORIGINAL_SHIFT_1] DECIMAL(5,3) DEFAULT  NULL,
    [ORIGINAL_SHIFT_2] DECIMAL(5,3) DEFAULT  NULL,
    [ORIGINAL_SHIFT_3] DECIMAL(5,3) DEFAULT  NULL
)

ALTER TABLE [dbo].[CALENDAR_CHANGE] ADD CONSTRAINT [FK_CAL_CHANGE_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[CALENDAR_CHANGE] ADD CONSTRAINT [FKEY0126] FOREIGN KEY ([RESOURCE_ID]) REFERENCES [dbo].[SHOP_RESOURCE]([ID]);

ALTER TABLE [dbo].[CALENDAR_CHANGE] ADD CONSTRAINT [FKEY0267] FOREIGN KEY ([SCHEDULE_ID]) REFERENCES [dbo].[SCHEDULE]([ID]);
