CREATE TABLE [dbo].[JOURNAL_DIM_FILTER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(50) DEFAULT  NOT NULL,
    [CRITERIA_TYPE] NVARCHAR(50) DEFAULT  NOT NULL,
    [IS_DEFAULT] NCHAR(1) DEFAULT ('N') NOT NULL,
    [CRITERIA_COMPARISN] NVARCHAR(10) DEFAULT  NULL,
    [CRITERIA_TEXT] VARBINARY(MAX) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[JOURNAL_DIM_FILTER] ADD CONSTRAINT [PK_JOURN_DIM_FLTR] PRIMARY KEY ([USER_ID], [NAME], [CRITERIA_TYPE]);
