CREATE TABLE [dbo].[TABLE_LIST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TABLE_NAME] NVARCHAR(100) DEFAULT  NOT NULL,
    [LAST_MOD_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[TABLE_LIST] ADD CONSTRAINT [PK_TABLE_LIST] PRIMARY KEY ([TABLE_NAME]);
