CREATE TABLE [dbo].[TERMS_INST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TERMS_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [INST_NO] smallint DEFAULT  NOT NULL,
    [INST_PERCENT] DECIMAL(6,3) DEFAULT ((0)) NOT NULL,
    [PERIOD] smallint DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[TERMS_INST] ADD CONSTRAINT [PK_TERMS_INST] PRIMARY KEY ([TERMS_ID], [INST_NO]);

ALTER TABLE [dbo].[TERMS_INST] ADD CONSTRAINT [FK_TERMS_INST_00] FOREIGN KEY ([TERMS_ID]) REFERENCES [dbo].[TERMS]([ID]);
