CREATE TABLE [dbo].[VR_MENU] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LOCALE] NVARCHAR(30) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL
)

ALTER TABLE [dbo].[VR_MENU] ADD CONSTRAINT [PK_VR_MENU] PRIMARY KEY ([ID], [LOCALE]);
