CREATE TABLE [dbo].[ADJ_REASON_SYNC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EVENT_ID] int DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [REASON_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [EXCEPTION] NCHAR(1) DEFAULT  NOT NULL,
    [SUBSCRIPTIONS] int DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[ADJ_REASON_SYNC] ADD CONSTRAINT [PK_ADJ_REASON_SYNC] PRIMARY KEY ([EVENT_ID]);
