CREATE TABLE [dbo].[PURC_ORDER_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PURC_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PURC_ORDER_BINARY] ADD CONSTRAINT [PK_PURC_ORDER_BINARY] PRIMARY KEY ([PURC_ORDER_ID], [TYPE]);

ALTER TABLE [dbo].[PURC_ORDER_BINARY] ADD CONSTRAINT [FKEY0164] FOREIGN KEY ([PURC_ORDER_ID]) REFERENCES [dbo].[PURCHASE_ORDER]([ID]);
