CREATE TABLE [dbo].[ACCOUNT_PERIOD] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ACCT_YEAR] DECIMAL(4,0) DEFAULT  NOT NULL,
    [ACCT_PERIOD] DECIMAL(2,0) DEFAULT  NOT NULL,
    [STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [BEGIN_DATE] datetime DEFAULT  NULL,
    [END_DATE] datetime DEFAULT  NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CALENDAR_ID] NVARCHAR(15) DEFAULT  NULL,
    [LOCK_MFG] NCHAR(1) DEFAULT ('N') NOT NULL,
    [LOCK_AR] NCHAR(1) DEFAULT ('N') NOT NULL,
    [LOCK_AP] NCHAR(1) DEFAULT ('N') NOT NULL,
    [LOCK_GJ] NCHAR(1) DEFAULT ('N') NOT NULL
)

ALTER TABLE [dbo].[ACCOUNT_PERIOD] ADD CONSTRAINT [PK_ACCOUNT_PERIOD] PRIMARY KEY ([SITE_ID], [ACCT_YEAR], [ACCT_PERIOD]);
