CREATE TABLE [dbo].[PRODUCT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [REV_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [ADJ_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [INV_MAT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [INV_LAB_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [INV_BUR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [INV_SER_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [VAR_MAT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [VAR_LAB_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [VAR_BUR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [VAR_SER_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CGS_MAT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CGS_LAB_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CGS_BUR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CGS_SER_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [WIP_MAT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [WIP_LAB_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [WIP_BUR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [WIP_SER_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [WITHHOLDING_CODE] NVARCHAR(15) DEFAULT  NULL,
    [DEMAND_FENCE_1] int DEFAULT  NULL,
    [DEMAND_FENCE_2] int DEFAULT  NULL,
    [COST_CATEGORY_ID] NVARCHAR(15) DEFAULT  NULL,
    [ACTIVE_FLAG] NCHAR(1) DEFAULT ('Y') NOT NULL,
    [CONSUMABLE_EXP_ACCT_ID] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[PRODUCT] ADD CONSTRAINT [PK_PRODUCT] PRIMARY KEY ([CODE]);

ALTER TABLE [dbo].[PRODUCT] ADD CONSTRAINT [FKEY9303] FOREIGN KEY ([WITHHOLDING_CODE]) REFERENCES [dbo].[WITHHOLDING]([CODE]);
