CREATE TABLE [dbo].[CONSIGN_RECEIVER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PURC_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NULL,
    [RECEIVED_DATE] datetime DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CARRIER_ID] NVARCHAR(15) DEFAULT  NULL,
    [BOL_ID] NVARCHAR(20) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CONSIGN_RECEIVER] ADD CONSTRAINT [PK_CONSIGN_RCVR] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[CONSIGN_RECEIVER] ADD CONSTRAINT [FKEY9613] FOREIGN KEY ([PURC_ORDER_ID]) REFERENCES [dbo].[PURCHASE_ORDER]([ID]);

ALTER TABLE [dbo].[CONSIGN_RECEIVER] ADD CONSTRAINT [FKEY9614] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);
