CREATE TABLE [dbo].[CASH_RECEIPT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CHECK_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BANK_ACCOUNT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NULL,
    [CHECK_DATE] datetime DEFAULT  NOT NULL,
    [STATUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT  NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DEPOSIT_ID] NVARCHAR(15) DEFAULT  NULL,
    [MARKED_FOR_PURGE] NCHAR(1) DEFAULT ('') NOT NULL,
    [PAYMENT_METHOD] NCHAR(1) DEFAULT ('') NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_EXCH_RATE] NCHAR(1) DEFAULT  NULL,
    [VOID_DATE] datetime DEFAULT  NULL,
    [VOID_CLEARED_DATE] datetime DEFAULT  NULL,
    [GROUP_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[CASH_RECEIPT] ADD CONSTRAINT [PK_CASH_RECEIPT] PRIMARY KEY ([CUSTOMER_ID], [CHECK_ID]);

ALTER TABLE [dbo].[CASH_RECEIPT] ADD CONSTRAINT [FKEY0027] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[CASH_RECEIPT] ADD CONSTRAINT [FKEY0068] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);

ALTER TABLE [dbo].[CASH_RECEIPT] ADD CONSTRAINT [FKEY0220] FOREIGN KEY ([BANK_ACCOUNT_ID]) REFERENCES [dbo].[BANK_ACCOUNT]([ID]);

ALTER TABLE [dbo].[CASH_RECEIPT] ADD CONSTRAINT [FKEY0282] FOREIGN KEY ([BANK_ACCOUNT_ID], [DEPOSIT_ID]) REFERENCES [dbo].[BANK_DEPOSIT]([BANK_ACCOUNT_ID], [DEPOSIT_ID]);

ALTER TABLE [dbo].[CASH_RECEIPT] ADD CONSTRAINT [FKEY9394] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
