CREATE TABLE [dbo].[VMDI_SPECIAL_COLS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [LAYOUT_KEY] NCHAR(3) DEFAULT  NOT NULL,
    [TABLE_NAME] NVARCHAR(18) DEFAULT  NOT NULL,
    [COLUMN_NAME] NVARCHAR(18) DEFAULT  NOT NULL,
    [SPECIAL_INST] NCHAR(1) DEFAULT  NULL,
    [SEGMENT_TYPE] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[VMDI_SPECIAL_COLS] ADD CONSTRAINT [PK_VMDI_SPEC_COLS] PRIMARY KEY ([LAYOUT_KEY], [TABLE_NAME], [COLUMN_NAME]);
