CREATE TABLE [dbo].[VR_MENU_NODE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [MENU_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [NODE_ID] int DEFAULT  NOT NULL,
    [PARENT_NODE_ID] int DEFAULT  NULL,
    [MENU_STRING] NVARCHAR(40) DEFAULT  NULL,
    [PROGRAM_ID] NVARCHAR(80) DEFAULT  NULL,
    [URL_STRING] NVARCHAR(255) DEFAULT  NULL,
    [DEFAULT_VIEW_ID] NVARCHAR(50) DEFAULT  NULL,
    [LOCALE] NVARCHAR(30) DEFAULT  NOT NULL,
    [ALLOW_VFIN] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[VR_MENU_NODE] ADD CONSTRAINT [PK_VR_MENU_NODE] PRIMARY KEY ([MENU_ID], [NODE_ID], [LOCALE]);

ALTER TABLE [dbo].[VR_MENU_NODE] ADD CONSTRAINT [FK_VR_MENU] FOREIGN KEY ([MENU_ID], [LOCALE]) REFERENCES [dbo].[VR_MENU]([ID], [LOCALE]);
