CREATE TABLE [dbo].[VMQUERY_ITEM_AUTHORITY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [ITEM_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [PERMISSION] NCHAR(1) DEFAULT ('N') NOT NULL
)

ALTER TABLE [dbo].[VMQUERY_ITEM_AUTHORITY] ADD CONSTRAINT [PK_VMQUERY_ITEM_AUTHORITY] PRIMARY KEY ([USER_ID], [ITEM_ID]);
