CREATE TABLE [dbo].[EQUIP_AREA] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [id] NVARCHAR(15) DEFAULT  NOT NULL,
    [description] NVARCHAR(50) DEFAULT  NULL
)

ALTER TABLE [dbo].[EQUIP_AREA] ADD CONSTRAINT [PK_EQUIP_AREA] PRIMARY KEY ([id]);
