CREATE TABLE [dbo].[EQUIP_TYPE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL
)

ALTER TABLE [dbo].[EQUIP_TYPE] ADD CONSTRAINT [PK_EQUIP_TYPE] PRIMARY KEY ([ID]);
