CREATE TABLE [dbo].[EQUIP_BRANCH] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AREA_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL
)

ALTER TABLE [dbo].[EQUIP_BRANCH] ADD CONSTRAINT [PK_EQUIP_BRANCH] PRIMARY KEY ([ID], [AREA_ID]);

ALTER TABLE [dbo].[EQUIP_BRANCH] ADD CONSTRAINT [FKEY9509] FOREIGN KEY ([AREA_ID]) REFERENCES [dbo].[EQUIP_AREA]([id]);
