CREATE TABLE [dbo].[COR_INBOX_ENTRY] (
    [C_ID] bigint IDENTITY(1,1) DEFAULT  NOT NULL,
    [C_XML] VARBINARY(MAX) DEFAULT  NOT NULL,
    [C_TENANT_ID] NVARCHAR(250) DEFAULT  NOT NULL,
    [C_MESSAGE_PRIORITY] int DEFAULT ((4)) NOT NULL,
    [C_CREATED_DATE_TIME] datetime DEFAULT  NOT NULL,
    [C_WAS_PROCESSED] int DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[COR_INBOX_ENTRY] ADD CONSTRAINT [PK_COR_INBOX_ENTRY] PRIMARY KEY ([C_ID]);
