CREATE TABLE [dbo].[SERVICE_RECEIPT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TRANSACTION_ID] int DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [OPERATION_SEQ_NO] smallint DEFAULT  NOT NULL,
    [SERVICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [FIXED_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [GOOD_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [BAD_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [TRANSACTION_DATE] datetime DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NULL,
    [PURC_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [PURC_ORDER_LINE_NO] smallint DEFAULT  NULL,
    [ACT_SERVICE_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [REJECTED_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [ACT_FREIGHT] DECIMAL(23,8) DEFAULT  NULL,
    [SHIPPING_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [WEIGHT_UM] NVARCHAR(15) DEFAULT  NULL,
    [SERVICE_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [RECEIVER_ID] NVARCHAR(15) DEFAULT  NULL,
    [RECEIVER_LINE_NO] smallint DEFAULT  NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NULL,
    [UNIT_COST] DECIMAL(22,8) DEFAULT  NULL,
    [PURC_DEL_LINE_NO] smallint DEFAULT  NULL,
    [RCVR_DEL_LINE_NO] smallint DEFAULT  NULL,
    [ACT_BURDEN_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [DEPARTMENT_ID] NVARCHAR(15) DEFAULT  NULL,
    [COST_CATEGORY_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_GOOD_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [USER_BAD_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [LAST_RETRO_DATE] datetime DEFAULT  NULL,
    [ACT_RATE_ID] NVARCHAR(15) DEFAULT  NULL,
    [ACT_PERIOD_ID] NVARCHAR(15) DEFAULT  NULL,
    [RETRO_RATE_ID] NVARCHAR(15) DEFAULT  NULL,
    [RETRO_PERIOD_ID] NVARCHAR(15) DEFAULT  NULL,
    [RETRO_RATE_CODE] NCHAR(1) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SERVICE_RECEIPT] ADD CONSTRAINT [PK_SERVICE_RECEIPT] PRIMARY KEY ([TRANSACTION_ID]);

ALTER TABLE [dbo].[SERVICE_RECEIPT] ADD CONSTRAINT [FK_SERVICE_RECEIPT_00] FOREIGN KEY ([DEPARTMENT_ID]) REFERENCES [dbo].[DEPARTMENT]([ID]);

ALTER TABLE [dbo].[SERVICE_RECEIPT] ADD CONSTRAINT [FK_SERVICE_RECEIPT_01] FOREIGN KEY ([COST_CATEGORY_ID]) REFERENCES [dbo].[COST_CATEGORY]([ID]);

ALTER TABLE [dbo].[SERVICE_RECEIPT] ADD CONSTRAINT [FK_SRVRCPT_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[SERVICE_RECEIPT] ADD CONSTRAINT [FKEY0116] FOREIGN KEY ([SERVICE_ID]) REFERENCES [dbo].[SERVICE]([ID]);

ALTER TABLE [dbo].[SERVICE_RECEIPT] ADD CONSTRAINT [FKEY0274] FOREIGN KEY ([PURC_ORDER_ID], [PURC_ORDER_LINE_NO]) REFERENCES [dbo].[PURC_ORDER_LINE]([PURC_ORDER_ID], [LINE_NO]);
