CREATE TABLE [dbo].[PURC_GROUP_USER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PURC_REQ_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [GROUP_TYPE] NVARCHAR(2) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [IS_LEADER] NCHAR(1) DEFAULT  NULL,
    [USER_SIGNOFF] NCHAR(1) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[PURC_GROUP_USER] ADD CONSTRAINT [PK_PURC_GROUP_USER] PRIMARY KEY ([PURC_REQ_ID], [GROUP_TYPE], [USER_ID]);

ALTER TABLE [dbo].[PURC_GROUP_USER] ADD CONSTRAINT [FK_PURC_GROUP_USER_00] FOREIGN KEY ([PURC_REQ_ID]) REFERENCES [dbo].[PURC_REQUISITION]([ID]);
