CREATE TABLE [dbo].[ACCOUNT_GROUP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [GROUP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [ADD_ASSET_EXPENSE] int DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[ACCOUNT_GROUP] ADD CONSTRAINT [PK_ACCOUNT_GROUP] PRIMARY KEY ([GROUP_ID], [ACCOUNT_ID]);

ALTER TABLE [dbo].[ACCOUNT_GROUP] ADD CONSTRAINT [FKEY0190] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);
