CREATE TABLE [dbo].[CASH_PLAN_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CASH_PLAN_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [CATEGORY] NVARCHAR(30) DEFAULT  NULL,
    [TYPE] NCHAR(1) DEFAULT  NULL,
    [CLASS] smallint DEFAULT  NULL
)

ALTER TABLE [dbo].[CASH_PLAN_LINE] ADD CONSTRAINT [PK_CASH_PLAN_LINE] PRIMARY KEY ([CASH_PLAN_ID], [LINE_NO]);

ALTER TABLE [dbo].[CASH_PLAN_LINE] ADD CONSTRAINT [FKEY9550] FOREIGN KEY ([CASH_PLAN_ID]) REFERENCES [dbo].[CASH_PLAN]([ID]);
