CREATE TABLE [dbo].[PLANNING_MPS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PLANNING_PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WANT_DATE] datetime DEFAULT  NOT NULL,
    [ORDER_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PLANNING_MPS] ADD CONSTRAINT [FK_PLNG_MPS_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[PLANNING_MPS] ADD CONSTRAINT [FKEY9364] FOREIGN KEY ([PLANNING_PART_ID], [SITE_ID]) REFERENCES [dbo].[PLANNING_PART]([ID], [SITE_ID]);
