CREATE TABLE [dbo].[QUOTE_ORDER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [QUOTE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[QUOTE_ORDER] ADD CONSTRAINT [PK_QUOTE_ORDER] PRIMARY KEY ([QUOTE_ID], [CUST_ORDER_ID]);

ALTER TABLE [dbo].[QUOTE_ORDER] ADD CONSTRAINT [FKEY0158] FOREIGN KEY ([CUST_ORDER_ID]) REFERENCES [dbo].[CUSTOMER_ORDER]([ID]);

ALTER TABLE [dbo].[QUOTE_ORDER] ADD CONSTRAINT [FKEY0178] FOREIGN KEY ([QUOTE_ID]) REFERENCES [dbo].[QUOTE]([ID]);
