CREATE TABLE [dbo].[PAYABLE_INST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VOUCHER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [INST_NO] smallint DEFAULT  NOT NULL,
    [DUE_DATE] datetime DEFAULT  NOT NULL,
    [TOTAL_AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [PAID_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [LAST_PAID_DATE] datetime DEFAULT  NULL,
    [ZERO_DATE] datetime DEFAULT  NULL,
    [PAY_STATUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [PAYMENT_DATE] datetime DEFAULT  NULL,
    [AUTHORIZED_PAYMENT] DECIMAL(23,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[PAYABLE_INST] ADD CONSTRAINT [PK_PAYABLE_INST] PRIMARY KEY ([VOUCHER_ID], [INST_NO]);
