CREATE TABLE [dbo].[LMC_MRP_CUMM_LT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [CALC_LT] int DEFAULT  NULL,
    [OVERRIDE_LT] int DEFAULT  NULL,
    [ENG_ID] VARCHAR(3) DEFAULT  NULL,
    [SITE_ID] VARCHAR(15) DEFAULT  NOT NULL,
    [INSPECT_LT] int DEFAULT  NULL,
    [PLAN_BUY_LT] int DEFAULT  NULL,
    [BASE_QTY] int DEFAULT ((0)) NOT NULL,
    [BASE_LT_DAYS] int DEFAULT ((0)) NOT NULL,
    [INC_QTY] int DEFAULT ((0)) NOT NULL,
    [INC_LT_DAYS] int DEFAULT ((0)) NOT NULL,
    [LT_DIRECTION] CHAR(1) DEFAULT ('F') NOT NULL,
    [LT_DAYS_OFFSET] int DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[LMC_MRP_CUMM_LT] ADD CONSTRAINT [pk_lmc_mrp_cumm_lt] PRIMARY KEY ([PART_ID], [SITE_ID]);
