CREATE TABLE [dbo].[VMDI_ACK_CODES] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ACK_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL
)

ALTER TABLE [dbo].[VMDI_ACK_CODES] ADD CONSTRAINT [PK_VMDI_ACK_CODES] PRIMARY KEY ([ACK_ID]);
