CREATE TABLE [dbo].[DOCUMENT_EML_AUDIT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DOCUMENT_ID] NVARCHAR(128) DEFAULT  NOT NULL,
    [DOC_FILE_PATH] NVARCHAR(255) DEFAULT  NOT NULL,
    [RECIPIENT_LIST] NVARCHAR(2000) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [EMAIL_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL,
    [REL_TYPE] NVARCHAR(15) DEFAULT  NULL,
    [REL_ID] NVARCHAR(15) DEFAULT  NULL
)
