CREATE TABLE [dbo].[CONSOLIDATION_LOG] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CONSOLIDATION_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [START_DATE] datetime DEFAULT  NOT NULL,
    [END_DATE] datetime DEFAULT  NOT NULL,
    [FILENAME] NVARCHAR(15) DEFAULT  NULL,
    [TYPE] NCHAR(1) DEFAULT  NULL
)
