CREATE TABLE [dbo].[ACCOUNT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(120) DEFAULT  NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [SUMMARY_ACCOUNT] NCHAR(1) DEFAULT ('') NOT NULL,
    [PARENT_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NULL,
    [REVALUE] NCHAR(1) DEFAULT ('') NOT NULL,
    [PROJECT_ACCOUNT] NCHAR(1) DEFAULT  NULL,
    [ACTIVE_FLAG] NCHAR(1) DEFAULT  NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[ACCOUNT] ADD CONSTRAINT [PK_ACCOUNT] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[ACCOUNT] ADD CONSTRAINT [FKEY9407] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
