CREATE TABLE [dbo].[DEMAND_FORECAST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [REQUIRED_DATE] datetime DEFAULT  NOT NULL,
    [REQUIRED_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[DEMAND_FORECAST] ADD CONSTRAINT [FK_DEMAND_FORECAST_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[DEMAND_FORECAST] ADD CONSTRAINT [FKEY0097] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);
