CREATE TABLE [dbo].[APPLICATION_GROUP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [GROUP_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [LANGUAGE_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [MENU_STRING] NVARCHAR(20) DEFAULT  NOT NULL,
    [ACCELERATOR] NCHAR(1) DEFAULT  NOT NULL,
    [SEQ_NO] smallint DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[APPLICATION_GROUP] ADD CONSTRAINT [PK_APPLICATION_GROUP] PRIMARY KEY ([GROUP_ID], [LANGUAGE_ID]);
