CREATE TABLE [dbo].[ACCOUNT_BUDGET] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ACCT_YEAR] DECIMAL(4,0) DEFAULT  NOT NULL,
    [ACCT_PERIOD] DECIMAL(2,0) DEFAULT  NOT NULL,
    [BUDGET_TYPE] NVARCHAR(15) DEFAULT  NOT NULL,
    [BUDGET_CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BUDGET_DR_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [BUDGET_CR_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [FLAG] int DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[ACCOUNT_BUDGET] ADD CONSTRAINT [PK_ACCOUNT_BUDGET] PRIMARY KEY ([ACCOUNT_ID], [SITE_ID], [ACCT_YEAR], [ACCT_PERIOD], [BUDGET_TYPE], [BUDGET_CODE], [CURRENCY_ID]);

ALTER TABLE [dbo].[ACCOUNT_BUDGET] ADD CONSTRAINT [FKEY9501] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[ACCOUNT_BUDGET] ADD CONSTRAINT [FKEY9502] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[ACCOUNT_BUDGET] ADD CONSTRAINT [FKEY9503] FOREIGN KEY ([BUDGET_TYPE]) REFERENCES [dbo].[BUDGET_TYPE]([id]);

ALTER TABLE [dbo].[ACCOUNT_BUDGET] ADD CONSTRAINT [FKEY9504] FOREIGN KEY ([BUDGET_CODE]) REFERENCES [dbo].[BUDGET_CODE]([ID]);

ALTER TABLE [dbo].[ACCOUNT_BUDGET] ADD CONSTRAINT [FKEY9505] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
