CREATE TABLE [dbo].[DEF_SHIPPING_LBL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SHIPTO_ADDR_NO] int DEFAULT  NOT NULL,
    [DEF_LBL_FORMAT_ID] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[DEF_SHIPPING_LBL] ADD CONSTRAINT [PK_DEF_SHIPPING_LBL] PRIMARY KEY ([PART_ID], [CUSTOMER_ID], [SHIPTO_ADDR_NO]);
