CREATE TABLE [dbo].[REVENUE_DETAIL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [REV_DIST_ID] int DEFAULT  NOT NULL,
    [PROJECT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [EAC_ID] NVARCHAR(15) DEFAULT  NULL,
    [PACKLIST_ID] NVARCHAR(15) DEFAULT  NULL,
    [PACKLIST_LINE_NO] smallint DEFAULT  NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [CUST_ORDER_LINE_NO] smallint DEFAULT  NULL,
    [EVENT_SEQ_NO] smallint DEFAULT  NULL,
    [TRANS_POC_REV] DECIMAL(23,8) DEFAULT  NULL,
    [TRANS_COGS_MAT] DECIMAL(23,8) DEFAULT  NULL,
    [TRANS_COGS_LAB] DECIMAL(23,8) DEFAULT  NULL,
    [TRANS_COGS_BUR] DECIMAL(23,8) DEFAULT  NULL,
    [TRANS_COGS_SERV] DECIMAL(23,8) DEFAULT  NULL,
    [TRANS_FEE_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [TRANS_FEE_PERCENT] DECIMAL(15,2) DEFAULT  NULL,
    [TARGET_REVENUE] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [POC_PERCENT] DECIMAL(15,2) DEFAULT  NULL,
    [POC_USER_PERCENT] DECIMAL(15,2) DEFAULT  NULL,
    [REV_TRANS_TYPE] NCHAR(1) DEFAULT  NULL,
    [TRANSACTION_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[REVENUE_DETAIL] ADD CONSTRAINT [PK_REVENUE_DETAIL] PRIMARY KEY ([REV_DIST_ID], [PROJECT_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[REVENUE_DETAIL] ADD CONSTRAINT [FK_REVENUE_DETAIL_00] FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[PROJECT_INFO]([ID]);

ALTER TABLE [dbo].[REVENUE_DETAIL] ADD CONSTRAINT [FK_REVENUE_DETAIL_01] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[REVENUE_DETAIL] ADD CONSTRAINT [FK_REVENUE_DETAIL_02] FOREIGN KEY ([PACKLIST_ID]) REFERENCES [dbo].[SHIPPER]([PACKLIST_ID]);

ALTER TABLE [dbo].[REVENUE_DETAIL] ADD CONSTRAINT [FK_REVENUE_DETAIL_03] FOREIGN KEY ([INVOICE_ID]) REFERENCES [dbo].[RECEIVABLE]([INVOICE_ID]);

ALTER TABLE [dbo].[REVENUE_DETAIL] ADD CONSTRAINT [FK_REVENUE_DETAIL_04] FOREIGN KEY ([CUST_ORDER_ID]) REFERENCES [dbo].[CUSTOMER_ORDER]([ID]);
