CREATE TABLE [dbo].[PLANNED_MATL_REQ] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PARENT_PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [PARENT_SEQ_NO] int DEFAULT  NOT NULL,
    [REQ_NO] smallint DEFAULT  NOT NULL,
    [REQUIRED_PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [REQUIRED_DATE] datetime DEFAULT  NULL,
    [REQUIRED_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PLANNED_MATL_REQ] ADD CONSTRAINT [FK_PLND_REQ_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
