CREATE TABLE [dbo].[RECEIVABLE_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[RECEIVABLE_BINARY] ADD CONSTRAINT [PK_RECEIVABLE_BINARY] PRIMARY KEY ([INVOICE_ID], [TYPE]);

ALTER TABLE [dbo].[RECEIVABLE_BINARY] ADD CONSTRAINT [FKEY0232] FOREIGN KEY ([INVOICE_ID]) REFERENCES [dbo].[RECEIVABLE]([INVOICE_ID]);
