CREATE TABLE [dbo].[SOA_NOUN] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(50) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(50) DEFAULT  NOT NULL,
    [SOR] NCHAR(1) DEFAULT  NOT NULL,
    [SYNC_IO] NCHAR(1) DEFAULT  NOT NULL,
    [PROCESS_IO] NCHAR(1) DEFAULT  NOT NULL,
    [GET_IO] NCHAR(1) DEFAULT  NOT NULL,
    [LOAD_IO] NCHAR(1) DEFAULT  NOT NULL,
    [NOUN_TYPE] NVARCHAR(3) DEFAULT  NULL,
    [ID_GRANULARITY] NCHAR(1) DEFAULT  NULL,
    [USE_GEN_SERVICE] NCHAR(1) DEFAULT ('N') NOT NULL,
    [OPTIONS] NVARCHAR(250) DEFAULT  NULL,
    [SETTINGS] NVARCHAR(250) DEFAULT  NULL
)

ALTER TABLE [dbo].[SOA_NOUN] ADD CONSTRAINT [PK_SOA_NOUN] PRIMARY KEY ([ID], [NAME]);
