CREATE TABLE [dbo].[CUST_ORDER_SHARE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SHARE_SALESREP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SHARE_PERCENT] DECIMAL(6,3) DEFAULT  NULL
)

ALTER TABLE [dbo].[CUST_ORDER_SHARE] ADD CONSTRAINT [PK_CUST_ORDER_SHARE] PRIMARY KEY ([CUST_ORDER_ID], [SHARE_SALESREP_ID]);

ALTER TABLE [dbo].[CUST_ORDER_SHARE] ADD CONSTRAINT [FKEY0154] FOREIGN KEY ([CUST_ORDER_ID]) REFERENCES [dbo].[CUSTOMER_ORDER]([ID]);

ALTER TABLE [dbo].[CUST_ORDER_SHARE] ADD CONSTRAINT [FKEY0270] FOREIGN KEY ([SHARE_SALESREP_ID]) REFERENCES [dbo].[SALES_REP]([ID]);
