CREATE TABLE [dbo].[DOCUMENT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [REFERENCE_TYPE] NVARCHAR(5) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL,
    [CATEGORY_ID] NVARCHAR(15) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [DOC_FILE_PATH] NVARCHAR(255) DEFAULT  NULL,
    [ECN_REVISION] NCHAR(1) DEFAULT  NULL,
    [REVISION_ID] NVARCHAR(8) DEFAULT  NULL,
    [STAGE_ID] NVARCHAR(15) DEFAULT  NULL,
    [ECN_REV_CONTROL] NCHAR(1) DEFAULT  NULL,
    [USER_1] NVARCHAR(80) DEFAULT  NULL,
    [USER_2] NVARCHAR(80) DEFAULT  NULL,
    [USER_3] NVARCHAR(80) DEFAULT  NULL,
    [USER_4] NVARCHAR(80) DEFAULT  NULL,
    [USER_5] NVARCHAR(80) DEFAULT  NULL,
    [USER_6] NVARCHAR(80) DEFAULT  NULL,
    [USER_7] NVARCHAR(80) DEFAULT  NULL,
    [USER_8] NVARCHAR(80) DEFAULT  NULL,
    [USER_9] NVARCHAR(80) DEFAULT  NULL,
    [USER_10] NVARCHAR(80) DEFAULT  NULL,
    [UDF_LAYOUT_ID] NVARCHAR(15) DEFAULT  NULL,
    [ALLOW_EMAIL] NCHAR(1) DEFAULT  NULL,
    [PATH_TYPE] NCHAR(1) DEFAULT ('N') NOT NULL
)

ALTER TABLE [dbo].[DOCUMENT] ADD CONSTRAINT [PK_DOCUMENT] PRIMARY KEY ([ID]);
