CREATE TABLE [dbo].[REVALUE_DIST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [REVALUE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DIST_NO] int DEFAULT  NOT NULL,
    [ENTRY_NO] int DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [AMOUNT_TYPE] NCHAR(2) DEFAULT  NOT NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [POSTING_STATUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [BATCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [NATIVE] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[REVALUE_DIST] ADD CONSTRAINT [PK_REVALUE_DIST] PRIMARY KEY ([REVALUE_ID], [DIST_NO], [ENTRY_NO], [CURRENCY_ID]);

ALTER TABLE [dbo].[REVALUE_DIST] ADD CONSTRAINT [FKEY9476] FOREIGN KEY ([REVALUE_ID]) REFERENCES [dbo].[REVALUE]([ID]);

ALTER TABLE [dbo].[REVALUE_DIST] ADD CONSTRAINT [FKEY9477] FOREIGN KEY ([GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[REVALUE_DIST] ADD CONSTRAINT [FKEY9478] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[REVALUE_DIST] ADD CONSTRAINT [FKEY9479] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
