CREATE TABLE [dbo].[PRIORITY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[PRIORITY] ADD CONSTRAINT [PK_PRIORITY] PRIMARY KEY ([CODE]);
