CREATE TABLE [dbo].[LABOR_TICKET] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TRANSACTION_ID] int DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [OPERATION_SEQ_NO] smallint DEFAULT  NULL,
    [TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [SETUP_COMPLETED] NCHAR(1) DEFAULT ('') NOT NULL,
    [EMPLOYEE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DEPARTMENT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NULL,
    [HOURLY_COST] DECIMAL(15,2) DEFAULT  NULL,
    [CLOCK_IN] datetime DEFAULT  NULL,
    [CLOCK_OUT] datetime DEFAULT  NULL,
    [HOURS_WORKED] DECIMAL(7,2) DEFAULT  NULL,
    [HOURS_BREAK] DECIMAL(7,2) DEFAULT  NULL,
    [MULTIPLIER_1] DECIMAL(5,3) DEFAULT  NULL,
    [MULTIPLIER_2] DECIMAL(5,3) DEFAULT  NULL,
    [GOOD_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [BAD_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [TRANSACTION_DATE] datetime DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NULL,
    [BURDEN_PER_HR] DECIMAL(22,8) DEFAULT  NULL,
    [BURDEN_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [BUR_PER_OPERATION] DECIMAL(23,8) DEFAULT  NULL,
    [POSTING_CANDIDATE] NCHAR(1) DEFAULT ('') NOT NULL,
    [HOURS_OVERALL] DECIMAL(7,2) DEFAULT  NULL,
    [HOURS_PREVIOUS] DECIMAL(7,2) DEFAULT  NULL,
    [INDIRECT_CODE] NCHAR(1) DEFAULT ('') NOT NULL,
    [INDIRECT_ID] NVARCHAR(15) DEFAULT  NULL,
    [SHIFT_DATE] datetime DEFAULT  NULL,
    [BREAK_CLOCKIN] datetime DEFAULT  NULL,
    [HOURS_BREAK_IND] DECIMAL(5,2) DEFAULT  NULL,
    [ACT_LABOR_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [ACT_BURDEN_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [ACT_CLOCK_IN] datetime DEFAULT  NULL,
    [ACT_CLOCK_OUT] datetime DEFAULT  NULL,
    [STARTING_TRANS] NCHAR(1) DEFAULT  NULL,
    [BURDEN_PER_UNIT] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_COST] DECIMAL(22,8) DEFAULT  NULL,
    [GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [EARNING_CODE_ID] NVARCHAR(15) DEFAULT  NULL,
    [BUDGET_ACCT_YEAR] DECIMAL(4,0) DEFAULT  NULL,
    [BUDGET_ACCT_PERIOD] DECIMAL(2,0) DEFAULT  NULL,
    [MILESTONE_TXN_ID] int DEFAULT  NULL,
    [MILESTONE_UPDATED] NCHAR(1) DEFAULT  NULL,
    [COST_CATEGORY_ID] NVARCHAR(15) DEFAULT  NULL,
    [AUTOGEN_TXN_ID] int DEFAULT  NULL,
    [UNADJ_CLOCK_IN] datetime DEFAULT  NULL,
    [UNADJ_CLOCK_OUT] datetime DEFAULT  NULL,
    [DEVIATION_ID] NVARCHAR(15) DEFAULT  NULL,
    [DATA_COLL_COMP] NCHAR(1) DEFAULT  NULL,
    [PRD_INSP_PLAN_ID] NVARCHAR(16) DEFAULT  NULL,
    [ACT_RATE_ID] NVARCHAR(15) DEFAULT  NULL,
    [ACT_PERIOD_ID] NVARCHAR(15) DEFAULT  NULL,
    [RETRO_RATE_ID] NVARCHAR(15) DEFAULT  NULL,
    [RETRO_PERIOD_ID] NVARCHAR(15) DEFAULT  NULL,
    [RETRO_RATE_CODE] NCHAR(1) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [START_MACHINE_ID] NVARCHAR(240) DEFAULT  NULL,
    [STOP_MACHINE_ID] NVARCHAR(240) DEFAULT  NULL
)

ALTER TABLE [dbo].[LABOR_TICKET] ADD CONSTRAINT [PK_LABOR_TICKET] PRIMARY KEY ([TRANSACTION_ID]);

ALTER TABLE [dbo].[LABOR_TICKET] ADD CONSTRAINT [FK_LABOR_TICKET_00] FOREIGN KEY ([DEVIATION_ID]) REFERENCES [dbo].[DEVIATION_REASON]([ID]);

ALTER TABLE [dbo].[LABOR_TICKET] ADD CONSTRAINT [FK_LABORTICKET_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[LABOR_TICKET] ADD CONSTRAINT [FKEY0048] FOREIGN KEY ([INDIRECT_ID]) REFERENCES [dbo].[INDIRECT]([ID]);

ALTER TABLE [dbo].[LABOR_TICKET] ADD CONSTRAINT [FKEY0051] FOREIGN KEY ([EARNING_CODE_ID]) REFERENCES [dbo].[EARNING_CODE]([ID]);

ALTER TABLE [dbo].[LABOR_TICKET] ADD CONSTRAINT [FKEY0086] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [dbo].[EMPLOYEE]([ID]);

ALTER TABLE [dbo].[LABOR_TICKET] ADD CONSTRAINT [FKEY0129] FOREIGN KEY ([RESOURCE_ID]) REFERENCES [dbo].[SHOP_RESOURCE]([ID]);
