CREATE TABLE [dbo].[PHYS_INV_PIECES] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PHYS_COUNT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TAG_NO] int DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NULL,
    [LENGTH] DECIMAL(14,4) DEFAULT  NULL,
    [WIDTH] DECIMAL(14,4) DEFAULT  NULL,
    [HEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [LOCATION_ID] NVARCHAR(15) DEFAULT  NULL,
    [DIMENSIONS_UM] NVARCHAR(15) DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [SUB_TAG_NO] int DEFAULT  NULL
)
