CREATE TABLE [dbo].[SETUP_ATTRIBUTE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [DATA_TYPE] NCHAR(1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SETUP_ATTRIBUTE] ADD CONSTRAINT [PK_SETUP_ATTRIBUTE] PRIMARY KEY ([ID]);
