CREATE TABLE [dbo].[NEXT_NUMBER_GEN] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TABLE_NAME] NVARCHAR(18) DEFAULT  NULL,
    [COLUMN_NAME] NVARCHAR(18) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(30) DEFAULT  NULL,
    [ALPHA_PREFIX] NVARCHAR(4) DEFAULT  NULL,
    [NEXT_NUMBER] int DEFAULT  NULL,
    [ALPHA_SUFFIX] NVARCHAR(4) DEFAULT  NULL,
    [LEADING_ZEROS] NCHAR(1) DEFAULT  NULL,
    [DECIMAL_PLACES] smallint DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL
)
