CREATE TABLE [dbo].[GPSUMF] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [GUBOID] NVARCHAR(30) DEFAULT  NULL,
    [GUBOVL] NVARCHAR(15) DEFAULT  NULL,
    [GUBODS] NVARCHAR(30) DEFAULT  NULL
)
