CREATE TABLE [dbo].[SHIP_VIA_SYNC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EVENT_ID] int DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [SHIP_VIA_CODE] NVARCHAR(40) DEFAULT  NOT NULL,
    [EXCEPTION] NCHAR(1) DEFAULT  NOT NULL,
    [SUBSCRIPTIONS] int DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[SHIP_VIA_SYNC] ADD CONSTRAINT [PK_SHIP_VIA_SYNC] PRIMARY KEY ([EVENT_ID]);
