CREATE TABLE [dbo].[SERV_DISP_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DISPATCH_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SERV_DISP_BINARY] ADD CONSTRAINT [PK_SERV_DISP_BINARY] PRIMARY KEY ([DISPATCH_ID], [TYPE]);
