CREATE TABLE [dbo].[PROJECT_BUDGET] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [SEQUENCE_NO] int DEFAULT  NOT NULL,
    [DEPARTMENT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [COST_CATEGORY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BUDGET_HOURS] DECIMAL(7,2) DEFAULT  NULL,
    [BUDGET_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [DISTRIBUTION_ID] NVARCHAR(15) DEFAULT  NULL,
    [WBS_CODE] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[PROJECT_BUDGET] ADD CONSTRAINT [PK_PROJECT_BUDGET] PRIMARY KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [SEQUENCE_NO], [DEPARTMENT_ID], [COST_CATEGORY_ID]);

ALTER TABLE [dbo].[PROJECT_BUDGET] ADD CONSTRAINT [FK_PROJECT_BUDGET_00] FOREIGN KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID]) REFERENCES [dbo].[WORK_ORDER]([TYPE], [BASE_ID], [LOT_ID], [SPLIT_ID], [SUB_ID]);

ALTER TABLE [dbo].[PROJECT_BUDGET] ADD CONSTRAINT [FK_PROJECT_BUDGET_01] FOREIGN KEY ([DEPARTMENT_ID]) REFERENCES [dbo].[DEPARTMENT]([ID]);

ALTER TABLE [dbo].[PROJECT_BUDGET] ADD CONSTRAINT [FK_PROJECT_BUDGET_02] FOREIGN KEY ([COST_CATEGORY_ID]) REFERENCES [dbo].[COST_CATEGORY]([ID]);

ALTER TABLE [dbo].[PROJECT_BUDGET] ADD CONSTRAINT [FK_PROJECT_BUDGET_03] FOREIGN KEY ([DISTRIBUTION_ID]) REFERENCES [dbo].[DISTRIBUTION]([ID]);
