CREATE TABLE [dbo].[CONSOLID_ACCOUNT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PARENT_ACCT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(120) DEFAULT  NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CONSOLID_ACCOUNT] ADD CONSTRAINT [PK_CONSOLID_ACCT] PRIMARY KEY ([PARENT_ACCT_ID]);
