CREATE TABLE [dbo].[SALES_REP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(40) DEFAULT  NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NULL,
    [EMPLOYEE_ID] NVARCHAR(15) DEFAULT  NULL,
    [PAY_METHOD] NCHAR(1) DEFAULT ('') NOT NULL,
    [DEF_COMMISSION_PCT] DECIMAL(6,3) DEFAULT  NULL,
    [EARNING_CODE_ID] NVARCHAR(15) DEFAULT  NULL,
    [ACTIVE] NCHAR(1) DEFAULT ('Y') NOT NULL
)

ALTER TABLE [dbo].[SALES_REP] ADD CONSTRAINT [PK_SALES_REP] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[SALES_REP] ADD CONSTRAINT [FKEY0049] FOREIGN KEY ([EARNING_CODE_ID]) REFERENCES [dbo].[EARNING_CODE]([ID]);

ALTER TABLE [dbo].[SALES_REP] ADD CONSTRAINT [FKEY0072] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);

ALTER TABLE [dbo].[SALES_REP] ADD CONSTRAINT [FKEY0085] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [dbo].[EMPLOYEE]([ID]);
