CREATE TABLE [dbo].[PLANNING_BOM] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PARENT_PLN_PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SUBORD_PLN_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [SUBORD_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [PERCENT_PER] DECIMAL(12,6) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PLANNING_BOM] ADD CONSTRAINT [FK_PLNG_BOM_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
