CREATE TABLE [dbo].[SK_QA_REQUIREMENTS_PICKLIST] (
    [QAReqName] VARCHAR(50) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SK_QA_REQUIREMENTS_PICKLIST] ADD CONSTRAINT [PK_SK_QA_REQUIREMENTS_PICKLIST] PRIMARY KEY ([QAReqName]);
