CREATE TABLE [dbo].[PURCHASE_CONTRACT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [STATUS_REASON_CODE] NVARCHAR(100) DEFAULT  NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [VENDOR_CONTRACT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[PURCHASE_CONTRACT] ADD CONSTRAINT [PK_PURCHASE_CONTRACT] PRIMARY KEY ([ID]);
