CREATE TABLE [dbo].[CUSTOMER_PRICE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SELLING_UM] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUSTOMER_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [QTY_BREAK_1] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_2] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_3] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_4] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_5] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_6] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_7] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_8] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_9] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_10] DECIMAL(20,8) DEFAULT  NULL,
    [UNIT_PRICE_1] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_2] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_3] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_4] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_5] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_6] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_7] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_8] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_9] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_10] DECIMAL(22,8) DEFAULT  NULL,
    [DEFAULT_UNIT_PRICE] DECIMAL(22,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[CUSTOMER_PRICE] ADD CONSTRAINT [PK_CUSTOMER_PRICE] PRIMARY KEY ([CUSTOMER_ID], [PART_ID], [SELLING_UM]);

ALTER TABLE [dbo].[CUSTOMER_PRICE] ADD CONSTRAINT [FKEY0063] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);

ALTER TABLE [dbo].[CUSTOMER_PRICE] ADD CONSTRAINT [FKEY0088] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);

ALTER TABLE [dbo].[CUSTOMER_PRICE] ADD CONSTRAINT [FKEY0260] FOREIGN KEY ([SELLING_UM]) REFERENCES [dbo].[UNITS]([UNIT_OF_MEASURE]);
