CREATE TABLE [dbo].[NMFC_CODE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ARTICLE] NVARCHAR(8) DEFAULT  NULL,
    [SUB] NVARCHAR(3) DEFAULT  NULL,
    [LTL_CLASS] NVARCHAR(5) DEFAULT  NULL,
    [TL_CLASS] NVARCHAR(5) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(250) DEFAULT  NULL,
    [HAZARDOUS] NCHAR(1) DEFAULT ('') NOT NULL
)

ALTER TABLE [dbo].[NMFC_CODE] ADD CONSTRAINT [PK_NMFC_CODE] PRIMARY KEY ([ID]);
