CREATE TABLE [dbo].[GAGE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [GAGE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [TYPE] NVARCHAR(15) DEFAULT  NULL,
    [SERIALNUM_REQD] NCHAR(1) DEFAULT ('') NOT NULL
)

ALTER TABLE [dbo].[GAGE] ADD CONSTRAINT [PK_GAGE] PRIMARY KEY ([GAGE_ID]);
