CREATE TABLE [dbo].[DEMSUP_SUMMARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SPID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ID] int DEFAULT  NOT NULL,
    [RECEIVED_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[DEMSUP_SUMMARY] ADD CONSTRAINT [PK_DEMSUP_SUM] PRIMARY KEY ([SPID], [ID]);
