CREATE TABLE [dbo].[TASK_REJ_CODES] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[TASK_REJ_CODES] ADD CONSTRAINT [PK_TASK_REJ_CODES] PRIMARY KEY ([CODE]);
