CREATE TABLE [dbo].[TEST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT  NOT NULL,
    [LAST_UPDATE] datetime DEFAULT  NOT NULL,
    [QTY_REPORTED] int DEFAULT ((0)) NOT NULL,
    [HOURS_REPORTED] DECIMAL(14,6) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[TEST] ADD CONSTRAINT [PK_TEST] PRIMARY KEY ([ID]);
