CREATE TABLE [dbo].[CONSOLIDATION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[CONSOLIDATION] ADD CONSTRAINT [PK_CONSOLIDATION] PRIMARY KEY ([ID]);
