CREATE TABLE [dbo].[PALLET_DETAIL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PACKLIST_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PACKLIST_LINE_NO] smallint DEFAULT  NOT NULL,
    [PALLET_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [CARTON_COUNT] smallint DEFAULT  NOT NULL,
    [SHIPPING_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [PACKAGE_TYPE] NVARCHAR(5) DEFAULT  NULL,
    [QTY_PER_PKG] DECIMAL(20,8) DEFAULT  NULL,
    [DEL_LINE_NO] smallint DEFAULT  NULL,
    [SKID_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [SKID_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [CONTAINER_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [CONTAINER_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [CREATE_INV_TRANS] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[PALLET_DETAIL] ADD CONSTRAINT [PK_PALLET_DETAIL] PRIMARY KEY ([PACKLIST_ID], [PACKLIST_LINE_NO], [PALLET_ID]);

ALTER TABLE [dbo].[PALLET_DETAIL] ADD CONSTRAINT [FKEY9105] FOREIGN KEY ([PACKLIST_ID], [PACKLIST_LINE_NO]) REFERENCES [dbo].[SHIPPER_LINE]([PACKLIST_ID], [LINE_NO]);
