CREATE TABLE [dbo].[VMDI_LAYOUT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [KEY] NCHAR(3) DEFAULT  NOT NULL,
    [VERSION] NCHAR(4) DEFAULT  NOT NULL,
    [DIRECTION] NCHAR(1) DEFAULT  NOT NULL,
    [OUTPUT_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [INBOUND_RULE] NCHAR(1) DEFAULT  NOT NULL,
    [STYLE] NCHAR(1) DEFAULT  NOT NULL,
    [FIELD_DELIMITER] NCHAR(1) DEFAULT  NULL,
    [RECORD_DELIMITER] NCHAR(1) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [LAST_RUN_DATE] datetime DEFAULT  NULL,
    [DEL_UNSHIPPED] NCHAR(1) DEFAULT  NULL,
    [PREFIX_TOKEN] NVARCHAR(15) DEFAULT  NULL,
    [AUTOGENERATE] NCHAR(1) DEFAULT  NULL,
    [SAVE_DATA_FLOW] NCHAR(1) DEFAULT ('') NOT NULL,
    [DEL_UNSHIPPED_LN] NCHAR(1) DEFAULT  NULL,
    [description] NVARCHAR(80) DEFAULT  NULL,
    [SPECIAL_CONDITION] NVARCHAR(250) DEFAULT  NULL,
    [LINE_INBOUND_RULE] NCHAR(1) DEFAULT  NULL,
    [DEL_INBOUND_RULE] NCHAR(1) DEFAULT  NULL,
    [INBOUND_QTY_RULE] NCHAR(1) DEFAULT  NULL,
    [ALLOW_UPD_DISP_ORD] NCHAR(1) DEFAULT  NULL,
    [CHK_BLANKET_FLAG] NCHAR(1) DEFAULT  NULL,
    [INV_OUTBOUND_RULE] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[VMDI_LAYOUT] ADD CONSTRAINT [PK_VMDI_LAYOUT] PRIMARY KEY ([KEY], [VERSION], [DIRECTION]);
