CREATE TABLE [dbo].[REVISION_NUMBERING] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [STAGE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [REVISION_ID] NVARCHAR(8) DEFAULT  NULL
)

ALTER TABLE [dbo].[REVISION_NUMBERING] ADD CONSTRAINT [PK_REVISION_NUMBERING] PRIMARY KEY ([STAGE_ID], [LINE_NO]);
