CREATE TABLE [dbo].[INSTALLMENT_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [INSTALLMENT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [INST_TYPE] NCHAR(2) DEFAULT  NOT NULL,
    [INST_NO] smallint DEFAULT  NOT NULL,
    [INST_PERCENT] DECIMAL(6,3) DEFAULT ((0)) NOT NULL,
    [PERIOD] smallint DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[INSTALLMENT_LINE] ADD CONSTRAINT [PK_INSTALLMENT_LINE] PRIMARY KEY ([INSTALLMENT_ID], [INST_TYPE], [INST_NO]);

ALTER TABLE [dbo].[INSTALLMENT_LINE] ADD CONSTRAINT [FK_INSTALLMENT_LINE_00] FOREIGN KEY ([INSTALLMENT_ID], [INST_TYPE]) REFERENCES [dbo].[INSTALLMENT]([ID], [INST_TYPE]);
