CREATE TABLE [dbo].[PURC_REQ_LINE_DEL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PURC_REQ_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PURC_REQ_LINE_NO] smallint DEFAULT  NOT NULL,
    [DEL_SCHED_LINE_NO] smallint DEFAULT  NOT NULL,
    [DESIRED_RECV_DATE] datetime DEFAULT  NULL,
    [USER_ORDER_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [ORDER_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [SHIPTO_ID] NVARCHAR(20) DEFAULT  NULL,
    [SHIPFROM_ID] NVARCHAR(20) DEFAULT  NULL,
    [USER_RECEIVED_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [PIECE_COUNT] int DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_1] NVARCHAR(30) DEFAULT  NULL,
    [USER_2] NVARCHAR(30) DEFAULT  NULL,
    [USER_3] NVARCHAR(30) DEFAULT  NULL,
    [USER_4] NVARCHAR(30) DEFAULT  NULL,
    [USER_5] NVARCHAR(30) DEFAULT  NULL,
    [USER_6] NVARCHAR(30) DEFAULT  NULL,
    [USER_7] NVARCHAR(30) DEFAULT  NULL,
    [USER_8] NVARCHAR(30) DEFAULT  NULL,
    [USER_9] NVARCHAR(30) DEFAULT  NULL,
    [USER_10] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[PURC_REQ_LINE_DEL] ADD CONSTRAINT [PK_PURC_REQ_LINE_DEL] PRIMARY KEY ([PURC_REQ_ID], [PURC_REQ_LINE_NO], [DEL_SCHED_LINE_NO]);
