CREATE TABLE [dbo].[SKILLS_AUDIT_Operation] (
    [rowid] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BASE_ID] NVARCHAR(30) DEFAULT  NULL,
    [LOT_ID] NVARCHAR(3) DEFAULT  NULL,
    [SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [SEQUENCE_NO] smallint DEFAULT  NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NULL,
    [COMPLETED_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [STATUS] NVARCHAR(1) DEFAULT  NULL,
    [EVENT] NVARCHAR(1) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NULL,
    [creation_DATE] datetime DEFAULT  NULL
)
