CREATE TABLE [dbo].[MOVE_REQUEST_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [MOVE_REQUEST_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] int DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [OPERATION_SEQ_NO] smallint DEFAULT  NULL,
    [PIECE_NO] smallint DEFAULT  NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(255) DEFAULT  NULL,
    [QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [PIECE_COUNT] DECIMAL(20,8) DEFAULT  NULL,
    [LENGTH] DECIMAL(14,4) DEFAULT  NULL,
    [WIDTH] DECIMAL(14,4) DEFAULT  NULL,
    [HEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [DIMENSIONS_UM] NVARCHAR(15) DEFAULT  NULL,
    [WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [WEIGHT_UM] NVARCHAR(15) DEFAULT  NULL,
    [INV_TRANS_ID] int DEFAULT  NULL,
    [SERV_TRANS_ID] int DEFAULT  NULL,
    [LAB_TRANS_ID] int DEFAULT  NULL
)

ALTER TABLE [dbo].[MOVE_REQUEST_LINE] ADD CONSTRAINT [PK_MOVE_REQUEST_LINE] PRIMARY KEY ([MOVE_REQUEST_ID], [LINE_NO]);

ALTER TABLE [dbo].[MOVE_REQUEST_LINE] ADD CONSTRAINT [FK_MOVE_REQ_LINE_LAB_TICKET] FOREIGN KEY ([LAB_TRANS_ID]) REFERENCES [dbo].[LABOR_TICKET]([TRANSACTION_ID]);

ALTER TABLE [dbo].[MOVE_REQUEST_LINE] ADD CONSTRAINT [FK_MOVE_REQUEST_LINE_INV_TRANS] FOREIGN KEY ([INV_TRANS_ID]) REFERENCES [dbo].[INVENTORY_TRANS]([TRANSACTION_ID]);

ALTER TABLE [dbo].[MOVE_REQUEST_LINE] ADD CONSTRAINT [FK_MOVE_REQUEST_LINE_MOVE_RQST] FOREIGN KEY ([MOVE_REQUEST_ID]) REFERENCES [dbo].[MOVE_REQUEST]([ID]);

ALTER TABLE [dbo].[MOVE_REQUEST_LINE] ADD CONSTRAINT [FK_MOVE_REQUEST_LINE_PART] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);

ALTER TABLE [dbo].[MOVE_REQUEST_LINE] ADD CONSTRAINT [FK_MOVE_REQUEST_LINE_SERV_REC] FOREIGN KEY ([SERV_TRANS_ID]) REFERENCES [dbo].[SERVICE_RECEIPT]([TRANSACTION_ID]);
