CREATE TABLE [dbo].[VENDOR_BUYER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BUYER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [EFFECTIVE_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[VENDOR_BUYER] ADD CONSTRAINT [PK_VENDOR_BUYER] PRIMARY KEY ([VENDOR_ID], [BUYER_ID]);
