CREATE TABLE [dbo].[SHIFT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [SHIFT_BEG_BEF_WIN] smallint DEFAULT  NULL,
    [SHIFT_BEG_AFT_WIN] smallint DEFAULT  NULL,
    [SHIFT_END_BEF_WIN] smallint DEFAULT  NULL,
    [SHIFT_END_AFT_WIN] smallint DEFAULT  NULL,
    [BTWN_JOB_LAG_TIME] smallint DEFAULT  NULL,
    [BREAKS_WINDOW] smallint DEFAULT  NULL,
    [INDIRECT_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[SHIFT] ADD CONSTRAINT [PK_SHIFT] PRIMARY KEY ([ID]);
