CREATE TABLE [dbo].[DBR_EVENT_DETECT] (
    [EVENT_CLASS] NVARCHAR(2) DEFAULT  NOT NULL,
    [EVENT_ACTION] NVARCHAR(2) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [DOC_TYPE] NVARCHAR(2) DEFAULT  NULL,
    [DOC_BASE_ID] NVARCHAR(30) DEFAULT  NULL,
    [DOC_LOT_ID] NVARCHAR(15) DEFAULT  NULL,
    [DOC_SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [DOC_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [DOC_SEQ_NO] int DEFAULT  NULL,
    [DOC_SUB_SEQ_NO] smallint DEFAULT  NULL,
    [CAUSE] NVARCHAR(5) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [STATUS] NCHAR(1) DEFAULT  NULL,
    [ERROR_MSG] NVARCHAR(250) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)
