CREATE TABLE [dbo].[T_SEC_APPROX_K1] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [T] DECIMAL(3,1) DEFAULT  NOT NULL,
    [OUTSIDE_LIM1] DECIMAL(6,4) DEFAULT  NOT NULL,
    [OUTSIDE_LIM2] DECIMAL(6,4) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[T_SEC_APPROX_K1] ADD CONSTRAINT [PK_T_SEC_APPROX_K1] PRIMARY KEY ([T]);
