CREATE TABLE [dbo].[VENDOR_CONTACT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CONTACT_NO] smallint DEFAULT  NOT NULL,
    [CONTACT_FIRST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_LAST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_POSITION] NVARCHAR(50) DEFAULT  NULL,
    [CONTACT_INITIAL] NVARCHAR(2) DEFAULT  NULL,
    [CONTACT_HONORIFIC] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_PHONE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_FAX] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_MOBILE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_EMAIL] NVARCHAR(100) DEFAULT  NULL
)

ALTER TABLE [dbo].[VENDOR_CONTACT] ADD CONSTRAINT [PK_VENDOR_CONTACT] PRIMARY KEY ([VENDOR_ID], [CONTACT_NO]);

ALTER TABLE [dbo].[VENDOR_CONTACT] ADD CONSTRAINT [FKEY0075] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);
