CREATE TABLE [dbo].[CASH_PLAN_ACCOUNT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CASH_PLAN_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CASH_PLAN_LINE_NO] smallint DEFAULT  NOT NULL,
    [ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CASH_PLAN_ACCOUNT] ADD CONSTRAINT [PK_CASH_PLAN_ACCOUNT] PRIMARY KEY ([CASH_PLAN_ID], [CASH_PLAN_LINE_NO], [ACCOUNT_ID]);

ALTER TABLE [dbo].[CASH_PLAN_ACCOUNT] ADD CONSTRAINT [FKEYCP03] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);
