CREATE TABLE [dbo].[LMC_MRP_FILTER_GROUP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USERID] VARCHAR(30) DEFAULT  NOT NULL,
    [CATEGORY] VARCHAR(30) DEFAULT  NOT NULL,
    [LIST_ID] VARCHAR(15) DEFAULT  NOT NULL,
    [VM_CODE] VARCHAR(80) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[LMC_MRP_FILTER_GROUP] ADD CONSTRAINT [PK_LMC_MRP_FILTER_GROUP] PRIMARY KEY ([USERID], [CATEGORY], [LIST_ID], [VM_CODE]);
