CREATE TABLE [dbo].[ECN] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [SUBJECT] NVARCHAR(60) DEFAULT  NULL,
    [ORIGINATOR] NVARCHAR(60) DEFAULT  NULL,
    [DIST_LIST] NVARCHAR(60) DEFAULT  NULL,
    [AUTHORIZATION_1] NVARCHAR(15) DEFAULT  NULL,
    [AUTHORIZATION_2] NVARCHAR(15) DEFAULT  NULL,
    [AUTHORIZATION_3] NVARCHAR(15) DEFAULT  NULL,
    [AUTHORIZATION_4] NVARCHAR(15) DEFAULT  NULL,
    [AUTH_DATE_1] datetime DEFAULT  NULL,
    [AUTH_DATE_2] datetime DEFAULT  NULL,
    [AUTH_DATE_3] datetime DEFAULT  NULL,
    [AUTH_DATE_4] datetime DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [MODIFY_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[ECN] ADD CONSTRAINT [PK_ECN] PRIMARY KEY ([ID]);
