CREATE TABLE [dbo].[EQUIP_MAINT_DISC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [MAINT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DISCOUNT_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [DISCOUNT_VALUE] DECIMAL(23,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[EQUIP_MAINT_DISC] ADD CONSTRAINT [PK_EQ_MAINT_DISC] PRIMARY KEY ([MAINT_ID], [CUSTOMER_ID]);

ALTER TABLE [dbo].[EQUIP_MAINT_DISC] ADD CONSTRAINT [FKEY9507] FOREIGN KEY ([MAINT_ID]) REFERENCES [dbo].[EQUIP_MAINT_TYPE]([ID]);

ALTER TABLE [dbo].[EQUIP_MAINT_DISC] ADD CONSTRAINT [FKEY9508] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);
