CREATE TABLE [dbo].[NOTIFICATION_DATA] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [PRIMARY_KEY] NVARCHAR(15) DEFAULT  NOT NULL,
    [OWNER_ID] NVARCHAR(15) DEFAULT  NULL,
    [DOC_ID] NVARCHAR(15) DEFAULT  NULL,
    [DOC_ID2] NVARCHAR(15) DEFAULT  NULL,
    [DOC_ID3] int DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [EMPLOYEE_ID] NVARCHAR(20) DEFAULT  NULL,
    [ACTION] NVARCHAR(15) DEFAULT  NULL,
    [EMAIL_ADDR] NVARCHAR(2000) DEFAULT  NULL
)
