CREATE TABLE [dbo].[SEMAPHORE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [EVENT_NO] int DEFAULT ((0)) NOT NULL
)
