CREATE TABLE [dbo].[PART_PO_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PART_PO_BINARY] ADD CONSTRAINT [PK_PART_PO_BINARY] PRIMARY KEY ([PART_ID], [TYPE]);
