CREATE TABLE [dbo].[GROUP_USER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [GROUP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [IS_LEADER] NCHAR(1) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_SIGNOFF] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[GROUP_USER] ADD CONSTRAINT [PK_GROUP_USER] PRIMARY KEY ([GROUP_ID], [USER_ID]);
