CREATE TABLE [dbo].[ECN_DISPOSITION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[ECN_DISPOSITION] ADD CONSTRAINT [PK_ECN_DISPOSITION] PRIMARY KEY ([CODE]);
