CREATE TABLE [dbo].[WH_SHIP_ADVICE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [BOL_ID] NVARCHAR(20) DEFAULT  NULL,
    [CARRIER_REF] NVARCHAR(50) DEFAULT  NULL,
    [TRANS_METHOD_CODE] NVARCHAR(20) DEFAULT  NULL,
    [SHIPMENT_ID] NVARCHAR(20) DEFAULT  NULL,
    [WSA_ON_HOLD] NCHAR(1) DEFAULT  NULL,
    [WSA_TRANSMITTED] NCHAR(1) DEFAULT  NULL,
    [WSA_TRANSMITTED_BY] NVARCHAR(8) DEFAULT  NULL,
    [WSA_TRANSMIT_DATE] datetime DEFAULT  NULL,
    [SHIP_DATE_CHG_RSN] NVARCHAR(2) DEFAULT  NULL,
    [CARRIER_RT_CHG_RSN] NVARCHAR(2) DEFAULT  NULL,
    [USER_1] NVARCHAR(80) DEFAULT  NULL,
    [USER_2] NVARCHAR(80) DEFAULT  NULL,
    [USER_3] NVARCHAR(80) DEFAULT  NULL,
    [USER_4] NVARCHAR(80) DEFAULT  NULL,
    [USER_5] NVARCHAR(80) DEFAULT  NULL,
    [USER_6] NVARCHAR(80) DEFAULT  NULL,
    [USER_7] NVARCHAR(80) DEFAULT  NULL,
    [USER_8] NVARCHAR(80) DEFAULT  NULL,
    [USER_9] NVARCHAR(80) DEFAULT  NULL,
    [USER_10] NVARCHAR(80) DEFAULT  NULL,
    [UDF_LAYOUT_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[WH_SHIP_ADVICE] ADD CONSTRAINT [PK_WH_SHIP_ADVICE] PRIMARY KEY ([ID]);
