CREATE TABLE [dbo].[TOOLBAR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BITMAP] NVARCHAR(250) DEFAULT  NULL,
    [POSITION] int DEFAULT  NULL,
    [TOOLTIP] NVARCHAR(40) DEFAULT  NULL,
    [EXECUTE_COMMAND] NVARCHAR(250) DEFAULT  NULL,
    [USE_KEY_IN_CMD_LINE] NCHAR(1) DEFAULT  NULL,
    [ADD_ENTRY_TO_TOOLBAR] NCHAR(1) DEFAULT  NULL,
    [TOOLBAR_TYPE] NVARCHAR(10) DEFAULT  NULL
)

ALTER TABLE [dbo].[TOOLBAR] ADD CONSTRAINT [PK_TOOLBAR] PRIMARY KEY ([USER_ID], [PROGRAM_ID], [ID]);
