CREATE TABLE [dbo].[PURC_REQ_CURR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PURC_REQ_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[PURC_REQ_CURR] ADD CONSTRAINT [PK_PURC_REQ_CURR] PRIMARY KEY ([PURC_REQ_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[PURC_REQ_CURR] ADD CONSTRAINT [FK_PURC_REQ_CURR_00] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[PURC_REQ_CURR] ADD CONSTRAINT [FK_PURC_REQ_CURR_01] FOREIGN KEY ([PURC_REQ_ID]) REFERENCES [dbo].[PURC_REQUISITION]([ID]);
