CREATE TABLE [dbo].[UNP_MNT_CALLS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CALL_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [EQUIP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [STATUS] NVARCHAR(3) DEFAULT  NOT NULL,
    [FAULT_TYPE] NVARCHAR(15) DEFAULT  NOT NULL,
    [FAULT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [REMEDY_TYPE] NVARCHAR(15) DEFAULT  NULL,
    [REMEDY_CODE] NVARCHAR(15) DEFAULT  NULL,
    [DATE_OPENED] datetime DEFAULT  NULL,
    [DATE_CLOSED] datetime DEFAULT  NULL,
    [RESOURCE_SELECTED] NVARCHAR(15) DEFAULT  NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_TYPE] NVARCHAR(1) DEFAULT  NULL,
    [STD_REPAIR_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [STD_REPAIR_LOT_ID] NVARCHAR(3) DEFAULT  NULL,
    [URGENCY] NVARCHAR(15) DEFAULT  NULL,
    [ESCALATION] NVARCHAR(15) DEFAULT  NULL,
    [TASK_TIME] int DEFAULT  NULL,
    [TRAVEL_TIME] int DEFAULT  NULL,
    [REQUESTED_DATE] datetime DEFAULT  NULL,
    [CONFIRMED_DATE] datetime DEFAULT  NULL,
    [CONTACT_ID] NVARCHAR(25) DEFAULT  NULL,
    [CONTACT_FAX] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_FIRST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_HONORIFIC] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_INITIAL] NVARCHAR(2) DEFAULT  NULL,
    [CONTACT_LAST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_PHONE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_POSITION] NVARCHAR(50) DEFAULT  NULL,
    [CONTACT_SALUTATION] NVARCHAR(60) DEFAULT  NULL,
    [CONTACT_MOBILE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_EMAIL] NVARCHAR(100) DEFAULT  NULL,
    [SHIP_TO_ADDR_NO] int DEFAULT  NULL,
    [USER_1] NVARCHAR(80) DEFAULT  NULL,
    [USER_2] NVARCHAR(80) DEFAULT  NULL,
    [USER_3] NVARCHAR(80) DEFAULT  NULL,
    [USER_4] NVARCHAR(80) DEFAULT  NULL,
    [USER_5] NVARCHAR(80) DEFAULT  NULL,
    [USER_6] NVARCHAR(80) DEFAULT  NULL,
    [USER_7] NVARCHAR(80) DEFAULT  NULL,
    [USER_8] NVARCHAR(80) DEFAULT  NULL,
    [USER_9] NVARCHAR(80) DEFAULT  NULL,
    [USER_10] NVARCHAR(80) DEFAULT  NULL,
    [UDF_LAYOUT_ID] NVARCHAR(15) DEFAULT  NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [CUST_ORDER_LINE_NO] smallint DEFAULT  NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [INVOICE_FLAG] NVARCHAR(1) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CONTACT_PHONE_EXT] NVARCHAR(10) DEFAULT  NULL
)

ALTER TABLE [dbo].[UNP_MNT_CALLS] ADD CONSTRAINT [PK_UNP_MNT_CALLS] PRIMARY KEY ([CALL_ID]);

ALTER TABLE [dbo].[UNP_MNT_CALLS] ADD CONSTRAINT [FK_UNP_MNT_CONT_ID] FOREIGN KEY ([CONTACT_ID]) REFERENCES [dbo].[CONTACT]([ID]);

ALTER TABLE [dbo].[UNP_MNT_CALLS] ADD CONSTRAINT [FKEY9521] FOREIGN KEY ([FAULT_CODE], [FAULT_TYPE]) REFERENCES [dbo].[UNP_MNT_FAULT_CODE]([ID], [TYPE_ID]);

ALTER TABLE [dbo].[UNP_MNT_CALLS] ADD CONSTRAINT [FKEY9522] FOREIGN KEY ([URGENCY]) REFERENCES [dbo].[UNP_MNT_URGENCY]([ID]);

ALTER TABLE [dbo].[UNP_MNT_CALLS] ADD CONSTRAINT [FKEY9523] FOREIGN KEY ([ESCALATION]) REFERENCES [dbo].[UNP_MNT_ESCALATION]([ID]);

ALTER TABLE [dbo].[UNP_MNT_CALLS] ADD CONSTRAINT [FKEY9524] FOREIGN KEY ([REMEDY_CODE], [REMEDY_TYPE]) REFERENCES [dbo].[UNP_MNT_REM_CODE]([ID], [TYPE_ID]);

ALTER TABLE [dbo].[UNP_MNT_CALLS] ADD CONSTRAINT [FKEY9525] FOREIGN KEY ([RESOURCE_SELECTED]) REFERENCES [dbo].[SHOP_RESOURCE]([ID]);

ALTER TABLE [dbo].[UNP_MNT_CALLS] ADD CONSTRAINT [FKEY9526] FOREIGN KEY ([EQUIP_ID]) REFERENCES [dbo].[EQUIPMENT]([EQUIP_ID]);

ALTER TABLE [dbo].[UNP_MNT_CALLS] ADD CONSTRAINT [FKEY9527] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);
