CREATE TABLE [dbo].[VMDI_DATA] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [LAYOUT_KEY] NCHAR(3) DEFAULT  NOT NULL,
    [LAYOUT_VERSION] NCHAR(4) DEFAULT  NOT NULL,
    [LAYOUT_DIRECTION] NCHAR(1) DEFAULT  NOT NULL,
    [SEGMENT_TYPE] NCHAR(3) DEFAULT  NOT NULL,
    [TABLE_NAME] NVARCHAR(18) DEFAULT  NOT NULL,
    [COLUMN_NAME] NVARCHAR(30) DEFAULT  NOT NULL,
    [TYPE] NVARCHAR(9) DEFAULT  NOT NULL,
    [LENGTH] smallint DEFAULT  NOT NULL,
    [SCALE] smallint DEFAULT  NOT NULL,
    [COLNO] smallint DEFAULT  NOT NULL,
    [DUPLICATE_CRITERIA] int DEFAULT  NULL
)

ALTER TABLE [dbo].[VMDI_DATA] ADD CONSTRAINT [PK_VMDI_DATA] PRIMARY KEY ([LAYOUT_KEY], [LAYOUT_VERSION], [LAYOUT_DIRECTION], [SEGMENT_TYPE], [TABLE_NAME], [COLUMN_NAME]);

ALTER TABLE [dbo].[VMDI_DATA] ADD CONSTRAINT [FKEY9104] FOREIGN KEY ([LAYOUT_KEY], [LAYOUT_VERSION], [LAYOUT_DIRECTION]) REFERENCES [dbo].[VMDI_LAYOUT]([KEY], [VERSION], [DIRECTION]);
