CREATE TABLE [dbo].[SERVICE_SHIPPING] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DISPATCH_ADDR_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [SERVICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SERVICE_PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [CONTAINER_PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [CONTAINER_UM] NVARCHAR(15) DEFAULT  NULL,
    [CONTAINER_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [STD_PCS_CONTAINER] DECIMAL(20,8) DEFAULT  NULL,
    [SKID_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [SKID_UM] NVARCHAR(15) DEFAULT  NULL,
    [SKID_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [STD_CONTAINER_SKID] DECIMAL(20,8) DEFAULT  NULL,
    [CONTAINER_TYPE] NVARCHAR(20) DEFAULT  NULL,
    [DEFAULT_CONTAINER] NCHAR(1) DEFAULT  NULL,
    [VEND_SERV_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [PACKAGE_TYPE] NVARCHAR(5) DEFAULT  NULL,
    [CREATE_INV_TRANS] NCHAR(1) DEFAULT  NULL,
    [SERV_PART_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [SERV_PART_WGHT_UM] NVARCHAR(15) DEFAULT  NULL,
    [DOCK_CODE] NVARCHAR(20) DEFAULT  NULL
)

ALTER TABLE [dbo].[SERVICE_SHIPPING] ADD CONSTRAINT [PK_SERVICE_SHIPPING] PRIMARY KEY ([VENDOR_ID], [DISPATCH_ADDR_ID], [SERVICE_ID], [SERVICE_PART_ID], [CONTAINER_PART_ID]);

ALTER TABLE [dbo].[SERVICE_SHIPPING] ADD CONSTRAINT [FK_SERVICE_SHIPPING_00] FOREIGN KEY ([SERVICE_PART_ID]) REFERENCES [dbo].[PART]([ID]);

ALTER TABLE [dbo].[SERVICE_SHIPPING] ADD CONSTRAINT [FK_SERVICE_SHIPPING_01] FOREIGN KEY ([SERVICE_ID]) REFERENCES [dbo].[SERVICE]([ID]);
