CREATE TABLE [dbo].[VEND_GROUP_RELATION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [GROUP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[VEND_GROUP_RELATION] ADD CONSTRAINT [PK_VEND_GROUP_RELATION] PRIMARY KEY ([GROUP_ID], [VENDOR_ID]);
