CREATE TABLE [dbo].[CUST_ORDER_CURR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[CUST_ORDER_CURR] ADD CONSTRAINT [PK_CUST_ORD_CURR] PRIMARY KEY ([CUST_ORDER_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[CUST_ORDER_CURR] ADD CONSTRAINT [FKEY9424] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[CUST_ORDER_CURR] ADD CONSTRAINT [FKEY9425] FOREIGN KEY ([CUST_ORDER_ID]) REFERENCES [dbo].[CUSTOMER_ORDER]([ID]);
