CREATE TABLE [dbo].[PURC_LINE_DEL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PURC_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PURC_ORDER_LINE_NO] smallint DEFAULT  NOT NULL,
    [DEL_SCHED_LINE_NO] smallint DEFAULT  NOT NULL,
    [DESIRED_RECV_DATE] datetime DEFAULT  NULL,
    [ACTUAL_RECV_DATE] datetime DEFAULT  NULL,
    [USER_ORDER_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [ORDER_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [RECEIVED_QTY] DECIMAL(20,8) DEFAULT ((0)) NULL,
    [SHIPTO_ID] NVARCHAR(20) DEFAULT  NULL,
    [RELEASE_NUMBER] NVARCHAR(30) DEFAULT  NULL,
    [USER_1] NVARCHAR(30) DEFAULT  NULL,
    [USER_2] NVARCHAR(30) DEFAULT  NULL,
    [USER_RECEIVED_QTY] DECIMAL(20,8) DEFAULT ((0)) NULL,
    [PIECE_COUNT] int DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [WIP_VAS_REQUIRED] NCHAR(1) DEFAULT  NULL,
    [ALLOCATED_QTY] DECIMAL(20,8) DEFAULT ((0)) NULL,
    [FULFILLED_QTY] DECIMAL(20,8) DEFAULT ((0)) NULL,
    [DISPATCH_ADDR_ID] NVARCHAR(20) DEFAULT  NULL,
    [SHIPFROM_ID] NVARCHAR(20) DEFAULT  NULL,
    [DISPATCHED] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[PURC_LINE_DEL] ADD CONSTRAINT [PK_PURC_LINE_DEL] PRIMARY KEY ([PURC_ORDER_ID], [PURC_ORDER_LINE_NO], [DEL_SCHED_LINE_NO]);

ALTER TABLE [dbo].[PURC_LINE_DEL] ADD CONSTRAINT [FKEY0168] FOREIGN KEY ([PURC_ORDER_ID], [PURC_ORDER_LINE_NO]) REFERENCES [dbo].[PURC_ORDER_LINE]([PURC_ORDER_ID], [LINE_NO]);
