CREATE TABLE [dbo].[INV_TRANS_DIST_TRC] (
    [IN_TRANS_ID] int DEFAULT  NOT NULL,
    [OUT_TRANS_ID] int DEFAULT  NOT NULL,
    [TRACE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DIST_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [ACT_MATERIAL_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [ACT_LABOR_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [ACT_BURDEN_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [ACT_SERVICE_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[INV_TRANS_DIST_TRC] ADD CONSTRAINT [PK_INV_TRANS_DIST_TRC] PRIMARY KEY ([IN_TRANS_ID], [OUT_TRANS_ID], [TRACE_ID]);

ALTER TABLE [dbo].[INV_TRANS_DIST_TRC] ADD CONSTRAINT [FKEY_ITDT_IN] FOREIGN KEY ([IN_TRANS_ID]) REFERENCES [dbo].[INVENTORY_TRANS]([TRANSACTION_ID]);

ALTER TABLE [dbo].[INV_TRANS_DIST_TRC] ADD CONSTRAINT [FKEY_ITDT_OUT] FOREIGN KEY ([OUT_TRANS_ID]) REFERENCES [dbo].[INVENTORY_TRANS]([TRANSACTION_ID]);
