CREATE TABLE [dbo].[MENU_NAME] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [SEQ_NO] int DEFAULT  NOT NULL,
    [ID] NVARCHAR(40) DEFAULT  NOT NULL,
    [MENU_TEXT] NVARCHAR(80) DEFAULT  NULL,
    [BKGD_COLOR] NVARCHAR(20) DEFAULT  NULL,
    [TEXT_COLOR] NVARCHAR(20) DEFAULT  NULL
)

ALTER TABLE [dbo].[MENU_NAME] ADD CONSTRAINT [PK_MENU_NAME] PRIMARY KEY ([USER_ID], [SEQ_NO], [ID]);
