CREATE TABLE [dbo].[WIP_VAS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WIP_VAS_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [UNIT_PRICE] DECIMAL(22,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[WIP_VAS] ADD CONSTRAINT [PK_WIP_VAS] PRIMARY KEY ([WIP_VAS_ID]);
