CREATE TABLE [dbo].[MACRO] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(8) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(100) DEFAULT  NOT NULL,
    [MACRO] image DEFAULT  NULL
)

ALTER TABLE [dbo].[MACRO] ADD CONSTRAINT [PK_MACRO] PRIMARY KEY ([USER_ID], [PROGRAM_ID], [NAME]);
