CREATE TABLE [dbo].[REVALUE_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [REVALUE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] int DEFAULT  NOT NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [GROUP_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[REVALUE_LINE] ADD CONSTRAINT [PK_REVALUE_LINE] PRIMARY KEY ([REVALUE_ID], [LINE_NO]);

ALTER TABLE [dbo].[REVALUE_LINE] ADD CONSTRAINT [FKEY9473] FOREIGN KEY ([REVALUE_ID]) REFERENCES [dbo].[REVALUE]([ID]);

ALTER TABLE [dbo].[REVALUE_LINE] ADD CONSTRAINT [FKEY9474] FOREIGN KEY ([GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[REVALUE_LINE] ADD CONSTRAINT [FKEY9475] FOREIGN KEY ([GROUP_ID], [GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT_GROUP]([GROUP_ID], [ACCOUNT_ID]);
