CREATE TABLE [dbo].[MASTER_SCHEDULE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [MASTER_SCHEDULE_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WANT_DATE] datetime DEFAULT  NOT NULL,
    [ORDER_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [FIRMED] NCHAR(1) DEFAULT ('') NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[MASTER_SCHEDULE] ADD CONSTRAINT [FK_MSTRSCHD_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[MASTER_SCHEDULE] ADD CONSTRAINT [FKEY0096] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);
