CREATE TABLE [dbo].[EQUIP_RELEASE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EQUIP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RELEASE_NO] NVARCHAR(30) DEFAULT  NOT NULL,
    [RELEASE_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[EQUIP_RELEASE] ADD CONSTRAINT [PK_EQUIP_RELEASE] PRIMARY KEY ([EQUIP_ID], [RELEASE_NO]);
