CREATE TABLE [dbo].[PURC_HISTORY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PURC_REQ_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PURC_HISTORY] ADD CONSTRAINT [PK_PURC_HISTORY] PRIMARY KEY ([PURC_REQ_ID], [TYPE]);

ALTER TABLE [dbo].[PURC_HISTORY] ADD CONSTRAINT [FK_PURC_HISTORY_00] FOREIGN KEY ([PURC_REQ_ID]) REFERENCES [dbo].[PURC_REQUISITION]([ID]);
