CREATE TABLE [dbo].[SPREAD_PROFILE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [TYPE] NVARCHAR(1) DEFAULT  NOT NULL,
    [ACCT_PERIOD] DECIMAL(2,0) DEFAULT  NOT NULL,
    [PROFILE_AMOUNT] DECIMAL(23,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[SPREAD_PROFILE] ADD CONSTRAINT [PK_SPREAD_PROFILE] PRIMARY KEY ([ID], [ACCT_PERIOD]);
