CREATE TABLE [dbo].[LMC_APPS_SETTINGS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [APP_ID] VARCHAR(30) DEFAULT  NOT NULL,
    [SITE_ID] VARCHAR(15) DEFAULT  NOT NULL,
    [ENTITY] VARCHAR(15) DEFAULT  NOT NULL,
    [SETTING] VARCHAR(80) DEFAULT  NOT NULL,
    [VALUE] VARCHAR(500) DEFAULT  NULL
)

ALTER TABLE [dbo].[LMC_APPS_SETTINGS] ADD CONSTRAINT [PK_LMC_APPS_SETTINGS] PRIMARY KEY ([APP_ID], [SITE_ID], [ENTITY], [SETTING]);
