CREATE TABLE [dbo].[ENTITY_SETTINGS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ENTITY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(50) DEFAULT  NOT NULL,
    [SETTING_VALUE] NVARCHAR(250) DEFAULT  NULL
)

ALTER TABLE [dbo].[ENTITY_SETTINGS] ADD CONSTRAINT [PK_ENTITY_SETTINGS] PRIMARY KEY ([ENTITY_ID], [NAME]);
