CREATE TABLE [dbo].[PROJECT_DIST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROJECT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SOURCE_TYPE] NVARCHAR(20) DEFAULT  NOT NULL,
    [SOURCE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DIST_NO] smallint DEFAULT  NOT NULL,
    [ENTRY_NO] smallint DEFAULT  NOT NULL,
    [PROJECT_SUMMARY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [AMOUNT_TYPE] NCHAR(2) DEFAULT  NOT NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [POSTING_STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [SOURCE_LOT_ID] NVARCHAR(3) DEFAULT  NULL,
    [SOURCE_SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [SOURCE_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [BATCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [NATIVE] NCHAR(1) DEFAULT  NULL,
    [HOURS] DECIMAL(15,2) DEFAULT  NULL
)

ALTER TABLE [dbo].[PROJECT_DIST] ADD CONSTRAINT [PK_PROJECT_DIST] PRIMARY KEY ([PROJECT_ID], [SOURCE_TYPE], [SOURCE_ID], [DIST_NO], [ENTRY_NO], [PROJECT_SUMMARY_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[PROJECT_DIST] ADD CONSTRAINT [FK_PROJECT_DIST_01] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[PROJECT_DIST] ADD CONSTRAINT [FK_PROJECT_DIST_02] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[PROJECT_DIST] ADD CONSTRAINT [FK_PROJECT_DIST_03] FOREIGN KEY ([GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);
