CREATE TABLE [dbo].[PART_LOCATION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LOCATION_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [HOLD_REASON_ID] NVARCHAR(15) DEFAULT  NULL,
    [QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [LOCKED] NCHAR(1) DEFAULT ('N') NOT NULL,
    [TRANSIT] NCHAR(1) DEFAULT ('N') NOT NULL,
    [LAST_COUNT_DATE] datetime DEFAULT  NULL,
    [PURGE_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [COMMITTED_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [DEF_BACKFLUSH_LOC] NCHAR(1) DEFAULT ('N') NOT NULL,
    [AUTO_ISSUE_LOC] NCHAR(1) DEFAULT ('N') NOT NULL,
    [DEF_INSPECT_LOC] NCHAR(1) DEFAULT ('N') NOT NULL,
    [DC_CLASS_ID] NCHAR(1) DEFAULT  NULL,
    [ORDER_POINT] DECIMAL(20,8) DEFAULT  NULL,
    [ORDER_UP_TO_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [FROM_HOLD_REASON_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[PART_LOCATION] ADD CONSTRAINT [PK_PART_LOCATION] PRIMARY KEY ([PART_ID], [WAREHOUSE_ID], [LOCATION_ID]);

ALTER TABLE [dbo].[PART_LOCATION] ADD CONSTRAINT [FKEY0092] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);

ALTER TABLE [dbo].[PART_LOCATION] ADD CONSTRAINT [FKEY0119] FOREIGN KEY ([WAREHOUSE_ID], [LOCATION_ID]) REFERENCES [dbo].[LOCATION]([WAREHOUSE_ID], [ID]);

ALTER TABLE [dbo].[PART_LOCATION] ADD CONSTRAINT [FKEY0265] FOREIGN KEY ([HOLD_REASON_ID]) REFERENCES [dbo].[HOLD_REASON]([ID]);
