CREATE TABLE [dbo].[SHIPTO_PRICE_GROUP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SHIPTO_PRICE_GROUP] ADD CONSTRAINT [PK_SHIPTO_PRICE_GROUP] PRIMARY KEY ([CODE]);
