CREATE TABLE [dbo].[CASH_PLAN_AMOUNT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CASH_PLAN_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CASH_PLAN_LINE_NO] smallint DEFAULT  NOT NULL,
    [YEAR] DECIMAL(4,0) DEFAULT  NOT NULL,
    [PERIOD] DECIMAL(2,0) DEFAULT  NOT NULL,
    [AMOUNT_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[CASH_PLAN_AMOUNT] ADD CONSTRAINT [PK_CASH_PLAN_AMOUNT] PRIMARY KEY ([CASH_PLAN_ID], [CASH_PLAN_LINE_NO], [YEAR], [PERIOD], [AMOUNT_TYPE]);

ALTER TABLE [dbo].[CASH_PLAN_AMOUNT] ADD CONSTRAINT [FKEY9551] FOREIGN KEY ([CASH_PLAN_ID], [CASH_PLAN_LINE_NO]) REFERENCES [dbo].[CASH_PLAN_LINE]([CASH_PLAN_ID], [LINE_NO]);
