CREATE TABLE [dbo].[CUST_ORD_TYPE_SYNC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EVENT_ID] int DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [CUST_ORDER_TYPE] NVARCHAR(20) DEFAULT  NOT NULL,
    [EXCEPTION] NCHAR(1) DEFAULT  NOT NULL,
    [SUBSCRIPTIONS] int DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[CUST_ORD_TYPE_SYNC] ADD CONSTRAINT [PK_CUST_ORD_TYPE_SYNC] PRIMARY KEY ([EVENT_ID]);
