CREATE TABLE [dbo].[BANK_ADJ_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BANK_ACCOUNT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ADJUSTMENT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [REFERENCE] NVARCHAR(80) DEFAULT  NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [PRODUCT_CODE] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[BANK_ADJ_LINE] ADD CONSTRAINT [PK_BANK_ADJ_LINE] PRIMARY KEY ([BANK_ACCOUNT_ID], [ADJUSTMENT_ID], [LINE_NO]);
