CREATE TABLE [dbo].[REVALUE_CURR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [REVALUE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [AVG_SELL_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [AVG_BUY_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[REVALUE_CURR] ADD CONSTRAINT [PK_REVALUE_CURR] PRIMARY KEY ([REVALUE_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[REVALUE_CURR] ADD CONSTRAINT [FKEY9480] FOREIGN KEY ([REVALUE_ID]) REFERENCES [dbo].[REVALUE]([ID]);

ALTER TABLE [dbo].[REVALUE_CURR] ADD CONSTRAINT [FKEY9481] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
