CREATE TABLE [dbo].[USER_SITE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [VIEWABLE_SITES] NCHAR(1) DEFAULT  NULL,
    [DEFAULT_SITE] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[USER_SITE] ADD CONSTRAINT [PK_USER_SITE] PRIMARY KEY ([SITE_ID], [USER_ID]);

ALTER TABLE [dbo].[USER_SITE] ADD CONSTRAINT [FK_USER_SITE_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
