CREATE TABLE [dbo].[GJ_LINE_CURR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [GJ_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[GJ_LINE_CURR] ADD CONSTRAINT [PK_GJ_CURR_LINE] PRIMARY KEY ([GJ_ID], [LINE_NO], [CURRENCY_ID]);

ALTER TABLE [dbo].[GJ_LINE_CURR] ADD CONSTRAINT [FKEY9440] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[GJ_LINE_CURR] ADD CONSTRAINT [FKEY9441] FOREIGN KEY ([GJ_ID], [LINE_NO]) REFERENCES [dbo].[GJ_LINE]([GJ_ID], [LINE_NO]);
