CREATE TABLE [dbo].[UNP_MNT_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CALL_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[UNP_MNT_BINARY] ADD CONSTRAINT [PK_UNP_MNT_BINARY] PRIMARY KEY ([CALL_ID], [TYPE]);
