CREATE TABLE [dbo].[CYCLE_COUNT_PART] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [COUNT_FREQ] smallint DEFAULT  NULL,
    [LAST_COUNT_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[CYCLE_COUNT_PART] ADD CONSTRAINT [PK_CYCLE_COUNT_PART] PRIMARY KEY ([PART_ID], [WAREHOUSE_ID]);

ALTER TABLE [dbo].[CYCLE_COUNT_PART] ADD CONSTRAINT [FKEY0111] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);

ALTER TABLE [dbo].[CYCLE_COUNT_PART] ADD CONSTRAINT [FKEY0291] FOREIGN KEY ([WAREHOUSE_ID]) REFERENCES [dbo].[WAREHOUSE]([ID]);
