CREATE TABLE [dbo].[USER_PGM_AUTHORITY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(8) DEFAULT  NOT NULL,
    [PROGRAM_COMPONENT] NVARCHAR(8) DEFAULT  NOT NULL,
    [PERMISSION] NCHAR(1) DEFAULT ('') NOT NULL,
    [PROFILE_STRING] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[USER_PGM_AUTHORITY] ADD CONSTRAINT [PK_USER_PGM_AUTHORITY] PRIMARY KEY ([USER_ID], [PROGRAM_ID], [PROGRAM_COMPONENT]);
