CREATE TABLE [dbo].[APP_CONFIG] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] int DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(30) DEFAULT  NULL,
    [CAPTION] NVARCHAR(100) DEFAULT  NOT NULL,
    [KEY_1] NVARCHAR(30) DEFAULT  NULL,
    [KEY_2] NVARCHAR(30) DEFAULT  NULL,
    [LOCKED] NCHAR(1) DEFAULT ('N') NOT NULL,
    [SHARED] NCHAR(1) DEFAULT ('N') NOT NULL,
    [CONFIG] image DEFAULT  NULL
)

ALTER TABLE [dbo].[APP_CONFIG] ADD CONSTRAINT [PK_APP_CONFIG] PRIMARY KEY ([ID]);
