CREATE TABLE [dbo].[RCR_PAYABLE_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RCR_PAYABLE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [REFERENCE] NVARCHAR(40) DEFAULT  NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [VAT_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [VAT_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [VAT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [FIXED_CHARGE] DECIMAL(23,8) DEFAULT  NULL,
    [DISC_ALLOWED] NCHAR(1) DEFAULT  NOT NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [VAT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [VAT_RCV_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [VAT_RCV_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [WITHHOLD_TYPE] NCHAR(1) DEFAULT  NULL,
    [VAT_RCV_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [HTS_CODE] NVARCHAR(20) DEFAULT  NULL,
    [ORIG_COUNTRY_ID] NVARCHAR(50) DEFAULT  NULL,
    [DUTY_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [DUTY_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [DUTY_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [vat_category] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [PRODUCT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [VAT_IE_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [VAT_IE_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [VAT_IE_DR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [VAT_IE_CR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[RCR_PAYABLE_LINE] ADD CONSTRAINT [PK_RCR_PAYABLE_LINE] PRIMARY KEY ([RCR_PAYABLE_ID], [LINE_NO]);

ALTER TABLE [dbo].[RCR_PAYABLE_LINE] ADD CONSTRAINT [FKEY0230] FOREIGN KEY ([RCR_PAYABLE_ID]) REFERENCES [dbo].[RCR_PAYABLE]([ID]);

ALTER TABLE [dbo].[RCR_PAYABLE_LINE] ADD CONSTRAINT [FKEY0280] FOREIGN KEY ([GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[RCR_PAYABLE_LINE] ADD CONSTRAINT [FKEY9582] FOREIGN KEY ([vat_category]) REFERENCES [dbo].[VAT_CATEGORY]([ID]);
