CREATE TABLE [dbo].[REVENUE_DIST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] int DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [PROJECT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ENTRY_NO] smallint DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [AMOUNT_TYPE] NCHAR(2) DEFAULT  NOT NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [POSTING_STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [BATCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [TRANSACTION_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [NATIVE] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[REVENUE_DIST] ADD CONSTRAINT [PK_REVENUE_DIST] PRIMARY KEY ([ID], [LINE_NO], [PROJECT_ID], [ENTRY_NO], [CURRENCY_ID]);

ALTER TABLE [dbo].[REVENUE_DIST] ADD CONSTRAINT [FK_REVDST_BATCH] FOREIGN KEY ([SITE_ID], [BATCH_ID]) REFERENCES [dbo].[JOURNAL_BATCH]([SITE_ID], [ID]);

ALTER TABLE [dbo].[REVENUE_DIST] ADD CONSTRAINT [FK_REVENUE_DIST_00] FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[PROJECT_INFO]([ID]);

ALTER TABLE [dbo].[REVENUE_DIST] ADD CONSTRAINT [FK_REVENUE_DIST_01] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[REVENUE_DIST] ADD CONSTRAINT [FK_REVENUE_DIST_03] FOREIGN KEY ([GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);
