CREATE TABLE [dbo].[RECEIVER_LINE_DEL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RECEIVER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RECEIVER_LINE_NO] smallint DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [PURC_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [PURC_ORDER_LINE_NO] smallint DEFAULT  NULL,
    [PURC_DEL_LINE_NO] smallint DEFAULT  NULL,
    [USER_RECEIVED_QTY] DECIMAL(20,8) DEFAULT ((0)) NULL,
    [RECEIVED_QTY] DECIMAL(20,8) DEFAULT ((0)) NULL,
    [PIECE_COUNT] int DEFAULT  NULL
)

ALTER TABLE [dbo].[RECEIVER_LINE_DEL] ADD CONSTRAINT [PK_RECEIVER_LINE_DEL] PRIMARY KEY ([RECEIVER_ID], [RECEIVER_LINE_NO], [LINE_NO]);

ALTER TABLE [dbo].[RECEIVER_LINE_DEL] ADD CONSTRAINT [FKEY9374] FOREIGN KEY ([PURC_ORDER_ID], [PURC_ORDER_LINE_NO]) REFERENCES [dbo].[PURC_ORDER_LINE]([PURC_ORDER_ID], [LINE_NO]);
