CREATE TABLE [dbo].[WAREHOUSE_ADDRESS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ADDR_NO] int DEFAULT  NOT NULL,
    [SHIPTO_ID] NVARCHAR(20) DEFAULT  NULL,
    [NAME] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_1] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_2] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_3] NVARCHAR(50) DEFAULT  NULL,
    [CITY] NVARCHAR(30) DEFAULT  NULL,
    [STATE] NVARCHAR(10) DEFAULT  NULL,
    [ZIPCODE] NVARCHAR(10) DEFAULT  NULL,
    [COUNTRY] NVARCHAR(50) DEFAULT  NULL,
    [WAREHOUSE_ADDR_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [VAT_REGISTRATION] NVARCHAR(25) DEFAULT  NULL
)

ALTER TABLE [dbo].[WAREHOUSE_ADDRESS] ADD CONSTRAINT [PK_WAREHOUSE_ADDRESS] PRIMARY KEY ([WAREHOUSE_ID], [ADDR_NO]);

ALTER TABLE [dbo].[WAREHOUSE_ADDRESS] ADD CONSTRAINT [FKEY9620] FOREIGN KEY ([WAREHOUSE_ID]) REFERENCES [dbo].[WAREHOUSE]([ID]);
