CREATE TABLE [dbo].[VENDOR_REMIT_ADDR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ADDR_NO] int DEFAULT  NOT NULL,
    [NAME] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_1] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_2] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_3] NVARCHAR(50) DEFAULT  NULL,
    [CITY] NVARCHAR(30) DEFAULT  NULL,
    [STATE] NVARCHAR(10) DEFAULT  NULL,
    [ZIPCODE] NVARCHAR(10) DEFAULT  NULL,
    [COUNTRY] NVARCHAR(50) DEFAULT  NULL,
    [VENDOR_REMIT_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[VENDOR_REMIT_ADDR] ADD CONSTRAINT [PK_VENDOR_REMIT_ADDR] PRIMARY KEY ([VENDOR_ID], [ADDR_NO]);

ALTER TABLE [dbo].[VENDOR_REMIT_ADDR] ADD CONSTRAINT [FKEY9371] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);
