CREATE TABLE [dbo].[EMPLOYEE_SITE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [EMPLOYEE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DEFAULT_SITE] NCHAR(1) DEFAULT  NULL,
    [BASE_PAY_RATE] DECIMAL(22,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[EMPLOYEE_SITE] ADD CONSTRAINT [PK_EMPLOYEE_SITE] PRIMARY KEY ([SITE_ID], [EMPLOYEE_ID]);

ALTER TABLE [dbo].[EMPLOYEE_SITE] ADD CONSTRAINT [FK_EMP_SITE_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
