CREATE TABLE [dbo].[SCHEDULE_GROUP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL
)

ALTER TABLE [dbo].[SCHEDULE_GROUP] ADD CONSTRAINT [PK_SCHEDULE_GROUP] PRIMARY KEY ([ID]);
