CREATE TABLE [dbo].[RCR_GJ_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RCR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DEBIT_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [CREDIT_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [REFERENCE] NVARCHAR(80) DEFAULT  NULL,
    [COST_CATEGORY_ID] NVARCHAR(15) DEFAULT  NULL,
    [DEPARTMENT_ID] NVARCHAR(15) DEFAULT  NULL,
    [PROJECT_ID] NVARCHAR(15) DEFAULT  NULL,
    [WBS_CODE] NVARCHAR(30) DEFAULT  NULL,
    [PROJ_REF_SEQ_NO] smallint DEFAULT  NULL,
    [PROJ_REF_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [ACCOUNT_YEAR] DECIMAL(4,0) DEFAULT  NULL,
    [HOURS] DECIMAL(15,2) DEFAULT  NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [PRODUCT_CODE] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[RCR_GJ_LINE] ADD CONSTRAINT [PK_RCR_GJ_LINE] PRIMARY KEY ([RCR_ID], [LINE_NO]);
