CREATE TABLE [dbo].[V_TASK_CATEGORY] (
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL,
    [KEYWORD_ID] NVARCHAR(15) DEFAULT  NULL,
    [LAST_MODIFIED] datetime DEFAULT  NULL,
    [LAST_USER] NVARCHAR(20) DEFAULT  NULL,
    [NEWONCOMPLETE] smallint DEFAULT  NULL,
    [RECORDHISTORY] smallint DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT  NULL,
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[V_TASK_CATEGORY] ADD CONSTRAINT [X_V_TASK_CATEGORY_0] PRIMARY KEY ([ID]);
