CREATE TABLE [dbo].[T_NORMAL_DIST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [T] DECIMAL(3,1) DEFAULT  NOT NULL,
    [OUTSIDE_OF_LIM] DECIMAL(6,4) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[T_NORMAL_DIST] ADD CONSTRAINT [PK_T_NORMAL_DIST] PRIMARY KEY ([T]);
