CREATE TABLE [dbo].[DISTRIBUTION_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DISTRIBUTION_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] int DEFAULT  NOT NULL,
    [INTERVAL_PERCENT] DECIMAL(7,4) DEFAULT  NULL
)

ALTER TABLE [dbo].[DISTRIBUTION_LINE] ADD CONSTRAINT [PK_DISTRIBUTION_LINE] PRIMARY KEY ([DISTRIBUTION_ID], [LINE_NO]);

ALTER TABLE [dbo].[DISTRIBUTION_LINE] ADD CONSTRAINT [FK_DISTRIBUTION_LINE_00] FOREIGN KEY ([DISTRIBUTION_ID]) REFERENCES [dbo].[DISTRIBUTION]([ID]);
