CREATE TABLE [dbo].[TRACE_NUMBERING] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [NEXT_NUMBER] DECIMAL(15,0) DEFAULT  NULL,
    [ALPHA_PREFIX] NVARCHAR(4) DEFAULT  NULL,
    [ALPHA_SUFFIX] NVARCHAR(4) DEFAULT  NULL,
    [DECIMAL_PLACES] smallint DEFAULT  NULL,
    [LEADING_ZEROS] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[TRACE_NUMBERING] ADD CONSTRAINT [PK_TRACE_NUMBERING] PRIMARY KEY ([ID]);
