CREATE TABLE [dbo].[WORKFLOW_EVENT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[WORKFLOW_EVENT] ADD CONSTRAINT [PK_WORKFLOW_EVENT] PRIMARY KEY ([CREATE_DATE]);
