CREATE TABLE [dbo].[LMC_MRP_POAUTH] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USERID] VARCHAR(30) DEFAULT  NOT NULL,
    [LVL] int DEFAULT  NOT NULL,
    [SIGN_OFF] int DEFAULT  NOT NULL,
    [DEPT_ID] VARCHAR(15) DEFAULT  NULL,
    [EMAIL] int DEFAULT  NOT NULL,
    [SITE_ID] VARCHAR(15) DEFAULT  NOT NULL
)
