CREATE TABLE [dbo].[GL_INTERFACE_ACCT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [INTERFACE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [GL_GROUP_ID] NVARCHAR(15) DEFAULT  NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[GL_INTERFACE_ACCT] ADD CONSTRAINT [PK_GL_INTERFACE_ACCT] PRIMARY KEY ([SITE_ID], [INTERFACE_ID]);

ALTER TABLE [dbo].[GL_INTERFACE_ACCT] ADD CONSTRAINT [FKEY0000] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[GL_INTERFACE_ACCT] ADD CONSTRAINT [FKEY0029] FOREIGN KEY ([INTERFACE_ID]) REFERENCES [dbo].[GL_INTERFACE]([ID]);

ALTER TABLE [dbo].[GL_INTERFACE_ACCT] ADD CONSTRAINT [FKEY0193] FOREIGN KEY ([GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);
