CREATE TABLE [dbo].[SETUP_TYPE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[SETUP_TYPE] ADD CONSTRAINT [PK_SETUP_TYPE] PRIMARY KEY ([ID]);
