CREATE TABLE [dbo].[PROJECT_STATUS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PROJECT_STATUS] ADD CONSTRAINT [PK_PROJECT_STATUS] PRIMARY KEY ([CODE]);
