CREATE TABLE [dbo].[CASH_BOOK_SUMMARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BANK_ACCOUNT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ACCT_YEAR] DECIMAL(4,0) DEFAULT  NOT NULL,
    [ACCT_PERIOD] DECIMAL(2,0) DEFAULT  NOT NULL,
    [CLEARED_BALANCE] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [ACCT_BALANCE] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CASH_BOOK_SUMMARY] ADD CONSTRAINT [PK_CASH_BOOK_SUMMARY] PRIMARY KEY ([BANK_ACCOUNT_ID], [ACCT_YEAR], [ACCT_PERIOD], [SITE_ID]);

ALTER TABLE [dbo].[CASH_BOOK_SUMMARY] ADD CONSTRAINT [FK_CSH_BKSUM_2SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
