CREATE TABLE [dbo].[VMDI_CSH_HDR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PENDING_ID] int DEFAULT  NOT NULL,
    [PENDING_FLAG] NCHAR(1) DEFAULT  NOT NULL,
    [TRANSACTION_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CHECK_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [BANK_ID] NVARCHAR(10) DEFAULT  NULL,
    [ACCOUNT_NO] NVARCHAR(30) DEFAULT  NULL,
    [ROUTING_NO] NVARCHAR(35) DEFAULT  NULL,
    [CHECK_DATE] datetime DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NULL,
    [ISO_CURRENCY_CD] NVARCHAR(5) DEFAULT  NULL,
    [BANK_ACCOUNT_ID] NVARCHAR(10) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT  NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT  NULL,
    [DEPOSIT_ID] NVARCHAR(15) DEFAULT  NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[VMDI_CSH_HDR] ADD CONSTRAINT [PK_VMDI_CSH_HDR] PRIMARY KEY ([CUSTOMER_ID], [CHECK_ID]);
