CREATE TABLE [dbo].[QUOTE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NULL,
    [NAME] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_1] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_2] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_3] NVARCHAR(50) DEFAULT  NULL,
    [CITY] NVARCHAR(30) DEFAULT  NULL,
    [STATE] NVARCHAR(10) DEFAULT  NULL,
    [ZIPCODE] NVARCHAR(10) DEFAULT  NULL,
    [COUNTRY] NVARCHAR(50) DEFAULT  NULL,
    [QUOTE_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_ID] NVARCHAR(25) DEFAULT  NULL,
    [CONTACT_FIRST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_LAST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_INITIAL] NVARCHAR(2) DEFAULT  NULL,
    [CONTACT_POSITION] NVARCHAR(50) DEFAULT  NULL,
    [CONTACT_HONORIFIC] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_SALUTATION] NVARCHAR(60) DEFAULT  NULL,
    [CONTACT_PHONE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_FAX] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_EMAIL] NVARCHAR(100) DEFAULT  NULL,
    [SALESREP_ID] NVARCHAR(15) DEFAULT  NULL,
    [TERRITORY] NVARCHAR(15) DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [WON_LOSS_DATE] datetime DEFAULT  NULL,
    [WON_LOSS_REASON] NVARCHAR(80) DEFAULT  NULL,
    [QUOTE_DATE] datetime DEFAULT  NOT NULL,
    [EXPIRATION_DATE] datetime DEFAULT  NULL,
    [FOLLOWUP_DATE] datetime DEFAULT  NULL,
    [EXPECTED_WIN_DATE] datetime DEFAULT  NULL,
    [WIN_PROBABILITY] DECIMAL(3,2) DEFAULT  NULL,
    [SHIP_VIA] NVARCHAR(40) DEFAULT  NULL,
    [FREE_ON_BOARD] NVARCHAR(25) DEFAULT  NULL,
    [TERMS_NET_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [TERMS_NET_DAYS] smallint DEFAULT  NULL,
    [TERMS_NET_DATE] datetime DEFAULT  NULL,
    [TERMS_DISC_DAYS] smallint DEFAULT  NULL,
    [TERMS_DISC_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [TERMS_DISC_DATE] datetime DEFAULT  NULL,
    [TERMS_DISC_PERCENT] DECIMAL(5,3) DEFAULT  NULL,
    [TERMS_DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [FREIGHT_TERMS] NCHAR(1) DEFAULT ('') NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [QUOTED_LEADTIME] smallint DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DISCOUNT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [PRINTED_DATE] datetime DEFAULT  NULL,
    [USER_1] NVARCHAR(80) DEFAULT  NULL,
    [USER_2] NVARCHAR(80) DEFAULT  NULL,
    [USER_3] NVARCHAR(80) DEFAULT  NULL,
    [USER_4] NVARCHAR(80) DEFAULT  NULL,
    [USER_5] NVARCHAR(80) DEFAULT  NULL,
    [USER_6] NVARCHAR(80) DEFAULT  NULL,
    [USER_7] NVARCHAR(80) DEFAULT  NULL,
    [USER_8] NVARCHAR(80) DEFAULT  NULL,
    [USER_9] NVARCHAR(80) DEFAULT  NULL,
    [USER_10] NVARCHAR(80) DEFAULT  NULL,
    [UDF_LAYOUT_ID] NVARCHAR(15) DEFAULT  NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [PROJECT_ID] NVARCHAR(15) DEFAULT  NULL,
    [TERMS_ID] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_PHONE_EXT] NVARCHAR(10) DEFAULT  NULL,
    [TERMS_DISC_BASIS] NVARCHAR(32) DEFAULT  NULL
)

ALTER TABLE [dbo].[QUOTE] ADD CONSTRAINT [PK_QUOTE] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[QUOTE] ADD CONSTRAINT [FK_QUOTE_CONT_ID] FOREIGN KEY ([CONTACT_ID]) REFERENCES [dbo].[CONTACT]([ID]);

ALTER TABLE [dbo].[QUOTE] ADD CONSTRAINT [FKEY0013] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[QUOTE] ADD CONSTRAINT [FKEY0059] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[QUOTE] ADD CONSTRAINT [FKEY0066] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);

ALTER TABLE [dbo].[QUOTE] ADD CONSTRAINT [FKEY0275] FOREIGN KEY ([DISCOUNT_CODE]) REFERENCES [dbo].[CUSTOMER_DISCOUNT]([DISCOUNT_CODE]);

ALTER TABLE [dbo].[QUOTE] ADD CONSTRAINT [FKEY9625] FOREIGN KEY ([TERMS_ID]) REFERENCES [dbo].[TERMS]([ID]);
