CREATE TABLE [dbo].[VR_DATA_SOURCE_TABLE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DATA_SOURCE_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [ALIAS] NVARCHAR(30) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(80) DEFAULT  NOT NULL,
    [TYPE] int DEFAULT  NOT NULL,
    [SEQ_NO] int DEFAULT  NOT NULL,
    [JOIN_TYPE] int DEFAULT ((0)) NOT NULL,
    [JOIN_TEXT] NVARCHAR(2000) DEFAULT  NULL
)

ALTER TABLE [dbo].[VR_DATA_SOURCE_TABLE] ADD CONSTRAINT [PK_VR_DATA_SOURCE_TABLE] PRIMARY KEY ([DATA_SOURCE_ID], [ALIAS]);

ALTER TABLE [dbo].[VR_DATA_SOURCE_TABLE] ADD CONSTRAINT [FK_DATA_SRC_TBL_TO_DATA_SRC] FOREIGN KEY ([DATA_SOURCE_ID]) REFERENCES [dbo].[VR_DATA_SOURCE]([ID]);
