CREATE TABLE [dbo].[HISTORY_DATA] (
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [TBL_NAME] NVARCHAR(50) DEFAULT  NOT NULL,
    [COL_NAME] NVARCHAR(50) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT  NOT NULL,
    [PRIMARY_KEY] NVARCHAR(254) DEFAULT  NULL,
    [ACTION] NVARCHAR(15) DEFAULT  NULL,
    [OLD_VALUE] NVARCHAR(255) DEFAULT  NULL,
    [NEW_VALUE] NVARCHAR(255) DEFAULT  NULL
)
