CREATE TABLE [dbo].[LOGINS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [MACHINE_ID] NVARCHAR(40) DEFAULT  NULL,
    [PROGRAM_ID] NVARCHAR(30) DEFAULT  NULL,
    [LOGIN_TIME] datetime DEFAULT (getdate()) NOT NULL,
    [LAST_ACTIVITY] datetime DEFAULT (getdate()) NOT NULL,
    [LICENSE_NUMBER] NVARCHAR(50) DEFAULT  NULL,
    [CHECKSUM] NVARCHAR(80) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NULL
)
