CREATE TABLE [dbo].[STATE_PROVINCE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(10) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(40) DEFAULT  NULL
)

ALTER TABLE [dbo].[STATE_PROVINCE] ADD CONSTRAINT [PK_STATE_PROVINCE] PRIMARY KEY ([CODE]);
