CREATE TABLE [dbo].[GJ] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [GJ_DATE] datetime DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [TOTAL_DR_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [TOTAL_CR_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NULL,
    [POST_ALL_TRACKING] NCHAR(1) DEFAULT ('') NOT NULL,
    [POST_AS_NATIVE] NCHAR(1) DEFAULT ('') NOT NULL,
    [USER_EXCH_RATE] NCHAR(1) DEFAULT ('') NOT NULL,
    [ALLOCATION_ID] NVARCHAR(5) DEFAULT  NULL,
    [RECURRING_ID] NVARCHAR(15) DEFAULT  NULL,
    [ACT_RATE_ID] NVARCHAR(15) DEFAULT  NULL,
    [ACT_PERIOD_ID] NVARCHAR(15) DEFAULT  NULL,
    [RETRO_RATE_ID] NVARCHAR(15) DEFAULT  NULL,
    [RETRO_PERIOD_ID] NVARCHAR(15) DEFAULT  NULL,
    [RETRO_RATE_CODE] NCHAR(1) DEFAULT  NULL,
    [POSTING_CANDIDATE] NCHAR(1) DEFAULT ('Y') NOT NULL
)

ALTER TABLE [dbo].[GJ] ADD CONSTRAINT [PK_GJ] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[GJ] ADD CONSTRAINT [FKEY9436] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
