CREATE TABLE [dbo].[VENDOR_ENTITY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ENTITY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TOTAL_OPEN_ORDERS] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [TOTAL_OPEN_PAYB] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [OPEN_ORDER_COUNT] int DEFAULT ((0)) NOT NULL,
    [OPEN_PAYB_COUNT] int DEFAULT ((0)) NOT NULL,
    [CREATED_BY] NVARCHAR(20) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [MODIFIED_BY] NVARCHAR(20) DEFAULT  NULL,
    [MODIFY_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[VENDOR_ENTITY] ADD CONSTRAINT [PK_VENDOR_ENTITY] PRIMARY KEY ([ENTITY_ID], [VENDOR_ID]);

ALTER TABLE [dbo].[VENDOR_ENTITY] ADD CONSTRAINT [FK_VENDOR_ENTITY_TO_CUSTOMER] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);

ALTER TABLE [dbo].[VENDOR_ENTITY] ADD CONSTRAINT [FK_VENDOR_ENTITY_TO_ENTITY] FOREIGN KEY ([ENTITY_ID]) REFERENCES [dbo].[ACCOUNTING_ENTITY]([ID]);
