CREATE TABLE [dbo].[CONSIGN_RCVR_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RECEIVER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [PURC_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [PURC_ORDER_LINE_NO] smallint DEFAULT  NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [USER_RECEIVED_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [RECEIVED_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [LOCATION_ID] NVARCHAR(15) DEFAULT  NULL,
    [TRANSACTION_ID] int DEFAULT  NULL,
    [PIECE_COUNT] DECIMAL(20,8) DEFAULT  NULL,
    [LENGTH] DECIMAL(14,4) DEFAULT  NULL,
    [WIDTH] DECIMAL(14,4) DEFAULT  NULL,
    [HEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [DIMENSIONS_UM] NVARCHAR(15) DEFAULT  NULL,
    [REJECTED_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [HTS_CODE] NVARCHAR(20) DEFAULT  NULL,
    [ORIG_COUNTRY_ID] NVARCHAR(50) DEFAULT  NULL,
    [GROSS_WEIGHT] DECIMAL(15,4) DEFAULT  NULL
)

ALTER TABLE [dbo].[CONSIGN_RCVR_LINE] ADD CONSTRAINT [PK_CONSIGN_RCVR_LINE] PRIMARY KEY ([RECEIVER_ID], [LINE_NO]);

ALTER TABLE [dbo].[CONSIGN_RCVR_LINE] ADD CONSTRAINT [FKEY9615] FOREIGN KEY ([RECEIVER_ID]) REFERENCES [dbo].[CONSIGN_RECEIVER]([ID]);

ALTER TABLE [dbo].[CONSIGN_RCVR_LINE] ADD CONSTRAINT [FKEY9616] FOREIGN KEY ([PURC_ORDER_ID], [PURC_ORDER_LINE_NO]) REFERENCES [dbo].[PURC_ORDER_LINE]([PURC_ORDER_ID], [LINE_NO]);
