CREATE TABLE [dbo].[PROCESS_TYPE_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PROCESS_TYPE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PROCESS] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(120) DEFAULT  NULL,
    [SEQUENCE_NO] smallint DEFAULT  NULL,
    [DOCUMENT_TYPE] NVARCHAR(20) DEFAULT  NULL,
    [STANDARD_DAYS] DECIMAL(14,2) DEFAULT ((0)) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[PROCESS_TYPE_LINE] ADD CONSTRAINT [PK_PROCESS_TYPE_LINE] PRIMARY KEY ([SITE_ID], [PROCESS_TYPE_ID], [PROCESS]);
