CREATE TABLE [dbo].[PROJ_INFO_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROJECT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PROJ_INFO_BINARY] ADD CONSTRAINT [PK_PROJ_INFO_BINARY] PRIMARY KEY ([PROJECT_ID], [TYPE]);
