CREATE TABLE [dbo].[BANK_STATEMENT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BANK_ACCOUNT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [STATEMENT_DATE] datetime DEFAULT  NOT NULL,
    [STARTING_BALANCE] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [ENDING_BALANCE] DECIMAL(23,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[BANK_STATEMENT] ADD CONSTRAINT [PK_BANK_STATEMENT] PRIMARY KEY ([BANK_ACCOUNT_ID], [STATEMENT_DATE]);
