CREATE TABLE [dbo].[SHIPTO_ADDRESS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ADDR_NO] int DEFAULT  NOT NULL,
    [NAME] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_1] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_2] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_3] NVARCHAR(50) DEFAULT  NULL,
    [CITY] NVARCHAR(30) DEFAULT  NULL,
    [STATE] NVARCHAR(10) DEFAULT  NULL,
    [ZIPCODE] NVARCHAR(10) DEFAULT  NULL,
    [COUNTRY] NVARCHAR(50) DEFAULT  NULL,
    [ARRIVAL_CODE] NVARCHAR(25) DEFAULT  NULL,
    [TRANS_CODE] NVARCHAR(25) DEFAULT  NULL,
    [COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [SHIPTO_ADDR_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [NATURE_OF_TRANS] int DEFAULT  NULL,
    [MODE_OF_TRANSPORT] int DEFAULT  NULL,
    [SIRET_NUMBER] DECIMAL(14,0) DEFAULT  NULL,
    [SHIPTO_ID] NVARCHAR(20) DEFAULT  NULL,
    [VAT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [VAT_OVERRIDE_SEQ] NVARCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[SHIPTO_ADDRESS] ADD CONSTRAINT [PK_SHIPTO_ADDRESS] PRIMARY KEY ([ADDR_NO]);

ALTER TABLE [dbo].[SHIPTO_ADDRESS] ADD CONSTRAINT [FK_SHIPTOADD_CNTRY] FOREIGN KEY ([COUNTRY_ID]) REFERENCES [dbo].[COUNTRY]([ID]);

ALTER TABLE [dbo].[SHIPTO_ADDRESS] ADD CONSTRAINT [FKEY9323] FOREIGN KEY ([ARRIVAL_CODE]) REFERENCES [dbo].[PORT_OF_ARRIVAL]([CODE]);

ALTER TABLE [dbo].[SHIPTO_ADDRESS] ADD CONSTRAINT [FKEY9324] FOREIGN KEY ([TRANS_CODE]) REFERENCES [dbo].[PORT_OF_TRANS]([CODE]);

ALTER TABLE [dbo].[SHIPTO_ADDRESS] ADD CONSTRAINT [FKEY9326] FOREIGN KEY ([NATURE_OF_TRANS]) REFERENCES [dbo].[NATURE_OF_TRANS]([CODE]);

ALTER TABLE [dbo].[SHIPTO_ADDRESS] ADD CONSTRAINT [FKEY9327] FOREIGN KEY ([MODE_OF_TRANSPORT]) REFERENCES [dbo].[MODE_OF_TRANSPORT]([CODE]);
