CREATE TABLE [dbo].[HISTORY_SCHEMA] (
    [TBL_NAME] NVARCHAR(50) DEFAULT  NOT NULL,
    [COL_NAME] NVARCHAR(50) DEFAULT  NOT NULL,
    [COL_TYPE] NVARCHAR(15) DEFAULT  NULL,
    [IS_PRIMARY] NCHAR(1) DEFAULT  NULL,
    [PK_ORDER] int DEFAULT  NULL
)

ALTER TABLE [dbo].[HISTORY_SCHEMA] ADD CONSTRAINT [PK_HISTORY_SCHEMA] PRIMARY KEY ([TBL_NAME], [COL_NAME]);
