CREATE TABLE [dbo].[VEND_CONT_EML_DOC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CONTACT_NO] smallint DEFAULT  NOT NULL,
    [DOCUMENT_TYPE] NVARCHAR(3) DEFAULT  NOT NULL,
    [CONTACT_ID] NVARCHAR(25) DEFAULT  NULL,
    [CONTACT_EMAIL] NVARCHAR(100) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[VEND_CONT_EML_DOC] ADD CONSTRAINT [FKEY9606] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);
