CREATE TABLE [dbo].[DBR_SETTINGS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CCR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RANK] int DEFAULT  NOT NULL,
    [STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [SHIPPING_BUFFER] int DEFAULT  NOT NULL,
    [ASSEMBLY_BUFFER] int DEFAULT  NOT NULL,
    [CCR_BUFFER] int DEFAULT  NOT NULL,
    [ROD] int DEFAULT  NOT NULL,
    [MTS_CCR_BUFFER] int DEFAULT  NOT NULL,
    [EMERGENCY_STOCKPCT] int DEFAULT  NULL,
    [EMERGENCY_ZONE] int DEFAULT  NULL,
    [SHIP_BUF_PCT_CHK] int DEFAULT  NULL,
    [BM_LAST_COLLECT] datetime DEFAULT  NULL,
    [BM_COLLECT_MODE] NCHAR(1) DEFAULT  NULL,
    [YELLOW_ZONE] int DEFAULT  NULL,
    [YELLOW_STOCKPCT] int DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[DBR_SETTINGS] ADD CONSTRAINT [PK_DBR_SETTINGS] PRIMARY KEY ([SITE_ID], [CCR_ID]);
