CREATE TABLE [dbo].[LMC_MRP_USER_GRID_SETTINGS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USERID] VARCHAR(20) DEFAULT  NOT NULL,
    [GRID] VARCHAR(20) DEFAULT  NOT NULL,
    [COL] VARCHAR(80) DEFAULT  NOT NULL,
    [VISIBLE] CHAR(1) DEFAULT  NOT NULL,
    [COL_INDEX] int DEFAULT  NOT NULL,
    [WIDTH] int DEFAULT  NOT NULL,
    [GRIDS_VERSION] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[LMC_MRP_USER_GRID_SETTINGS] ADD CONSTRAINT [PK_LMC_MRP_USER_GRID_SETTINGS] PRIMARY KEY ([USERID], [GRID], [COL]);
