CREATE TABLE [dbo].[VENDOR_PART] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [VENDOR_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [LONG_DESCRIPTION] image DEFAULT  NULL,
    [LEADTIME_BUFFER] smallint DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[VENDOR_PART] ADD CONSTRAINT [FK_VEND_PART_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[VENDOR_PART] ADD CONSTRAINT [FKEY0080] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);

ALTER TABLE [dbo].[VENDOR_PART] ADD CONSTRAINT [FKEY0102] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);
