CREATE TABLE [dbo].[VMDI_CSH_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PENDING_ID] int DEFAULT  NOT NULL,
    [PENDING_FLAG] NCHAR(1) DEFAULT  NOT NULL,
    [TRANSACTION_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CHECK_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [PACKLIST_ID] NVARCHAR(15) DEFAULT  NULL,
    [BOL_ID] NVARCHAR(20) DEFAULT  NULL,
    [ASN_ID] NVARCHAR(20) DEFAULT  NULL,
    [DISCOUNT_APPLIED] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [REFERENCE] NVARCHAR(40) DEFAULT  NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT  NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT  NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[VMDI_CSH_LINE] ADD CONSTRAINT [PK_VMDI_CSH_LINE] PRIMARY KEY ([CUSTOMER_ID], [CHECK_ID], [LINE_NO]);
