CREATE TABLE [dbo].[BID_RATE_GROUP_CATEGORY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BID_RATE_GROUP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BID_RATE_CATEGORY_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[BID_RATE_GROUP_CATEGORY] ADD CONSTRAINT [PK_BID_RATE_GROUP_CATEGORY] PRIMARY KEY ([BID_RATE_GROUP_ID], [BID_RATE_CATEGORY_ID]);
