CREATE TABLE [dbo].[ACCOUNT_BAL_DIM] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ACCT_YEAR] DECIMAL(4,0) DEFAULT  NOT NULL,
    [ACCT_PERIOD] DECIMAL(2,0) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT (' ') NOT NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT (' ') NOT NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT (' ') NOT NULL,
    [PRODUCT_CODE] NVARCHAR(15) DEFAULT (' ') NOT NULL,
    [DEBIT_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [CREDIT_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [FLAG] int DEFAULT ((0)) NOT NULL,
    [CURR_BALANCE] DECIMAL(23,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[ACCOUNT_BAL_DIM] ADD CONSTRAINT [PK_ACCT_BAL_DIM] PRIMARY KEY ([ACCOUNT_ID], [SITE_ID], [ACCT_YEAR], [ACCT_PERIOD], [CURRENCY_ID], [USER_DIMENSION_1], [USER_DIMENSION_2], [CUST_ORDER_ID], [PRODUCT_CODE]);

ALTER TABLE [dbo].[ACCOUNT_BAL_DIM] ADD CONSTRAINT [FK_ACCTBALDIM_CURR] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[ACCOUNT_BAL_DIM] ADD CONSTRAINT [FK_ACCTBALDIM_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
