CREATE TABLE [dbo].[IBT_SHIPPER_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SHIPPER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] int DEFAULT  NOT NULL,
    [IBT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [IBT_LINE_NO] int DEFAULT  NOT NULL,
    [USER_SHIPPED_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [SHIPPED_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [ACT_FREIGHT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [SHIPPING_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [WEIGHT_UM] NVARCHAR(15) DEFAULT  NULL,
    [CARTON_COUNT] int DEFAULT  NULL,
    [IN_TRANSACTION_ID] int DEFAULT  NULL,
    [OUT_TRANSACTION_ID] int DEFAULT  NULL,
    [NMFC_CODE_ID] NVARCHAR(15) DEFAULT  NULL,
    [PACKAGE_TYPE] NVARCHAR(5) DEFAULT  NULL,
    [PALLET_COUNT] int DEFAULT  NULL,
    [SHIPPING_UM] NVARCHAR(15) DEFAULT  NULL,
    [LONG_DESCRIPTION] image DEFAULT  NULL,
    [DIMENSIONS_UM] NVARCHAR(15) DEFAULT  NULL,
    [SHIP_DIMENSIONS] NVARCHAR(50) DEFAULT  NULL,
    [SERVICE_CHARGE_ID] NVARCHAR(15) DEFAULT  NULL,
    [MISC_REFERENCE] NVARCHAR(40) DEFAULT  NULL,
    [VAT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [UNIT_PRICE] DECIMAL(22,8) DEFAULT  NULL,
    [ITA_SPECIAL_CHARGE] NVARCHAR(1) DEFAULT  NULL,
    [NET_SHIP_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [TARE_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [PIECE_COUNT] DECIMAL(20,8) DEFAULT  NULL,
    [LENGTH] DECIMAL(14,4) DEFAULT  NULL,
    [WIDTH] DECIMAL(14,4) DEFAULT  NULL,
    [HEIGHT] DECIMAL(14,4) DEFAULT  NULL
)

ALTER TABLE [dbo].[IBT_SHIPPER_LINE] ADD CONSTRAINT [PK_IBT_SHIPPER_LINE] PRIMARY KEY ([SHIPPER_ID], [LINE_NO]);

ALTER TABLE [dbo].[IBT_SHIPPER_LINE] ADD CONSTRAINT [FKEY9492] FOREIGN KEY ([SHIPPER_ID]) REFERENCES [dbo].[IBT_SHIPPER]([SHIPPER_ID]);
