CREATE TABLE [dbo].[NOTIFICATION_EMPLOYEE_DOC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [DOC_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DOC_LINE_NO] smallint DEFAULT  NOT NULL,
    [EMPLOYEE_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NULL,
    [NOTIFY_ME_TYPE] NCHAR(1) DEFAULT ('N') NOT NULL
)

ALTER TABLE [dbo].[NOTIFICATION_EMPLOYEE_DOC] ADD CONSTRAINT [PK_NOTIFICATION_EMPLOYEE_DOC] PRIMARY KEY ([PROGRAM_ID], [DOC_ID], [DOC_LINE_NO], [EMPLOYEE_ID], [NOTIFY_ME_TYPE]);
