CREATE TABLE [dbo].[DISPATCH_PALLET] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DISPATCH_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DISPATCH_LINE_NO] smallint DEFAULT  NOT NULL,
    [PALLET_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [CARTON_COUNT] smallint DEFAULT  NOT NULL,
    [SHIPPING_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [PACKAGE_TYPE] NVARCHAR(5) DEFAULT  NULL,
    [QTY_PER_PKG] DECIMAL(20,8) DEFAULT  NULL,
    [SKID_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [SKID_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [CONTAINER_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [CONTAINER_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [CREATE_INV_TRANS] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[DISPATCH_PALLET] ADD CONSTRAINT [PK_DISPATCH_PALLET] PRIMARY KEY ([DISPATCH_ID], [DISPATCH_LINE_NO], [PALLET_ID]);
