CREATE TABLE [dbo].[CLYRPD] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [YQDATE] DECIMAL(7,0) DEFAULT  NULL,
    [YQYEAR] DECIMAL(3,0) DEFAULT  NULL,
    [YQPERD] DECIMAL(2,0) DEFAULT  NULL,
    [YQDTMT] DECIMAL(7,0) DEFAULT  NULL,
    [YQBLNK] NVARCHAR(15) DEFAULT  NULL
)
