CREATE TABLE [dbo].[INSPECTION_ORDER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(16) DEFAULT  NOT NULL,
    [ENTITY_ID] NVARCHAR(22) DEFAULT  NOT NULL,
    [LOCATION_ID] NVARCHAR(100) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DOCUMENT_ID] NVARCHAR(16) DEFAULT  NULL,
    [VARIATION_ID] bigint DEFAULT  NULL,
    [LID] NVARCHAR(64) DEFAULT  NULL,
    [ORDER_TYPE] NVARCHAR(20) DEFAULT  NOT NULL,
    [STATUS] NVARCHAR(20) DEFAULT ('Open') NOT NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [QTY_RECEIVED_BASE] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [QTY_ACCEPTED_BASE] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [QTY_REJECTED_BASE] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [QTY_HOLD_BASE] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [QTY_UNIT_BASE] NVARCHAR(16) DEFAULT  NULL,
    [QTY_RECEIVED] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [QTY_ACCEPTED] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [QTY_REJECTED] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [QTY_HOLD] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [QTY_UNIT] NVARCHAR(16) DEFAULT  NULL,
    [RECEIVER_ID] NVARCHAR(15) DEFAULT  NULL,
    [RECEIVER_LINE_NO] smallint DEFAULT  NULL,
    [INV_TRANS_ID] int DEFAULT  NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [OPERATION_SEQ_NO] smallint DEFAULT  NULL,
    [EMPLOYEE_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NULL,
    [LAST_MOD_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[INSPECTION_ORDER] ADD CONSTRAINT [PK_INSPECTION_ORDER] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[INSPECTION_ORDER] ADD CONSTRAINT [FK_IO_TO_EMP] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [dbo].[EMPLOYEE]([ID]);

ALTER TABLE [dbo].[INSPECTION_ORDER] ADD CONSTRAINT [FK_IO_TO_INV_TRANS] FOREIGN KEY ([INV_TRANS_ID]) REFERENCES [dbo].[INVENTORY_TRANS]([TRANSACTION_ID]);

ALTER TABLE [dbo].[INSPECTION_ORDER] ADD CONSTRAINT [FK_IO_TO_OP] FOREIGN KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO]) REFERENCES [dbo].[OPERATION]([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [SEQUENCE_NO]);

ALTER TABLE [dbo].[INSPECTION_ORDER] ADD CONSTRAINT [FK_IO_TO_RCVR_LINE] FOREIGN KEY ([RECEIVER_ID], [RECEIVER_LINE_NO]) REFERENCES [dbo].[RECEIVER_LINE]([RECEIVER_ID], [LINE_NO]);
