CREATE TABLE [dbo].[CURRENCY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(40) DEFAULT  NULL,
    [SHORT_NAME] NVARCHAR(10) DEFAULT  NULL,
    [COUNTRY_PROFILE] NVARCHAR(40) DEFAULT  NULL,
    [I_CURRENCY] smallint DEFAULT  NULL,
    [I_CURR_DIGITS] smallint DEFAULT  NULL,
    [I_NEG_CURR] smallint DEFAULT  NULL,
    [S_CURRENCY] NVARCHAR(40) DEFAULT  NULL,
    [S_THOUSAND] NCHAR(1) DEFAULT  NULL,
    [EURO_PARTICIPANT] NCHAR(1) DEFAULT ('') NOT NULL,
    [XCHG_RATE] DECIMAL(15,8) DEFAULT  NULL,
    [ISO_CODE] NVARCHAR(5) DEFAULT  NULL,
    [REPORTING_CURRENCY] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[CURRENCY] ADD CONSTRAINT [PK_CURRENCY] PRIMARY KEY ([ID]);
