CREATE TABLE [dbo].[SERVICE_CHARGE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [TRADE_DISC_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [COMMISSION_PCT] DECIMAL(6,3) DEFAULT  NULL,
    [SALES_TAX_GROUP_ID] NVARCHAR(15) DEFAULT  NULL,
    [PRODUCT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [COMMODITY_CODE] NVARCHAR(15) DEFAULT  NULL,
    [VAT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [UNIT_PRICE] DECIMAL(22,6) DEFAULT  NULL,
    [GL_REVENUE_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [INTRASTAT_INCLUDE] NCHAR(1) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ACTIVE_FLAG] NCHAR(1) DEFAULT ('Y') NOT NULL
)

ALTER TABLE [dbo].[SERVICE_CHARGE] ADD CONSTRAINT [PK_SERVICE_CHARGE] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[SERVICE_CHARGE] ADD CONSTRAINT [FK_SRVCHARGE_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
