CREATE TABLE [dbo].[EARNING_CODE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL
)

ALTER TABLE [dbo].[EARNING_CODE] ADD CONSTRAINT [PK_EARNING_CODE] PRIMARY KEY ([ID]);
