CREATE TABLE [dbo].[PART_SUBSTITUTE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SUBSTITUTE_PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [RANK] smallint DEFAULT  NULL
)

ALTER TABLE [dbo].[PART_SUBSTITUTE] ADD CONSTRAINT [PK_PART_SUBST] PRIMARY KEY ([PART_ID], [SUBSTITUTE_PART_ID]);
