CREATE TABLE [dbo].[DEFAULT_DATA] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [TABLE_NAME] NVARCHAR(30) DEFAULT  NOT NULL,
    [COLUMN_NAME] NVARCHAR(30) DEFAULT  NOT NULL,
    [DEFAULT_STRING] NVARCHAR(100) DEFAULT  NULL
)

ALTER TABLE [dbo].[DEFAULT_DATA] ADD CONSTRAINT [PK_DEFAULT_DATA] PRIMARY KEY ([SITE_ID], [USER_ID], [TABLE_NAME], [COLUMN_NAME]);

ALTER TABLE [dbo].[DEFAULT_DATA] ADD CONSTRAINT [FK_DEFAULT_DATA_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
