CREATE TABLE [dbo].[BURDEN_BATCH_RATES] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BATCH_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BURDEN_RATE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BURDEN_PERIOD_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [POSTING_STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[BURDEN_BATCH_RATES] ADD CONSTRAINT [PK_BURDEN_BATCH_RATES] PRIMARY KEY ([SITE_ID], [BATCH_ID]);
