CREATE TABLE [dbo].[PROJECT_TYPE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [USE_FOR_COMMERCIAL] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[PROJECT_TYPE] ADD CONSTRAINT [PK_PROJECT_TYPE] PRIMARY KEY ([CODE]);
