CREATE TABLE [dbo].[CUST_ORDL_WIP_VAS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUST_ORDER_LINE_NO] smallint DEFAULT  NOT NULL,
    [WIP_VAS_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [WIP_VAS_UNIT_PRICE] DECIMAL(22,8) DEFAULT ((0)) NOT NULL,
    [LONG_DESCRIPTION] image DEFAULT  NULL
)

ALTER TABLE [dbo].[CUST_ORDL_WIP_VAS] ADD CONSTRAINT [PK_CO_LN_WIPVAS] PRIMARY KEY ([CUST_ORDER_ID], [CUST_ORDER_LINE_NO], [WIP_VAS_ID]);
