CREATE TABLE [dbo].[FIN_DIST_DETAIL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROCESS_TYPE] NVARCHAR(5) DEFAULT  NOT NULL,
    [SOURCE_ID] NVARCHAR(40) DEFAULT  NOT NULL,
    [SOURCE_LINE_NO] smallint DEFAULT  NOT NULL,
    [SOURCE_DIST_NO] smallint DEFAULT  NOT NULL,
    [SOURCE_ENTRY_NO] smallint DEFAULT  NOT NULL,
    [AMOUNT_TYPE] NCHAR(2) DEFAULT  NOT NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[FIN_DIST_DETAIL] ADD CONSTRAINT [PK_FIN_DIST_LINE_ACCT] PRIMARY KEY ([PROCESS_TYPE], [SOURCE_ID], [SOURCE_DIST_NO], [SOURCE_ENTRY_NO], [SOURCE_LINE_NO], [AMOUNT_TYPE], [GL_ACCOUNT_ID], [CURRENCY_ID]);
