CREATE TABLE [dbo].[VEND_BANK_ACCOUNT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(30) DEFAULT  NULL,
    [BANK_ID] NVARCHAR(10) DEFAULT  NULL,
    [ACCOUNT_NO] NVARCHAR(30) DEFAULT  NULL,
    [ACCOUNT_TYPE] NVARCHAR(2) DEFAULT  NULL,
    [BRANCH_ID] NVARCHAR(10) DEFAULT  NULL,
    [BANK_NAME] NVARCHAR(50) DEFAULT  NULL,
    [BANK_ADDR_1] NVARCHAR(50) DEFAULT  NULL,
    [BANK_ADDR_2] NVARCHAR(50) DEFAULT  NULL,
    [BANK_ADDR_3] NVARCHAR(50) DEFAULT  NULL,
    [BANK_CITY] NVARCHAR(30) DEFAULT  NULL,
    [BANK_ZIPCODE] NVARCHAR(10) DEFAULT  NULL,
    [BANK_STATE] NVARCHAR(10) DEFAULT  NULL,
    [BANK_COUNTRY] NVARCHAR(50) DEFAULT  NULL,
    [BANK_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [IBAN] NVARCHAR(40) DEFAULT  NULL,
    [BIC] NVARCHAR(15) DEFAULT  NULL,
    [XML_PAY_EXPORT] NVARCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[VEND_BANK_ACCOUNT] ADD CONSTRAINT [PK_VEND_BANK_ACCOUNT] PRIMARY KEY ([ID]);
