CREATE TABLE [dbo].[DIVISION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[DIVISION] ADD CONSTRAINT [PK_DIVISION] PRIMARY KEY ([CODE]);
