CREATE TABLE [dbo].[LMC_MRP_GRID_COL_TITLES] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [GRID] VARCHAR(20) DEFAULT  NOT NULL,
    [COL] VARCHAR(80) DEFAULT  NOT NULL,
    [TITLE] VARCHAR(120) DEFAULT  NULL
)

ALTER TABLE [dbo].[LMC_MRP_GRID_COL_TITLES] ADD CONSTRAINT [PK_LMC_MRP_GRID_COL_TITLES] PRIMARY KEY ([GRID], [COL]);
