CREATE TABLE [dbo].[PART_TRACE_LOCATION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LOCATION_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TRACE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[PART_TRACE_LOCATION] ADD CONSTRAINT [PK_PART_TRACE_LOCATION] PRIMARY KEY ([PART_ID], [WAREHOUSE_ID], [LOCATION_ID], [TRACE_ID]);

ALTER TABLE [dbo].[PART_TRACE_LOCATION] ADD CONSTRAINT [FKEY9621] FOREIGN KEY ([PART_ID], [WAREHOUSE_ID], [LOCATION_ID]) REFERENCES [dbo].[PART_LOCATION]([PART_ID], [WAREHOUSE_ID], [LOCATION_ID]);
