CREATE TABLE [dbo].[PART_ALIAS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL,
    [TYPE] NVARCHAR(30) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PART_ALIAS] ADD CONSTRAINT [PK_PART_ALIAS] PRIMARY KEY ([PART_ID], [ID]);

ALTER TABLE [dbo].[PART_ALIAS] ADD CONSTRAINT [FK_PART_ALIAS_00] FOREIGN KEY ([TYPE]) REFERENCES [dbo].[PART_ALIAS_TYPE]([ID]);

ALTER TABLE [dbo].[PART_ALIAS] ADD CONSTRAINT [FKEY9485] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);
