CREATE TABLE [dbo].[PRORATED_LABOR_TX] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PRORATE_ID] int DEFAULT  NOT NULL,
    [TRANSACTION_ID] int DEFAULT  NOT NULL,
    [PRORATE_TYPE] NCHAR(1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PRORATED_LABOR_TX] ADD CONSTRAINT [PK_PRORATED_LABOR] PRIMARY KEY ([PRORATE_ID], [TRANSACTION_ID]);

ALTER TABLE [dbo].[PRORATED_LABOR_TX] ADD CONSTRAINT [FK_PRORATED_LABOR_00] FOREIGN KEY ([TRANSACTION_ID]) REFERENCES [dbo].[LABOR_TICKET]([TRANSACTION_ID]);
