CREATE TABLE [dbo].[CASH_DISBURSEMENT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BANK_ACCOUNT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CONTROL_NO] int DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NULL,
    [CHECK_NO] int DEFAULT  NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NULL,
    [CHECK_DATE] datetime DEFAULT  NOT NULL,
    [MEMO] NVARCHAR(40) DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT  NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CLEARED] NCHAR(1) DEFAULT ('') NOT NULL,
    [MARKED_FOR_PURGE] NCHAR(1) DEFAULT ('') NOT NULL,
    [VEND_BANK_ACCT_ID] NVARCHAR(15) DEFAULT  NULL,
    [PAYEE_REF_CODE] NVARCHAR(10) DEFAULT  NULL,
    [PAYMENT_METHOD] NCHAR(1) DEFAULT ('') NOT NULL,
    [PAYMENT_BATCH_NO] int DEFAULT  NULL,
    [PAYMENT_FILENAME] NVARCHAR(15) DEFAULT  NULL,
    [NAME] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_1] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_2] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_3] NVARCHAR(50) DEFAULT  NULL,
    [CITY] NVARCHAR(30) DEFAULT  NULL,
    [STATE] NVARCHAR(10) DEFAULT  NULL,
    [ZIPCODE] NVARCHAR(10) DEFAULT  NULL,
    [COUNTRY] NVARCHAR(50) DEFAULT  NULL,
    [CASH_DISBURSE_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [CLEARED_DATE] datetime DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [USER_EXCH_RATE] NCHAR(1) DEFAULT ('') NOT NULL,
    [VOID_DATE] datetime DEFAULT  NULL,
    [VOID_CLEARED_DATE] datetime DEFAULT  NULL,
    [GROUP_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[CASH_DISBURSEMENT] ADD CONSTRAINT [PK_CASH_DISBURSEMENT] PRIMARY KEY ([BANK_ACCOUNT_ID], [CONTROL_NO]);

ALTER TABLE [dbo].[CASH_DISBURSEMENT] ADD CONSTRAINT [FKEY0022] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[CASH_DISBURSEMENT] ADD CONSTRAINT [FKEY0083] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);

ALTER TABLE [dbo].[CASH_DISBURSEMENT] ADD CONSTRAINT [FKEY0219] FOREIGN KEY ([BANK_ACCOUNT_ID]) REFERENCES [dbo].[BANK_ACCOUNT]([ID]);

ALTER TABLE [dbo].[CASH_DISBURSEMENT] ADD CONSTRAINT [FKEY9363] FOREIGN KEY ([VEND_BANK_ACCT_ID]) REFERENCES [dbo].[VEND_BANK_ACCOUNT]([ID]);

ALTER TABLE [dbo].[CASH_DISBURSEMENT] ADD CONSTRAINT [FKEY9403] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
