CREATE TABLE [dbo].[SOA_CODE_LIST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [LIST_ID] NVARCHAR(100) DEFAULT  NOT NULL,
    [AGENCY_ID] NVARCHAR(10) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(100) DEFAULT  NOT NULL,
    [CODE_NAME] NVARCHAR(64) DEFAULT  NULL,
    [CODE_DESC] NVARCHAR(250) DEFAULT  NULL,
    [STATUS] NVARCHAR(15) DEFAULT  NOT NULL,
    [EFFECTIVE_DATE] datetime DEFAULT  NULL,
    [EXPIRATION_DATE] datetime DEFAULT  NULL,
    [READ_ONLY] NCHAR(1) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[SOA_CODE_LIST] ADD CONSTRAINT [PK_SOA_CODE_LIST] PRIMARY KEY ([LIST_ID], [AGENCY_ID], [CODE]);

ALTER TABLE [dbo].[SOA_CODE_LIST] ADD CONSTRAINT [FK_SOA_DIMENSION] FOREIGN KEY ([LIST_ID], [AGENCY_ID]) REFERENCES [dbo].[SOA_DIMENSION]([ID], [AGENCY_ID]);
