CREATE TABLE [dbo].[VENDOR_ADDRESS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ADDR_NO] int DEFAULT  NOT NULL,
    [NAME] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_1] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_2] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_3] NVARCHAR(50) DEFAULT  NULL,
    [CITY] NVARCHAR(30) DEFAULT  NULL,
    [STATE] NVARCHAR(10) DEFAULT  NULL,
    [ZIPCODE] NVARCHAR(10) DEFAULT  NULL,
    [COUNTRY] NVARCHAR(50) DEFAULT  NULL,
    [VENDOR_ADDR_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [TRANS_CODE] NVARCHAR(25) DEFAULT  NULL,
    [COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [VAT_REGISTRATION] NVARCHAR(25) DEFAULT  NULL,
    [DEF_LBL_FORMAT_ID] NVARCHAR(30) DEFAULT  NULL,
    [VAT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [VAT_OVERRIDE_SEQ] NVARCHAR(1) DEFAULT  NULL,
    [DISPATCH_ADDR_ID] NVARCHAR(20) DEFAULT  NULL,
    [CARRIER_ID] NVARCHAR(20) DEFAULT  NULL,
    [DISP_PALLET_REQ] NCHAR(1) DEFAULT  NULL,
    [VAT_EXEMPT] NCHAR(1) DEFAULT ('N') NOT NULL
)

ALTER TABLE [dbo].[VENDOR_ADDRESS] ADD CONSTRAINT [PK_VENDOR_ADDRESS] PRIMARY KEY ([VENDOR_ID], [ADDR_NO]);

ALTER TABLE [dbo].[VENDOR_ADDRESS] ADD CONSTRAINT [FKEY0074] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);

ALTER TABLE [dbo].[VENDOR_ADDRESS] ADD CONSTRAINT [FKEY9322] FOREIGN KEY ([TRANS_CODE]) REFERENCES [dbo].[PORT_OF_TRANS]([CODE]);

ALTER TABLE [dbo].[VENDOR_ADDRESS] ADD CONSTRAINT [FKEY9466] FOREIGN KEY ([DEF_LBL_FORMAT_ID]) REFERENCES [dbo].[LABEL_FORMAT]([ID]);
