CREATE TABLE [dbo].[WAREHOUSE_WIP_VAS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WIP_VAS_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [UNIT_PRICE] DECIMAL(22,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[WAREHOUSE_WIP_VAS] ADD CONSTRAINT [PK_WHS_WIP_VAS] PRIMARY KEY ([WAREHOUSE_ID], [PART_ID], [WIP_VAS_ID]);
