CREATE TABLE [dbo].[INSPECTION_REASON] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[INSPECTION_REASON] ADD CONSTRAINT [PK_INSP_REASON] PRIMARY KEY ([ID]);
