CREATE TABLE [dbo].[SERV_CHARGE_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SERVICE_CHARGE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SERV_CHARGE_BINARY] ADD CONSTRAINT [PK_SERV_CHARGE_BINARY] PRIMARY KEY ([SERVICE_CHARGE_ID], [TYPE]);
