CREATE TABLE [dbo].[GOTO_TABLE_COLUMN] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [GOTO_VMPGM_PROGRAM_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [GOTO_VMPGM_GOTO_ID] int DEFAULT  NOT NULL,
    [TABLE_NAME] NVARCHAR(30) DEFAULT  NOT NULL,
    [COL_SEQ] int DEFAULT  NOT NULL,
    [COLUMN_NAME] NVARCHAR(30) DEFAULT  NOT NULL,
    [IS_PRIMARY] NVARCHAR(1) DEFAULT  NOT NULL,
    [IS_VALUE] NVARCHAR(1) DEFAULT  NULL,
    [FIXED_VALUE] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[GOTO_TABLE_COLUMN] ADD CONSTRAINT [PK_GOTO_TABLE_COLUMN] PRIMARY KEY ([GOTO_VMPGM_PROGRAM_ID], [GOTO_VMPGM_GOTO_ID], [TABLE_NAME], [COL_SEQ], [COLUMN_NAME]);

ALTER TABLE [dbo].[GOTO_TABLE_COLUMN] ADD CONSTRAINT [FK_GOTO_TABLE_COLUMN_TO_GOTO_VMPGM] FOREIGN KEY ([GOTO_VMPGM_PROGRAM_ID], [GOTO_VMPGM_GOTO_ID]) REFERENCES [dbo].[GOTO_VMPGM]([PROGRAM_ID], [GOTO_ID]);
