CREATE TABLE [dbo].[INV_TRANS_AVE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TRANSACTION_ID] int DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [INV_MATERIAL_COST] DECIMAL(23,8) DEFAULT  NOT NULL,
    [INV_LABOR_COST] DECIMAL(23,8) DEFAULT  NOT NULL,
    [INV_BURDEN_COST] DECIMAL(23,8) DEFAULT  NOT NULL,
    [INV_SERVICE_COST] DECIMAL(23,8) DEFAULT  NOT NULL,
    [INVENTORY_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [AVE_MATERIAL_COST] DECIMAL(23,8) DEFAULT  NOT NULL,
    [AVE_LABOR_COST] DECIMAL(23,8) DEFAULT  NOT NULL,
    [AVE_BURDEN_COST] DECIMAL(23,8) DEFAULT  NOT NULL,
    [AVE_SERVICE_COST] DECIMAL(23,8) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[INV_TRANS_AVE] ADD CONSTRAINT [PK_INV_TRANS_AVE] PRIMARY KEY ([TRANSACTION_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[INV_TRANS_AVE] ADD CONSTRAINT [FKEY9497] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[INV_TRANS_AVE] ADD CONSTRAINT [FKEY9498] FOREIGN KEY ([TRANSACTION_ID]) REFERENCES [dbo].[INVENTORY_TRANS]([TRANSACTION_ID]);
