CREATE TABLE [dbo].[UNITS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [UNIT_OF_MEASURE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [SCALE] smallint DEFAULT  NOT NULL,
    [CATEGORY] NVARCHAR(64) DEFAULT  NULL,
    [USER_DEFINED_UOM] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[UNITS] ADD CONSTRAINT [PK_UNITS] PRIMARY KEY ([UNIT_OF_MEASURE]);
