CREATE TABLE [dbo].[QUERY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(80) DEFAULT  NOT NULL,
    [QUERY] image DEFAULT  NULL,
    [AUTO_JOIN] NCHAR(1) DEFAULT ('N') NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[QUERY] ADD CONSTRAINT [PK_QUERY] PRIMARY KEY ([USER_ID], [NAME]);
