CREATE TABLE [dbo].[INDIVIDUAL_PRV_HISTORY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] int DEFAULT  NOT NULL,
    [DATA_GROUP] NVARCHAR(30) DEFAULT  NOT NULL,
    [DOCUMENT_ID] NVARCHAR(50) DEFAULT  NOT NULL,
    [ACTION] NVARCHAR(10) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[INDIVIDUAL_PRV_HISTORY] ADD CONSTRAINT [PK_IND_PRV_HISTORY] PRIMARY KEY ([ID]);
