CREATE TABLE [dbo].[PHYS_COUNT_LOC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PHYS_COUNT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LOCATION_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PHYS_COUNT_LOC] ADD CONSTRAINT [PK_PHYS_COUNT_LOC] PRIMARY KEY ([PHYS_COUNT_ID], [WAREHOUSE_ID], [LOCATION_ID]);
