CREATE TABLE [dbo].[LABOR_TICKET_BREAK] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TRANSACTION_ID] int DEFAULT  NOT NULL,
    [CLOCK_IN] datetime DEFAULT  NOT NULL,
    [CLOCK_OUT] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[LABOR_TICKET_BREAK] ADD CONSTRAINT [PK_LABOR_TICKET_BREAK] PRIMARY KEY ([TRANSACTION_ID], [CLOCK_IN]);

ALTER TABLE [dbo].[LABOR_TICKET_BREAK] ADD CONSTRAINT [FK_LABOR_TICKET_BREAK_00] FOREIGN KEY ([TRANSACTION_ID]) REFERENCES [dbo].[LABOR_TICKET]([TRANSACTION_ID]);
