CREATE TABLE [dbo].[ESB_INBOUND_DUPLICATE] (
    [C_ID] bigint IDENTITY(1,1) DEFAULT  NOT NULL,
    [C_MESSAGE_ID] NVARCHAR(250) DEFAULT  NOT NULL,
    [C_CREATED_DATE_TIME] datetime DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[ESB_INBOUND_DUPLICATE] ADD CONSTRAINT [PK_ESB_INBOUND_DUPLICATE] PRIMARY KEY ([C_ID]);
