CREATE TABLE [dbo].[PLANNING_FORECAST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [FORECAST_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [REQUIRED_DATE] datetime DEFAULT  NOT NULL,
    [REQUIRED_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [ACTIVE] NCHAR(1) DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PLANNING_FORECAST] ADD CONSTRAINT [FK_PLNG_FORECAST_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
