CREATE TABLE [dbo].[GPSCMF] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [GCBOID] NVARCHAR(30) DEFAULT  NULL,
    [GCBOVL] NVARCHAR(15) DEFAULT  NULL,
    [GCLNID] NVARCHAR(2) DEFAULT  NULL,
    [GCBODS] NVARCHAR(30) DEFAULT  NULL
)
