CREATE TABLE [dbo].[SERVICE_RCVR_DISP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RECEIVER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RECEIVER_LINE_NO] smallint DEFAULT  NOT NULL,
    [DISPATCH_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DISPATCH_LINE_NO] smallint DEFAULT  NOT NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SERVICE_RCVR_DISP] ADD CONSTRAINT [PK_SERVICE_RCVR_DISP] PRIMARY KEY ([RECEIVER_ID], [RECEIVER_LINE_NO], [DISPATCH_ID], [DISPATCH_LINE_NO]);
