CREATE TABLE [dbo].[SHIP_REASON] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL,
    [GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [DEFAULT_WHSE_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[SHIP_REASON] ADD CONSTRAINT [PK_SHIP_REASON] PRIMARY KEY ([TYPE], [CODE]);
