CREATE TABLE [dbo].[IBT_LINE_TRC_CTL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [IBT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [IBT_LINE_NO] int DEFAULT  NOT NULL,
    [SERIAL_ID_CTL] NVARCHAR(170) DEFAULT  NULL,
    [LOT_ID_CTL] NVARCHAR(170) DEFAULT  NULL,
    [APROPERTY_1_CTL] NVARCHAR(170) DEFAULT  NULL,
    [APROPERTY_2_CTL] NVARCHAR(170) DEFAULT  NULL,
    [APROPERTY_3_CTL] NVARCHAR(170) DEFAULT  NULL,
    [APROPERTY_4_CTL] NVARCHAR(170) DEFAULT  NULL,
    [APROPERTY_5_CTL] NVARCHAR(170) DEFAULT  NULL,
    [NPROPERTY_1_CTL] NVARCHAR(40) DEFAULT  NULL,
    [NPROPERTY_2_CTL] NVARCHAR(40) DEFAULT  NULL,
    [NPROPERTY_3_CTL] NVARCHAR(40) DEFAULT  NULL,
    [NPROPERTY_4_CTL] NVARCHAR(40) DEFAULT  NULL,
    [NPROPERTY_5_CTL] NVARCHAR(40) DEFAULT  NULL,
    [EXPIRE_DATE_CTL] NVARCHAR(50) DEFAULT  NULL,
    [PROD_DATE_CTL] NVARCHAR(50) DEFAULT  NULL,
    [REC_BY_DATE_CTL] NVARCHAR(50) DEFAULT  NULL,
    [AVAILABLE_DATE_CTL] NVARCHAR(50) DEFAULT  NULL,
    [SHIP_BY_DATE_CTL] NVARCHAR(50) DEFAULT  NULL
)

ALTER TABLE [dbo].[IBT_LINE_TRC_CTL] ADD CONSTRAINT [PK_IBT_LINE_TRC_CTL] PRIMARY KEY ([IBT_ID], [IBT_LINE_NO]);
