CREATE TABLE [dbo].[INV_RECEIPT_DIST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [INV_TRANS_ID] int DEFAULT  NOT NULL,
    [DEMAND_SUPPLY_ID] int DEFAULT  NOT NULL,
    [QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[INV_RECEIPT_DIST] ADD CONSTRAINT [PK_INV_RCPT_DIST] PRIMARY KEY ([INV_TRANS_ID], [DEMAND_SUPPLY_ID]);

ALTER TABLE [dbo].[INV_RECEIPT_DIST] ADD CONSTRAINT [FKEY9554] FOREIGN KEY ([INV_TRANS_ID]) REFERENCES [dbo].[INVENTORY_TRANS]([TRANSACTION_ID]);
