CREATE TABLE [dbo].[IBT_RECEIVER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [IBT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RECEIVED_DATE] datetime DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [MARKED_FOR_PURGE] NCHAR(1) DEFAULT ('') NOT NULL,
    [SHIP_REASON_CD] NVARCHAR(15) DEFAULT  NULL,
    [SHIPPER_ID] NVARCHAR(15) DEFAULT  NULL,
    [RCPT_ACK_RECEIVED] datetime DEFAULT  NULL,
    [CONTACT_ID] NVARCHAR(25) DEFAULT  NULL,
    [CONTACT_FIRST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_LAST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_INITIAL] NVARCHAR(2) DEFAULT  NULL,
    [CONTACT_POSITION] NVARCHAR(50) DEFAULT  NULL,
    [CONTACT_HONORIFIC] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_SALUTATION] NVARCHAR(60) DEFAULT  NULL,
    [CONTACT_PHONE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_FAX] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_MOBILE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_EMAIL] NVARCHAR(100) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CONTACT_PHONE_EXT] NVARCHAR(10) DEFAULT  NULL
)

ALTER TABLE [dbo].[IBT_RECEIVER] ADD CONSTRAINT [PK_IBT_RECEIVER] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[IBT_RECEIVER] ADD CONSTRAINT [FK_IBT_REC_CONT_ID] FOREIGN KEY ([CONTACT_ID]) REFERENCES [dbo].[CONTACT]([ID]);

ALTER TABLE [dbo].[IBT_RECEIVER] ADD CONSTRAINT [FK_IBT_RECEIVER_00] FOREIGN KEY ([SHIPPER_ID]) REFERENCES [dbo].[IBT_SHIPPER]([SHIPPER_ID]);

ALTER TABLE [dbo].[IBT_RECEIVER] ADD CONSTRAINT [FK_IBT_RECEIVER_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[IBT_RECEIVER] ADD CONSTRAINT [FKEY9493] FOREIGN KEY ([IBT_ID]) REFERENCES [dbo].[IBT]([ID]);
