CREATE TABLE [dbo].[PURC_MATL_DETAIL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PURC_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DIST_NO] smallint DEFAULT  NOT NULL,
    [TRANSACTION_ID] int DEFAULT  NOT NULL,
    [PURC_ORDER_LINE_NO] smallint DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [ACT_MATERIAL_COST] DECIMAL(23,8) DEFAULT  NULL,
    [ACT_LABOR_COST] DECIMAL(23,8) DEFAULT  NULL,
    [ACT_BURDEN_COST] DECIMAL(23,8) DEFAULT  NULL,
    [ACT_SERVICE_COST] DECIMAL(23,8) DEFAULT  NULL,
    [REFERENCE] NVARCHAR(50) DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [DR_MAT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [DR_LAB_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [DR_BUR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [DR_SER_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CR_MAT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CR_LAB_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CR_BUR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CR_SER_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[PURC_MATL_DETAIL] ADD CONSTRAINT [PK_PURC_MATL_DETAIL] PRIMARY KEY ([PURC_ORDER_ID], [DIST_NO], [TRANSACTION_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[PURC_MATL_DETAIL] ADD CONSTRAINT [FKEY9002] FOREIGN KEY ([PURC_ORDER_ID]) REFERENCES [dbo].[PURCHASE_ORDER]([ID]);

ALTER TABLE [dbo].[PURC_MATL_DETAIL] ADD CONSTRAINT [FKEY9456] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
