CREATE TABLE [dbo].[WITHHOLDING] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [TAX_PERCENT] DECIMAL(15,2) DEFAULT  NOT NULL,
    [TAX_ALLOWANCE_PCT] DECIMAL(15,2) DEFAULT  NOT NULL,
    [TAX_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[WITHHOLDING] ADD CONSTRAINT [PK_WITHHOLDING] PRIMARY KEY ([CODE]);
