CREATE TABLE [dbo].[SHOP_VIEW] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VIEW_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [SEQ_NO] smallint DEFAULT  NOT NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SHOP_VIEW] ADD CONSTRAINT [PK_SHOP_VIEW] PRIMARY KEY ([VIEW_ID], [SEQ_NO], [RESOURCE_ID]);

ALTER TABLE [dbo].[SHOP_VIEW] ADD CONSTRAINT [FKEY0125] FOREIGN KEY ([RESOURCE_ID]) REFERENCES [dbo].[SHOP_RESOURCE]([ID]);
