CREATE TABLE [dbo].[EMPLOYEE_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EMPLOYEE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[EMPLOYEE_BINARY] ADD CONSTRAINT [PK_EMPLOYEE_BINARY] PRIMARY KEY ([EMPLOYEE_ID], [TYPE]);
