CREATE TABLE [dbo].[PREFERENCES] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(50) DEFAULT  NULL,
    [SECTION] NVARCHAR(100) DEFAULT  NOT NULL,
    [ENTRY] NVARCHAR(100) DEFAULT  NOT NULL,
    [VALUE] NVARCHAR(255) DEFAULT  NULL,
    [IS_GLOBAL] NCHAR(1) DEFAULT ('N') NOT NULL,
    [IS_ACTIVE] NCHAR(1) DEFAULT ('Y') NOT NULL,
    [MODIFY_DATE] datetime DEFAULT  NULL
)
