CREATE TABLE [dbo].[DOCUMENT_REF_WF] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WORKFLOW_TYPE] NVARCHAR(30) DEFAULT  NOT NULL,
    [APPLICATION_AREA] NVARCHAR(30) DEFAULT  NOT NULL,
    [TEMPLATE_NAME] NVARCHAR(30) DEFAULT  NOT NULL,
    [REFERENCE] NVARCHAR(100) DEFAULT  NOT NULL,
    [WORKFLOW_BOX_LABEL] NVARCHAR(30) DEFAULT  NOT NULL,
    [DOCUMENT_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [SOURCE_TYPE] NCHAR(1) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [DOC_NUM] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[DOCUMENT_REF_WF] ADD CONSTRAINT [PK_DOCUMENT_REF_WF] PRIMARY KEY ([WORKFLOW_TYPE], [APPLICATION_AREA], [TEMPLATE_NAME], [REFERENCE], [WORKFLOW_BOX_LABEL], [DOC_NUM]);
