CREATE TABLE [dbo].[REASON] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TYPE] NCHAR(2) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[REASON] ADD CONSTRAINT [PK_REASON] PRIMARY KEY ([TYPE], [CODE]);
