CREATE TABLE [dbo].[BURDEN_DIST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BURDEN_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DIST_NO] smallint DEFAULT  NOT NULL,
    [ENTRY_NO] smallint DEFAULT  NOT NULL,
    [BURDEN_CATEGORY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [AMOUNT_TYPE] NCHAR(2) DEFAULT  NOT NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [POSTING_STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [BATCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [NATIVE] NCHAR(1) DEFAULT  NULL,
    [SOURCE_TYPE] NVARCHAR(20) DEFAULT  NOT NULL,
    [IS_RETRO] NCHAR(1) DEFAULT ('N') NOT NULL,
    [IS_PROJECT] NCHAR(1) DEFAULT ('N') NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[BURDEN_DIST] ADD CONSTRAINT [PK_BURDEN_DIST] PRIMARY KEY ([BURDEN_ID], [DIST_NO], [ENTRY_NO], [BURDEN_CATEGORY_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[BURDEN_DIST] ADD CONSTRAINT [FK_BURDEN_DIST_00] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[BURDEN_DIST] ADD CONSTRAINT [FK_BURDEN_DIST_01] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[BURDEN_DIST] ADD CONSTRAINT [FK_BURDEN_DIST_02] FOREIGN KEY ([GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[BURDEN_DIST] ADD CONSTRAINT [FK_BURDEN_DIST_03] FOREIGN KEY ([SITE_ID], [BATCH_ID]) REFERENCES [dbo].[JOURNAL_BATCH]([SITE_ID], [ID]);
