CREATE TABLE [dbo].[CASH_DISBURSE_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BANK_ACCOUNT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CONTROL_NO] int DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [VOUCHER_ID] NVARCHAR(15) DEFAULT  NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NULL,
    [REFERENCE_INFO] NVARCHAR(40) DEFAULT  NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT  NOT NULL,
    [DISCOUNT_APPLIED] DECIMAL(23,8) DEFAULT  NOT NULL,
    [WITHHOLDING_CODE] NVARCHAR(15) DEFAULT  NULL,
    [WITHHELD_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [WH_ALLOWED_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [WH_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [APPLIED_TYPE] NVARCHAR(1) DEFAULT  NULL,
    [MEMO_VOUCHER_ID] NVARCHAR(15) DEFAULT  NULL,
    [PCURR_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [PCURR_DISC_APPLIED] DECIMAL(23,8) DEFAULT  NULL,
    [PCURR_WH_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [PCURR_WH_ALLWD_AMT] DECIMAL(23,8) DEFAULT  NULL,
    [INST_NO] smallint DEFAULT  NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [PAYB_VENDOR_ID] NVARCHAR(15) DEFAULT  NULL,
    [PAYB_VENDOR_NAME] NVARCHAR(50) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CASH_DISBURSE_LINE] ADD CONSTRAINT [PK_CASH_DISBURSE_LINE] PRIMARY KEY ([BANK_ACCOUNT_ID], [CONTROL_NO], [LINE_NO]);

ALTER TABLE [dbo].[CASH_DISBURSE_LINE] ADD CONSTRAINT [FK_CDL_PAYB_VEND] FOREIGN KEY ([PAYB_VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);

ALTER TABLE [dbo].[CASH_DISBURSE_LINE] ADD CONSTRAINT [FK_CSH_DSB_LINE_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[CASH_DISBURSE_LINE] ADD CONSTRAINT [FKEY0227] FOREIGN KEY ([VOUCHER_ID]) REFERENCES [dbo].[PAYABLE]([VOUCHER_ID]);

ALTER TABLE [dbo].[CASH_DISBURSE_LINE] ADD CONSTRAINT [FKEY0228] FOREIGN KEY ([BANK_ACCOUNT_ID], [CONTROL_NO]) REFERENCES [dbo].[CASH_DISBURSEMENT]([BANK_ACCOUNT_ID], [CONTROL_NO]);

ALTER TABLE [dbo].[CASH_DISBURSE_LINE] ADD CONSTRAINT [FKEY0278] FOREIGN KEY ([GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);
