CREATE TABLE [dbo].[PART_SHIPPING] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SHIPTO_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [CONTAINER_PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [CONTAINER_UM] NVARCHAR(15) DEFAULT  NULL,
    [CONTAINER_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [STD_PCS_CONTAINER] DECIMAL(20,8) DEFAULT  NULL,
    [SKID_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [SKID_UM] NVARCHAR(15) DEFAULT  NULL,
    [SKID_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [STD_CONTAINER_SKID] DECIMAL(20,8) DEFAULT  NULL,
    [CONTAINER_TYPE] NVARCHAR(20) DEFAULT  NULL,
    [DEFAULT_CONTAINER] NVARCHAR(1) DEFAULT  NULL,
    [CUST_SHIP_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [PACKAGE_TYPE] NVARCHAR(5) DEFAULT  NULL,
    [CREATE_INV_TRANS] NCHAR(1) DEFAULT  NULL,
    [DOCK_CODE] NVARCHAR(20) DEFAULT  NULL
)

ALTER TABLE [dbo].[PART_SHIPPING] ADD CONSTRAINT [PK_PART_SHIPPING] PRIMARY KEY ([CUSTOMER_ID], [SHIPTO_ID], [PART_ID], [CONTAINER_PART_ID]);

ALTER TABLE [dbo].[PART_SHIPPING] ADD CONSTRAINT [FKEY9444] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);
