CREATE TABLE [dbo].[CUSTOMER_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CUSTOMER_BINARY] ADD CONSTRAINT [PK_CUSTOMER_BINARY] PRIMARY KEY ([CUSTOMER_ID], [TYPE]);

ALTER TABLE [dbo].[CUSTOMER_BINARY] ADD CONSTRAINT [FKEY0061] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);
