CREATE TABLE [dbo].[RFQ_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RFQ_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(120) DEFAULT  NULL,
    [VENDOR_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [MFG_NAME] NVARCHAR(30) DEFAULT  NULL,
    [MFG_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [PRODUCT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [COMMODITY_CODE] NVARCHAR(15) DEFAULT  NULL,
    [QTY_BREAK_1] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_2] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_3] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_4] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_5] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_6] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_7] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_8] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_9] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_10] DECIMAL(20,8) DEFAULT  NULL,
    [PURCHASE_UM] NVARCHAR(15) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [SERVICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [SHIPPING_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [ORIG_STAGE_REVISION_ID] NVARCHAR(24) DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[RFQ_LINE] ADD CONSTRAINT [PK_RFQ_LINE] PRIMARY KEY ([RFQ_ID], [LINE_NO]);

ALTER TABLE [dbo].[RFQ_LINE] ADD CONSTRAINT [FKEY0252] FOREIGN KEY ([RFQ_ID]) REFERENCES [dbo].[REQUEST_FOR_QUOTE]([ID]);

ALTER TABLE [dbo].[RFQ_LINE] ADD CONSTRAINT [FKEY0294] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);
