CREATE TABLE [dbo].[DISTRIBUTION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [STATUS] NVARCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[DISTRIBUTION] ADD CONSTRAINT [PK_DISTRIBUTION] PRIMARY KEY ([ID]);
