CREATE TABLE [dbo].[PLANNING_PART] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PLANNING_PART] ADD CONSTRAINT [PK_PLANNING_PART] PRIMARY KEY ([ID], [SITE_ID]);

ALTER TABLE [dbo].[PLANNING_PART] ADD CONSTRAINT [FK_PLNG_PART_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
