CREATE TABLE [dbo].[IBT_RECEIVER_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RECEIVER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] int DEFAULT  NOT NULL,
    [IBT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [IBT_LINE_NO] int DEFAULT  NOT NULL,
    [USER_RECEIVED_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [RECEIVED_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [ACT_FREIGHT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [LOCATION_ID] NVARCHAR(15) DEFAULT  NULL,
    [IN_TRANSACTION_ID] int DEFAULT  NULL,
    [OUT_TRANSACTION_ID] int DEFAULT  NULL,
    [SHIPPER_ID] NVARCHAR(15) DEFAULT  NULL,
    [SHIPPER_LINE_NO] int DEFAULT  NULL,
    [PIECE_COUNT] DECIMAL(20,8) DEFAULT  NULL,
    [LENGTH] DECIMAL(14,4) DEFAULT  NULL,
    [WIDTH] DECIMAL(14,4) DEFAULT  NULL,
    [HEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [DIMENSIONS_UM] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[IBT_RECEIVER_LINE] ADD CONSTRAINT [PK_IBT_RECEIVER_LINE] PRIMARY KEY ([RECEIVER_ID], [LINE_NO]);

ALTER TABLE [dbo].[IBT_RECEIVER_LINE] ADD CONSTRAINT [FK_IBT_RECEIVER_LINE_00] FOREIGN KEY ([SHIPPER_ID]) REFERENCES [dbo].[IBT_SHIPPER]([SHIPPER_ID]);

ALTER TABLE [dbo].[IBT_RECEIVER_LINE] ADD CONSTRAINT [FKEY9495] FOREIGN KEY ([RECEIVER_ID]) REFERENCES [dbo].[IBT_RECEIVER]([ID]);
