CREATE TABLE [dbo].[SI_BATCH_LABOR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] VARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] CHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] VARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] VARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] VARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] VARCHAR(3) DEFAULT  NOT NULL,
    [SEQUENCE_NO] smallint DEFAULT  NOT NULL,
    [RESOURCE_ID] VARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SI_BATCH_LABOR] ADD CONSTRAINT [PK_SI_BATCH_LABOR] PRIMARY KEY ([ID], [WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [SEQUENCE_NO]);
