CREATE TABLE [dbo].[DEPARTMENT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [DEFAULT_DEPARTMENT] NCHAR(1) DEFAULT  NULL,
    [PARENT_DEPT_ID] NVARCHAR(15) DEFAULT  NULL,
    [MATL_COST_CAT_ID] NVARCHAR(15) DEFAULT  NULL,
    [SERV_COST_CAT_ID] NVARCHAR(15) DEFAULT  NULL,
    [LAB_COST_CAT_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[DEPARTMENT] ADD CONSTRAINT [PK_DEPARTMENT] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[DEPARTMENT] ADD CONSTRAINT [FK_DEPARTMENT_00] FOREIGN KEY ([MATL_COST_CAT_ID]) REFERENCES [dbo].[COST_CATEGORY]([ID]);

ALTER TABLE [dbo].[DEPARTMENT] ADD CONSTRAINT [FK_DEPARTMENT_01] FOREIGN KEY ([SERV_COST_CAT_ID]) REFERENCES [dbo].[COST_CATEGORY]([ID]);

ALTER TABLE [dbo].[DEPARTMENT] ADD CONSTRAINT [FK_DEPARTMENT_02] FOREIGN KEY ([LAB_COST_CAT_ID]) REFERENCES [dbo].[COST_CATEGORY]([ID]);
