CREATE TABLE [dbo].[LABEL_FORMAT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [LABEL_TYPE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [FORMAT_FILE_NAME] NVARCHAR(250) DEFAULT  NULL,
    [LABEL_PRINTER_ID] smallint DEFAULT  NULL,
    [QTY_TO_PRINT] smallint DEFAULT  NULL,
    [LABEL_MULT_FLAG] NCHAR(1) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[LABEL_FORMAT] ADD CONSTRAINT [PK_LABEL_FORMAT] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[LABEL_FORMAT] ADD CONSTRAINT [FKEY9459] FOREIGN KEY ([LABEL_TYPE_ID]) REFERENCES [dbo].[LABEL_TYPE]([ID]);
