CREATE TABLE [dbo].[SER_SIMULATION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SIMULATION_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SERVICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [PRV_CST_PER_UNIT] DECIMAL(22,8) DEFAULT  NULL,
    [PRV_BASE_CHG_SER] DECIMAL(23,8) DEFAULT  NULL,
    [PRV_MIN_CHG] DECIMAL(23,8) DEFAULT  NULL,
    [SIM_CST_PER_UNIT] DECIMAL(22,8) DEFAULT  NULL,
    [SIM_BASE_CHG_SER] DECIMAL(23,8) DEFAULT  NULL,
    [SIM_MIN_CHG] DECIMAL(23,8) DEFAULT  NULL,
    [PRV_CREATE_DATE] datetime DEFAULT  NULL,
    [SIM_CREATE_DATE] datetime DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SER_SIMULATION] ADD CONSTRAINT [PK_SER_SIMULATION] PRIMARY KEY ([SIMULATION_ID], [SERVICE_ID]);

ALTER TABLE [dbo].[SER_SIMULATION] ADD CONSTRAINT [FK_SER_SIMULATION_00] FOREIGN KEY ([SIMULATION_ID]) REFERENCES [dbo].[SIMULATION]([ID]);

ALTER TABLE [dbo].[SER_SIMULATION] ADD CONSTRAINT [FK_SER_SIMULATION_01] FOREIGN KEY ([SERVICE_ID]) REFERENCES [dbo].[SERVICE]([ID]);
