CREATE TABLE [dbo].[CASH_PLAN_SITE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CASH_PLAN_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CASH_PLAN_SITE] ADD CONSTRAINT [PK_CASH_PLAN_SITE] PRIMARY KEY ([CASH_PLAN_ID], [SITE_ID]);

ALTER TABLE [dbo].[CASH_PLAN_SITE] ADD CONSTRAINT [FK_CP_SITE_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
