CREATE TABLE [dbo].[PAYABLE_CURR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VOUCHER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[PAYABLE_CURR] ADD CONSTRAINT [PK_PAYABLE_CURR] PRIMARY KEY ([VOUCHER_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[PAYABLE_CURR] ADD CONSTRAINT [FKEY9400] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[PAYABLE_CURR] ADD CONSTRAINT [FKEY9401] FOREIGN KEY ([VOUCHER_ID]) REFERENCES [dbo].[PAYABLE]([VOUCHER_ID]);
