CREATE TABLE [dbo].[INDIRECT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [INDIRECT_CODE] NCHAR(1) DEFAULT  NOT NULL,
    [ACTIVE] NCHAR(1) DEFAULT ('Y') NULL
)

ALTER TABLE [dbo].[INDIRECT] ADD CONSTRAINT [PK_INDIRECT] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[INDIRECT] ADD CONSTRAINT [FKEY0255] FOREIGN KEY ([GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);
