CREATE TABLE [dbo].[TRACE_INV_TRANS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [TRACE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [TRANSACTION_ID] int DEFAULT  NOT NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [COSTED_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[TRACE_INV_TRANS] ADD CONSTRAINT [PK_TRACE_INV_TRANS] PRIMARY KEY ([PART_ID], [TRACE_ID], [TRANSACTION_ID]);

ALTER TABLE [dbo].[TRACE_INV_TRANS] ADD CONSTRAINT [FKEY0241] FOREIGN KEY ([PART_ID], [TRACE_ID]) REFERENCES [dbo].[TRACE]([PART_ID], [ID]);

ALTER TABLE [dbo].[TRACE_INV_TRANS] ADD CONSTRAINT [FKEY0284] FOREIGN KEY ([TRANSACTION_ID]) REFERENCES [dbo].[INVENTORY_TRANS]([TRANSACTION_ID]);
