CREATE TABLE [dbo].[RECVR_LINE_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RECEIVER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RECEIVER_LINE_NO] smallint DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[RECVR_LINE_BINARY] ADD CONSTRAINT [PK_RECVR_LINE_BINARY] PRIMARY KEY ([RECEIVER_ID], [RECEIVER_LINE_NO]);

ALTER TABLE [dbo].[RECVR_LINE_BINARY] ADD CONSTRAINT [FK_RECVR_LINE_BINARY] FOREIGN KEY ([RECEIVER_ID], [RECEIVER_LINE_NO]) REFERENCES [dbo].[RECEIVER_LINE]([RECEIVER_ID], [LINE_NO]);
