CREATE TABLE [dbo].[PURC_ORDER_REQ] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PURC_ORD_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PURC_ORD_LINE_NO] smallint DEFAULT  NOT NULL,
    [PURC_REQ_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PURC_REQ_LINE_NO] smallint DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PURC_ORDER_REQ] ADD CONSTRAINT [PK_PURC_ORDER_REQ] PRIMARY KEY ([PURC_ORD_ID], [PURC_ORD_LINE_NO], [PURC_REQ_ID], [PURC_REQ_LINE_NO]);
