CREATE TABLE [dbo].[EQUIP_LABOR_PRICE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(10) DEFAULT  NOT NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [NORMAL] DECIMAL(22,8) DEFAULT  NULL,
    [OVERTIME_1] DECIMAL(22,8) DEFAULT  NULL,
    [OVERTIME_2] DECIMAL(22,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[EQUIP_LABOR_PRICE] ADD CONSTRAINT [PK_EQ_LAB_PRICE] PRIMARY KEY ([ID], [RESOURCE_ID]);

ALTER TABLE [dbo].[EQUIP_LABOR_PRICE] ADD CONSTRAINT [FKEY9510] FOREIGN KEY ([RESOURCE_ID]) REFERENCES [dbo].[SHOP_RESOURCE]([ID]);
