CREATE TABLE [dbo].[USER_PROFILE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [PROFILE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[USER_PROFILE] ADD CONSTRAINT [PK_USER_PROFILE] PRIMARY KEY ([USER_ID], [PROFILE_ID]);
