CREATE TABLE [dbo].[GL_BURDEN_MAP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DEPARTMENT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PROJECT_TYPE] NVARCHAR(15) DEFAULT  NOT NULL,
    [COST_GROUP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DEBIT_GL_ACCOUNT] NVARCHAR(30) DEFAULT  NULL,
    [CREDIT_GL_ACCOUNT] NVARCHAR(30) DEFAULT  NULL,
    [BURDEN_GROUP_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[GL_BURDEN_MAP] ADD CONSTRAINT [PK_GL_BURDEN_MAP] PRIMARY KEY ([DEPARTMENT_ID], [PROJECT_TYPE], [COST_GROUP_ID]);

ALTER TABLE [dbo].[GL_BURDEN_MAP] ADD CONSTRAINT [FK_GL_BURDEN_MAP_00] FOREIGN KEY ([DEPARTMENT_ID]) REFERENCES [dbo].[DEPARTMENT]([ID]);

ALTER TABLE [dbo].[GL_BURDEN_MAP] ADD CONSTRAINT [FK_GL_BURDEN_MAP_01] FOREIGN KEY ([PROJECT_TYPE]) REFERENCES [dbo].[PROJECT_TYPE]([CODE]);

ALTER TABLE [dbo].[GL_BURDEN_MAP] ADD CONSTRAINT [FK_GL_BURDEN_MAP_02] FOREIGN KEY ([COST_GROUP_ID]) REFERENCES [dbo].[COST_GROUP]([ID]);

ALTER TABLE [dbo].[GL_BURDEN_MAP] ADD CONSTRAINT [FK_GL_BURDEN_MAP_03] FOREIGN KEY ([DEBIT_GL_ACCOUNT]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[GL_BURDEN_MAP] ADD CONSTRAINT [FK_GL_BURDEN_MAP_04] FOREIGN KEY ([CREDIT_GL_ACCOUNT]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[GL_BURDEN_MAP] ADD CONSTRAINT [FK_GL_BURDEN_MAP_05] FOREIGN KEY ([BURDEN_GROUP_ID]) REFERENCES [dbo].[BURDEN_GROUP]([ID]);
