CREATE TABLE [dbo].[ALLOCATION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(5) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [GROUP_ID] NVARCHAR(15) DEFAULT  NULL,
    [FROM_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [FROM_SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TRIGGER_FREQ] NCHAR(1) DEFAULT ('') NOT NULL,
    [TRIGGER_DAY] smallint DEFAULT  NULL,
    [VARIABLE_NAME_1] NVARCHAR(30) DEFAULT  NULL,
    [VARIABLE_NAME_2] NVARCHAR(30) DEFAULT  NULL,
    [VARIABLE_NAME_3] NVARCHAR(30) DEFAULT  NULL,
    [VARIABLE_NAME_4] NVARCHAR(30) DEFAULT  NULL,
    [VARIABLE_NAME_5] NVARCHAR(30) DEFAULT  NULL,
    [VARIABLE_NAME_6] NVARCHAR(30) DEFAULT  NULL,
    [VARIABLE_NAME_7] NVARCHAR(30) DEFAULT  NULL,
    [VARIABLE_NAME_8] NVARCHAR(30) DEFAULT  NULL,
    [VARIABLE_NAME_9] NVARCHAR(30) DEFAULT  NULL,
    [VARIABLE_NAME_10] NVARCHAR(30) DEFAULT  NULL,
    [VARIABLE_VALUE_1] DECIMAL(23,8) DEFAULT  NULL,
    [VARIABLE_VALUE_2] DECIMAL(23,8) DEFAULT  NULL,
    [VARIABLE_VALUE_3] DECIMAL(23,8) DEFAULT  NULL,
    [VARIABLE_VALUE_4] DECIMAL(23,8) DEFAULT  NULL,
    [VARIABLE_VALUE_5] DECIMAL(23,8) DEFAULT  NULL,
    [VARIABLE_VALUE_6] DECIMAL(23,8) DEFAULT  NULL,
    [VARIABLE_VALUE_7] DECIMAL(23,8) DEFAULT  NULL,
    [VARIABLE_VALUE_8] DECIMAL(23,8) DEFAULT  NULL,
    [VARIABLE_VALUE_9] DECIMAL(23,8) DEFAULT  NULL,
    [VARIABLE_VALUE_10] DECIMAL(23,8) DEFAULT  NULL,
    [TRIGGER_COUNT] smallint DEFAULT  NULL,
    [TRIGGER_MAX] smallint DEFAULT  NULL,
    [TRIGGER_LAST_DATE] datetime DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NULL,
    [POST_ALL_TRACKING] NCHAR(1) DEFAULT ('') NOT NULL,
    [POST_AS_NATIVE] NCHAR(1) DEFAULT ('') NOT NULL,
    [CREATE_DATE] datetime DEFAULT  NULL,
    [LAST_EXECUTED_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[ALLOCATION] ADD CONSTRAINT [PK_ALLOCATION] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[ALLOCATION] ADD CONSTRAINT [FKEY0016] FOREIGN KEY ([FROM_SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[ALLOCATION] ADD CONSTRAINT [FKEY9484] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
