CREATE TABLE [dbo].[CONSOLIDATION_MAP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CONSOLIDATION_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [LOCAL_ACCT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [PARENT_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [DERIVED] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[CONSOLIDATION_MAP] ADD CONSTRAINT [PK_CONSOLID_MAP] PRIMARY KEY ([CONSOLIDATION_ID], [LINE_NO]);

ALTER TABLE [dbo].[CONSOLIDATION_MAP] ADD CONSTRAINT [FKEY9482] FOREIGN KEY ([LOCAL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[CONSOLIDATION_MAP] ADD CONSTRAINT [FKEY9483] FOREIGN KEY ([PARENT_ACCT_ID]) REFERENCES [dbo].[CONSOLID_ACCOUNT]([PARENT_ACCT_ID]);
