CREATE TABLE [dbo].[SALES_TAX_GRP_PART] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ADDR_NO] int DEFAULT  NOT NULL,
    [SHIPTO_ID] NVARCHAR(20) DEFAULT  NULL,
    [DEF_SALES_TAX_GRP_ID] NVARCHAR(15) DEFAULT  NOT NULL
)
