CREATE TABLE [dbo].[EQUIPMENT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [EQUIP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(250) DEFAULT  NULL,
    [TYPE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [MODEL] NVARCHAR(15) DEFAULT  NOT NULL,
    [SERIAL_NO] NVARCHAR(10) DEFAULT  NULL,
    [MANUF_DATE] datetime DEFAULT  NULL,
    [VM_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [VM_WO_BASE_ID] NVARCHAR(30) DEFAULT  NULL,
    [ENG_REL_NO] NVARCHAR(30) DEFAULT  NULL,
    [INSTALL_DATE] datetime DEFAULT  NULL,
    [DEFAULT_RESOURCE] NVARCHAR(15) DEFAULT  NULL,
    [MACH_RESOURCE] NVARCHAR(15) DEFAULT  NULL,
    [SERVICE_AREA] NVARCHAR(15) DEFAULT  NULL,
    [BRANCH] NVARCHAR(15) DEFAULT  NULL,
    [MAINT_TYPE] NVARCHAR(15) DEFAULT  NULL,
    [CLASS] NVARCHAR(5) DEFAULT  NULL,
    [PERIOD] int DEFAULT  NULL,
    [START_HOUR] int DEFAULT  NULL,
    [FINISH_HOUR] int DEFAULT  NULL,
    [ADDITIONAL_CHARGES] NVARCHAR(1) DEFAULT  NULL,
    [PARTS_FOC] NVARCHAR(1) DEFAULT  NULL,
    [MILEAGE_FOC] NVARCHAR(1) DEFAULT  NULL,
    [LABOR_FOC] NVARCHAR(1) DEFAULT  NULL,
    [LABORPL] NVARCHAR(10) DEFAULT  NULL,
    [PARTPL] NVARCHAR(10) DEFAULT  NULL,
    [CONTRACT_NO] NVARCHAR(15) DEFAULT  NULL,
    [START_DATE] datetime DEFAULT  NULL,
    [FINISH_DATE] datetime DEFAULT  NULL,
    [INTERNAL] NVARCHAR(1) DEFAULT  NULL,
    [CONTACT_FAX] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_FIRST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_HONORIFIC] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_INITIAL] NVARCHAR(2) DEFAULT  NULL,
    [CONTACT_LAST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_PHONE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_POSITION] NVARCHAR(50) DEFAULT  NULL,
    [CONTACT_SALUTATION] NVARCHAR(60) DEFAULT  NULL,
    [CONTACT_MOBILE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_EMAIL] NVARCHAR(100) DEFAULT  NULL,
    [SHIP_TO_ADDR_NO] int DEFAULT  NULL,
    [USER_1] NVARCHAR(80) DEFAULT  NULL,
    [USER_2] NVARCHAR(80) DEFAULT  NULL,
    [USER_3] NVARCHAR(80) DEFAULT  NULL,
    [USER_4] NVARCHAR(80) DEFAULT  NULL,
    [USER_5] NVARCHAR(80) DEFAULT  NULL,
    [USER_6] NVARCHAR(80) DEFAULT  NULL,
    [USER_7] NVARCHAR(80) DEFAULT  NULL,
    [USER_8] NVARCHAR(80) DEFAULT  NULL,
    [USER_9] NVARCHAR(80) DEFAULT  NULL,
    [USER_10] NVARCHAR(80) DEFAULT  NULL,
    [UDF_LAYOUT_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CONTACT_ID] NVARCHAR(25) DEFAULT  NULL,
    [CONTACT_PHONE_EXT] NVARCHAR(10) DEFAULT  NULL
)

ALTER TABLE [dbo].[EQUIPMENT] ADD CONSTRAINT [PK_EQUIPMENT] PRIMARY KEY ([EQUIP_ID]);

ALTER TABLE [dbo].[EQUIPMENT] ADD CONSTRAINT [FK_EQUIP_CONT_ID] FOREIGN KEY ([CONTACT_ID]) REFERENCES [dbo].[CONTACT]([ID]);

ALTER TABLE [dbo].[EQUIPMENT] ADD CONSTRAINT [FK_EQUIPMENT_00] FOREIGN KEY ([TYPE_ID], [MODEL]) REFERENCES [dbo].[EQUIP_MODEL]([TYPE_ID], [ID]);

ALTER TABLE [dbo].[EQUIPMENT] ADD CONSTRAINT [FKEY9513] FOREIGN KEY ([TYPE_ID]) REFERENCES [dbo].[EQUIP_TYPE]([ID]);

ALTER TABLE [dbo].[EQUIPMENT] ADD CONSTRAINT [FKEY9515] FOREIGN KEY ([VM_PART_ID]) REFERENCES [dbo].[PART]([ID]);

ALTER TABLE [dbo].[EQUIPMENT] ADD CONSTRAINT [FKEY9516] FOREIGN KEY ([SERVICE_AREA]) REFERENCES [dbo].[EQUIP_AREA]([id]);

ALTER TABLE [dbo].[EQUIPMENT] ADD CONSTRAINT [FKEY9517] FOREIGN KEY ([BRANCH], [SERVICE_AREA]) REFERENCES [dbo].[EQUIP_BRANCH]([ID], [AREA_ID]);

ALTER TABLE [dbo].[EQUIPMENT] ADD CONSTRAINT [FKEY9518] FOREIGN KEY ([DEFAULT_RESOURCE]) REFERENCES [dbo].[SHOP_RESOURCE]([ID]);
