CREATE TABLE [dbo].[JOURNAL_BATCH] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NVARCHAR(3) DEFAULT ('') NOT NULL,
    [BATCH_DATE] datetime DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [LOCKED] NCHAR(1) DEFAULT ('') NOT NULL,
    [DEBIT_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [CREDIT_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[JOURNAL_BATCH] ADD CONSTRAINT [PK_JOURNAL_BATCH] PRIMARY KEY ([SITE_ID], [ID]);
