CREATE TABLE [dbo].[EC_LINE_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EC_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] int DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[EC_LINE_BINARY] ADD CONSTRAINT [PK_EC_LINE_BINARY] PRIMARY KEY ([EC_ID], [LINE_NO], [TYPE]);

ALTER TABLE [dbo].[EC_LINE_BINARY] ADD CONSTRAINT [FK_EC_LINE_BINARY] FOREIGN KEY ([EC_ID], [LINE_NO]) REFERENCES [dbo].[EC_LINE]([EC_ID], [LINE_NO]);
