CREATE TABLE [dbo].[BANK_ADJUSTMENT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BANK_ACCOUNT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ADJUSTMENT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [TRANSACTION_DATE] datetime DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT  NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT  NOT NULL,
    [REFERENCE] NVARCHAR(80) DEFAULT  NULL,
    [POSTING_STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [BATCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CASH_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CLEARED] NCHAR(1) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [CLEARED_DATE] datetime DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [USER_EXCH_RATE] NCHAR(1) DEFAULT  NULL,
    [DEPOSIT_ID] NVARCHAR(15) DEFAULT  NULL,
    [CONTROL_NO] int DEFAULT  NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[BANK_ADJUSTMENT] ADD CONSTRAINT [PK_BANK_ADJUSTMENT] PRIMARY KEY ([BANK_ACCOUNT_ID], [ADJUSTMENT_ID]);

ALTER TABLE [dbo].[BANK_ADJUSTMENT] ADD CONSTRAINT [FKEY0222] FOREIGN KEY ([BANK_ACCOUNT_ID]) REFERENCES [dbo].[BANK_ACCOUNT]([ID]);

ALTER TABLE [dbo].[BANK_ADJUSTMENT] ADD CONSTRAINT [FKEY0298] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[BANK_ADJUSTMENT] ADD CONSTRAINT [FKEY9430] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
