CREATE TABLE [dbo].[WORKFLOW] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TYPE] NVARCHAR(30) DEFAULT  NOT NULL,
    [APPLICATION_AREA] NVARCHAR(30) DEFAULT  NOT NULL,
    [TEMPLATE_NAME] NVARCHAR(30) DEFAULT  NOT NULL,
    [REFERENCE] NVARCHAR(100) DEFAULT  NOT NULL,
    [STATUS] NVARCHAR(30) DEFAULT  NULL,
    [DBTABLE] NVARCHAR(30) DEFAULT  NULL,
    [EVALUATE_ON_TIMER] NCHAR(1) DEFAULT  NULL,
    [DIAGRAM] image DEFAULT  NULL,
    [curr_step_name] NVARCHAR(15) DEFAULT  NULL,
    [curr_step_id] NVARCHAR(10) DEFAULT  NULL,
    [curr_approv_user] NVARCHAR(15) DEFAULT  NULL,
    [curr_step_start_on] datetime DEFAULT  NULL,
    [curr_step_last_notified] datetime DEFAULT  NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[WORKFLOW] ADD CONSTRAINT [PK_WORKFLOW] PRIMARY KEY ([TYPE], [APPLICATION_AREA], [TEMPLATE_NAME], [REFERENCE]);
