CREATE TABLE [dbo].[DEVIATION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[DEVIATION] ADD CONSTRAINT [PK_DEVIATION] PRIMARY KEY ([ID]);
