CREATE TABLE [dbo].[FEEDING_OPERATIONS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BUFFER_ID] int DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [OPERATION_SEQ_NO] smallint DEFAULT  NOT NULL,
    [FED_TYPE] NCHAR(1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[FEEDING_OPERATIONS] ADD CONSTRAINT [PK_FEEDING_OPERATIONS] PRIMARY KEY ([BUFFER_ID], [WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO]);

ALTER TABLE [dbo].[FEEDING_OPERATIONS] ADD CONSTRAINT [FKEY_FEEDOPS_BUF] FOREIGN KEY ([BUFFER_ID]) REFERENCES [dbo].[BUFFER]([ID]);

ALTER TABLE [dbo].[FEEDING_OPERATIONS] ADD CONSTRAINT [FKEY_FEEDOPS_OPER] FOREIGN KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO]) REFERENCES [dbo].[OPERATION]([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [SEQUENCE_NO]);
