CREATE TABLE [dbo].[EVENT_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EVENT_ID] int DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS_LENGTH] int DEFAULT ((0)) NOT NULL,
    [BITS] image DEFAULT  NULL
)

ALTER TABLE [dbo].[EVENT_BINARY] ADD CONSTRAINT [PK_EVENT_BINARY] PRIMARY KEY ([EVENT_ID], [TYPE]);
