CREATE TABLE [dbo].[WIP_MAT_LOCATION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[WIP_MAT_LOCATION] ADD CONSTRAINT [PK_WIP_MAT_LOCATION] PRIMARY KEY ([WAREHOUSE_ID], [ID]);

ALTER TABLE [dbo].[WIP_MAT_LOCATION] ADD CONSTRAINT [FK_WIP_LOC_WH] FOREIGN KEY ([WAREHOUSE_ID]) REFERENCES [dbo].[WAREHOUSE]([ID]);
