CREATE TABLE [dbo].[RECEIVER_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RECEIVER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [PURC_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PURC_ORDER_LINE_NO] smallint DEFAULT  NOT NULL,
    [USER_RECEIVED_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [RECEIVED_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [INSPECT_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [ACT_FREIGHT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [INVOICED_DATE] datetime DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [LOCATION_ID] NVARCHAR(15) DEFAULT  NULL,
    [TRANSACTION_ID] int DEFAULT  NULL,
    [SERV_TRANS_ID] int DEFAULT  NULL,
    [PIECE_COUNT] DECIMAL(20,8) DEFAULT  NULL,
    [LENGTH] DECIMAL(14,4) DEFAULT  NULL,
    [WIDTH] DECIMAL(14,4) DEFAULT  NULL,
    [HEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [DIMENSIONS_UM] NVARCHAR(15) DEFAULT  NULL,
    [REJECTED_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [HTS_CODE] NVARCHAR(20) DEFAULT  NULL,
    [ORIG_COUNTRY_ID] NVARCHAR(50) DEFAULT  NULL,
    [UNIT_PRICE] DECIMAL(22,8) DEFAULT  NULL,
    [LANDED_UNIT_PRICE] DECIMAL(22,8) DEFAULT  NULL,
    [FIXED_CHARGE] DECIMAL(23,8) DEFAULT  NULL,
    [INTRASTAT_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [DATA_COLL_COMP] NCHAR(1) DEFAULT  NULL,
    [GROSS_WEIGHT] DECIMAL(15,4) DEFAULT  NULL,
    [CNSN_OUT_TRANS_ID] int DEFAULT  NULL,
    [INSP_REASON_CD] NVARCHAR(15) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(120) DEFAULT  NULL
)

ALTER TABLE [dbo].[RECEIVER_LINE] ADD CONSTRAINT [PK_RECEIVER_LINE] PRIMARY KEY ([RECEIVER_ID], [LINE_NO]);

ALTER TABLE [dbo].[RECEIVER_LINE] ADD CONSTRAINT [FKEY0171] FOREIGN KEY ([PURC_ORDER_ID], [PURC_ORDER_LINE_NO]) REFERENCES [dbo].[PURC_ORDER_LINE]([PURC_ORDER_ID], [LINE_NO]);

ALTER TABLE [dbo].[RECEIVER_LINE] ADD CONSTRAINT [FKEY0172] FOREIGN KEY ([RECEIVER_ID]) REFERENCES [dbo].[RECEIVER]([ID]);
