CREATE TABLE [dbo].[SHOP_RESOURCE_SITE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SCHEDULE_NORMALLY] NCHAR(1) DEFAULT  NULL,
    [AUTO_REPORTING] NCHAR(1) DEFAULT  NULL,
    [SHIFT_1_CAPACITY] smallint DEFAULT  NULL,
    [SHIFT_2_CAPACITY] smallint DEFAULT  NULL,
    [SHIFT_3_CAPACITY] smallint DEFAULT  NULL,
    [SETUP_COST_PER_HR] DECIMAL(22,8) DEFAULT ((0)) NOT NULL,
    [RUN_COST_PER_HR] DECIMAL(22,8) DEFAULT ((0)) NOT NULL,
    [SERVICE_BUFFER] int DEFAULT  NULL,
    [BUR_PER_HR_SETUP] DECIMAL(22,8) DEFAULT ((0)) NOT NULL,
    [BUR_PER_HR_RUN] DECIMAL(22,8) DEFAULT ((0)) NOT NULL,
    [RUN_COST_PER_UNIT] DECIMAL(22,8) DEFAULT ((0)) NOT NULL,
    [BUR_PERCENT_SETUP] DECIMAL(6,3) DEFAULT ((0)) NOT NULL,
    [BUR_PERCENT_RUN] DECIMAL(6,3) DEFAULT ((0)) NOT NULL,
    [BUR_PER_OPERATION] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [AFC_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [AFB_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [SCHEDULE_TYPE] smallint DEFAULT  NULL,
    [MIN_SEGMENT_SIZE] DECIMAL(14,2) DEFAULT  NULL,
    [EFFICIENCY_FACTOR] DECIMAL(14,2) DEFAULT  NULL,
    [BUR_PER_UNIT_RUN] DECIMAL(22,8) DEFAULT ((0)) NOT NULL,
    [MONITOR_LOAD] NCHAR(1) DEFAULT  NULL,
    [COST_CATEGORY_ID] NVARCHAR(15) DEFAULT  NULL,
    [DEPARTMENT_ID] NVARCHAR(15) DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT  NULL,
    [UDF_LAYOUT_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_1] NVARCHAR(80) DEFAULT  NULL,
    [USER_2] NVARCHAR(80) DEFAULT  NULL,
    [USER_3] NVARCHAR(80) DEFAULT  NULL,
    [USER_4] NVARCHAR(80) DEFAULT  NULL,
    [USER_5] NVARCHAR(80) DEFAULT  NULL,
    [USER_6] NVARCHAR(80) DEFAULT  NULL,
    [USER_7] NVARCHAR(80) DEFAULT  NULL,
    [USER_8] NVARCHAR(80) DEFAULT  NULL,
    [USER_9] NVARCHAR(80) DEFAULT  NULL,
    [USER_10] NVARCHAR(80) DEFAULT  NULL,
    [BID_RATE_CATEGORY_ID] NVARCHAR(15) DEFAULT  NULL,
    [QUANTITY_REPORTING] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[SHOP_RESOURCE_SITE] ADD CONSTRAINT [PK_SHOP_RESOURCE_SITE] PRIMARY KEY ([SITE_ID], [RESOURCE_ID]);

ALTER TABLE [dbo].[SHOP_RESOURCE_SITE] ADD CONSTRAINT [FK_SHOP_RES_SITE_TO_SHOP_RESOURCE] FOREIGN KEY ([RESOURCE_ID]) REFERENCES [dbo].[SHOP_RESOURCE]([ID]);

ALTER TABLE [dbo].[SHOP_RESOURCE_SITE] ADD CONSTRAINT [FK_SHOP_RES_SITE_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
