CREATE TABLE [dbo].[HARMONIZED_TARIFF] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [HTS_CODE] NVARCHAR(20) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [DUTY_PERCENT] DECIMAL(6,4) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[HARMONIZED_TARIFF] ADD CONSTRAINT [PK_HARMONY_TARIFF] PRIMARY KEY ([HTS_CODE]);
