CREATE TABLE [dbo].[SALES_REP_SHARE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SALESREP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SHARE_SALESREP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SHARE_PERCENT] DECIMAL(6,3) DEFAULT  NULL
)

ALTER TABLE [dbo].[SALES_REP_SHARE] ADD CONSTRAINT [PK_SALES_REP_SHARE] PRIMARY KEY ([SALESREP_ID], [SHARE_SALESREP_ID]);

ALTER TABLE [dbo].[SALES_REP_SHARE] ADD CONSTRAINT [FKEY0256] FOREIGN KEY ([SHARE_SALESREP_ID]) REFERENCES [dbo].[SALES_REP]([ID]);
