CREATE TABLE [dbo].[QUOTE_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [QUOTE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[QUOTE_BINARY] ADD CONSTRAINT [PK_QUOTE_BINARY] PRIMARY KEY ([QUOTE_ID], [TYPE]);

ALTER TABLE [dbo].[QUOTE_BINARY] ADD CONSTRAINT [FKEY0179] FOREIGN KEY ([QUOTE_ID]) REFERENCES [dbo].[QUOTE]([ID]);
