CREATE TABLE [dbo].[LMC_VEXP_HIST_DATA] (
    [USER_ID] VARCHAR(20) DEFAULT  NOT NULL,
    [TBL_NAME] VARCHAR(50) DEFAULT  NOT NULL,
    [COL_NAME] VARCHAR(50) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT  NOT NULL,
    [PRIMARY_KEY] VARCHAR(254) DEFAULT  NULL,
    [ACTION] VARCHAR(15) DEFAULT  NULL,
    [OLD_VALUE] VARCHAR(254) DEFAULT  NULL,
    [NEW_VALUE] VARCHAR(254) DEFAULT  NULL
)
