CREATE TABLE [dbo].[WORK_ORDER_SYNC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EVENT_ID] int DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [EXCEPTION] NCHAR(1) DEFAULT  NOT NULL,
    [SUBSCRIPTIONS] int DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[WORK_ORDER_SYNC] ADD CONSTRAINT [PK_WORK_ORD_SYNC] PRIMARY KEY ([EVENT_ID]);
