CREATE TABLE [dbo].[PALLET] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [BOL_ID] NVARCHAR(20) DEFAULT  NULL,
    [TARE_ID] NVARCHAR(30) DEFAULT  NULL,
    [PACKAGE_TYPE] NVARCHAR(5) DEFAULT  NULL,
    [CARTON_COUNT] int DEFAULT  NULL,
    [QTY_PER_CARTON] DECIMAL(20,8) DEFAULT  NULL,
    [SHIPPING_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [USER_SHIP_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [WEIGHT_UM] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[PALLET] ADD CONSTRAINT [PK_PALLET] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[PALLET] ADD CONSTRAINT [FK_PALLET_BOL] FOREIGN KEY ([BOL_ID]) REFERENCES [dbo].[BOL]([ID]);

ALTER TABLE [dbo].[PALLET] ADD CONSTRAINT [FKEY9565] FOREIGN KEY ([TARE_ID]) REFERENCES [dbo].[TARE]([ID]);
