CREATE TABLE [dbo].[DECISION_PARAMS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PARAM_ID] int DEFAULT  NOT NULL,
    [PTS_INA_ROW_ONE_SI] smallint DEFAULT  NOT NULL,
    [STEADY_UP_OR_DOWN] smallint DEFAULT  NOT NULL,
    [ALTERNATING_UP_AND] smallint DEFAULT  NOT NULL,
    [TWO_SIGMAS_ACTUAL] smallint DEFAULT  NOT NULL,
    [OUT_OF_TWO_SIGMA] smallint DEFAULT  NOT NULL,
    [ONE_SIGMA_ACTUAL] smallint DEFAULT  NOT NULL,
    [OUT_OF_ONE_SIGMA] smallint DEFAULT  NOT NULL,
    [LESS_THAN_1_SIGMA] smallint DEFAULT  NOT NULL,
    [GRTR_THAN_1_SIGMA] smallint DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[DECISION_PARAMS] ADD CONSTRAINT [PK_DECISION_PARAMS] PRIMARY KEY ([PARAM_ID]);
