CREATE TABLE [dbo].[QUOTE_LINE_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [QUOTE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [QUOTE_LINE_NO] smallint DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[QUOTE_LINE_BINARY] ADD CONSTRAINT [PK_QUOTE_LINE_BINARY] PRIMARY KEY ([QUOTE_ID], [QUOTE_LINE_NO], [TYPE]);

ALTER TABLE [dbo].[QUOTE_LINE_BINARY] ADD CONSTRAINT [FKEY0181] FOREIGN KEY ([QUOTE_ID], [QUOTE_LINE_NO]) REFERENCES [dbo].[QUOTE_LINE]([QUOTE_ID], [LINE_NO]);
