CREATE TABLE [dbo].[VR_GRID_CONFIG_COLUMN] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [GRID_CONFIG_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(80) DEFAULT  NOT NULL,
    [IS_VISIBLE] NCHAR(1) DEFAULT ('Y') NOT NULL,
    [SEQ_NO] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[VR_GRID_CONFIG_COLUMN] ADD CONSTRAINT [PK_VR_GRID_CONFIG_COLUMN] PRIMARY KEY ([GRID_CONFIG_ID], [NAME]);

ALTER TABLE [dbo].[VR_GRID_CONFIG_COLUMN] ADD CONSTRAINT [FK_GRID_COL_TO_GRID_CFG] FOREIGN KEY ([GRID_CONFIG_ID]) REFERENCES [dbo].[VR_GRID_CONFIG]([ID]);
