CREATE TABLE [dbo].[DOCUMENT_REF_EAC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROJECT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [EAC_VERSION] NVARCHAR(15) DEFAULT  NOT NULL,
    [DOCUMENT_ID] NVARCHAR(128) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[DOCUMENT_REF_EAC] ADD CONSTRAINT [PK_DOCUMENT_REF_EAC] PRIMARY KEY ([PROJECT_ID], [EAC_VERSION], [DOCUMENT_ID]);
