CREATE TABLE [dbo].[TRACE_DATE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DATE_NAME] NVARCHAR(20) DEFAULT  NOT NULL,
    [TRACE_DAYS] int DEFAULT  NULL,
    [FROM_DATE_NAME] NVARCHAR(20) DEFAULT  NULL,
    [CLASS_ID] NCHAR(1) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[TRACE_DATE] ADD CONSTRAINT [PK_TRACE_DATE] PRIMARY KEY ([PART_ID], [DATE_NAME]);
