CREATE TABLE [dbo].[EQUIP_PM_EXCEPTION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EQUIP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PROFILE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [EXCEPTION_MONTH] int DEFAULT  NULL,
    [FROM_DATE] datetime DEFAULT  NULL,
    [TO_DATE] datetime DEFAULT  NULL
)
