CREATE TABLE [dbo].[DRILLBACK] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(50) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [PROGRAM_NAME] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[DRILLBACK] ADD CONSTRAINT [PK_DRILLBACK] PRIMARY KEY ([ID], [PROGRAM_ID]);
