CREATE TABLE [dbo].[VR_PAYABLE_DET] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VOUCHER_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NULL,
    [PURC_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [PURC_ORDER_LINE_NO] smallint DEFAULT  NULL,
    [RECEIVER_ID] NVARCHAR(15) DEFAULT  NULL,
    [RECEIVER_LINE_NO] smallint DEFAULT  NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NULL
)
