CREATE TABLE [dbo].[APP_CONFIG_USER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] int DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DEFAULT_APP_CONFIG_ID] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[APP_CONFIG_USER] ADD CONSTRAINT [PK_APP_CONFIG_USER] PRIMARY KEY ([PROGRAM_ID], [USER_ID]);

ALTER TABLE [dbo].[APP_CONFIG_USER] ADD CONSTRAINT [FK_APP_CONFIG_USER_TO_APP] FOREIGN KEY ([DEFAULT_APP_CONFIG_ID]) REFERENCES [dbo].[APP_CONFIG]([ID]);
