CREATE TABLE [dbo].[REQUIREMENT_SCHED] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SCHEDULE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [SEQUENCE_NO] smallint DEFAULT  NOT NULL,
    [PIECE_NO] smallint DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [REQUIRED_DATE] datetime DEFAULT  NULL,
    [PROBLEM_CODE] int DEFAULT  NULL,
    [DUE_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[REQUIREMENT_SCHED] ADD CONSTRAINT [PK_REQUIREMENT_SCHED] PRIMARY KEY ([SCHEDULE_ID], [WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [SEQUENCE_NO], [PIECE_NO]);

ALTER TABLE [dbo].[REQUIREMENT_SCHED] ADD CONSTRAINT [FKEY0106] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);

ALTER TABLE [dbo].[REQUIREMENT_SCHED] ADD CONSTRAINT [FKEY0187] FOREIGN KEY ([SCHEDULE_ID]) REFERENCES [dbo].[SCHEDULE]([ID]);

ALTER TABLE [dbo].[REQUIREMENT_SCHED] ADD CONSTRAINT [FKEY9601] FOREIGN KEY ([SCHEDULE_ID], [WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID]) REFERENCES [dbo].[WORK_ORDER_SCHED]([SCHEDULE_ID], [WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID]);
