CREATE TABLE [dbo].[PROJECT_BATCH_LINK] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SOURCE_BATCH_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PROJECT_BATCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [PROJ_BURD_BATCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [COMM_BURD_BATCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PROJECT_BATCH_LINK] ADD CONSTRAINT [PK_PROJECT_BATCH_LINK] PRIMARY KEY ([SITE_ID], [SOURCE_BATCH_ID]);
