CREATE TABLE [dbo].[SHIP_VIA] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(40) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[SHIP_VIA] ADD CONSTRAINT [PK_SHIP_VIA] PRIMARY KEY ([CODE]);
