CREATE TABLE [dbo].[LMC_MRP_SOFT_ALLOC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] VARCHAR(50) DEFAULT  NOT NULL,
    [DMD_SOURCE] VARCHAR(3) DEFAULT  NOT NULL,
    [DMD_DOC] VARCHAR(50) DEFAULT  NOT NULL,
    [SUP_SOURCE] VARCHAR(3) DEFAULT  NOT NULL,
    [SUP_DOC] VARCHAR(50) DEFAULT  NOT NULL,
    [QTY] DECIMAL(14,4) DEFAULT  NOT NULL,
    [GEN_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL
)
