CREATE TABLE [dbo].[RMA_LINE_DSL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RMA_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RMA_LINE_NO] smallint DEFAULT  NOT NULL,
    [DSL_ID] int DEFAULT  NOT NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[RMA_LINE_DSL] ADD CONSTRAINT [PK_RMA_LINE_DSL] PRIMARY KEY ([RMA_ID], [RMA_LINE_NO], [DSL_ID]);

ALTER TABLE [dbo].[RMA_LINE_DSL] ADD CONSTRAINT [FK_RMA_LINE_DSL_RMA_LINE] FOREIGN KEY ([RMA_ID], [RMA_LINE_NO]) REFERENCES [dbo].[RMA_LINE]([RMA_ID], [LINE_NO]);
