CREATE TABLE [dbo].[PART_WHS_REPLENISH] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BEGIN_DATE] datetime DEFAULT  NOT NULL,
    [END_DATE] datetime DEFAULT  NOT NULL,
    [REPLENISH_LEVEL] DECIMAL(20,8) DEFAULT  NOT NULL,
    [IS_RECURRING] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[PART_WHS_REPLENISH] ADD CONSTRAINT [PK_PART_WHS_REPLENISH] PRIMARY KEY ([PART_ID], [WAREHOUSE_ID], [BEGIN_DATE], [END_DATE]);
