CREATE TABLE [dbo].[NOTIFICATION_EMPLOYEE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [EMPLOYEE_ID] NVARCHAR(20) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[NOTIFICATION_EMPLOYEE] ADD CONSTRAINT [PK_NOTIFICATION_EMPLOYEE] PRIMARY KEY ([PROGRAM_ID], [ID], [EMPLOYEE_ID]);
