CREATE TABLE [dbo].[ECN_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ECN_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[ECN_BINARY] ADD CONSTRAINT [PK_ECN_BINARY] PRIMARY KEY ([ECN_ID], [TYPE]);
