CREATE TABLE [dbo].[RMA_LINE_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RMA_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RMA_LINE_NO] smallint DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[RMA_LINE_BINARY] ADD CONSTRAINT [PK_RMA_LINE_BINARY] PRIMARY KEY ([RMA_ID], [RMA_LINE_NO], [TYPE]);

ALTER TABLE [dbo].[RMA_LINE_BINARY] ADD CONSTRAINT [FKEY9378] FOREIGN KEY ([RMA_ID], [RMA_LINE_NO]) REFERENCES [dbo].[RMA_LINE]([RMA_ID], [LINE_NO]);
