CREATE TABLE [dbo].[HONORIFIC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[HONORIFIC] ADD CONSTRAINT [PK_HONORIFIC] PRIMARY KEY ([NAME]);
