CREATE TABLE [dbo].[VENDOR_CALENDAR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SERVICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [START_DATE] datetime DEFAULT  NOT NULL,
    [END_DATE] datetime DEFAULT  NOT NULL,
    [DAY_PERCENT] smallint DEFAULT  NOT NULL
)
