CREATE TABLE [dbo].[ECN_REQ_PART_ALT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ECN_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] int DEFAULT  NOT NULL,
    [ECN_ENTRY_NO] smallint DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [OPERATION_SEQ_NO] smallint DEFAULT  NOT NULL,
    [PIECE_NO] smallint DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [RANK] smallint DEFAULT  NULL
)

ALTER TABLE [dbo].[ECN_REQ_PART_ALT] ADD CONSTRAINT [PK_ECN_REQ_PART_ALT] PRIMARY KEY ([ECN_ID], [LINE_NO], [ECN_ENTRY_NO], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO], [PIECE_NO], [PART_ID]);

ALTER TABLE [dbo].[ECN_REQ_PART_ALT] ADD CONSTRAINT [FK_ECN_REQ_PART_ALT] FOREIGN KEY ([ECN_ID], [LINE_NO], [ECN_ENTRY_NO]) REFERENCES [dbo].[ECN_DETAIL]([ECN_ID], [LINE_NO], [ENTRY_NO]);
