CREATE TABLE [dbo].[TARIFF] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL
)

ALTER TABLE [dbo].[TARIFF] ADD CONSTRAINT [PK_TARIFF] PRIMARY KEY ([CODE]);
