CREATE TABLE [dbo].[PURC_REQ_LN_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PURC_REQ_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PURC_REQ_LINE_NO] smallint DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PURC_REQ_LN_BINARY] ADD CONSTRAINT [PK_PURC_REQ_LN_BINARY] PRIMARY KEY ([PURC_REQ_ID], [PURC_REQ_LINE_NO], [TYPE]);

ALTER TABLE [dbo].[PURC_REQ_LN_BINARY] ADD CONSTRAINT [FK_PURC_REQ_LN_BINARY_00] FOREIGN KEY ([PURC_REQ_ID], [PURC_REQ_LINE_NO]) REFERENCES [dbo].[PURC_REQ_LINE]([PURC_REQ_ID], [LINE_NO]);
