CREATE TABLE [dbo].[LABEL_TYPE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(30) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[LABEL_TYPE] ADD CONSTRAINT [PK_LABEL_TYPE] PRIMARY KEY ([ID]);
