CREATE TABLE [dbo].[UNP_MNT_URGENCY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL
)

ALTER TABLE [dbo].[UNP_MNT_URGENCY] ADD CONSTRAINT [PK_UNP_MNT_URGE] PRIMARY KEY ([ID]);
