CREATE TABLE [dbo].[EXPIRED_PWD] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CYCLE_NO] int DEFAULT  NOT NULL,
    [USER_PWD] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[EXPIRED_PWD] ADD CONSTRAINT [PK_EXPIRED_PWD] PRIMARY KEY ([USER_ID], [CYCLE_NO]);
