CREATE TABLE [dbo].[EQUIP_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EQUIP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[EQUIP_BINARY] ADD CONSTRAINT [PK_EQUIP_BINARY] PRIMARY KEY ([EQUIP_ID], [TYPE]);
