CREATE TABLE [dbo].[VR_DATA_SOURCE_COLUMN] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DATA_SOURCE_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(80) DEFAULT  NOT NULL,
    [TABLE_ALIAS] NVARCHAR(30) DEFAULT  NULL,
    [LABEL] NVARCHAR(80) DEFAULT  NULL,
    [SQL_REF] NVARCHAR(2000) DEFAULT  NULL,
    [DATA_TYPE] NVARCHAR(20) DEFAULT  NOT NULL,
    [DATA_FORMAT] NVARCHAR(80) DEFAULT  NULL,
    [BACKGROUND_COLOR] NVARCHAR(11) DEFAULT  NULL,
    [TEXT_COLOR] NVARCHAR(11) DEFAULT  NULL,
    [CELL_BKGD_COLOR] NVARCHAR(100) DEFAULT  NULL,
    [CELL_TEXT_COLOR] NVARCHAR(100) DEFAULT  NULL,
    [CLASS_NAME] NVARCHAR(50) DEFAULT  NULL,
    [FILTER_TYPE] NVARCHAR(15) DEFAULT ('NONE') NOT NULL,
    [FILTER_SOURCE_TYPE] NVARCHAR(15) DEFAULT  NULL,
    [FILTER_SOURCE_TEXT] NVARCHAR(2000) DEFAULT  NULL,
    [SEQ_NO] int DEFAULT  NOT NULL,
    [IS_VISIBLE] NCHAR(1) DEFAULT ('Y') NOT NULL
)

ALTER TABLE [dbo].[VR_DATA_SOURCE_COLUMN] ADD CONSTRAINT [PK_VR_DATA_SOURCE_COLUMN] PRIMARY KEY ([DATA_SOURCE_ID], [NAME]);

ALTER TABLE [dbo].[VR_DATA_SOURCE_COLUMN] ADD CONSTRAINT [FK_DATA_SRC_COL_TO_DATA_SRC] FOREIGN KEY ([DATA_SOURCE_ID]) REFERENCES [dbo].[VR_DATA_SOURCE]([ID]);
