CREATE TABLE [dbo].[RESOURCE_SETUP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SETUP_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[RESOURCE_SETUP] ADD CONSTRAINT [PK_RESOURCE_SETUP] PRIMARY KEY ([RESOURCE_ID], [SETUP_ID]);
