CREATE TABLE [dbo].[WIP_BALANCE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [FLAG] NCHAR(1) DEFAULT  NOT NULL,
    [MATERIAL_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [LABOR_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [BURDEN_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [SERVICE_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [MAT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [LAB_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [BUR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [SER_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[WIP_BALANCE] ADD CONSTRAINT [PK_WIP_BALANCE] PRIMARY KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [POSTING_DATE], [CURRENCY_ID]);

ALTER TABLE [dbo].[WIP_BALANCE] ADD CONSTRAINT [FK_WIPBAL_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[WIP_BALANCE] ADD CONSTRAINT [FKEY9115] FOREIGN KEY ([MAT_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[WIP_BALANCE] ADD CONSTRAINT [FKEY9116] FOREIGN KEY ([LAB_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[WIP_BALANCE] ADD CONSTRAINT [FKEY9117] FOREIGN KEY ([BUR_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[WIP_BALANCE] ADD CONSTRAINT [FKEY9118] FOREIGN KEY ([SER_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[WIP_BALANCE] ADD CONSTRAINT [FKEY9416] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
