CREATE TABLE [dbo].[RFQ_LINE_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RFQ_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RFQ_LINE_NO] smallint DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[RFQ_LINE_BINARY] ADD CONSTRAINT [PK_RFQ_LINE_BINARY] PRIMARY KEY ([RFQ_ID], [RFQ_LINE_NO], [TYPE]);
