CREATE TABLE [dbo].[EC_HISTORY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EC_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[EC_HISTORY] ADD CONSTRAINT [PK_EC_HISTORY] PRIMARY KEY ([EC_ID], [TYPE]);

ALTER TABLE [dbo].[EC_HISTORY] ADD CONSTRAINT [FK_EC_HISTORY] FOREIGN KEY ([EC_ID]) REFERENCES [dbo].[EC]([ID]);
