CREATE TABLE [dbo].[FINANCIAL_CALENDAR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PERIOD_TYPE] NCHAR(1) DEFAULT ('M') NOT NULL,
    [PERIODS_PER_YEAR] smallint DEFAULT ((12)) NOT NULL,
    [FISCAL_YEAR_END_MONTH] DECIMAL(2,0) DEFAULT  NULL,
    [FISCAL_YEAR_END_DAY] DECIMAL(2,0) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [ACTIVE_FLAG] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[FINANCIAL_CALENDAR] ADD CONSTRAINT [PK_FIN_CALENDAR] PRIMARY KEY ([ID]);
