CREATE TABLE [dbo].[REGION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(2) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL
)

ALTER TABLE [dbo].[REGION] ADD CONSTRAINT [PK_REGION] PRIMARY KEY ([ID]);
