CREATE TABLE [dbo].[PROJ_DIST_DETAIL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROJECT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SOURCE_TYPE] NVARCHAR(20) DEFAULT  NOT NULL,
    [SOURCE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SOURCE_TRANS_ID] int DEFAULT ((0)) NOT NULL,
    [SOURCE_LINE_NO] smallint DEFAULT ((0)) NOT NULL,
    [DIST_NO] smallint DEFAULT  NOT NULL,
    [PROJECT_SUMMARY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SOURCE_LOT_ID] NVARCHAR(3) DEFAULT  NULL,
    [SOURCE_SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [SOURCE_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [ACT_MATERIAL_COST] DECIMAL(23,8) DEFAULT  NULL,
    [ACT_LABOR_COST] DECIMAL(23,8) DEFAULT  NULL,
    [ACT_BURDEN_COST] DECIMAL(23,8) DEFAULT  NULL,
    [ACT_SERVICE_COST] DECIMAL(23,8) DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [REFERENCE] NVARCHAR(50) DEFAULT  NULL,
    [ACT_HOURS] DECIMAL(15,2) DEFAULT  NULL
)

ALTER TABLE [dbo].[PROJ_DIST_DETAIL] ADD CONSTRAINT [PK_PROJ_DIST_DETAIL] PRIMARY KEY ([PROJECT_ID], [SOURCE_TYPE], [SOURCE_ID], [SOURCE_TRANS_ID], [SOURCE_LINE_NO], [DIST_NO], [PROJECT_SUMMARY_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[PROJ_DIST_DETAIL] ADD CONSTRAINT [FK_PROJ_DIST_DETAIL_01] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
