CREATE TABLE [dbo].[RATE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [USE_FOR_ACTUALS] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[RATE] ADD CONSTRAINT [PK_RATE] PRIMARY KEY ([ID]);
