CREATE TABLE [dbo].[LMC_MRP_LOG] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PASS] int DEFAULT  NOT NULL,
    [PART_ID] VARCHAR(40) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] VARCHAR(15) DEFAULT  NOT NULL,
    [SITE_ID] VARCHAR(15) DEFAULT  NOT NULL,
    [COMMENT] VARCHAR(MAX) DEFAULT  NULL,
    [PROC_START] datetime DEFAULT (getdate()) NOT NULL
)
