CREATE TABLE [dbo].[ECN_OPER_RESOURCE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ECN_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] int DEFAULT  NOT NULL,
    [ECN_ENTRY_NO] smallint DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [SEQUENCE_NO] smallint DEFAULT  NOT NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NULL,
    [PERCENT_DURATION] smallint DEFAULT  NULL,
    [JUSTIFICATION] NCHAR(1) DEFAULT  NULL,
    [NUM_MEM_TO_SCHED] smallint DEFAULT  NULL,
    [SCHED_EQUAL_CAP] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[ECN_OPER_RESOURCE] ADD CONSTRAINT [PK_ECN_OPER_RESOURCE] PRIMARY KEY ([ECN_ID], [LINE_NO], [ECN_ENTRY_NO], [WORKORDER_SUB_ID], [SEQUENCE_NO], [RESOURCE_ID]);

ALTER TABLE [dbo].[ECN_OPER_RESOURCE] ADD CONSTRAINT [FK_ECN_OPER_RESOURCE] FOREIGN KEY ([ECN_ID], [LINE_NO], [ECN_ENTRY_NO]) REFERENCES [dbo].[ECN_DETAIL]([ECN_ID], [LINE_NO], [ENTRY_NO]);
