CREATE TABLE [dbo].[MFG_WIN_EXCEPTION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(30) DEFAULT  NOT NULL,
    [OUTLINE_OBJ_TYPE] int DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT  NULL,
    [PRIORITY] smallint DEFAULT  NULL,
    [EXPRESSION_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [EXPRESSION] NVARCHAR(254) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[MFG_WIN_EXCEPTION] ADD CONSTRAINT [PK_MFG_WIN_EXCEPTION] PRIMARY KEY ([NAME], [OUTLINE_OBJ_TYPE], [USER_ID]);
