CREATE TABLE [dbo].[PHYS_COUNT_LOC_ADJ] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PHYS_COUNT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LOCATION_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [LOCATION_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [ADJUST_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[PHYS_COUNT_LOC_ADJ] ADD CONSTRAINT [PK_PHYS_COUNT_LOC_ADJ] PRIMARY KEY ([PHYS_COUNT_ID], [WAREHOUSE_ID], [LOCATION_ID], [PART_ID]);

ALTER TABLE [dbo].[PHYS_COUNT_LOC_ADJ] ADD CONSTRAINT [FKEY9622] FOREIGN KEY ([PHYS_COUNT_ID]) REFERENCES [dbo].[PHYSICAL_COUNT]([ID]);
