CREATE TABLE [dbo].[WORK_ORDER_SCHED] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SCHEDULE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [START_DATE] datetime DEFAULT  NULL,
    [FINISH_DATE] datetime DEFAULT  NULL,
    [SCHEDULE_TIME] DECIMAL(5,2) DEFAULT  NULL,
    [PASS_COUNT] int DEFAULT  NULL,
    [SCHEDULE_RANK] int DEFAULT  NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL,
    [CCR_COUNT] int DEFAULT  NULL,
    [PROBLEM_CODE] int DEFAULT  NULL
)

ALTER TABLE [dbo].[WORK_ORDER_SCHED] ADD CONSTRAINT [PK_WORK_ORDER_SCHED] PRIMARY KEY ([SCHEDULE_ID], [WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID]);

ALTER TABLE [dbo].[WORK_ORDER_SCHED] ADD CONSTRAINT [FKEY0105] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);

ALTER TABLE [dbo].[WORK_ORDER_SCHED] ADD CONSTRAINT [FKEY9599] FOREIGN KEY ([SCHEDULE_ID]) REFERENCES [dbo].[SCHEDULE]([ID]);
