CREATE TABLE [dbo].[VR_ANALYTIC_CONFIG_PROP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ANALYTIC_CONFIG_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [PROPERTY_NAME] NVARCHAR(80) DEFAULT  NOT NULL,
    [PROPERTY_VALUE] NVARCHAR(250) DEFAULT  NOT NULL,
    [SEQUENCE_NO] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[VR_ANALYTIC_CONFIG_PROP] ADD CONSTRAINT [PK_VR_ANALYTIC_CONFIG_PROP] PRIMARY KEY ([ANALYTIC_CONFIG_ID], [PROPERTY_NAME]);

ALTER TABLE [dbo].[VR_ANALYTIC_CONFIG_PROP] ADD CONSTRAINT [FK_ANAL_PROP_TO_ANAL_CFG] FOREIGN KEY ([ANALYTIC_CONFIG_ID]) REFERENCES [dbo].[VR_ANALYTIC_CONFIG]([ID]);
