CREATE TABLE [dbo].[VEND_CONTACT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CONTACT_NO] smallint DEFAULT  NULL,
    [CONTACT_ID] NVARCHAR(25) DEFAULT  NOT NULL,
    [PRIMARY_CONTACT] NCHAR(1) DEFAULT ('N') NOT NULL
)

ALTER TABLE [dbo].[VEND_CONTACT] ADD CONSTRAINT [PK_VEND_CONTACT] PRIMARY KEY ([VENDOR_ID], [CONTACT_ID]);

ALTER TABLE [dbo].[VEND_CONTACT] ADD CONSTRAINT [FK_VEND_CONT_CONT] FOREIGN KEY ([CONTACT_ID]) REFERENCES [dbo].[CONTACT]([ID]);

ALTER TABLE [dbo].[VEND_CONTACT] ADD CONSTRAINT [FK_VEND_CONT_VEND] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);
