CREATE TABLE [dbo].[PART_REPLENISHMENT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [BEGIN_DATE] datetime DEFAULT  NOT NULL,
    [END_DATE] datetime DEFAULT  NOT NULL,
    [REPLENISH_LEVEL] DECIMAL(20,8) DEFAULT  NOT NULL,
    [IS_RECURRING] NCHAR(1) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PART_REPLENISHMENT] ADD CONSTRAINT [PKPART_REPLENISHMENT] PRIMARY KEY ([SITE_ID], [PART_ID], [BEGIN_DATE], [END_DATE]);
