CREATE TABLE [dbo].[WBS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(30) DEFAULT  NOT NULL,
    [PROJECT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT  NULL,
    [BILLABLE] NCHAR(1) DEFAULT  NULL,
    [CLIN] NVARCHAR(15) DEFAULT  NULL,
    [CWBS] NVARCHAR(30) DEFAULT  NULL,
    [CDRL] NVARCHAR(20) DEFAULT  NULL,
    [DEF_DEPARTMENT_ID] NVARCHAR(15) DEFAULT  NULL,
    [TRANSFER_COSTS] NCHAR(1) DEFAULT  NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[WBS] ADD CONSTRAINT [PK_WBS] PRIMARY KEY ([CODE], [PROJECT_ID]);

ALTER TABLE [dbo].[WBS] ADD CONSTRAINT [FK_WBS_DEPT_00] FOREIGN KEY ([DEF_DEPARTMENT_ID]) REFERENCES [dbo].[DEPARTMENT]([ID]);
