CREATE TABLE [dbo].[SCREEN_SIZE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SECTION] NVARCHAR(100) DEFAULT  NOT NULL,
    [ENTRY] NVARCHAR(100) DEFAULT  NOT NULL,
    [VALUE] NVARCHAR(100) DEFAULT  NULL,
    [MODIFY_DATE] datetime DEFAULT  NULL
)
