CREATE TABLE [dbo].[PROJECT_ETC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROJECT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ETC_VERSION_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [VERSION_DATE] datetime DEFAULT  NULL,
    [CURRENT_FLAG] NCHAR(1) DEFAULT  NULL,
    [LOCKED_FLAG] NCHAR(1) DEFAULT  NULL,
    [ACCOUNT_YEAR] DECIMAL(4,0) DEFAULT  NULL,
    [ACCOUNT_PERIOD] DECIMAL(2,0) DEFAULT  NULL
)

ALTER TABLE [dbo].[PROJECT_ETC] ADD CONSTRAINT [PK_PROJECT_ETC] PRIMARY KEY ([PROJECT_ID], [ETC_VERSION_ID]);
