CREATE TABLE [dbo].[SERVICE_DISP_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DISPATCH_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [PURC_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [PURC_ORDER_LINE_NO] smallint DEFAULT  NULL,
    [SERVICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SERVICE_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [USER_DISPATCH_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [DISPATCH_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [RECEIVED_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [ACT_FREIGHT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [SHIPPING_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [WEIGHT_UM] NVARCHAR(15) DEFAULT  NULL,
    [SHIPPING_UM] NVARCHAR(15) DEFAULT  NULL,
    [PROMISE_DATE] datetime DEFAULT  NULL,
    [DESIRED_RECV_DATE] datetime DEFAULT  NULL,
    [CALC_RECV_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [VAT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [CARTON_COUNT] smallint DEFAULT  NULL,
    [PACKAGE_TYPE] NVARCHAR(5) DEFAULT  NULL,
    [UNIT_COST] DECIMAL(22,8) DEFAULT  NULL,
    [DISPATCH_ADDR_ID] NVARCHAR(20) DEFAULT  NULL,
    [NET_SHIP_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [TARE_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [PALLET_COUNT] DECIMAL(20,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[SERVICE_DISP_LINE] ADD CONSTRAINT [PK_SERVICE_DISP_LINE] PRIMARY KEY ([DISPATCH_ID], [LINE_NO]);

ALTER TABLE [dbo].[SERVICE_DISP_LINE] ADD CONSTRAINT [FKEY9365] FOREIGN KEY ([DISPATCH_ID]) REFERENCES [dbo].[SERVICE_DISPATCH]([ID]);
