CREATE TABLE [dbo].[PART_ALIAS_TYPE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL
)

ALTER TABLE [dbo].[PART_ALIAS_TYPE] ADD CONSTRAINT [PK_PART_ALIAS_TYPE] PRIMARY KEY ([ID]);
