CREATE TABLE [dbo].[SERVICE_RCPT_CURR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TRANSACTION_ID] int DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ACT_MATERIAL_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [ACT_LABOR_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [ACT_BURDEN_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [ACT_SERVICE_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[SERVICE_RCPT_CURR] ADD CONSTRAINT [PK_SERVICE_RCPT_CURR] PRIMARY KEY ([TRANSACTION_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[SERVICE_RCPT_CURR] ADD CONSTRAINT [FKEY9446] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
