CREATE TABLE [dbo].[PURC_RFQ_REQ] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RFQ_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RFQ_LINE_NO] smallint DEFAULT  NOT NULL,
    [PURC_REQ_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PURC_REQ_LINE_NO] smallint DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PURC_RFQ_REQ] ADD CONSTRAINT [PK_PURC_RFQ_REQ] PRIMARY KEY ([RFQ_ID], [RFQ_LINE_NO], [PURC_REQ_ID], [PURC_REQ_LINE_NO]);
