CREATE TABLE [dbo].[PAYABLE_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VOUCHER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PAYABLE_BINARY] ADD CONSTRAINT [PK_PAYABLE_BINARY] PRIMARY KEY ([VOUCHER_ID], [TYPE]);
