CREATE TABLE [dbo].[TEST_STEP_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TEST_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [STEP_NO] int DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[TEST_STEP_BINARY] ADD CONSTRAINT [PK_TEST_STEP_BINARY] PRIMARY KEY ([TEST_ID], [STEP_NO], [TYPE]);

ALTER TABLE [dbo].[TEST_STEP_BINARY] ADD CONSTRAINT [FKEY0246] FOREIGN KEY ([TEST_ID], [STEP_NO]) REFERENCES [dbo].[TEST_STEP]([TEST_ID], [STEP_NO]);
