CREATE TABLE [dbo].[NATURE_OF_TRANS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] int DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL
)

ALTER TABLE [dbo].[NATURE_OF_TRANS] ADD CONSTRAINT [PK_NATURE_OF_TRANS] PRIMARY KEY ([CODE]);
