CREATE TABLE [dbo].[TRACE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [NUMBERING_ID] NVARCHAR(30) DEFAULT  NULL,
    [OUT_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [IN_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [REPORTED_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [ASSIGNED_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [APROPERTY_1] NVARCHAR(80) DEFAULT  NULL,
    [APROPERTY_2] NVARCHAR(80) DEFAULT  NULL,
    [APROPERTY_3] NVARCHAR(80) DEFAULT  NULL,
    [APROPERTY_4] NVARCHAR(80) DEFAULT  NULL,
    [APROPERTY_5] NVARCHAR(80) DEFAULT  NULL,
    [NPROPERTY_1] DECIMAL(15,6) DEFAULT  NULL,
    [NPROPERTY_2] DECIMAL(15,6) DEFAULT  NULL,
    [NPROPERTY_3] DECIMAL(15,6) DEFAULT  NULL,
    [NPROPERTY_4] DECIMAL(15,6) DEFAULT  NULL,
    [NPROPERTY_5] DECIMAL(15,6) DEFAULT  NULL,
    [COMMENTS] NVARCHAR(250) DEFAULT  NULL,
    [EXPIRATION_DATE] datetime DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [DISP_IN_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [DISP_OUT_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [UNAVAILABLE_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [OWNER_ID] NVARCHAR(15) DEFAULT  NULL,
    [LOT_ID] NVARCHAR(30) DEFAULT  NULL,
    [SERIAL_ID] NVARCHAR(30) DEFAULT  NULL,
    [COMMITTED_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [PRODUCTION_DATE] datetime DEFAULT  NULL,
    [RECEIVE_BY_DATE] datetime DEFAULT  NULL,
    [AVAILABLE_DATE] datetime DEFAULT  NULL,
    [SHIP_BY_DATE] datetime DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[TRACE] ADD CONSTRAINT [PK_TRACE] PRIMARY KEY ([PART_ID], [ID]);

ALTER TABLE [dbo].[TRACE] ADD CONSTRAINT [FKEY0108] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);
