CREATE TABLE [dbo].[SOA_CODE_MAP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [LIST_ID] NVARCHAR(100) DEFAULT  NOT NULL,
    [AGENCY_ID] NVARCHAR(10) DEFAULT  NOT NULL,
    [SOA_CODE] NVARCHAR(100) DEFAULT  NOT NULL,
    [VE_CODE] NVARCHAR(50) DEFAULT  NOT NULL,
    [VE_CODE_DESC] NVARCHAR(250) DEFAULT  NULL
)

ALTER TABLE [dbo].[SOA_CODE_MAP] ADD CONSTRAINT [FK_SOA_CODE_LIST] FOREIGN KEY ([LIST_ID], [AGENCY_ID], [SOA_CODE]) REFERENCES [dbo].[SOA_CODE_LIST]([LIST_ID], [AGENCY_ID], [CODE]);
