CREATE TABLE [dbo].[VENDOR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_1] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_2] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_3] NVARCHAR(50) DEFAULT  NULL,
    [CITY] NVARCHAR(30) DEFAULT  NULL,
    [STATE] NVARCHAR(10) DEFAULT  NULL,
    [ZIPCODE] NVARCHAR(10) DEFAULT  NULL,
    [COUNTRY] NVARCHAR(50) DEFAULT  NULL,
    [VENDOR_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_FIRST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_LAST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_INITIAL] NVARCHAR(2) DEFAULT  NULL,
    [CONTACT_POSITION] NVARCHAR(50) DEFAULT  NULL,
    [CONTACT_HONORIFIC] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_SALUTATION] NVARCHAR(60) DEFAULT  NULL,
    [CONTACT_PHONE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_FAX] NVARCHAR(20) DEFAULT  NULL,
    [REMIT_TO_NAME] NVARCHAR(50) DEFAULT  NULL,
    [REMIT_TO_ADDR_1] NVARCHAR(50) DEFAULT  NULL,
    [REMIT_TO_ADDR_2] NVARCHAR(50) DEFAULT  NULL,
    [REMIT_TO_ADDR_3] NVARCHAR(50) DEFAULT  NULL,
    [REMIT_TO_CITY] NVARCHAR(30) DEFAULT  NULL,
    [REMIT_TO_STATE] NVARCHAR(10) DEFAULT  NULL,
    [REMIT_TO_ZIPCODE] NVARCHAR(10) DEFAULT  NULL,
    [REMIT_TO_COUNTRY] NVARCHAR(50) DEFAULT  NULL,
    [REMIT_TO_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [FREE_ON_BOARD] NVARCHAR(25) DEFAULT  NULL,
    [SHIP_VIA] NVARCHAR(40) DEFAULT  NULL,
    [BUYER] NVARCHAR(20) DEFAULT  NULL,
    [REPORT_1099_MISC] NCHAR(1) DEFAULT ('') NOT NULL,
    [TERMS_NET_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [TERMS_NET_DAYS] smallint DEFAULT  NULL,
    [TERMS_NET_DATE] datetime DEFAULT  NULL,
    [TERMS_DISC_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [TERMS_DISC_DAYS] smallint DEFAULT  NULL,
    [TERMS_DISC_DATE] datetime DEFAULT  NULL,
    [TERMS_DISC_PERCENT] DECIMAL(5,3) DEFAULT  NULL,
    [TERMS_DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [TAX_ID_NUMBER] NVARCHAR(25) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL,
    [DEF_EXP_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [DEF_SLS_TAX_GRP_ID] NVARCHAR(30) DEFAULT  NULL,
    [MATCH_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [MATCH_HIGH_PCT] DECIMAL(6,3) DEFAULT  NULL,
    [MATCH_LOW_PCT] DECIMAL(6,3) DEFAULT  NULL,
    [LAST_ORDER_DATE] datetime DEFAULT  NULL,
    [OPEN_DATE] datetime DEFAULT  NULL,
    [MODIFY_DATE] datetime DEFAULT  NULL,
    [USER_1] NVARCHAR(80) DEFAULT  NULL,
    [USER_2] NVARCHAR(80) DEFAULT  NULL,
    [USER_3] NVARCHAR(80) DEFAULT  NULL,
    [USER_4] NVARCHAR(80) DEFAULT  NULL,
    [USER_5] NVARCHAR(80) DEFAULT  NULL,
    [USER_6] NVARCHAR(80) DEFAULT  NULL,
    [USER_7] NVARCHAR(80) DEFAULT  NULL,
    [USER_8] NVARCHAR(80) DEFAULT  NULL,
    [USER_9] NVARCHAR(80) DEFAULT  NULL,
    [USER_10] NVARCHAR(80) DEFAULT  NULL,
    [DEF_PAYB_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [UDF_LAYOUT_ID] NVARCHAR(15) DEFAULT  NULL,
    [ARRIVAL_CODE] NVARCHAR(25) DEFAULT  NULL,
    [TRANS_CODE] NVARCHAR(25) DEFAULT  NULL,
    [COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [NATURE_OF_TRANS] int DEFAULT  NULL,
    [MODE_OF_TRANSPORT] int DEFAULT  NULL,
    [SIRET_NUMBER] DECIMAL(14,0) DEFAULT  NULL,
    [VAT_REGISTRATION] NVARCHAR(25) DEFAULT  NULL,
    [VAT_BOOK_CODE_I] NVARCHAR(5) DEFAULT  NULL,
    [VAT_BOOK_CODE_M] NVARCHAR(5) DEFAULT  NULL,
    [VAT_EXEMPT] NCHAR(1) DEFAULT  NULL,
    [WITHHOLDING_CODE] NVARCHAR(15) DEFAULT  NULL,
    [VEND_BANK_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [PAYEE_REF_CODE] NVARCHAR(10) DEFAULT  NULL,
    [PAYMENT_METHOD] NCHAR(1) DEFAULT ('') NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NULL,
    [SOCIAL_SECURITY_NO] NVARCHAR(15) DEFAULT  NULL,
    [DATE_OF_BIRTH] datetime DEFAULT  NULL,
    [SEX] NCHAR(1) DEFAULT  NULL,
    [PLACE_OF_BIRTH] NVARCHAR(30) DEFAULT  NULL,
    [STATE_OF_BIRTH] NVARCHAR(10) DEFAULT  NULL,
    [PRIORITY] smallint DEFAULT  NULL,
    [DEF_EXP_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [QA_PERCENTAGE] DECIMAL(5,2) DEFAULT  NULL,
    [PREF_ORDER_MEDIUM] NVARCHAR(15) DEFAULT  NULL,
    [DEF_CARRIER_ID] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_MOBILE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_EMAIL] NVARCHAR(100) DEFAULT  NULL,
    [DEF_TRANS_CURRENCY] NVARCHAR(15) DEFAULT  NULL,
    [DEF_LBL_FORMAT_ID] NVARCHAR(30) DEFAULT  NULL,
    [VAT_DISCOUNTED] NVARCHAR(1) DEFAULT ('') NOT NULL,
    [VAT_ALWAYS_DISC] NVARCHAR(1) DEFAULT ('') NOT NULL,
    [VAT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [VAT_OVERRIDE_SEQ] NVARCHAR(1) DEFAULT ('') NOT NULL,
    [RETURN_TRANS] int DEFAULT  NULL,
    [WEB_URL] NVARCHAR(255) DEFAULT  NULL,
    [SHIPTO_ID] NVARCHAR(20) DEFAULT  NULL,
    [DISPATCH_ADDR_ID] NVARCHAR(20) DEFAULT  NULL,
    [DISP_PALLET_REQ] NCHAR(1) DEFAULT  NULL,
    [ACTIVE_FLAG] NCHAR(1) DEFAULT  NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [DEF_TERMS_ID] NVARCHAR(15) DEFAULT  NULL,
    [VENDOR_GROUP_ID] NVARCHAR(15) DEFAULT  NULL,
    [INTERNAL_VENDOR] NCHAR(1) DEFAULT  NULL,
    [PREVENT_EDIT_PO_RECEIPT] NCHAR(1) DEFAULT  NULL,
    [CONTACT_PHONE_EXT] NVARCHAR(10) DEFAULT  NULL,
    [EMAIL_VEND_ON_NEW_ORDER] NCHAR(1) DEFAULT ('N') NOT NULL,
    [EMAIL_VEND_ON_CHG_ORDER] NCHAR(1) DEFAULT ('N') NOT NULL,
    [EMAIL_VEND_ON_PO_RECEIPT] NCHAR(1) DEFAULT ('N') NOT NULL,
    [EMAIL_EMPL_ON_NEW_ORDER] NCHAR(1) DEFAULT ('N') NOT NULL,
    [EMAIL_EMPL_ON_CHG_ORDER] NCHAR(1) DEFAULT ('N') NOT NULL,
    [EMAIL_EMPL_ON_PO_RECEIPT] NCHAR(1) DEFAULT ('N') NOT NULL,
    [EMAIL_EMPL_ON_INV_PAID] NCHAR(1) DEFAULT ('N') NOT NULL,
    [CREATED_BY] NVARCHAR(20) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [MODIFIED_BY] NVARCHAR(20) DEFAULT  NULL,
    [TERMS_DISC_BASIS] NVARCHAR(32) DEFAULT  NULL
)

ALTER TABLE [dbo].[VENDOR] ADD CONSTRAINT [PK_VENDOR] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[VENDOR] ADD CONSTRAINT [FK_VEND_GROUP_ID] FOREIGN KEY ([VENDOR_GROUP_ID]) REFERENCES [dbo].[VENDOR_GROUP]([ID]);

ALTER TABLE [dbo].[VENDOR] ADD CONSTRAINT [FK_VENDOR_CNTRY] FOREIGN KEY ([COUNTRY_ID]) REFERENCES [dbo].[COUNTRY]([ID]);

ALTER TABLE [dbo].[VENDOR] ADD CONSTRAINT [FKEY0058] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[VENDOR] ADD CONSTRAINT [FKEY0262] FOREIGN KEY ([DEF_EXP_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[VENDOR] ADD CONSTRAINT [FKEY9316] FOREIGN KEY ([ARRIVAL_CODE]) REFERENCES [dbo].[PORT_OF_ARRIVAL]([CODE]);

ALTER TABLE [dbo].[VENDOR] ADD CONSTRAINT [FKEY9317] FOREIGN KEY ([TRANS_CODE]) REFERENCES [dbo].[PORT_OF_TRANS]([CODE]);

ALTER TABLE [dbo].[VENDOR] ADD CONSTRAINT [FKEY9319] FOREIGN KEY ([NATURE_OF_TRANS]) REFERENCES [dbo].[NATURE_OF_TRANS]([CODE]);

ALTER TABLE [dbo].[VENDOR] ADD CONSTRAINT [FKEY9320] FOREIGN KEY ([MODE_OF_TRANSPORT]) REFERENCES [dbo].[MODE_OF_TRANSPORT]([CODE]);

ALTER TABLE [dbo].[VENDOR] ADD CONSTRAINT [FKEY9321] FOREIGN KEY ([WITHHOLDING_CODE]) REFERENCES [dbo].[WITHHOLDING]([CODE]);

ALTER TABLE [dbo].[VENDOR] ADD CONSTRAINT [FKEY9465] FOREIGN KEY ([DEF_LBL_FORMAT_ID]) REFERENCES [dbo].[LABEL_FORMAT]([ID]);

ALTER TABLE [dbo].[VENDOR] ADD CONSTRAINT [FKEY9471] FOREIGN KEY ([DEF_TRANS_CURRENCY]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[VENDOR] ADD CONSTRAINT [FKEY9578] FOREIGN KEY ([RETURN_TRANS]) REFERENCES [dbo].[NATURE_OF_TRANS]([CODE]);

ALTER TABLE [dbo].[VENDOR] ADD CONSTRAINT [FKEY9628] FOREIGN KEY ([DEF_TERMS_ID]) REFERENCES [dbo].[TERMS]([ID]);
