CREATE TABLE [dbo].[CASH_RECEIPT_DIST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CHECK_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DIST_NO] smallint DEFAULT  NOT NULL,
    [ENTRY_NO] smallint DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [AMOUNT_TYPE] NCHAR(2) DEFAULT  NOT NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [POSTING_STATUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [BATCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [NATIVE] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[CASH_RECEIPT_DIST] ADD CONSTRAINT [PK_CASH_RECEIPT_DIST] PRIMARY KEY ([CUSTOMER_ID], [CHECK_ID], [DIST_NO], [ENTRY_NO], [CURRENCY_ID]);

ALTER TABLE [dbo].[CASH_RECEIPT_DIST] ADD CONSTRAINT [FK_RCTDST_BATCH] FOREIGN KEY ([SITE_ID], [BATCH_ID]) REFERENCES [dbo].[JOURNAL_BATCH]([SITE_ID], [ID]);

ALTER TABLE [dbo].[CASH_RECEIPT_DIST] ADD CONSTRAINT [FKEY0028] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[CASH_RECEIPT_DIST] ADD CONSTRAINT [FKEY0204] FOREIGN KEY ([GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[CASH_RECEIPT_DIST] ADD CONSTRAINT [FKEY0238] FOREIGN KEY ([CUSTOMER_ID], [CHECK_ID]) REFERENCES [dbo].[CASH_RECEIPT]([CUSTOMER_ID], [CHECK_ID]);

ALTER TABLE [dbo].[CASH_RECEIPT_DIST] ADD CONSTRAINT [FKEY9397] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
