CREATE TABLE [dbo].[VR_DATA_SOURCE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [SOURCE_TYPE] int DEFAULT  NOT NULL,
    [SCOPE_TYPE] int DEFAULT ('1') NOT NULL,
    [DESCRIPTION] NVARCHAR(250) DEFAULT  NULL,
    [USE_ANSI_92_JOIN] NCHAR(1) DEFAULT ('Y') NOT NULL,
    [STATUS] NCHAR(1) DEFAULT ('D') NOT NULL,
    [FILTER_TEXT] NVARCHAR(2000) DEFAULT  NULL,
    [CREATED_BY] NVARCHAR(20) DEFAULT  NULL,
    [LAST_MODIFIED_BY] NVARCHAR(20) DEFAULT  NULL,
    [LAST_MODIFIED] datetime DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[VR_DATA_SOURCE] ADD CONSTRAINT [PK_VR_DATA_SOURCE] PRIMARY KEY ([ID]);
