CREATE TABLE [dbo].[NMFC_CODE_SYNC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EVENT_ID] int DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [NMFC_CODE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [EXCEPTION] NCHAR(1) DEFAULT  NOT NULL,
    [SUBSCRIPTIONS] int DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[NMFC_CODE_SYNC] ADD CONSTRAINT [PK_NMFC_CODE_SYNC] PRIMARY KEY ([EVENT_ID]);
