CREATE TABLE [dbo].[EQUIP_PROFILE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROFILE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [EQUIP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LAST_DATE] datetime DEFAULT  NULL,
    [PROFILE_DAY] int DEFAULT  NULL,
    [DATE_DAYNO] int DEFAULT  NULL,
    [PROFILE_MONTH] int DEFAULT  NULL
)

ALTER TABLE [dbo].[EQUIP_PROFILE] ADD CONSTRAINT [PK_EQUIP_PROFILE] PRIMARY KEY ([PROFILE_ID], [EQUIP_ID]);

ALTER TABLE [dbo].[EQUIP_PROFILE] ADD CONSTRAINT [FKEY9520] FOREIGN KEY ([PROFILE_ID]) REFERENCES [dbo].[EQUIP_PM_PROFILE]([PROFILE_ID]);
