CREATE TABLE [dbo].[REVISION_HISTORY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [REVISION_ID] NVARCHAR(8) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [STAGE_ID] NVARCHAR(15) DEFAULT  NULL,
    [HISTORY_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [COMMENTS] NVARCHAR(250) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[REVISION_HISTORY] ADD CONSTRAINT [PK_REVISION_HISTORY] PRIMARY KEY ([REVISION_ID], [TYPE], [HISTORY_ID]);
