CREATE TABLE [dbo].[PHYSICAL_COUNT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [START_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [STARTING_TAG_NO] int DEFAULT  NOT NULL,
    [EXTRA_TAGS_BLANK] int DEFAULT  NOT NULL,
    [TAGS_PER_GROUP] int DEFAULT  NOT NULL,
    [STATUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [LOCK_INVENTORY] NCHAR(1) DEFAULT ('') NOT NULL,
    [ADJ_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DEFICIT_USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [DEFICIT_USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [DEFICIT_CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [OVERSTOCK_USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [OVERSTOCK_USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [OVERSTOCK_CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[PHYSICAL_COUNT] ADD CONSTRAINT [PK_PHYSICAL_COUNT] PRIMARY KEY ([ID]);
