CREATE TABLE [dbo].[SHIPTO_ALT_WAREHS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SHIPTO_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RANK] smallint DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[SHIPTO_ALT_WAREHS] ADD CONSTRAINT [PK_SHIPTO_ALT_WAREHS] PRIMARY KEY ([CUSTOMER_ID], [SHIPTO_ID], [WAREHOUSE_ID]);
