CREATE TABLE [dbo].[MARKET] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(45) DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NULL,
    [MARKET_RATE] DECIMAL(22,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[MARKET] ADD CONSTRAINT [PK_MARKET] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[MARKET] ADD CONSTRAINT [FKEY9591] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
