CREATE TABLE [dbo].[WO_SCH_PRIORITY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SCHEDULE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [GLOBAL_RANK] smallint DEFAULT  NULL
)

ALTER TABLE [dbo].[WO_SCH_PRIORITY] ADD CONSTRAINT [PK_WO_SCH_PRIORITY] PRIMARY KEY ([SCHEDULE_ID], [WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID]);

ALTER TABLE [dbo].[WO_SCH_PRIORITY] ADD CONSTRAINT [FKEY9375] FOREIGN KEY ([SCHEDULE_ID]) REFERENCES [dbo].[SCHEDULE]([ID]);

ALTER TABLE [dbo].[WO_SCH_PRIORITY] ADD CONSTRAINT [FKEY9376] FOREIGN KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID]) REFERENCES [dbo].[WORK_ORDER]([TYPE], [BASE_ID], [LOT_ID], [SPLIT_ID], [SUB_ID]);
