CREATE TABLE [dbo].[PART_PRICE_GROUP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PART_PRICE_GROUP] ADD CONSTRAINT [PK_PART_PRICE_GROUP] PRIMARY KEY ([CODE]);
