CREATE TABLE [dbo].[MOVE_EQUIP_TYPE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[MOVE_EQUIP_TYPE] ADD CONSTRAINT [PK_MOVE_EQUIP_TYPE] PRIMARY KEY ([ID]);
