CREATE TABLE [dbo].[RFQ_VENDOR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RFQ_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [QUOTED_DATE] datetime DEFAULT  NULL,
    [EXPIRATION_DATE] datetime DEFAULT  NULL,
    [FOLLOWUP_DATE] datetime DEFAULT  NULL,
    [EXPECTED_DATE] datetime DEFAULT  NULL,
    [NAME] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_1] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_2] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_3] NVARCHAR(50) DEFAULT  NULL,
    [CITY] NVARCHAR(30) DEFAULT  NULL,
    [STATE] NVARCHAR(10) DEFAULT  NULL,
    [ZIPCODE] NVARCHAR(10) DEFAULT  NULL,
    [COUNTRY] NVARCHAR(50) DEFAULT  NULL,
    [RFQ_VENDOR_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_ID] NVARCHAR(25) DEFAULT  NULL,
    [CONTACT_FIRST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_LAST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_INITIAL] NVARCHAR(2) DEFAULT  NULL,
    [CONTACT_POSITION] NVARCHAR(50) DEFAULT  NULL,
    [CONTACT_HONORIFIC] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_SALUTATION] NVARCHAR(60) DEFAULT  NULL,
    [CONTACT_PHONE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_FAX] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_EMAIL] NVARCHAR(100) DEFAULT  NULL,
    [SUPPLIER_QUOTE_ID] NVARCHAR(100) DEFAULT  NULL,
    [VENDOR_CONTRACT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CONTRACT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_PHONE_EXT] NVARCHAR(10) DEFAULT  NULL
)

ALTER TABLE [dbo].[RFQ_VENDOR] ADD CONSTRAINT [PK_RFQ_VENDOR] PRIMARY KEY ([RFQ_ID], [VENDOR_ID]);

ALTER TABLE [dbo].[RFQ_VENDOR] ADD CONSTRAINT [FK_RFQ_VEN_CONT_ID] FOREIGN KEY ([CONTACT_ID]) REFERENCES [dbo].[CONTACT]([ID]);

ALTER TABLE [dbo].[RFQ_VENDOR] ADD CONSTRAINT [FKEY0251] FOREIGN KEY ([RFQ_ID]) REFERENCES [dbo].[REQUEST_FOR_QUOTE]([ID]);

ALTER TABLE [dbo].[RFQ_VENDOR] ADD CONSTRAINT [FKEY0293] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);
