CREATE TABLE [dbo].[CUST_PRIORITY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PRIORITY_CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [FILL_RATE] DECIMAL(5,2) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[CUST_PRIORITY] ADD CONSTRAINT [PK_CUST_PRIORITY] PRIMARY KEY ([PRIORITY_CODE]);
