CREATE TABLE [dbo].[SECURITY_CLASS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SECURITY_CLASS] ADD CONSTRAINT [PK_SECURITY_CLASS] PRIMARY KEY ([CODE]);
