CREATE TABLE [dbo].[EQUIP_PM_SCHEDULE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [JOB_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PROFILE_ID] NVARCHAR(30) DEFAULT  NULL,
    [EQUIP_ID] NVARCHAR(15) DEFAULT  NULL,
    [ENG_ID] NVARCHAR(3) DEFAULT  NULL,
    [JOB_DATE] datetime DEFAULT  NULL,
    [START_DATE] datetime DEFAULT  NULL,
    [FINISH_DATE] datetime DEFAULT  NULL,
    [WO_CREATED] NVARCHAR(1) DEFAULT  NULL,
    [RESOURCE_ID] NVARCHAR(30) DEFAULT  NULL,
    [WO_CREATE_DATE] datetime DEFAULT  NULL,
    [WO_STATUS] NVARCHAR(1) DEFAULT  NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_TYPE] NVARCHAR(1) DEFAULT  NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [CUST_ORDER_LINE_NO] smallint DEFAULT  NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [INVOICE_FLAG] NVARCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[EQUIP_PM_SCHEDULE] ADD CONSTRAINT [PK_EQUIP_PM_SCHED] PRIMARY KEY ([JOB_ID]);

ALTER TABLE [dbo].[EQUIP_PM_SCHEDULE] ADD CONSTRAINT [FKEY9519] FOREIGN KEY ([PROFILE_ID]) REFERENCES [dbo].[EQUIP_PM_PROFILE]([PROFILE_ID]);
