CREATE TABLE [dbo].[PROJECT_CEILING] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROJECT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [COST_CATEGORY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BASE_CATEGORY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CLIN] NVARCHAR(15) DEFAULT  NOT NULL,
    [BASIS] NCHAR(1) DEFAULT  NULL,
    [BASIS_VALUE] DECIMAL(23,8) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(250) DEFAULT  NULL
)

ALTER TABLE [dbo].[PROJECT_CEILING] ADD CONSTRAINT [PK_PROJECT_CEILING] PRIMARY KEY ([PROJECT_ID], [TYPE], [COST_CATEGORY_ID], [BASE_CATEGORY_ID], [CLIN]);

ALTER TABLE [dbo].[PROJECT_CEILING] ADD CONSTRAINT [FK_PROJECT_CEILING_00] FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[PROJECT_INFO]([ID]);
