CREATE TABLE [dbo].[TERMS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [NET_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [NET_DAYS] smallint DEFAULT  NULL,
    [NET_DATE] datetime DEFAULT  NULL,
    [DISC_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [DISC_DAYS] smallint DEFAULT  NULL,
    [DISC_DATE] datetime DEFAULT  NULL,
    [DISC_PERCENT] DECIMAL(5,3) DEFAULT  NULL,
    [FREIGHT_TERMS] NCHAR(1) DEFAULT ('B') NULL,
    [END_OF_MONTH] NCHAR(1) DEFAULT  NULL,
    [VAT_ON_FIRST_INST] NCHAR(1) DEFAULT  NULL,
    [PERIOD_TYPE] NCHAR(1) DEFAULT  NULL,
    [DISC_BASIS] NVARCHAR(32) DEFAULT  NULL,
    [ACTIVE_FLAG] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[TERMS] ADD CONSTRAINT [PK_TERMS] PRIMARY KEY ([ID]);
