CREATE TABLE [dbo].[TRACE_SERV_DISP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [TRACE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DISPATCH_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DISP_LINE_NO] smallint DEFAULT  NOT NULL,
    [DISPATCH_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[TRACE_SERV_DISP] ADD CONSTRAINT [PK_TRACE_SERV_DISP] PRIMARY KEY ([PART_ID], [TRACE_ID], [DISPATCH_ID], [DISP_LINE_NO]);
