CREATE TABLE [dbo].[SIMULATION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT  NULL,
    [APPLIED_DATE] datetime DEFAULT  NULL,
    [NOTES] NVARCHAR(250) DEFAULT  NULL,
    [BATCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SIMULATION] ADD CONSTRAINT [PK_SIMULATION] PRIMARY KEY ([ID]);
