CREATE TABLE [dbo].[ACCOUNT_SITE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [IS_VIEWABLE] NCHAR(1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[ACCOUNT_SITE] ADD CONSTRAINT [PK_ACCOUNT_SITE] PRIMARY KEY ([ACCOUNT_ID], [SITE_ID]);

ALTER TABLE [dbo].[ACCOUNT_SITE] ADD CONSTRAINT [FK_ACCT_SITE_ACCT] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[ACCOUNT_SITE] ADD CONSTRAINT [FK_ACCT_SITE_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
