CREATE TABLE [dbo].[RCR_RECV_SHARE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RCR_RECV_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SHARE_SALESREP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SHARE_PERCENT] DECIMAL(6,3) DEFAULT  NULL
)

ALTER TABLE [dbo].[RCR_RECV_SHARE] ADD CONSTRAINT [PK_RCR_RECV_SHARE] PRIMARY KEY ([RCR_RECV_ID], [SHARE_SALESREP_ID]);

ALTER TABLE [dbo].[RCR_RECV_SHARE] ADD CONSTRAINT [FKEY9585] FOREIGN KEY ([RCR_RECV_ID]) REFERENCES [dbo].[RCR_RECEIVABLE]([ID]);

ALTER TABLE [dbo].[RCR_RECV_SHARE] ADD CONSTRAINT [FKEY9586] FOREIGN KEY ([SHARE_SALESREP_ID]) REFERENCES [dbo].[SALES_REP]([ID]);
