CREATE TABLE [dbo].[APS_LAYOUT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [KEY] NCHAR(3) DEFAULT  NOT NULL,
    [OUTPUT_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [STYLE] NCHAR(1) DEFAULT  NOT NULL,
    [FIELD_DELIMITER] NCHAR(1) DEFAULT  NULL,
    [RECORD_DELIMITER] NCHAR(1) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [LAST_RUN_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[APS_LAYOUT] ADD CONSTRAINT [PK_APS_LAYOUT] PRIMARY KEY ([KEY]);
