CREATE TABLE [dbo].[COR_PROPERTY] (
    [C_ID] bigint IDENTITY(1,1) DEFAULT  NOT NULL,
    [C_PROPERTY_NAME] NVARCHAR(250) DEFAULT  NOT NULL,
    [C_PROPERTY_VALUE] NVARCHAR(250) DEFAULT  NOT NULL
)
