CREATE TABLE [dbo].[PLANNED_LOAD] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CALC_DATE] datetime DEFAULT  NOT NULL,
    [HORIZON] int DEFAULT  NOT NULL,
    [SETUP_LOAD] DECIMAL(14,2) DEFAULT  NOT NULL,
    [RUN_LOAD] DECIMAL(14,2) DEFAULT  NOT NULL,
    [AVAIL_SETUP_LOAD] DECIMAL(14,2) DEFAULT  NOT NULL,
    [AVAIL_RUN_LOAD] DECIMAL(14,2) DEFAULT  NOT NULL,
    [WORKING_HOURS] DECIMAL(14,2) DEFAULT  NULL,
    [AVAILABLE_UNITS] int DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)
