CREATE TABLE [dbo].[COST_CATEGORY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [COST_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [COST_GROUP_ID] NVARCHAR(15) DEFAULT  NULL,
    [SPREAD_TYPE] NCHAR(1) DEFAULT  NULL,
    [BURDEN_APPLY_TYPE] NVARCHAR(2) DEFAULT  NULL,
    [ACTGRP_BURCAT_POOL] NVARCHAR(15) DEFAULT  NULL,
    [ACTGRP_BURCAT_BASE] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[COST_CATEGORY] ADD CONSTRAINT [PK_COST_CATEGORY] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[COST_CATEGORY] ADD CONSTRAINT [FK_COST_CATEGORY_00] FOREIGN KEY ([COST_GROUP_ID]) REFERENCES [dbo].[COST_GROUP]([ID]);
