CREATE TABLE [dbo].[VAT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [TYPE] NCHAR(1) DEFAULT ('D') NOT NULL,
    [TAX_PERCENT] DECIMAL(6,3) DEFAULT  NOT NULL,
    [TAX_RCV_PERCENT] DECIMAL(6,3) DEFAULT  NOT NULL,
    [TAX_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [TAX_RCV_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [TAX_IE_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [TAX_IE_DR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [TAX_IE_CR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [EFFECTIVE_DATE] datetime DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[VAT] ADD CONSTRAINT [PK_VAT] PRIMARY KEY ([CODE], [EFFECTIVE_DATE]);
