CREATE TABLE [dbo].[BANK_DEPOSIT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BANK_ACCOUNT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DEPOSIT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [DEPOSIT_DATE] datetime DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [CLEARED] NCHAR(1) DEFAULT ('') NOT NULL,
    [CLEARED_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[BANK_DEPOSIT] ADD CONSTRAINT [PK_BANK_DEPOSIT] PRIMARY KEY ([BANK_ACCOUNT_ID], [DEPOSIT_ID]);

ALTER TABLE [dbo].[BANK_DEPOSIT] ADD CONSTRAINT [FKEY0221] FOREIGN KEY ([BANK_ACCOUNT_ID]) REFERENCES [dbo].[BANK_ACCOUNT]([ID]);
