CREATE TABLE [dbo].[SERVICE_UNIT_CONV] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SERVICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [FROM_UM] NVARCHAR(15) DEFAULT  NOT NULL,
    [TO_UM] NVARCHAR(15) DEFAULT  NOT NULL,
    [CONVERSION_FACTOR] DECIMAL(15,8) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SERVICE_UNIT_CONV] ADD CONSTRAINT [PK_SERVICE_UNIT_CONV] PRIMARY KEY ([SERVICE_ID], [FROM_UM], [TO_UM]);
