CREATE TABLE [dbo].[APP_CONFIG_ITEM] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] int DEFAULT  NOT NULL,
    [APP_CONFIG_ID] int DEFAULT  NOT NULL,
    [CAPTION] NVARCHAR(100) DEFAULT  NOT NULL,
    [ITEM_TYPE] NVARCHAR(100) DEFAULT  NOT NULL,
    [PARENT_ITEM_ID] int DEFAULT  NULL,
    [POS_X] DECIMAL(14,4) DEFAULT  NULL,
    [POS_Y] DECIMAL(14,4) DEFAULT  NULL,
    [WIDTH] DECIMAL(14,4) DEFAULT  NULL,
    [HEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [ITEM_STATE] int DEFAULT  NULL,
    [ITEM_FOCUS] NCHAR(1) DEFAULT ('N') NOT NULL,
    [CONFIG] image DEFAULT  NULL
)

ALTER TABLE [dbo].[APP_CONFIG_ITEM] ADD CONSTRAINT [PK_APP_CONFIG_ITEM] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[APP_CONFIG_ITEM] ADD CONSTRAINT [FK_APP_CONFIG_ITEM_TO_APP] FOREIGN KEY ([APP_CONFIG_ID]) REFERENCES [dbo].[APP_CONFIG]([ID]);
