CREATE TABLE [dbo].[USAGE_ANALYSIS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CALC_VALUE] DECIMAL(23,8) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[USAGE_ANALYSIS] ADD CONSTRAINT [FK_USAGE_ANAL_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
