CREATE TABLE [dbo].[EVENT_LOG] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [EVENT_ID] smallint DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [CLASS] NVARCHAR(15) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL
)
