CREATE TABLE [dbo].[QUOTE_LINE_BILLING] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [QUOTE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [QUOTE_LINE_NO] smallint DEFAULT  NOT NULL,
    [EVENT_SEQ_NO] smallint DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [BILL_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [BILL_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [REV_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [REV_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [MILESTONE_ID] NVARCHAR(15) DEFAULT  NULL,
    [EVENT_DATE] datetime DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [REV_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[QUOTE_LINE_BILLING] ADD CONSTRAINT [PK_QUOTE_LINE_BILLING] PRIMARY KEY ([QUOTE_ID], [QUOTE_LINE_NO], [EVENT_SEQ_NO]);

ALTER TABLE [dbo].[QUOTE_LINE_BILLING] ADD CONSTRAINT [FKEY9107] FOREIGN KEY ([REV_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[QUOTE_LINE_BILLING] ADD CONSTRAINT [FKEY9113] FOREIGN KEY ([QUOTE_ID], [QUOTE_LINE_NO]) REFERENCES [dbo].[QUOTE_LINE]([QUOTE_ID], [LINE_NO]);
