CREATE TABLE [dbo].[ENUM_CODES] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TABLE_NAME] NVARCHAR(20) DEFAULT  NOT NULL,
    [COLUMN_NAME] NVARCHAR(20) DEFAULT  NOT NULL,
    [LANGUAGE_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [ENUM_TEXT] NVARCHAR(40) DEFAULT  NULL,
    [ENUM_VALUE] NVARCHAR(20) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[ENUM_CODES] ADD CONSTRAINT [PK_ENUM_CODES] PRIMARY KEY ([TABLE_NAME], [COLUMN_NAME], [LANGUAGE_ID], [ENUM_VALUE]);
