CREATE TABLE [dbo].[GOTO_VMPGM] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [GOTO_ID] int DEFAULT  NOT NULL,
    [WPARAM_ARG] int DEFAULT  NULL
)

ALTER TABLE [dbo].[GOTO_VMPGM] ADD CONSTRAINT [PK_GOTO_VMPGM] PRIMARY KEY ([PROGRAM_ID], [GOTO_ID]);
