CREATE TABLE [dbo].[ECN_REQ_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ECN_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] int DEFAULT  NOT NULL,
    [ECN_ENTRY_NO] smallint DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [OPERATION_SEQ_NO] smallint DEFAULT  NOT NULL,
    [PIECE_NO] smallint DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NULL
)

ALTER TABLE [dbo].[ECN_REQ_BINARY] ADD CONSTRAINT [PK_ECN_REQ_BINARY] PRIMARY KEY ([ECN_ID], [LINE_NO], [ECN_ENTRY_NO], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO], [PIECE_NO], [TYPE]);

ALTER TABLE [dbo].[ECN_REQ_BINARY] ADD CONSTRAINT [FK_ECN_REQ_BINARY] FOREIGN KEY ([ECN_ID], [LINE_NO], [ECN_ENTRY_NO], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO], [PIECE_NO]) REFERENCES [dbo].[ECN_REQUIREMENT]([ECN_ID], [LINE_NO], [ECN_ENTRY_NO], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO], [PIECE_NO]);
