CREATE TABLE [dbo].[PREF_DESCRIPTION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SECTION] NVARCHAR(100) DEFAULT  NOT NULL,
    [ENTRY] NVARCHAR(100) DEFAULT  NOT NULL,
    [VALUE] NVARCHAR(100) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(250) DEFAULT  NULL
)

ALTER TABLE [dbo].[PREF_DESCRIPTION] ADD CONSTRAINT [PK_PREF_DESCRIPTION] PRIMARY KEY ([SECTION], [ENTRY]);
