CREATE TABLE [dbo].[SOA_ID_MAP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [NOUN_ID] NVARCHAR(50) DEFAULT  NOT NULL,
    [SYS_KEY_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [SYS_ENTITY_ID] NVARCHAR(22) DEFAULT  NOT NULL,
    [SYS_AGENCY_ID] NVARCHAR(64) DEFAULT  NOT NULL,
    [SYS_SCHEME_NAME] NVARCHAR(64) DEFAULT  NULL,
    [SYS_AGENCY_NAME] NVARCHAR(64) DEFAULT  NULL,
    [SYS_LOC_ID] NVARCHAR(22) DEFAULT  NULL,
    [SYS_VARIATION] NVARCHAR(22) DEFAULT  NULL,
    [SOR_KEY_ID] NVARCHAR(80) DEFAULT  NULL,
    [SOR_ENTITY_ID] NVARCHAR(22) DEFAULT  NULL,
    [SOR_LID] NVARCHAR(64) DEFAULT  NULL,
    [SOR_SCHEME_NAME] NVARCHAR(64) DEFAULT  NULL,
    [SOR_AGENCY_NAME] NVARCHAR(64) DEFAULT  NULL,
    [SOR_LOC_ID] NVARCHAR(22) DEFAULT  NULL,
    [SOR_VARIATION] NVARCHAR(22) DEFAULT  NULL,
    [DID] NVARCHAR(255) DEFAULT  NULL,
    [SITE] NVARCHAR(15) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[SOA_ID_MAP] ADD CONSTRAINT [PK_SOA_ID_MAP] PRIMARY KEY ([NOUN_ID], [SYS_KEY_ID], [SYS_ENTITY_ID], [SYS_AGENCY_ID]);
