CREATE TABLE [dbo].[USER_DIM_MAPPING] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [OWNER_TABLE] NVARCHAR(25) DEFAULT  NOT NULL,
    [OWNER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DIMENSION] smallint DEFAULT  NOT NULL,
    [PROCESS_TYPE] NVARCHAR(5) DEFAULT  NOT NULL,
    [EFFECTIVE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [DEBIT_USER_DIM] NVARCHAR(15) DEFAULT  NULL,
    [CREDIT_USER_DIM] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[USER_DIM_MAPPING] ADD CONSTRAINT [PK_USER_DIM_MAP] PRIMARY KEY ([OWNER_TABLE], [OWNER_ID], [DIMENSION], [PROCESS_TYPE], [EFFECTIVE_DATE]);
