CREATE TABLE [dbo].[WORKORDER_AUDIT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SCHEDULE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [PASS_NO] int DEFAULT  NOT NULL,
    [PASS_DIRECTION] NCHAR(1) DEFAULT ('') NOT NULL,
    [PASS_RESULT] NCHAR(1) DEFAULT ('') NOT NULL,
    [START_DATE] datetime DEFAULT  NULL,
    [FINISH_DATE] datetime DEFAULT  NULL,
    [COULD_START_FINISH] datetime DEFAULT  NULL,
    [SCHEDULE_RANK] int DEFAULT  NULL
)

ALTER TABLE [dbo].[WORKORDER_AUDIT] ADD CONSTRAINT [PK_WORKORDER_AUDIT] PRIMARY KEY ([SCHEDULE_ID], [WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [PASS_NO]);

ALTER TABLE [dbo].[WORKORDER_AUDIT] ADD CONSTRAINT [FKEY0296] FOREIGN KEY ([SCHEDULE_ID]) REFERENCES [dbo].[SCHEDULE]([ID]);
