CREATE TABLE [dbo].[PERIOD] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [START_DATE] datetime DEFAULT  NOT NULL,
    [END_DATE] datetime DEFAULT  NOT NULL,
    [USE_TRANS_RATES] NCHAR(1) DEFAULT ('N') NOT NULL,
    [ACT_RATE_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PERIOD] ADD CONSTRAINT [PK_PERIOD] PRIMARY KEY ([ID], [SITE_ID]);
