CREATE TABLE [dbo].[SERVICE_SITE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SERVICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NULL,
    [EST_MIN_CHARGE] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [EST_BASE_CHARGE] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [SERVICE_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [PLAN_TRANSIT_DAYS] smallint DEFAULT  NULL,
    [SCHEDULE_RANK] smallint DEFAULT  NULL,
    [RUN] DECIMAL(20,8) DEFAULT  NULL,
    [RUN_TYPE] NVARCHAR(15) DEFAULT  NULL,
    [LOAD_SIZE_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [MINIMUM_MOVE_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [EST_COST_PER_UNIT] DECIMAL(22,8) DEFAULT ((0)) NOT NULL,
    [STATUS] NCHAR(1) DEFAULT  NULL,
    [VAT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [INTRASTAT_INCLUDE] NVARCHAR(1) DEFAULT  NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [BID_RATE_CATEGORY_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[SERVICE_SITE] ADD CONSTRAINT [PK_SERVICE_SITE] PRIMARY KEY ([SITE_ID], [SERVICE_ID]);

ALTER TABLE [dbo].[SERVICE_SITE] ADD CONSTRAINT [FK_SERV_SITE_TO_SERVICE] FOREIGN KEY ([SERVICE_ID]) REFERENCES [dbo].[SERVICE]([ID]);

ALTER TABLE [dbo].[SERVICE_SITE] ADD CONSTRAINT [FK_SERV_SITE_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
