CREATE TABLE [dbo].[ESB_PREVIOUS_VERSION_MEDIATION] (
    [C_ID] bigint IDENTITY(1,1) DEFAULT  NOT NULL,
    [C_LOGICAL_ID] NVARCHAR(250) DEFAULT  NOT NULL,
    [C_NOUN_NAME] NVARCHAR(250) DEFAULT  NOT NULL,
    [C_TENANT_ID] NVARCHAR(250) DEFAULT  NOT NULL,
    [C_ACCOUNTING_ENTITY_ID] NVARCHAR(250) DEFAULT  NULL,
    [C_LOCATION_ID] NVARCHAR(250) DEFAULT  NULL,
    [C_VARIATION_ID] NVARCHAR(250) DEFAULT  NULL,
    [C_REVISION_ID] NVARCHAR(250) DEFAULT  NULL,
    [C_NOUN_ID] NVARCHAR(250) DEFAULT  NOT NULL,
    [C_XML] VARBINARY(MAX) DEFAULT  NULL,
    [C_AGENCY_ROLE] NVARCHAR(250) DEFAULT  NULL
)

ALTER TABLE [dbo].[ESB_PREVIOUS_VERSION_MEDIATION] ADD CONSTRAINT [PK_ESB_PREVIOUS_VERSION_MEDIATION] PRIMARY KEY ([C_ID]);
