CREATE TABLE [dbo].[WEB_SESSION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [APPLICATION_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TOKEN] NVARCHAR(2000) DEFAULT  NOT NULL,
    [LAST_ACTIVITY] datetime DEFAULT (getdate()) NOT NULL,
    [EXPIRE_DATE] datetime DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[WEB_SESSION] ADD CONSTRAINT [PK_WEB_SESSION] PRIMARY KEY ([USER_ID], [APPLICATION_ID]);
