CREATE TABLE [dbo].[DIMENSION_DESC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DIMENSION_DESC] NVARCHAR(20) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[DIMENSION_DESC] ADD CONSTRAINT [PK_DIMENSION_DESC] PRIMARY KEY ([DIMENSION_DESC]);
