CREATE TABLE [dbo].[DBR_EVENT_TRIGGER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EVENT_CLASS] NVARCHAR(2) DEFAULT  NOT NULL,
    [EVENT_ACTION] NVARCHAR(2) DEFAULT  NOT NULL,
    [SENDER] NVARCHAR(128) DEFAULT  NULL,
    [SUBJECT] NVARCHAR(128) DEFAULT  NULL,
    [RECIPIENT] NVARCHAR(128) DEFAULT  NULL,
    [FREQUENCY] int DEFAULT  NULL,
    [FREQ_COUNT] int DEFAULT  NULL,
    [FREQ_DATE] datetime DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[DBR_EVENT_TRIGGER] ADD CONSTRAINT [PK_DBR_EVENT_TRIGGER] PRIMARY KEY ([SITE_ID], [EVENT_CLASS], [EVENT_ACTION]);
