CREATE TABLE [dbo].[BURDEN_GROUP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[BURDEN_GROUP] ADD CONSTRAINT [PK_BURDEN_GROUP] PRIMARY KEY ([ID]);
