CREATE TABLE [dbo].[IBT_SHIPPER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SHIPPER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [IBT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SHIPPED_DATE] datetime DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [MARKED_FOR_PURGE] NCHAR(1) DEFAULT ('') NOT NULL,
    [LONG_DESCRIPTION] image DEFAULT  NULL,
    [BOL_ID] NVARCHAR(20) DEFAULT  NULL,
    [ASN_ID] NVARCHAR(20) DEFAULT  NULL,
    [PRINTED_DATE] datetime DEFAULT  NULL,
    [FREE_ON_BOARD] NVARCHAR(25) DEFAULT  NULL,
    [SHIP_VIA] NVARCHAR(40) DEFAULT  NULL,
    [SALES_TAX_GROUP_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ESL_REPORT_NO] int DEFAULT  NULL,
    [ESL_FILENAME] NVARCHAR(15) DEFAULT  NULL,
    [SHIP_REASON_CD] NVARCHAR(15) DEFAULT  NULL,
    [CUSTOMS_DOC_ID] NVARCHAR(15) DEFAULT  NULL,
    [WEIGH_BILL_NUMBER] NVARCHAR(20) DEFAULT  NULL,
    [POOL_CODE] NVARCHAR(20) DEFAULT  NULL,
    [VEHICLE_NUMBER] NVARCHAR(20) DEFAULT  NULL,
    [INTER_CONSIGNEE] NVARCHAR(20) DEFAULT  NULL,
    [TARE_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [TOTAL_NET_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [TOTAL_GROSS_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [USER_RECEIVED_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [RECEIVED_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [RCPT_ACK_PRINTED] datetime DEFAULT  NULL,
    [CONTACT_ID] NVARCHAR(25) DEFAULT  NULL,
    [CONTACT_FIRST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_LAST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_INITIAL] NVARCHAR(2) DEFAULT  NULL,
    [CONTACT_POSITION] NVARCHAR(50) DEFAULT  NULL,
    [CONTACT_HONORIFIC] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_SALUTATION] NVARCHAR(60) DEFAULT  NULL,
    [CONTACT_PHONE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_FAX] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_MOBILE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_EMAIL] NVARCHAR(100) DEFAULT  NULL,
    [CONTACT_PHONE_EXT] NVARCHAR(10) DEFAULT  NULL
)

ALTER TABLE [dbo].[IBT_SHIPPER] ADD CONSTRAINT [PK_IBT_SHIPPER] PRIMARY KEY ([SHIPPER_ID]);

ALTER TABLE [dbo].[IBT_SHIPPER] ADD CONSTRAINT [FK_IBT_SHIPPER_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[IBT_SHIPPER] ADD CONSTRAINT [FK_IBT_SHP_CONT_ID] FOREIGN KEY ([CONTACT_ID]) REFERENCES [dbo].[CONTACT]([ID]);

ALTER TABLE [dbo].[IBT_SHIPPER] ADD CONSTRAINT [FKEY9490] FOREIGN KEY ([IBT_ID]) REFERENCES [dbo].[IBT]([ID]);
