CREATE TABLE [dbo].[PART_UNITS_CONV] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [FROM_UM] NVARCHAR(15) DEFAULT  NOT NULL,
    [TO_UM] NVARCHAR(15) DEFAULT  NOT NULL,
    [CONVERSION_FACTOR] DECIMAL(15,8) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PART_UNITS_CONV] ADD CONSTRAINT [PK_PART_UNITS_CONV] PRIMARY KEY ([PART_ID], [FROM_UM], [TO_UM]);

ALTER TABLE [dbo].[PART_UNITS_CONV] ADD CONSTRAINT [FKEY0032] FOREIGN KEY ([FROM_UM]) REFERENCES [dbo].[UNITS]([UNIT_OF_MEASURE]);

ALTER TABLE [dbo].[PART_UNITS_CONV] ADD CONSTRAINT [FKEY0091] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);
