CREATE TABLE [dbo].[SALES_TAX_GROUP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL
)

ALTER TABLE [dbo].[SALES_TAX_GROUP] ADD CONSTRAINT [PK_SALES_TAX_GROUP] PRIMARY KEY ([ID]);
