CREATE TABLE [dbo].[GROUPS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [DEF_AUTH_GRP] NCHAR(1) DEFAULT  NULL,
    [DEF_IMPL_GRP] NCHAR(1) DEFAULT  NULL,
    [DEF_APRV_GRP] NCHAR(1) DEFAULT  NULL,
    [DEF_DIST_GRP] NCHAR(1) DEFAULT  NULL,
    [APPROVAL_1] NCHAR(1) DEFAULT  NULL,
    [APPROVAL_2] NCHAR(1) DEFAULT  NULL,
    [APPROVAL_3] NCHAR(1) DEFAULT  NULL,
    [APPROVAL_4] NCHAR(1) DEFAULT  NULL,
    [GROUP_SIGNOFF] NCHAR(1) DEFAULT  NULL,
    [WORKFLOW_APPROVAL] NCHAR(1) DEFAULT  NULL,
    [IS_PROFILE] NCHAR(1) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[GROUPS] ADD CONSTRAINT [PK_GROUPS] PRIMARY KEY ([ID]);
