CREATE TABLE [dbo].[INTRA_CNSN_RCVR_LN] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RECEIVER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RECEIVER_LINE_NO] smallint DEFAULT  NOT NULL,
    [ARRIVAL_CODE] NVARCHAR(25) DEFAULT  NULL,
    [TRANS_CODE] NVARCHAR(25) DEFAULT  NULL,
    [TO_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [FROM_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [ORIG_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [REGION_ID] NVARCHAR(2) DEFAULT  NULL,
    [NATURE_OF_TRANS] int DEFAULT  NULL,
    [MODE_OF_TRANSPORT] int DEFAULT  NULL,
    [EXCISE_PRICE] DECIMAL(23,8) DEFAULT  NULL,
    [TARIFF_CODE] NVARCHAR(15) DEFAULT  NULL,
    [INTRA_REPORT_NO] int DEFAULT  NULL,
    [INTRA_FILENAME] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[INTRA_CNSN_RCVR_LN] ADD CONSTRAINT [PK_INTRA_CNSN_RCVR_LN] PRIMARY KEY ([RECEIVER_ID], [RECEIVER_LINE_NO]);

ALTER TABLE [dbo].[INTRA_CNSN_RCVR_LN] ADD CONSTRAINT [FKEY9619] FOREIGN KEY ([RECEIVER_ID], [RECEIVER_LINE_NO]) REFERENCES [dbo].[CONSIGN_RCVR_LINE]([RECEIVER_ID], [LINE_NO]);
