CREATE TABLE [dbo].[RES_SIMULATION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SIMULATION_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [PRV_SET_CST_PER_HR] DECIMAL(22,8) DEFAULT  NULL,
    [PRV_RUN_CST_PER_HR] DECIMAL(22,8) DEFAULT  NULL,
    [PRV_RUN_CST_PER_UN] DECIMAL(22,8) DEFAULT  NULL,
    [PRV_BUR_PER_HR_SET] DECIMAL(22,8) DEFAULT  NULL,
    [PRV_BUR_PER_HR_RUN] DECIMAL(22,8) DEFAULT  NULL,
    [PRV_BUR_PER_UN_RUN] DECIMAL(22,8) DEFAULT  NULL,
    [PRV_BUR_PER_OPER] DECIMAL(22,8) DEFAULT  NULL,
    [TOT_PRV_LAB_COST] DECIMAL(23,8) DEFAULT  NULL,
    [TOT_PRV_BUR_COST] DECIMAL(23,8) DEFAULT  NULL,
    [SIM_SET_CST_PER_HR] DECIMAL(22,8) DEFAULT  NULL,
    [SIM_RUN_CST_PER_HR] DECIMAL(22,8) DEFAULT  NULL,
    [SIM_RUN_CST_PER_UN] DECIMAL(22,8) DEFAULT  NULL,
    [SIM_BUR_PER_HR_SET] DECIMAL(22,8) DEFAULT  NULL,
    [SIM_BUR_PER_HR_RUN] DECIMAL(22,8) DEFAULT  NULL,
    [SIM_BUR_PER_UN_RUN] DECIMAL(22,8) DEFAULT  NULL,
    [SIM_BUR_PER_OPER] DECIMAL(22,8) DEFAULT  NULL,
    [TOT_SIM_LAB_COST] DECIMAL(23,8) DEFAULT  NULL,
    [TOT_SIM_BUR_COST] DECIMAL(23,8) DEFAULT  NULL,
    [PRV_CREATE_DATE] datetime DEFAULT  NULL,
    [SIM_CREATE_DATE] datetime DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[RES_SIMULATION] ADD CONSTRAINT [PK_] PRIMARY KEY ([SIMULATION_ID], [RESOURCE_ID]);

ALTER TABLE [dbo].[RES_SIMULATION] ADD CONSTRAINT [FK_RES_SIMULATION_00] FOREIGN KEY ([SIMULATION_ID]) REFERENCES [dbo].[SIMULATION]([ID]);

ALTER TABLE [dbo].[RES_SIMULATION] ADD CONSTRAINT [FK_RES_SIMULATION_01] FOREIGN KEY ([RESOURCE_ID]) REFERENCES [dbo].[SHOP_RESOURCE]([ID]);
