CREATE TABLE [dbo].[BURDEN_TRANS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BURDEN_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [PROJECT_SUMMARY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BURDEN_CATEGORY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [SOURCE_TYPE] NVARCHAR(20) DEFAULT  NULL,
    [SOURCE_TRANS_ID] int DEFAULT  NULL,
    [SOURCE_ID] NVARCHAR(30) DEFAULT  NULL,
    [SOURCE_LINE_NO] smallint DEFAULT  NULL,
    [ACCOUNT_YEAR] DECIMAL(4,0) DEFAULT  NULL,
    [ACCOUNT_PERIOD] DECIMAL(2,0) DEFAULT  NULL,
    [DEPARTMENT_ID] NVARCHAR(15) DEFAULT  NULL,
    [COST_CATEGORY_ID] NVARCHAR(15) DEFAULT  NULL,
    [IS_RETRO] NCHAR(1) DEFAULT ('') NOT NULL,
    [RATE_ID] NVARCHAR(15) DEFAULT  NULL,
    [PERIOD_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[BURDEN_TRANS] ADD CONSTRAINT [PK_BURDEN_TRANS] PRIMARY KEY ([BURDEN_ID], [PROJECT_SUMMARY_ID], [BURDEN_CATEGORY_ID]);

ALTER TABLE [dbo].[BURDEN_TRANS] ADD CONSTRAINT [FK_BURDEN_TRANS_00] FOREIGN KEY ([BURDEN_CATEGORY_ID]) REFERENCES [dbo].[COST_CATEGORY]([ID]);

ALTER TABLE [dbo].[BURDEN_TRANS] ADD CONSTRAINT [FK_BURDEN_TRANS_01] FOREIGN KEY ([DEPARTMENT_ID]) REFERENCES [dbo].[DEPARTMENT]([ID]);

ALTER TABLE [dbo].[BURDEN_TRANS] ADD CONSTRAINT [FK_BURDEN_TRANS_02] FOREIGN KEY ([COST_CATEGORY_ID]) REFERENCES [dbo].[COST_CATEGORY]([ID]);
