CREATE TABLE [dbo].[CHART_FACTORS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SUBGROUP_SIZE] smallint DEFAULT  NOT NULL,
    [A1] DECIMAL(14,8) DEFAULT  NOT NULL,
    [A2] DECIMAL(14,8) DEFAULT  NOT NULL,
    [A3] DECIMAL(14,8) DEFAULT  NOT NULL,
    [C4] DECIMAL(14,8) DEFAULT  NOT NULL,
    [B3] DECIMAL(14,8) DEFAULT  NOT NULL,
    [B4] DECIMAL(14,8) DEFAULT  NOT NULL,
    [LD2] DECIMAL(14,8) DEFAULT  NOT NULL,
    [D3] DECIMAL(14,8) DEFAULT  NOT NULL,
    [D4] DECIMAL(14,8) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CHART_FACTORS] ADD CONSTRAINT [PK_CHART_FACTORS] PRIMARY KEY ([SUBGROUP_SIZE]);
