CREATE TABLE [dbo].[APS_DATA] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [LAYOUT_KEY] NCHAR(3) DEFAULT  NOT NULL,
    [SEGMENT_TYPE] NCHAR(3) DEFAULT  NOT NULL,
    [TABLE_NAME] NVARCHAR(18) DEFAULT  NOT NULL,
    [COLUMN_NAME] NVARCHAR(18) DEFAULT  NOT NULL,
    [TYPE] NVARCHAR(8) DEFAULT  NOT NULL,
    [LENGTH] smallint DEFAULT  NOT NULL,
    [SCALE] smallint DEFAULT  NOT NULL,
    [COLNO] smallint DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[APS_DATA] ADD CONSTRAINT [PK_APS_DATA] PRIMARY KEY ([LAYOUT_KEY], [SEGMENT_TYPE], [TABLE_NAME], [COLUMN_NAME]);
