CREATE TABLE [dbo].[DETAIL_TABLE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SUMMARY_TABLE_ID] int DEFAULT  NOT NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [LINE_NO] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[DETAIL_TABLE] ADD CONSTRAINT [PK_DETAIL_TABLE] PRIMARY KEY ([SUMMARY_TABLE_ID], [LINE_NO]);
