CREATE TABLE [dbo].[APPLICATION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [LANGUAGE_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [MENU_STRING] NVARCHAR(40) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [CMD_LINE_ARGS] NVARCHAR(80) DEFAULT  NULL,
    [MODULE] NCHAR(1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[APPLICATION] ADD CONSTRAINT [PK_APPLICATION] PRIMARY KEY ([PROGRAM_ID], [LANGUAGE_ID]);
