CREATE TABLE [dbo].[RECEIVER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PURC_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RECEIVED_DATE] datetime DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [MARKED_FOR_PURGE] NCHAR(1) DEFAULT ('') NOT NULL,
    [SHIP_REASON_CD] NVARCHAR(15) DEFAULT  NULL,
    [CARRIER_ID] NVARCHAR(15) DEFAULT  NULL,
    [BOL_ID] NVARCHAR(20) DEFAULT  NULL,
    [VEND_PACK_ID] NVARCHAR(40) DEFAULT  NULL,
    [VEND_PACK_DATE] datetime DEFAULT  NULL,
    [VEND_FREIGHT_ID] NVARCHAR(40) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[RECEIVER] ADD CONSTRAINT [PK_RECEIVER] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[RECEIVER] ADD CONSTRAINT [FK_RECEIVER_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[RECEIVER] ADD CONSTRAINT [FKEY0167] FOREIGN KEY ([PURC_ORDER_ID]) REFERENCES [dbo].[PURCHASE_ORDER]([ID]);
