CREATE TABLE [dbo].[MACRO_PROFILE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(8) DEFAULT  NOT NULL,
    [MACRO_NAME] NVARCHAR(100) DEFAULT  NOT NULL,
    [PROFILE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[MACRO_PROFILE] ADD CONSTRAINT [PK_MACRO_PROFILE] PRIMARY KEY ([PROGRAM_ID], [MACRO_NAME], [PROFILE_ID]);
