CREATE TABLE [dbo].[CUST_LINE_BILLING] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUST_ORDER_LINE_NO] smallint DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [EVENT_SEQ_NO] smallint DEFAULT  NOT NULL,
    [BILL_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [BILL_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [REV_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [REV_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [MILESTONE_ID] NVARCHAR(15) DEFAULT  NULL,
    [EVENT_DATE] datetime DEFAULT  NULL,
    [TRIGGERED_FLAG] NCHAR(1) DEFAULT  NULL,
    [TRIGGERED_DATE] datetime DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [REV_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [BILLING_BASIS] NCHAR(1) DEFAULT  NULL,
    [REVENUE_STATUS] NCHAR(1) DEFAULT  NULL,
    [DOC_FILE_PATH] NVARCHAR(255) DEFAULT  NULL,
    [DOCUMENT_ID] NVARCHAR(128) DEFAULT  NULL,
    [DISTRIBUTED_DATE] datetime DEFAULT  NULL,
    [DOC_TOTAL_AMOUNT] DECIMAL(23,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[CUST_LINE_BILLING] ADD CONSTRAINT [PK_CUST_LINE_BILLING] PRIMARY KEY ([CUST_ORDER_ID], [CUST_ORDER_LINE_NO], [EVENT_SEQ_NO]);

ALTER TABLE [dbo].[CUST_LINE_BILLING] ADD CONSTRAINT [FKEY9106] FOREIGN KEY ([REV_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[CUST_LINE_BILLING] ADD CONSTRAINT [FKEY9112] FOREIGN KEY ([CUST_ORDER_ID], [CUST_ORDER_LINE_NO]) REFERENCES [dbo].[CUST_ORDER_LINE]([CUST_ORDER_ID], [LINE_NO]);
