CREATE TABLE [dbo].[WORKORDER_SUMMARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SPID] NVARCHAR(15) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [EST_ATL_MAT_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [EST_ATL_LAB_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [EST_ATL_BUR_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [EST_ATL_SER_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [REM_ATL_MAT_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [REM_ATL_LAB_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [REM_ATL_BUR_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [REM_ATL_SER_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [ACT_ATL_MAT_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [ACT_ATL_LAB_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [ACT_ATL_BUR_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [ACT_ATL_SER_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [STATUS] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[WORKORDER_SUMMARY] ADD CONSTRAINT [PK_WORKORD_SUM] PRIMARY KEY ([SPID], [WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID]);
