CREATE TABLE [dbo].[CONTROL_LIMITS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TEST_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [STEP_NO] int DEFAULT  NOT NULL,
    [LIMIT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LIMIT_TYPE] NVARCHAR(4) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [CENTRAL_LINE] DECIMAL(14,6) DEFAULT  NOT NULL,
    [LCL] DECIMAL(14,6) DEFAULT  NOT NULL,
    [UCL] DECIMAL(14,6) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT  NOT NULL,
    [START_SUBGROUP] smallint DEFAULT  NULL,
    [END_SUBGROUP] smallint DEFAULT  NULL,
    [NUM_OF_SUBGRPS] smallint DEFAULT  NULL
)

ALTER TABLE [dbo].[CONTROL_LIMITS] ADD CONSTRAINT [PK_CONTROL_LIMITS] PRIMARY KEY ([TEST_ID], [STEP_NO], [LIMIT_ID], [LIMIT_TYPE]);

ALTER TABLE [dbo].[CONTROL_LIMITS] ADD CONSTRAINT [FKEY0290] FOREIGN KEY ([TEST_ID], [STEP_NO]) REFERENCES [dbo].[TEST_STEP]([TEST_ID], [STEP_NO]);
