CREATE TABLE [dbo].[TRACE_DOCUMENTS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TRACE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [REFERENCE] NVARCHAR(40) DEFAULT  NOT NULL,
    [CERT_FILE_PATH] NVARCHAR(80) DEFAULT  NULL,
    [CERT_DOC_ID] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[TRACE_DOCUMENTS] ADD CONSTRAINT [PK_TRACE_DOCUMENTS] PRIMARY KEY ([TRACE_ID], [REFERENCE]);
