CREATE TABLE [dbo].[SALES_CODE_ENG] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SERIES_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [MODEL_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SALES_CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [ENG_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [COPY_SEQ_NO] smallint DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SALES_CODE_ENG] ADD CONSTRAINT [PK_SALES_CODE_ENG] PRIMARY KEY ([SERIES_ID], [MODEL_ID], [SALES_CODE], [SITE_ID]);

ALTER TABLE [dbo].[SALES_CODE_ENG] ADD CONSTRAINT [FKEY0110] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);

ALTER TABLE [dbo].[SALES_CODE_ENG] ADD CONSTRAINT [FKEY0243] FOREIGN KEY ([SERIES_ID], [MODEL_ID], [SITE_ID]) REFERENCES [dbo].[SERIES_MODEL_PART]([SERIES_ID], [MODEL_ID], [SITE_ID]);
