CREATE TABLE [dbo].[MODE_OF_TRANSPORT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] int DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL
)

ALTER TABLE [dbo].[MODE_OF_TRANSPORT] ADD CONSTRAINT [PK_MODE_OF_TRANSPORT] PRIMARY KEY ([CODE]);
