CREATE TABLE [dbo].[QUOTE_PRICE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [QUOTE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [QUOTE_LINE_NO] smallint DEFAULT  NOT NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [CALC_UNIT_COST] DECIMAL(22,8) DEFAULT  NULL,
    [CALC_UNIT_PRICE] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE] DECIMAL(22,8) DEFAULT  NOT NULL,
    [SELLING_UM] NVARCHAR(15) DEFAULT  NULL,
    [PUR_MATL_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [FAB_MATL_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [LABOR_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [BURDEN_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [SERVICE_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [PUR_MATL_MARKUP] DECIMAL(23,8) DEFAULT  NULL,
    [FAB_MATL_MARKUP] DECIMAL(23,8) DEFAULT  NULL,
    [LABOR_MARKUP] DECIMAL(23,8) DEFAULT  NULL,
    [BURDEN_MARKUP] DECIMAL(23,8) DEFAULT  NULL,
    [SERVICE_MARKUP] DECIMAL(23,8) DEFAULT  NULL,
    [IN_PROFORMA] NCHAR(1) DEFAULT ('') NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [PUR_MATL_GSA] DECIMAL(6,3) DEFAULT  NULL,
    [FAB_MATL_GSA] DECIMAL(6,3) DEFAULT  NULL,
    [LABOR_GSA] DECIMAL(6,3) DEFAULT  NULL,
    [BURDEN_GSA] DECIMAL(6,3) DEFAULT  NULL,
    [SERVICE_GSA] DECIMAL(6,3) DEFAULT  NULL,
    [TRADE_DISC_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [IN_TOTAL] NCHAR(1) DEFAULT ('') NOT NULL,
    [PIECE_COUNT] DECIMAL(20,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[QUOTE_PRICE] ADD CONSTRAINT [PK_QUOTE_PRICE] PRIMARY KEY ([QUOTE_ID], [QUOTE_LINE_NO], [QTY]);

ALTER TABLE [dbo].[QUOTE_PRICE] ADD CONSTRAINT [FKEY0182] FOREIGN KEY ([QUOTE_ID], [QUOTE_LINE_NO]) REFERENCES [dbo].[QUOTE_LINE]([QUOTE_ID], [LINE_NO]);
