CREATE TABLE [dbo].[ACCT_BAL_DIM_BATCH] (
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BATCH_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BATCH_ACTION] NCHAR(1) DEFAULT  NOT NULL,
    [ACCT_YEAR] DECIMAL(4,0) DEFAULT  NULL,
    [ACCT_PERIOD] DECIMAL(2,0) DEFAULT  NULL,
    [FAILED_ATTEMPTS] smallint DEFAULT ((0)) NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)
