CREATE TABLE [dbo].[CASH_DISBURSE_DIST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BANK_ACCOUNT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CONTROL_NO] int DEFAULT  NOT NULL,
    [DIST_NO] smallint DEFAULT  NOT NULL,
    [ENTRY_NO] smallint DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [AMOUNT_TYPE] NCHAR(2) DEFAULT ('') NOT NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [POSTING_STATUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [BATCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [NATIVE] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[CASH_DISBURSE_DIST] ADD CONSTRAINT [PK_CASH_DISBURSE_DIST] PRIMARY KEY ([BANK_ACCOUNT_ID], [CONTROL_NO], [DIST_NO], [ENTRY_NO], [CURRENCY_ID]);

ALTER TABLE [dbo].[CASH_DISBURSE_DIST] ADD CONSTRAINT [FK_DSBDST_BATCH] FOREIGN KEY ([SITE_ID], [BATCH_ID]) REFERENCES [dbo].[JOURNAL_BATCH]([SITE_ID], [ID]);

ALTER TABLE [dbo].[CASH_DISBURSE_DIST] ADD CONSTRAINT [FKEY0023] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[CASH_DISBURSE_DIST] ADD CONSTRAINT [FKEY0202] FOREIGN KEY ([GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[CASH_DISBURSE_DIST] ADD CONSTRAINT [FKEY0229] FOREIGN KEY ([BANK_ACCOUNT_ID], [CONTROL_NO]) REFERENCES [dbo].[CASH_DISBURSEMENT]([BANK_ACCOUNT_ID], [CONTROL_NO]);

ALTER TABLE [dbo].[CASH_DISBURSE_DIST] ADD CONSTRAINT [FKEY9406] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
