CREATE TABLE [dbo].[USER_FLD_AUTHORITY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [PROGRAM_FIELD] NVARCHAR(30) DEFAULT  NOT NULL,
    [PERMISSION] NCHAR(1) DEFAULT ('Y') NOT NULL
)

ALTER TABLE [dbo].[USER_FLD_AUTHORITY] ADD CONSTRAINT [PK_USER_FLD_AUTHORITY] PRIMARY KEY ([USER_ID], [PROGRAM_ID], [PROGRAM_FIELD]);
