CREATE TABLE [dbo].[UDF_LAYOUT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [UDF_LABELS] NVARCHAR(250) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[UDF_LAYOUT] ADD CONSTRAINT [PK_UDF_LAYOUT] PRIMARY KEY ([ID]);
