CREATE TABLE [dbo].[LMC_MRP_POAUTH_LVL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [LVL] int DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(14,4) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[LMC_MRP_POAUTH_LVL] ADD CONSTRAINT [PK_LMC_MRP_POAUTH] PRIMARY KEY ([LVL]);
