CREATE TABLE [dbo].[BUDGET_TYPE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [id] NVARCHAR(15) DEFAULT  NOT NULL,
    [description] NVARCHAR(40) DEFAULT  NULL
)

ALTER TABLE [dbo].[BUDGET_TYPE] ADD CONSTRAINT [pk_BUDGET_TYPE] PRIMARY KEY ([id]);
