CREATE TABLE [dbo].[CONTAINER_TYPE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[CONTAINER_TYPE] ADD CONSTRAINT [PK_CONTAINER_TYPE] PRIMARY KEY ([CODE]);
