CREATE TABLE [dbo].[EQUIP_PM_PROFILE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROFILE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [ENG_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [DESCRIPTION] image DEFAULT  NULL,
    [FREQ_TYPE] NVARCHAR(1) DEFAULT  NULL,
    [FREQUENCY] NVARCHAR(4) DEFAULT  NULL,
    [GIVEN_DAY] int DEFAULT  NULL,
    [GIVEN_DATE] int DEFAULT  NULL,
    [GIVEN_MONTH] int DEFAULT  NULL
)

ALTER TABLE [dbo].[EQUIP_PM_PROFILE] ADD CONSTRAINT [PK_EQ_PM_PROFILE] PRIMARY KEY ([PROFILE_ID]);

ALTER TABLE [dbo].[EQUIP_PM_PROFILE] ADD CONSTRAINT [FKEY9512] FOREIGN KEY ([ENG_ID]) REFERENCES [dbo].[EQUIP_MAINT_ENG]([ID]);
