CREATE TABLE [dbo].[REPORT_CAL_MAP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RPT_CAL_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [FIN_CAL_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BEGIN_ACCT_PERIOD] DECIMAL(2,0) DEFAULT  NOT NULL,
    [END_ACCT_PERIOD] DECIMAL(2,0) DEFAULT  NOT NULL,
    [BEGIN_ACCT_YEAR] DECIMAL(2,0) DEFAULT  NULL,
    [END_ACCT_YEAR] DECIMAL(2,0) DEFAULT  NULL
)

ALTER TABLE [dbo].[REPORT_CAL_MAP] ADD CONSTRAINT [PK_RPT_CAL_MAP] PRIMARY KEY ([RPT_CAL_ID], [FIN_CAL_ID]);

ALTER TABLE [dbo].[REPORT_CAL_MAP] ADD CONSTRAINT [FK_FIN_CAL_MAP] FOREIGN KEY ([FIN_CAL_ID]) REFERENCES [dbo].[FINANCIAL_CALENDAR]([ID]);

ALTER TABLE [dbo].[REPORT_CAL_MAP] ADD CONSTRAINT [FK_RPT_CAL_MAP] FOREIGN KEY ([RPT_CAL_ID]) REFERENCES [dbo].[REPORT_CALENDAR]([ID]);
