CREATE TABLE [dbo].[COST_GROUP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[COST_GROUP] ADD CONSTRAINT [PK_COST_GROUP] PRIMARY KEY ([ID]);
