CREATE TABLE [dbo].[VR_GRID_CONFIG] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(250) DEFAULT  NULL,
    [SCOPE_TYPE] int DEFAULT ('1') NOT NULL,
    [TITLE] NVARCHAR(80) DEFAULT  NULL,
    [DATA_SOURCE_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [STATUS] NCHAR(1) DEFAULT ('D') NOT NULL,
    [GRID_TYPE] NCHAR(1) DEFAULT ('D') NOT NULL,
    [VALUE_COL_NAME] NVARCHAR(80) DEFAULT  NULL,
    [VALUE_AGGR_TYPE] int DEFAULT ((0)) NOT NULL,
    [DEF_TOP_N] int DEFAULT ((0)) NOT NULL,
    [DEF_PERIOD_TYPE] int DEFAULT  NULL,
    [DEF_PERIODS] int DEFAULT  NULL,
    [DEF_HORIZ_PERIODS] int DEFAULT  NULL,
    [DEF_PERIOD_BEGIN] datetime DEFAULT  NULL,
    [DEF_PERIOD_END] datetime DEFAULT  NULL,
    [CREATED_BY] NVARCHAR(20) DEFAULT  NULL,
    [LAST_MODIFIED_BY] NVARCHAR(20) DEFAULT  NULL,
    [LAST_MODIFIED] datetime DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[VR_GRID_CONFIG] ADD CONSTRAINT [PK_VR_GRID_CONFIG] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[VR_GRID_CONFIG] ADD CONSTRAINT [FK_GRID_CFG_TO_DATA_SRC] FOREIGN KEY ([DATA_SOURCE_ID]) REFERENCES [dbo].[VR_DATA_SOURCE]([ID]);
