CREATE TABLE [dbo].[ACCOUNT_CHG_LOG] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TRANSACTION_ID] smallint DEFAULT  NOT NULL,
    [ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [FROM_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [TO_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[ACCOUNT_CHG_LOG] ADD CONSTRAINT [PK_ACCTCHGLOG] PRIMARY KEY ([TRANSACTION_ID]);

ALTER TABLE [dbo].[ACCOUNT_CHG_LOG] ADD CONSTRAINT [FK_ACCTCHGLOG_00] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);
