CREATE TABLE [dbo].[NOTIFICATION_TEMPLATE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [TYPE] NVARCHAR(10) DEFAULT  NOT NULL,
    [MESSAGE] NVARCHAR(2000) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[NOTIFICATION_TEMPLATE] ADD CONSTRAINT [PK_NOTIF_TEMPLATE] PRIMARY KEY ([PROGRAM_ID], [TYPE]);
