CREATE TABLE [dbo].[REQUIREMENT_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [OPERATION_SEQ_NO] smallint DEFAULT  NOT NULL,
    [PIECE_NO] smallint DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[REQUIREMENT_BINARY] ADD CONSTRAINT [PK_REQUIREMENT_BINARY] PRIMARY KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO], [PIECE_NO], [TYPE]);

ALTER TABLE [dbo].[REQUIREMENT_BINARY] ADD CONSTRAINT [FK_REQUIREMENT_BINARY_00] FOREIGN KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO], [PIECE_NO]) REFERENCES [dbo].[REQUIREMENT]([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO], [PIECE_NO]);
