CREATE TABLE [dbo].[ACCOUNT_BALANCE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ACCT_YEAR] DECIMAL(4,0) DEFAULT  NOT NULL,
    [ACCT_PERIOD] DECIMAL(2,0) DEFAULT  NOT NULL,
    [DEBIT_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [CREDIT_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [DEBIT_BUDGET] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [CREDIT_BUDGET] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [FLAG] int DEFAULT ((0)) NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [CURR_BALANCE] DECIMAL(23,8) DEFAULT  NULL,
    [SOA_BAL_SENT] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[ACCOUNT_BALANCE] ADD CONSTRAINT [PK_ACCOUNT_BALANCE] PRIMARY KEY ([ACCOUNT_ID], [SITE_ID], [ACCT_YEAR], [ACCT_PERIOD], [CURRENCY_ID]);

ALTER TABLE [dbo].[ACCOUNT_BALANCE] ADD CONSTRAINT [FKEY0014] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[ACCOUNT_BALANCE] ADD CONSTRAINT [FKEY9408] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
