CREATE TABLE [dbo].[FOB_POINT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(25) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [INTRANSIT_OWNER] NVARCHAR(25) DEFAULT  NULL
)

ALTER TABLE [dbo].[FOB_POINT] ADD CONSTRAINT [PK_FOB_POINT] PRIMARY KEY ([CODE]);
