CREATE TABLE [dbo].[QUOTE_OPT_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [QUOTE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [QUOTE_LINE_NO] int DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [SEQ_NO] int DEFAULT  NOT NULL,
    [BITS_LENGTH] int DEFAULT ((0)) NOT NULL,
    [BITS] image DEFAULT  NULL
)

ALTER TABLE [dbo].[QUOTE_OPT_BINARY] ADD CONSTRAINT [PK_QUOTE_OPT_BINARY] PRIMARY KEY ([QUOTE_ID], [QUOTE_LINE_NO], [TYPE], [SEQ_NO]);
