CREATE TABLE [dbo].[CURRENCY_EXCHANGE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [EFFECTIVE_DATE] datetime DEFAULT  NOT NULL,
    [SELL_RATE] DECIMAL(22,8) DEFAULT  NULL,
    [BUY_RATE] DECIMAL(22,8) DEFAULT  NULL,
    [ENTITY_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CURRENCY_EXCHANGE] ADD CONSTRAINT [PK_CURRENCY_EXCHANGE] PRIMARY KEY ([ENTITY_ID], [CURRENCY_ID], [EFFECTIVE_DATE]);

ALTER TABLE [dbo].[CURRENCY_EXCHANGE] ADD CONSTRAINT [FK_CURR_EXCH_TO_AE] FOREIGN KEY ([ENTITY_ID]) REFERENCES [dbo].[ACCOUNTING_ENTITY]([ID]);

ALTER TABLE [dbo].[CURRENCY_EXCHANGE] ADD CONSTRAINT [FKEY0056] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
