CREATE TABLE [dbo].[IBT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [FROM_WHSE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TO_WHSE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ORDER_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [TRANSIT_DAYS] DECIMAL(14,4) DEFAULT  NULL,
    [DESIRED_RECV_DATE] datetime DEFAULT  NULL,
    [DESIRED_SHIP_DATE] datetime DEFAULT  NULL,
    [BUYER] NVARCHAR(20) DEFAULT  NULL,
    [SHIP_VIA] NVARCHAR(40) DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [RECEIVED_DATE] datetime DEFAULT  NULL,
    [SHIPPED_DATE] datetime DEFAULT  NULL,
    [FREIGHT] DECIMAL(23,8) DEFAULT  NULL,
    [SHIP_REASON_CD] NVARCHAR(15) DEFAULT  NULL,
    [RETURNED_DATE] datetime DEFAULT  NULL,
    [CARRIER_ID] NVARCHAR(15) DEFAULT  NULL,
    [FREIGHT_TERMS] NCHAR(1) DEFAULT  NULL,
    [MARKED_FOR_PURGE] NCHAR(1) DEFAULT ('') NOT NULL,
    [UDF_LAYOUT_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_1] NVARCHAR(80) DEFAULT  NULL,
    [USER_2] NVARCHAR(80) DEFAULT  NULL,
    [USER_3] NVARCHAR(80) DEFAULT  NULL,
    [USER_4] NVARCHAR(80) DEFAULT  NULL,
    [USER_5] NVARCHAR(80) DEFAULT  NULL,
    [USER_6] NVARCHAR(80) DEFAULT  NULL,
    [USER_7] NVARCHAR(80) DEFAULT  NULL,
    [USER_8] NVARCHAR(80) DEFAULT  NULL,
    [USER_9] NVARCHAR(80) DEFAULT  NULL,
    [USER_10] NVARCHAR(80) DEFAULT  NULL,
    [OWNER_ID] NVARCHAR(15) DEFAULT  NULL,
    [DISPATCHED] NCHAR(1) DEFAULT  NULL,
    [CONSIGNED_XFR_TYPE] NCHAR(1) DEFAULT ('N') NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NULL,
    [SHIP_FROM_ADDR_NO] int DEFAULT  NULL,
    [SHIP_TO_ADDR_NO] int DEFAULT  NULL,
    [CONTACT_ID] NVARCHAR(25) DEFAULT  NULL,
    [CONTACT_FIRST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_LAST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_INITIAL] NVARCHAR(2) DEFAULT  NULL,
    [CONTACT_POSITION] NVARCHAR(50) DEFAULT  NULL,
    [CONTACT_HONORIFIC] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_SALUTATION] NVARCHAR(60) DEFAULT  NULL,
    [CONTACT_PHONE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_FAX] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_MOBILE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_EMAIL] NVARCHAR(100) DEFAULT  NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [CONTACT_PHONE_EXT] NVARCHAR(10) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[IBT] ADD CONSTRAINT [PK_IBT] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[IBT] ADD CONSTRAINT [FK_IBT_CONT_ID] FOREIGN KEY ([CONTACT_ID]) REFERENCES [dbo].[CONTACT]([ID]);

ALTER TABLE [dbo].[IBT] ADD CONSTRAINT [FK_IBT_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[IBT] ADD CONSTRAINT [FKEY9609] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);

ALTER TABLE [dbo].[IBT] ADD CONSTRAINT [FKEY9610] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);
