CREATE TABLE [dbo].[QUOTE_PRICING_BIN] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [QUOTE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[QUOTE_PRICING_BIN] ADD CONSTRAINT [PK_QUOTE_PRICING_BIN] PRIMARY KEY ([QUOTE_ID], [TYPE]);
