CREATE TABLE [dbo].[SIZING] (
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [SECTION] NVARCHAR(250) DEFAULT  NOT NULL,
    [ENTRY] NVARCHAR(100) DEFAULT  NOT NULL,
    [VALUE] NVARCHAR(100) DEFAULT  NOT NULL,
    [MODIFY_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SIZING] ADD CONSTRAINT [PK_SIZING] PRIMARY KEY ([USER_ID], [PROGRAM_ID], [SECTION], [ENTRY]);
