CREATE TABLE [dbo].[STAGE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [PROFILE] NCHAR(1) DEFAULT  NULL,
    [ALPHA_PREFIX] NVARCHAR(8) DEFAULT  NULL,
    [STARTING_NUMBER] int DEFAULT  NULL,
    [ENDING_NUMBER] int DEFAULT  NULL,
    [ALPHA_SUFFIX] NVARCHAR(8) DEFAULT  NULL,
    [LEADING_ZEROS] NCHAR(1) DEFAULT  NULL,
    [DECIMAL_PLACES] smallint DEFAULT  NULL,
    [OMIT_LETTERS] NVARCHAR(50) DEFAULT  NULL
)

ALTER TABLE [dbo].[STAGE] ADD CONSTRAINT [PK_STAGE] PRIMARY KEY ([ID]);
