CREATE TABLE [dbo].[GJ_CURR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [GJ_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[GJ_CURR] ADD CONSTRAINT [PK_GJ_CURR] PRIMARY KEY ([GJ_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[GJ_CURR] ADD CONSTRAINT [FKEY9442] FOREIGN KEY ([GJ_ID]) REFERENCES [dbo].[GJ]([ID]);

ALTER TABLE [dbo].[GJ_CURR] ADD CONSTRAINT [FKEY9443] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
