CREATE TABLE [dbo].[DEVIATION_REASON] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [PAID_FLAG] NCHAR(1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[DEVIATION_REASON] ADD CONSTRAINT [PK_DEVIATION_REASON] PRIMARY KEY ([ID]);
