CREATE TABLE [dbo].[DOCUMENT_REF_PATH] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [REFERENCE_TYPE] NVARCHAR(5) DEFAULT  NOT NULL,
    [DOC_FILE_PATH] NVARCHAR(255) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[DOCUMENT_REF_PATH] ADD CONSTRAINT [PK_DOCUMENT_REF_PATH] PRIMARY KEY ([SITE_ID], [ID]);
