CREATE TABLE [dbo].[DATA_EXPORT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [CONTEXT] NCHAR(1) DEFAULT  NOT NULL,
    [START_AT] int DEFAULT  NOT NULL,
    [ABUT_PREVIOUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [DATA_EXPRESSION] NVARCHAR(250) DEFAULT  NOT NULL,
    [DATA_LENGTH] int DEFAULT  NULL,
    [DATA_SCALE] int DEFAULT  NULL,
    [DATA_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [QUOTE_DATA] NCHAR(1) DEFAULT ('') NOT NULL,
    [COMMA_SEPARATE] NCHAR(1) DEFAULT ('') NOT NULL,
    [TERMINATE_RECORD] NCHAR(1) DEFAULT ('') NOT NULL,
    [FIELD_DELIMITER] NCHAR(1) DEFAULT  NULL,
    [TEXT_QUALIFIER] NCHAR(1) DEFAULT  NULL,
    [INDENT_LVL] int DEFAULT  NULL,
    [TAG] NVARCHAR(254) DEFAULT  NULL,
    [IS_ATTRIBUTE] NVARCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[DATA_EXPORT] ADD CONSTRAINT [PK_DATA_EXPORT] PRIMARY KEY ([ID], [TYPE], [CONTEXT], [START_AT]);
