CREATE TABLE [dbo].[USER_DIMENSION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DIMENSION] smallint DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL,
    [IS_SUMMARY] NCHAR(1) DEFAULT ('N') NOT NULL,
    [IS_RESERVED] NCHAR(1) DEFAULT ('N') NOT NULL,
    [PARENT_DIMENSION] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[USER_DIMENSION] ADD CONSTRAINT [PK_USER_DIMENSION] PRIMARY KEY ([DIMENSION], [ID]);
