CREATE TABLE [dbo].[EVENT_TRIGGER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] int DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NULL,
    [BASE_ID] NVARCHAR(30) DEFAULT  NULL,
    [LOT_ID] NVARCHAR(5) DEFAULT  NULL,
    [SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [CLASS] NCHAR(1) DEFAULT  NOT NULL,
    [EVENT_ACTION] NCHAR(1) DEFAULT  NOT NULL,
    [SENDER] NVARCHAR(128) DEFAULT  NULL,
    [SUBJECT] NVARCHAR(128) DEFAULT  NULL,
    [RECIPIENT] NVARCHAR(128) DEFAULT  NULL,
    [FREQUENCY] NCHAR(1) DEFAULT  NOT NULL,
    [FREQ_COUNT] int DEFAULT  NULL,
    [FREQ_DATE] datetime DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[EVENT_TRIGGER] ADD CONSTRAINT [PK_EVENT_TRIGGER] PRIMARY KEY ([ID]);
