CREATE TABLE [dbo].[LABEL_GROUP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [LABEL_TYPE_ID] NVARCHAR(30) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[LABEL_GROUP] ADD CONSTRAINT [PK_LABEL_GROUP] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[LABEL_GROUP] ADD CONSTRAINT [FKEY0299] FOREIGN KEY ([LABEL_TYPE_ID]) REFERENCES [dbo].[LABEL_TYPE]([ID]);
