CREATE TABLE [dbo].[TEST_STEP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TEST_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [STEP_NO] int DEFAULT  NOT NULL,
    [SEQ_NO] int DEFAULT  NOT NULL,
    [TYPE] NVARCHAR(4) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [DECISION_ID] int DEFAULT ((0)) NOT NULL,
    [STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [SAMPLE_SIZE] int DEFAULT  NOT NULL,
    [SUBGROUP_SIZE] int DEFAULT  NOT NULL,
    [NEXT_SUBGROUP_NO] int DEFAULT  NOT NULL,
    [DIMENSION_TYPE] NVARCHAR(40) DEFAULT  NULL,
    [DIMENSION_DESC] NVARCHAR(40) DEFAULT  NULL,
    [CURR_LIMIT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [GAGE_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [FREQUENCY_CODE] NVARCHAR(20) DEFAULT  NULL,
    [DEFECT_CLASS_CODE] NVARCHAR(15) DEFAULT  NULL,
    [SPEC_AIM] DECIMAL(14,6) DEFAULT  NULL,
    [SPEC_LOWER_LIMIT] DECIMAL(14,6) DEFAULT  NULL,
    [SPEC_UPPER_LIMIT] DECIMAL(14,6) DEFAULT  NULL,
    [CONTROL_DIMENSION] NCHAR(4) DEFAULT  NULL,
    [SOLO_DIMENSION] NCHAR(1) DEFAULT ('') NOT NULL,
    [CREATE_DATE] datetime DEFAULT  NOT NULL,
    [LAST_UPDATE] datetime DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[TEST_STEP] ADD CONSTRAINT [PK_TEST_STEP] PRIMARY KEY ([TEST_ID], [STEP_NO]);

ALTER TABLE [dbo].[TEST_STEP] ADD CONSTRAINT [FKEY0244] FOREIGN KEY ([TEST_ID]) REFERENCES [dbo].[TEST]([ID]);

ALTER TABLE [dbo].[TEST_STEP] ADD CONSTRAINT [FKEY0288] FOREIGN KEY ([GAGE_ID]) REFERENCES [dbo].[GAGE]([GAGE_ID]);
