CREATE TABLE [dbo].[CUSTOMER_BOOKINGS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BOOK_DATE] datetime DEFAULT  NOT NULL,
    [ORDER_DATE] datetime DEFAULT  NULL,
    [DESIRED_SHIP_DATE] datetime DEFAULT  NULL,
    [EDI_RELEASE_NO] NVARCHAR(30) DEFAULT  NULL,
    [EDI_ACCUM_SHIP_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [EDI_ACCUM_AUTH_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [EDI_ACCUM_BUY_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [EDI_ACCUM_SHIP_ADJ] DECIMAL(20,8) DEFAULT  NULL,
    [EDI_ACCUM_ORD_ADJ] DECIMAL(20,8) DEFAULT  NULL,
    [EDI_LAST_SHIPDATE] datetime DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [REVISION_ID] NVARCHAR(8) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CUSTOMER_BOOKINGS] ADD CONSTRAINT [PK_CUSTOMER_BOOKINGS] PRIMARY KEY ([CUST_ORDER_ID], [BOOK_DATE]);
