CREATE TABLE [dbo].[FOB_POINT_SYNC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EVENT_ID] int DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [FOB_POINT_CODE] NVARCHAR(25) DEFAULT  NOT NULL,
    [EXCEPTION] NCHAR(1) DEFAULT  NOT NULL,
    [SUBSCRIPTIONS] int DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[FOB_POINT_SYNC] ADD CONSTRAINT [PK_FOB_POINT_SYNC] PRIMARY KEY ([EVENT_ID]);
