CREATE TABLE [dbo].[WORKORDER_TRC_CTL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [OWNER_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[WORKORDER_TRC_CTL] ADD CONSTRAINT [PK_WORKORDER_TRC_CTL] PRIMARY KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID]);
