CREATE TABLE [dbo].[BURD_DIST_DETAIL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BURDEN_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [BURDEN_CATEGORY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SOURCE_TYPE] NVARCHAR(20) DEFAULT  NOT NULL,
    [SOURCE_TRANS_ID] int DEFAULT ((0)) NOT NULL,
    [SOURCE_ID] NVARCHAR(30) DEFAULT ('') NOT NULL,
    [SOURCE_LINE_NO] smallint DEFAULT ((0)) NOT NULL,
    [DIST_NO] smallint DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [IS_RETRO] NCHAR(1) DEFAULT ('') NOT NULL
)

ALTER TABLE [dbo].[BURD_DIST_DETAIL] ADD CONSTRAINT [PK_BURD_DIST_DETAIL] PRIMARY KEY ([BURDEN_ID], [BURDEN_CATEGORY_ID], [SOURCE_TYPE], [SOURCE_TRANS_ID], [SOURCE_ID], [SOURCE_LINE_NO], [DIST_NO], [CURRENCY_ID]);

ALTER TABLE [dbo].[BURD_DIST_DETAIL] ADD CONSTRAINT [FK_BURD_DIST_DETAIL_00] FOREIGN KEY ([BURDEN_CATEGORY_ID]) REFERENCES [dbo].[COST_CATEGORY]([ID]);

ALTER TABLE [dbo].[BURD_DIST_DETAIL] ADD CONSTRAINT [FK_BURD_DIST_DETAIL_01] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
