CREATE TABLE [dbo].[V_TASK_ACTIVITY_TYPE] (
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT  NULL,
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[V_TASK_ACTIVITY_TYPE] ADD CONSTRAINT [X_V_TASK_ACT_TYPE_0] PRIMARY KEY ([ID]);
