CREATE TABLE [dbo].[BID_RATE_CATEGORY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[BID_RATE_CATEGORY] ADD CONSTRAINT [PK_BID_RATE_CATEGORY] PRIMARY KEY ([ID]);
