CREATE TABLE [dbo].[tmpPOLines] (
    [vendor_id] NVARCHAR(15) DEFAULT  NOT NULL,
    [purc_order_id] NVARCHAR(15) DEFAULT  NOT NULL,
    [line_no] smallint DEFAULT  NOT NULL,
    [POStatus] NCHAR(1) DEFAULT  NOT NULL,
    [service_id] NVARCHAR(15) DEFAULT  NULL,
    [part_id] NVARCHAR(30) DEFAULT  NULL,
    [gl_expense_acct_id] NVARCHAR(30) DEFAULT  NULL,
    [vendor_part_id] NVARCHAR(30) DEFAULT  NULL,
    [mfg_name] NVARCHAR(30) DEFAULT  NULL,
    [mfg_part_id] NVARCHAR(30) DEFAULT  NULL,
    [order_qty] DECIMAL(20,8) DEFAULT  NOT NULL,
    [total_received_qty] DECIMAL(20,8) DEFAULT  NOT NULL,
    [unit_price] DECIMAL(22,8) DEFAULT  NOT NULL,
    [purchase_um] NVARCHAR(15) DEFAULT  NULL,
    [fixed_charge] DECIMAL(23,8) DEFAULT  NULL,
    [est_freight] DECIMAL(23,8) DEFAULT  NOT NULL,
    [department_id] NVARCHAR(15) DEFAULT  NULL,
    [commodity_code] NVARCHAR(15) DEFAULT  NULL,
    [product_code] NVARCHAR(15) DEFAULT  NULL,
    [desired_recv_date] datetime DEFAULT  NULL,
    [promise_date] datetime DEFAULT  NULL,
    [promise_ship_date] int DEFAULT  NULL,
    [line_status] NCHAR(1) DEFAULT  NOT NULL,
    [receiver_id] NVARCHAR(15) DEFAULT  NULL,
    [RcvLn] smallint DEFAULT  NULL,
    [RcvrUnitPrice] DECIMAL(22,8) DEFAULT  NULL,
    [landed_unit_price] DECIMAL(22,8) DEFAULT  NULL,
    [serv_trans_id] int DEFAULT  NULL,
    [RcvrFixedChg] DECIMAL(23,8) DEFAULT  NULL,
    [invoice_id] NVARCHAR(15) DEFAULT  NULL,
    [invoiced_date] datetime DEFAULT  NULL,
    [received_qty] DECIMAL(20,8) DEFAULT  NULL,
    [rejected_qty] DECIMAL(20,8) DEFAULT  NULL,
    [transaction_date] datetime DEFAULT  NULL,
    [transaction_id] int DEFAULT  NULL,
    [act_service_cost] DECIMAL(23,8) DEFAULT  NULL,
    [act_burden_cost] DECIMAL(23,8) DEFAULT  NULL,
    [act_freight] DECIMAL(23,8) DEFAULT  NULL,
    [bad_qty] DECIMAL(20,8) DEFAULT  NULL,
    [good_qty] DECIMAL(20,8) DEFAULT  NULL,
    [TxServiceID] NVARCHAR(15) DEFAULT  NULL,
    [TxServPartID] NVARCHAR(30) DEFAULT  NULL,
    [unit_cost] DECIMAL(22,8) DEFAULT  NULL,
    [DslBase] NVARCHAR(30) DEFAULT  NULL,
    [DslLot] NVARCHAR(15) DEFAULT  NULL,
    [DslSplit] NVARCHAR(3) DEFAULT  NULL,
    [DslSub] NVARCHAR(3) DEFAULT  NULL,
    [DslSeq] int DEFAULT  NULL,
    [TxVendor] NVARCHAR(15) DEFAULT  NULL
)
