CREATE TABLE [dbo].[WIP_RECEIPT_DETAIL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [DIST_NO] smallint DEFAULT  NOT NULL,
    [TRANSACTION_ID] int DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [PRODUCT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [FLAG] NCHAR(1) DEFAULT  NOT NULL,
    [ACT_MATERIAL_COST] DECIMAL(23,8) DEFAULT  NULL,
    [ACT_LABOR_COST] DECIMAL(23,8) DEFAULT  NULL,
    [ACT_BURDEN_COST] DECIMAL(23,8) DEFAULT  NULL,
    [ACT_SERVICE_COST] DECIMAL(23,8) DEFAULT  NULL,
    [VAR_MATERIAL_COST] DECIMAL(23,8) DEFAULT  NULL,
    [VAR_LABOR_COST] DECIMAL(23,8) DEFAULT  NULL,
    [VAR_BURDEN_COST] DECIMAL(23,8) DEFAULT  NULL,
    [VAR_SERVICE_COST] DECIMAL(23,8) DEFAULT  NULL,
    [REFERENCE] NVARCHAR(50) DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [DR_MAT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [DR_LAB_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [DR_BUR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [DR_SER_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CR_MAT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CR_LAB_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CR_BUR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CR_SER_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[WIP_RECEIPT_DETAIL] ADD CONSTRAINT [PK_WIP_RECEIPT_DETAIL] PRIMARY KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [DIST_NO], [TRANSACTION_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[WIP_RECEIPT_DETAIL] ADD CONSTRAINT [FKEY9008] FOREIGN KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID]) REFERENCES [dbo].[WORK_ORDER]([TYPE], [BASE_ID], [LOT_ID], [SPLIT_ID], [SUB_ID]);

ALTER TABLE [dbo].[WIP_RECEIPT_DETAIL] ADD CONSTRAINT [FKEY9451] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
