CREATE TABLE [dbo].[ACCOUNT_AT_NATIVE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ACCT_YEAR] DECIMAL(4,0) DEFAULT  NOT NULL,
    [ACCT_PERIOD] DECIMAL(2,0) DEFAULT  NOT NULL,
    [DEBIT_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [CREDIT_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[ACCOUNT_AT_NATIVE] ADD CONSTRAINT [PK_ACCT_NTV] PRIMARY KEY ([ACCOUNT_ID], [SITE_ID], [ACCT_YEAR], [ACCT_PERIOD], [CURRENCY_ID]);

ALTER TABLE [dbo].[ACCOUNT_AT_NATIVE] ADD CONSTRAINT [FKEY9409] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
