CREATE TABLE [dbo].[VENDOR_SERVICE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SERVICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [VENDOR_SERVICE_ID] NVARCHAR(30) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [EST_COST_PER_UNIT] DECIMAL(22,8) DEFAULT ((0)) NOT NULL,
    [EST_MIN_CHARGE] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [EST_BASE_CHARGE] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [VAT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [SCHEDULE_RANK] smallint DEFAULT  NULL,
    [RUN] DECIMAL(20,8) DEFAULT  NULL,
    [RUN_TYPE] NVARCHAR(15) DEFAULT  NULL,
    [LOAD_SIZE_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [TRANSIT_DAYS] DECIMAL(6,3) DEFAULT  NULL,
    [PURCHASE_UM] NVARCHAR(15) DEFAULT  NULL,
    [LONG_DESCRIPTION] image DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[VENDOR_SERVICE] ADD CONSTRAINT [PK_VENDOR_SERVICE] PRIMARY KEY ([SITE_ID], [SERVICE_ID], [VENDOR_ID]);

ALTER TABLE [dbo].[VENDOR_SERVICE] ADD CONSTRAINT [FK_VEND_SERV_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
