CREATE TABLE [dbo].[VAT_CATEGORY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CATEGORY_TYPE] NVARCHAR(1) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL
)

ALTER TABLE [dbo].[VAT_CATEGORY] ADD CONSTRAINT [PK_VAT_CATEGORY] PRIMARY KEY ([ID]);
