CREATE TABLE [dbo].[PASSWORD_CONFIG] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USE_DIFF_PASS] NCHAR(1) DEFAULT  NULL,
    [RETIRE_PASSWORD] NCHAR(1) DEFAULT  NULL,
    [RETIRE_PASS_DAYS] int DEFAULT  NULL,
    [REUSE_PASSWORD] NCHAR(1) DEFAULT  NULL,
    [REUSE_AFTER] int DEFAULT  NULL,
    [MINIMUM_LENGTH] smallint DEFAULT  NULL,
    [MINIMUM_DIGITS] smallint DEFAULT  NULL,
    [MINIMUM_LETTERS] smallint DEFAULT  NULL,
    [MINIMUM_UPPER] smallint DEFAULT  NULL,
    [MINIMUM_LOWER] smallint DEFAULT  NULL,
    [MINIMUM_SPECIAL] smallint DEFAULT  NULL,
    [RETRIES_ALLOWED] smallint DEFAULT  NULL,
    [MINS_BEFORE_RETRY] smallint DEFAULT  NULL,
    [PASSWORD_RESET] NCHAR(1) DEFAULT  NULL
)
