CREATE TABLE [dbo].[PAYB_LINE_CURR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VOUCHER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [ACT_MATERIAL_COST_MFG] DECIMAL(23,8) DEFAULT  NULL,
    [ACT_LABOR_COST_MFG] DECIMAL(23,8) DEFAULT  NULL,
    [ACT_BURDEN_COST_MFG] DECIMAL(23,8) DEFAULT  NULL,
    [ACT_SERVICE_COST_MFG] DECIMAL(23,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[PAYB_LINE_CURR] ADD CONSTRAINT [PK_PAYB_LINE_CURR] PRIMARY KEY ([VOUCHER_ID], [LINE_NO], [CURRENCY_ID]);

ALTER TABLE [dbo].[PAYB_LINE_CURR] ADD CONSTRAINT [FKEY9428] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[PAYB_LINE_CURR] ADD CONSTRAINT [FKEY9429] FOREIGN KEY ([VOUCHER_ID], [LINE_NO]) REFERENCES [dbo].[PAYABLE_LINE]([VOUCHER_ID], [LINE_NO]);
