CREATE TABLE [dbo].[CNSN_RCVR_LINE_DEL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RECEIVER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RECEIVER_LINE_NO] smallint DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [PURC_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PURC_ORDER_LINE_NO] smallint DEFAULT  NOT NULL,
    [PURC_DEL_LINE_NO] smallint DEFAULT  NOT NULL,
    [USER_RECEIVED_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [RECEIVED_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [PIECE_COUNT] DECIMAL(20,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[CNSN_RCVR_LINE_DEL] ADD CONSTRAINT [PK_CNSN_RCVR_LINE_DEL] PRIMARY KEY ([RECEIVER_ID], [RECEIVER_LINE_NO], [LINE_NO]);

ALTER TABLE [dbo].[CNSN_RCVR_LINE_DEL] ADD CONSTRAINT [FKEY9617] FOREIGN KEY ([RECEIVER_ID], [RECEIVER_LINE_NO]) REFERENCES [dbo].[CONSIGN_RCVR_LINE]([RECEIVER_ID], [LINE_NO]);

ALTER TABLE [dbo].[CNSN_RCVR_LINE_DEL] ADD CONSTRAINT [FKEY9618] FOREIGN KEY ([PURC_ORDER_ID], [PURC_ORDER_LINE_NO], [PURC_DEL_LINE_NO]) REFERENCES [dbo].[PURC_LINE_DEL]([PURC_ORDER_ID], [PURC_ORDER_LINE_NO], [DEL_SCHED_LINE_NO]);
