CREATE TABLE [dbo].[CUSTOMER_CONTACT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CONTACT_NO] smallint DEFAULT  NOT NULL,
    [CONTACT_FIRST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_LAST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_POSITION] NVARCHAR(50) DEFAULT  NULL,
    [CONTACT_INITIAL] NVARCHAR(2) DEFAULT  NULL,
    [CONTACT_HONORIFIC] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_PHONE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_FAX] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_MOBILE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_EMAIL] NVARCHAR(100) DEFAULT  NULL,
    [web_user_id] NVARCHAR(20) DEFAULT  NULL,
    [web_password] NVARCHAR(20) DEFAULT  NULL
)

ALTER TABLE [dbo].[CUSTOMER_CONTACT] ADD CONSTRAINT [PK_CUSTOMER_CONTACT] PRIMARY KEY ([CUSTOMER_ID], [CONTACT_NO]);

ALTER TABLE [dbo].[CUSTOMER_CONTACT] ADD CONSTRAINT [FKEY0064] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);
