CREATE TABLE [dbo].[NOTIFICATION_TOKEN] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [TYPE] NVARCHAR(10) DEFAULT  NOT NULL,
    [TOKEN] NVARCHAR(30) DEFAULT  NOT NULL,
    [TOKEN_TABLE] NVARCHAR(50) DEFAULT  NOT NULL,
    [TOKEN_COLUMN] NVARCHAR(200) DEFAULT  NOT NULL,
    [SELECTED_TOKEN] NCHAR(1) DEFAULT ('N') NOT NULL,
    [DATA_FORMAT_TYPE] NCHAR(1) DEFAULT ('S') NOT NULL,
    [MIN_DECIMAL_POSITIONS] NCHAR(1) DEFAULT ('0') NOT NULL,
    [CALCULATED_VALUE] NCHAR(1) DEFAULT ('N') NOT NULL
)

ALTER TABLE [dbo].[NOTIFICATION_TOKEN] ADD CONSTRAINT [PK_NOTIF_TOKEN] PRIMARY KEY ([PROGRAM_ID], [TYPE], [TOKEN]);
