CREATE TABLE [dbo].[CUST_ORD_PRICING_BIN] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CUST_ORD_PRICING_BIN] ADD CONSTRAINT [PK_CUST_ORD_PRICING_BIN] PRIMARY KEY ([CUST_ORDER_ID], [TYPE]);
