CREATE TABLE [dbo].[TC_MASTER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [PRINT_TYPE] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[TC_MASTER] ADD CONSTRAINT [PK_TC_MASTER] PRIMARY KEY ([ID]);
