CREATE TABLE [dbo].[ECN_DETAIL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ECN_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] int DEFAULT  NOT NULL,
    [ENTRY_NO] smallint DEFAULT  NOT NULL,
    [DETAIL_TYPE] int DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [OPERATION_SEQ_NO] int DEFAULT  NULL,
    [REQ_PIECE_NO] int DEFAULT  NULL,
    [CHILD_NOTIFY] NCHAR(1) DEFAULT ('N') NOT NULL,
    [LOCK_NOTIFY] NCHAR(1) DEFAULT ('Y') NOT NULL,
    [ECN_ACTION] NCHAR(1) DEFAULT ('E') NOT NULL,
    [RESTORED] NCHAR(1) DEFAULT ('N') NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [COMMENTS] NVARCHAR(250) DEFAULT  NULL
)

ALTER TABLE [dbo].[ECN_DETAIL] ADD CONSTRAINT [PK_ECN_DETAIL] PRIMARY KEY ([ECN_ID], [LINE_NO], [ENTRY_NO]);
