CREATE TABLE [dbo].[CO_PRODUCT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [MAT_COST_PERCENT] DECIMAL(6,3) DEFAULT  NOT NULL,
    [DESIRED_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [RECEIVED_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [LINE_STATUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [LAB_COST_PERCENT] DECIMAL(6,3) DEFAULT  NOT NULL,
    [BUR_COST_PERCENT] DECIMAL(6,3) DEFAULT  NOT NULL,
    [SER_COST_PERCENT] DECIMAL(6,3) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [WIP_VAS_REQUIRED] NCHAR(1) DEFAULT  NULL,
    [ALLOCATED_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [FULFILLED_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [QTY_IS_RATIO] NCHAR(1) DEFAULT  NULL,
    [QTY_PER] DECIMAL(20,8) DEFAULT  NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[CO_PRODUCT] ADD CONSTRAINT [PK_CO_PRODUCT] PRIMARY KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [PART_ID]);

ALTER TABLE [dbo].[CO_PRODUCT] ADD CONSTRAINT [FKEY0094] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);

ALTER TABLE [dbo].[CO_PRODUCT] ADD CONSTRAINT [FKEY0136] FOREIGN KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID]) REFERENCES [dbo].[WORK_ORDER]([TYPE], [BASE_ID], [LOT_ID], [SPLIT_ID], [SUB_ID]);
