CREATE TABLE [dbo].[RECEIVABLE_SCHED] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PROMISE_DATE] datetime DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[RECEIVABLE_SCHED] ADD CONSTRAINT [PK_RECEIVABLE_SCHED] PRIMARY KEY ([INVOICE_ID], [PROMISE_DATE]);
