CREATE TABLE [dbo].[PART_CROSS_SELLING] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [CROSS_SELL_PART_ID] NVARCHAR(30) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PART_CROSS_SELLING] ADD CONSTRAINT [PK_PART_X_SELLING] PRIMARY KEY ([PART_ID], [CROSS_SELL_PART_ID]);
