CREATE TABLE [dbo].[EQUIP_MAINT_ENG] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL
)

ALTER TABLE [dbo].[EQUIP_MAINT_ENG] ADD CONSTRAINT [PK_EQ_MAINT_ENG] PRIMARY KEY ([ID]);
