CREATE TABLE [dbo].[PACKAGE_TYPE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(5) DEFAULT  NOT NULL,
    [LENGTH] DECIMAL(14,4) DEFAULT  NULL,
    [WIDTH] DECIMAL(14,4) DEFAULT  NULL,
    [HEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [UNIT_OF_MEASURE] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[PACKAGE_TYPE] ADD CONSTRAINT [PK_PACKAGE_TYPE] PRIMARY KEY ([CODE]);
