CREATE TABLE [dbo].[VR_RECEIVABLE_HDR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [INVOICE_DATE] datetime DEFAULT  NULL,
    [LAST_PAID_DATE] datetime DEFAULT  NULL,
    [ZERO_DATE] datetime DEFAULT  NULL,
    [POSTING_DATE] datetime DEFAULT  NULL,
    [DUE_DATE] datetime DEFAULT  NULL,
    [TOTAL_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [PAID_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [DISCOUNT_GIVEN] DECIMAL(23,8) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NULL,
    [CUSTOMER_NAME] NVARCHAR(50) DEFAULT  NULL,
    [SALESREP_ID] NVARCHAR(15) DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT  NULL,
    [INVOICE_STYLE] NVARCHAR(20) DEFAULT  NULL
)
