CREATE TABLE [dbo].[EMPLOYEE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LAST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [FIRST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [MIDDLE_INITIAL] NCHAR(2) DEFAULT  NULL,
    [ADDR_1] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_2] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_3] NVARCHAR(50) DEFAULT  NULL,
    [CITY] NVARCHAR(30) DEFAULT  NULL,
    [STATE] NVARCHAR(10) DEFAULT  NULL,
    [ZIPCODE] NVARCHAR(10) DEFAULT  NULL,
    [COUNTRY] NVARCHAR(50) DEFAULT  NULL,
    [EMPLOYEE_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [PHONE] NVARCHAR(20) DEFAULT  NULL,
    [TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [DEPARTMENT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ACTIVE] NCHAR(1) DEFAULT ('') NOT NULL,
    [SHIFT_ID] NVARCHAR(15) DEFAULT  NULL,
    [EARNING_CODE_ID] NVARCHAR(15) DEFAULT  NULL,
    [COST_CATEGORY_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NULL,
    [EMAIL_ADDR] NVARCHAR(100) DEFAULT  NULL,
    [PAYROLL_SITE_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[EMPLOYEE] ADD CONSTRAINT [PK_EMPLOYEE] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[EMPLOYEE] ADD CONSTRAINT [FKEY0050] FOREIGN KEY ([EARNING_CODE_ID]) REFERENCES [dbo].[EARNING_CODE]([ID]);

ALTER TABLE [dbo].[EMPLOYEE] ADD CONSTRAINT [FKEY0263] FOREIGN KEY ([SHIFT_ID]) REFERENCES [dbo].[SHIFT]([ID]);
