CREATE TABLE [dbo].[WO_SETUP_ATTRIB] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [ATTRIBUTE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [NUMERIC_VALUE] DECIMAL(23,8) DEFAULT  NULL,
    [ALPHA_VALUE] NVARCHAR(30) DEFAULT  NULL,
    [DATE_VALUE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[WO_SETUP_ATTRIB] ADD CONSTRAINT [PK_WO_SETUP_ATTRIB] PRIMARY KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [ATTRIBUTE_ID]);
