CREATE TABLE [dbo].[LMC_MRP_USERS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] VARCHAR(30) DEFAULT  NOT NULL,
    [LAST_LOGIN] datetime DEFAULT  NULL,
    [MPS] CHAR(1) DEFAULT  NOT NULL,
    [KEY] VARCHAR(30) DEFAULT  NULL,
    [NETWORK_ADDRESS] VARCHAR(120) DEFAULT  NULL
)

ALTER TABLE [dbo].[LMC_MRP_USERS] ADD CONSTRAINT [PK_LMC_MRP_USERS] PRIMARY KEY ([USER_ID]);
