CREATE TABLE [dbo].[REQUIREMENT_COST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [OPERATION_SEQ_NO] smallint DEFAULT  NOT NULL,
    [REQ_PIECE_NO] smallint DEFAULT  NOT NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [UNIT_COST] DECIMAL(22,8) DEFAULT  NOT NULL,
    [FIXED_COST] DECIMAL(23,8) DEFAULT  NOT NULL,
    [MINIMUM_COST] DECIMAL(23,8) DEFAULT  NULL,
    [LEADTIME] smallint DEFAULT  NULL
)

ALTER TABLE [dbo].[REQUIREMENT_COST] ADD CONSTRAINT [PK_REQUIREMENT_COST] PRIMARY KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO], [REQ_PIECE_NO], [QTY]);

ALTER TABLE [dbo].[REQUIREMENT_COST] ADD CONSTRAINT [FKEY0140] FOREIGN KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO], [REQ_PIECE_NO]) REFERENCES [dbo].[REQUIREMENT]([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO], [PIECE_NO]);
