CREATE TABLE [dbo].[LMC_MRP_EXCEPTION_LOCK] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DOCUMENT] VARCHAR(80) DEFAULT  NOT NULL,
    [LOCKED] int DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [CREATE_USER] VARCHAR(80) DEFAULT  NOT NULL,
    [LAST_UPDATED] datetime DEFAULT  NULL,
    [LAST_UPDATED_BY] VARCHAR(80) DEFAULT  NULL,
    [COMMENTS] VARCHAR(800) DEFAULT  NULL
)

ALTER TABLE [dbo].[LMC_MRP_EXCEPTION_LOCK] ADD CONSTRAINT [PK_LMC_MRP_EXCEPTION_LOCK] PRIMARY KEY ([DOCUMENT]);
