CREATE TABLE [dbo].[DOCUMENT_REFERENCE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DOCUMENT_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT  NULL,
    [SOURCE_TYPE] NCHAR(1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[DOCUMENT_REFERENCE] ADD CONSTRAINT [PK_DOCUMENT_REFERENCE] PRIMARY KEY ([ID], [DOCUMENT_ID], [LINE_NO], [SOURCE_TYPE]);
