CREATE TABLE [dbo].[NOTATION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TYPE] NCHAR(2) DEFAULT  NOT NULL,
    [OWNER_ID] NVARCHAR(40) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT  NOT NULL,
    [NOTE] image DEFAULT  NULL
)

ALTER TABLE [dbo].[NOTATION] ADD CONSTRAINT [PK_NOTATION] PRIMARY KEY ([TYPE], [OWNER_ID], [CREATE_DATE]);
