CREATE TABLE [dbo].[BUFFER_STAT_WO_LOC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BUFFER_STATUS_ID] int DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [OPERATION_SEQ_NO] smallint DEFAULT  NOT NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NULL,
    [RES_PROCESSING_OP] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[BUFFER_STAT_WO_LOC] ADD CONSTRAINT [PK_BUFFER_STAT_WO_LOC] PRIMARY KEY ([BUFFER_STATUS_ID], [WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO]);

ALTER TABLE [dbo].[BUFFER_STAT_WO_LOC] ADD CONSTRAINT [FKEY_BUFSTWO_OPER] FOREIGN KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO]) REFERENCES [dbo].[OPERATION]([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [SEQUENCE_NO]);
