CREATE TABLE [dbo].[LMC_MRP_DATES] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DOCUMENT] VARCHAR(80) DEFAULT  NOT NULL,
    [PART_ID] VARCHAR(40) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] VARCHAR(15) DEFAULT  NOT NULL,
    [EARLIEST_DATE] datetime DEFAULT  NULL,
    [MOVE_TO_DATE] datetime DEFAULT  NULL,
    [REQ_ROWID] int DEFAULT  NOT NULL,
    [RECORD_TYPE] CHAR(1) DEFAULT  NOT NULL,
    [HIST_INFO] VARCHAR(MAX) DEFAULT  NULL
)

ALTER TABLE [dbo].[LMC_MRP_DATES] ADD CONSTRAINT [PK_LMC_MRP_DATES] PRIMARY KEY ([DOCUMENT], [REQ_ROWID]);
