CREATE TABLE [dbo].[PLANNED_ORDER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SEQ_NO] int DEFAULT  NOT NULL,
    [WANT_DATE] datetime DEFAULT  NULL,
    [ORDER_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [MAIN_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [MAIN_SEQ_NO] smallint DEFAULT  NULL,
    [SCHEDULE_ID] NVARCHAR(15) DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [WBS_CODE] NVARCHAR(30) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PLANNED_ORDER] ADD CONSTRAINT [FK_PLND_ORD_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[PLANNED_ORDER] ADD CONSTRAINT [FKEY0098] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);
