CREATE TABLE [dbo].[COR_OUTBOX_HEADERS] (
    [C_ID] bigint IDENTITY(1,1) DEFAULT  NOT NULL,
    [C_OUTBOX_ID] bigint DEFAULT  NOT NULL,
    [C_HEADER_KEY] NVARCHAR(250) DEFAULT  NOT NULL,
    [C_HEADER_VALUE] NVARCHAR(250) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[COR_OUTBOX_HEADERS] ADD CONSTRAINT [PK_COR_OUTBOX_HEADERS] PRIMARY KEY ([C_ID]);

ALTER TABLE [dbo].[COR_OUTBOX_HEADERS] ADD CONSTRAINT [FK_COR_OUTBOX_ENTRY] FOREIGN KEY ([C_OUTBOX_ID]) REFERENCES [dbo].[COR_OUTBOX_ENTRY]([C_ID]);
