CREATE TABLE [dbo].[EC_TYPES] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[EC_TYPES] ADD CONSTRAINT [PK_EC_TYPES] PRIMARY KEY ([CODE]);
