CREATE TABLE [dbo].[V_TASK_BINARY] (
    [TASK_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NVARCHAR(3) DEFAULT ('') NOT NULL,
    [BITS_LENGTH] int DEFAULT ((0)) NOT NULL,
    [LAST_MODIFIED] datetime DEFAULT  NULL,
    [LAST_USER] NVARCHAR(20) DEFAULT  NULL,
    [BITS] image DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[V_TASK_BINARY] ADD CONSTRAINT [X_V_TASK_BINARY_0] PRIMARY KEY ([TASK_ID], [TYPE]);
