CREATE TABLE [dbo].[DISCOUNT_PRICE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DISCOUNT_CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SELLING_UM] NVARCHAR(15) DEFAULT  NOT NULL,
    [QTY_BREAK_1] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_2] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_3] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_4] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_5] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_6] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_7] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_8] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_9] DECIMAL(20,8) DEFAULT  NULL,
    [QTY_BREAK_10] DECIMAL(20,8) DEFAULT  NULL,
    [UNIT_PRICE_1] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_2] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_3] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_4] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_5] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_6] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_7] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_8] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_9] DECIMAL(22,8) DEFAULT  NULL,
    [UNIT_PRICE_10] DECIMAL(22,8) DEFAULT  NULL,
    [DEFAULT_UNIT_PRICE] DECIMAL(22,8) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[DISCOUNT_PRICE] ADD CONSTRAINT [PK_DISCOUNT_PRICE] PRIMARY KEY ([DISCOUNT_CODE], [SITE_ID], [PART_ID], [SELLING_UM]);

ALTER TABLE [dbo].[DISCOUNT_PRICE] ADD CONSTRAINT [FK_DISCOUNT_PRICE_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[DISCOUNT_PRICE] ADD CONSTRAINT [FKEY0071] FOREIGN KEY ([DISCOUNT_CODE]) REFERENCES [dbo].[CUSTOMER_DISCOUNT]([DISCOUNT_CODE]);

ALTER TABLE [dbo].[DISCOUNT_PRICE] ADD CONSTRAINT [FKEY0089] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);

ALTER TABLE [dbo].[DISCOUNT_PRICE] ADD CONSTRAINT [FKEY0261] FOREIGN KEY ([SELLING_UM]) REFERENCES [dbo].[UNITS]([UNIT_OF_MEASURE]);
