CREATE TABLE [dbo].[RECEIVER_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RECEIVER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[RECEIVER_BINARY] ADD CONSTRAINT [PK_RECEIVER_BINARY] PRIMARY KEY ([RECEIVER_ID], [TYPE]);
