CREATE TABLE [dbo].[LANG_DESCRIPTION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [LANGUAGE_ID] NVARCHAR(2) DEFAULT  NOT NULL,
    [PART_DESCRIPTION] NVARCHAR(120) DEFAULT  NULL
)

ALTER TABLE [dbo].[LANG_DESCRIPTION] ADD CONSTRAINT [PK_LANG_DESC] PRIMARY KEY ([PART_ID], [LANGUAGE_ID]);

ALTER TABLE [dbo].[LANG_DESCRIPTION] ADD CONSTRAINT [FKEY9534] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);

ALTER TABLE [dbo].[LANG_DESCRIPTION] ADD CONSTRAINT [FKEY9535] FOREIGN KEY ([LANGUAGE_ID]) REFERENCES [dbo].[LANGUAGE]([ID]);
