CREATE TABLE [dbo].[DEMAND_SUPPLY_LINK] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] int DEFAULT  NOT NULL,
    [DEMAND_SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DEMAND_TYPE] NVARCHAR(2) DEFAULT  NOT NULL,
    [DEMAND_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [DEMAND_LOT_ID] NVARCHAR(15) DEFAULT  NULL,
    [DEMAND_SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [DEMAND_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [DEMAND_SEQ_NO] int DEFAULT  NULL,
    [DEMAND_NO] int DEFAULT  NULL,
    [SUPPLY_SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SUPPLY_TYPE] NVARCHAR(2) DEFAULT  NOT NULL,
    [SUPPLY_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SUPPLY_LOT_ID] NVARCHAR(15) DEFAULT  NULL,
    [SUPPLY_SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [SUPPLY_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [SUPPLY_SEQ_NO] int DEFAULT  NULL,
    [SUPPLY_NO] int DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [DEMAND_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [SUPPLY_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [ALLOCATED_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [RECEIVED_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [ISSUED_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [SUPPLY_MODE] NCHAR(1) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NULL,
    [TYPE] NCHAR(1) DEFAULT  NULL,
    [REALLOCATE] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[DEMAND_SUPPLY_LINK] ADD CONSTRAINT [PK_DEMAND_SUPPLY] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[DEMAND_SUPPLY_LINK] ADD CONSTRAINT [FK_DSL_DEMAND_TO_SITE] FOREIGN KEY ([DEMAND_SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[DEMAND_SUPPLY_LINK] ADD CONSTRAINT [FK_DSL_SUPPLY_TO_SITE] FOREIGN KEY ([SUPPLY_SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
