CREATE TABLE [dbo].[REPORT_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [REPORT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [ACCOUNT_ID_RANGE] NVARCHAR(250) DEFAULT  NULL,
    [ALTERNATE_DESCR] NVARCHAR(80) DEFAULT  NULL,
    [EXPLODE_TO_LEVEL] smallint DEFAULT  NULL,
    [SITE_ID_RANGE] NVARCHAR(250) DEFAULT  NULL,
    [SECTION_BREAK] NCHAR(1) DEFAULT ('') NOT NULL,
    [SECTION_TITLE] NVARCHAR(80) DEFAULT  NULL,
    [PRINT_CODE] int DEFAULT  NULL,
    [SEND_DATA] NCHAR(1) DEFAULT  NOT NULL,
    [BEGIN_PERIOD_ARRAY] NVARCHAR(250) DEFAULT  NULL,
    [BEGIN_YEAR_ARRAY] NVARCHAR(250) DEFAULT  NULL,
    [END_PERIOD_ARRAY] NVARCHAR(250) DEFAULT  NULL,
    [END_YEAR_ARRAY] NVARCHAR(250) DEFAULT  NULL,
    [PERSISTENT_ARRAY] NVARCHAR(250) DEFAULT  NULL,
    [SHOW_TRANSACTIONS] NCHAR(1) DEFAULT ('') NOT NULL,
    [ADD_LINE_ABOVE_TTL] NCHAR(1) DEFAULT  NULL,
    [CALENDAR_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[REPORT_LINE] ADD CONSTRAINT [PK_REPORT_LINE] PRIMARY KEY ([REPORT_ID], [LINE_NO]);

ALTER TABLE [dbo].[REPORT_LINE] ADD CONSTRAINT [FKEY0218] FOREIGN KEY ([REPORT_ID]) REFERENCES [dbo].[REPORT]([ID]);
