CREATE TABLE [dbo].[SALES_TAX] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NULL,
    [RTN_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[SALES_TAX] ADD CONSTRAINT [PK_SALES_TAX] PRIMARY KEY ([ID]);
