CREATE TABLE [dbo].[INSTALLMENT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [INST_TYPE] NCHAR(2) DEFAULT  NOT NULL,
    [END_OF_MONTH] NCHAR(1) DEFAULT  NULL,
    [VAT_ON_FIRST_INST] NCHAR(1) DEFAULT  NULL,
    [PERIOD_TYPE] NCHAR(1) DEFAULT ('') NOT NULL
)

ALTER TABLE [dbo].[INSTALLMENT] ADD CONSTRAINT [PK_INSTALLMENT] PRIMARY KEY ([ID], [INST_TYPE]);
