CREATE TABLE [dbo].[BURDEN_RULE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BURDEN_GROUP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [COST_CATEGORY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DEBIT_GL_ACCOUNT] NVARCHAR(30) DEFAULT  NULL,
    [CREDIT_GL_ACCOUNT] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[BURDEN_RULE] ADD CONSTRAINT [PK_BURDEN_RULE] PRIMARY KEY ([BURDEN_GROUP_ID], [COST_CATEGORY_ID]);

ALTER TABLE [dbo].[BURDEN_RULE] ADD CONSTRAINT [FK_BURDEN_RULE_00] FOREIGN KEY ([BURDEN_GROUP_ID]) REFERENCES [dbo].[BURDEN_GROUP]([ID]);

ALTER TABLE [dbo].[BURDEN_RULE] ADD CONSTRAINT [FK_BURDEN_RULE_01] FOREIGN KEY ([COST_CATEGORY_ID]) REFERENCES [dbo].[COST_CATEGORY]([ID]);

ALTER TABLE [dbo].[BURDEN_RULE] ADD CONSTRAINT [FK_BURDEN_RULE_02] FOREIGN KEY ([DEBIT_GL_ACCOUNT]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[BURDEN_RULE] ADD CONSTRAINT [FK_BURDEN_RULE_03] FOREIGN KEY ([CREDIT_GL_ACCOUNT]) REFERENCES [dbo].[ACCOUNT]([ID]);
