CREATE TABLE [dbo].[UOM_CATEGORY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(64) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[UOM_CATEGORY] ADD CONSTRAINT [PK_UOM_CATEGORY] PRIMARY KEY ([CODE]);
