CREATE TABLE [dbo].[PAYABLE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VOUCHER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NULL,
    [INVOICE_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [INVOICE_DATE] datetime DEFAULT  NOT NULL,
    [PAYMENT_DATE] datetime DEFAULT  NULL,
    [LAST_PAID_DATE] datetime DEFAULT  NULL,
    [ZERO_DATE] datetime DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NULL,
    [PAY_STATUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [TOTAL_AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [PAID_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [DISCOUNT_TAKEN] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [AUTHORIZED_PAYMENT] DECIMAL(23,8) DEFAULT  NULL,
    [TERMS_NET_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [TERMS_NET_DAYS] smallint DEFAULT  NULL,
    [TERMS_NET_DATE] datetime DEFAULT  NULL,
    [TERMS_DISC_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [TERMS_DISC_DAYS] smallint DEFAULT  NULL,
    [TERMS_DISC_DATE] datetime DEFAULT  NULL,
    [TERMS_DISC_PERCENT] DECIMAL(5,3) DEFAULT  NULL,
    [TERMS_DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [REPORT_1099_MISC] NCHAR(1) DEFAULT  NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT  NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [PAYB_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [MARKED_FOR_PURGE] NCHAR(1) DEFAULT ('') NOT NULL,
    [NEW_SELL_RATE] DECIMAL(15,8) DEFAULT  NULL,
    [NEW_BUY_RATE] DECIMAL(15,8) DEFAULT  NULL,
    [VAT_BOOK_CODE] NVARCHAR(5) DEFAULT  NULL,
    [VAT_REPORT_NO] int DEFAULT  NULL,
    [VAT_FILENAME] NVARCHAR(15) DEFAULT  NULL,
    [WITHHOLDING_CODE] NVARCHAR(15) DEFAULT  NULL,
    [WITHHELD_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [WH_ALLOWED_AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [REMIT_ADDR_NO] int DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [USER_EXCH_RATE] NCHAR(1) DEFAULT ('') NOT NULL,
    [VOID_DATE] datetime DEFAULT  NULL,
    [COMM_INVOICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [COMM_PAID_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [LANDED_COST_INV] NCHAR(1) DEFAULT  NULL,
    [ACT_RATE_ID] NVARCHAR(15) DEFAULT  NULL,
    [ACT_PERIOD_ID] NVARCHAR(15) DEFAULT  NULL,
    [RETRO_RATE_ID] NVARCHAR(15) DEFAULT  NULL,
    [RETRO_PERIOD_ID] NVARCHAR(15) DEFAULT  NULL,
    [RETRO_RATE_CODE] NCHAR(1) DEFAULT  NULL,
    [POSTING_CANDIDATE] NCHAR(1) DEFAULT ('Y') NOT NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [TERMS_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [TERMS_DISC_BASIS] NVARCHAR(32) DEFAULT  NULL
)

ALTER TABLE [dbo].[PAYABLE] ADD CONSTRAINT [PK_PAYABLE] PRIMARY KEY ([VOUCHER_ID]);

ALTER TABLE [dbo].[PAYABLE] ADD CONSTRAINT [FKEY0020] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[PAYABLE] ADD CONSTRAINT [FKEY0082] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);

ALTER TABLE [dbo].[PAYABLE] ADD CONSTRAINT [FKEY0277] FOREIGN KEY ([PAYB_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[PAYABLE] ADD CONSTRAINT [FKEY9399] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[PAYABLE] ADD CONSTRAINT [FKEY9631] FOREIGN KEY ([TERMS_ID]) REFERENCES [dbo].[TERMS]([ID]);
