CREATE TABLE [dbo].[SEGMENT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [REV_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [AR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [DEF_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [LIQ_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [PBC_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CGS_MAT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CGS_LAB_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CGS_BUR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CGS_SER_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [WIP_MAT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [WIP_LAB_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [WIP_BUR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [WIP_SER_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[SEGMENT] ADD CONSTRAINT [PK_SEGMENT] PRIMARY KEY ([CODE]);
