CREATE TABLE [dbo].[REPORT_CALENDAR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [ACTIVE_FLAG] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[REPORT_CALENDAR] ADD CONSTRAINT [PK_RPT_CALENDAR] PRIMARY KEY ([ID]);
