CREATE TABLE [dbo].[VENDOR_BANK] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BANK_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(50) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [ADDR_1] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_2] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_3] NVARCHAR(50) DEFAULT  NULL,
    [CITY] NVARCHAR(30) DEFAULT  NULL,
    [STATE] NVARCHAR(10) DEFAULT  NULL,
    [ZIPCODE] NVARCHAR(10) DEFAULT  NULL,
    [COUNTRY] NVARCHAR(50) DEFAULT  NULL,
    [COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [VENDOR_BANK_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [IBAN] NVARCHAR(40) DEFAULT  NULL,
    [SWIFT] NVARCHAR(30) DEFAULT  NULL,
    [ACCOUNT_NO] NVARCHAR(30) DEFAULT  NULL,
    [BRANCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [IS_DEFAULT] smallint DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[VENDOR_BANK] ADD CONSTRAINT [PK_VEND_BANK] PRIMARY KEY ([VENDOR_ID], [BANK_ID]);

ALTER TABLE [dbo].[VENDOR_BANK] ADD CONSTRAINT [FK_VEND_BANK_CNTRY] FOREIGN KEY ([COUNTRY_ID]) REFERENCES [dbo].[COUNTRY]([ID]);

ALTER TABLE [dbo].[VENDOR_BANK] ADD CONSTRAINT [FK_VEND_BANK_VEND] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);
