CREATE TABLE [dbo].[REVALUE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[REVALUE] ADD CONSTRAINT [PK_REVALUE] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[REVALUE] ADD CONSTRAINT [FKEY9472] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
