CREATE TABLE [dbo].[LMC_MRP_REPORTS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [MODULE] VARCHAR(10) DEFAULT  NOT NULL,
    [SITE] VARCHAR(15) DEFAULT  NOT NULL,
    [USER_OR_PROFILE] VARCHAR(30) DEFAULT  NOT NULL,
    [TITLE] VARCHAR(15) DEFAULT  NOT NULL,
    [PATH] VARCHAR(250) DEFAULT  NOT NULL,
    [PARAM] VARCHAR(30) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[LMC_MRP_REPORTS] ADD CONSTRAINT [PK_LMC_MRP_REPORTS] PRIMARY KEY ([MODULE], [SITE], [USER_OR_PROFILE], [TITLE]);
