CREATE TABLE [dbo].[OPER_SERVICE_COST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [OPERATION_SEQ_NO] smallint DEFAULT  NOT NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [UNIT_COST] DECIMAL(22,8) DEFAULT  NOT NULL,
    [BASE_CHARGE] DECIMAL(23,8) DEFAULT  NOT NULL,
    [MINIMUM_CHARGE] DECIMAL(23,8) DEFAULT  NULL,
    [LEADTIME] smallint DEFAULT  NULL
)

ALTER TABLE [dbo].[OPER_SERVICE_COST] ADD CONSTRAINT [PK_OPER_SERVICE_COST] PRIMARY KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO], [QTY]);
