CREATE TABLE [dbo].[DOCUMENT_SITE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DOCUMENT_ID] NVARCHAR(80) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[DOCUMENT_SITE] ADD CONSTRAINT [PK_DOCUMENT_SITE] PRIMARY KEY ([SITE_ID], [DOCUMENT_ID]);
