CREATE TABLE [dbo].[CUSTOMER_DISCOUNT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DISCOUNT_CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [DISCOUNT_PERCENT] DECIMAL(6,3) DEFAULT  NULL
)

ALTER TABLE [dbo].[CUSTOMER_DISCOUNT] ADD CONSTRAINT [PK_CUSTOMER_DISCOUNT] PRIMARY KEY ([DISCOUNT_CODE]);
