CREATE TABLE [dbo].[TASK_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TASK_TYPE] NVARCHAR(15) DEFAULT  NOT NULL,
    [TASK_NO] int DEFAULT  NOT NULL,
    [SEQ_NO] int DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[TASK_BINARY] ADD CONSTRAINT [PK_TASK_BINARY] PRIMARY KEY ([TASK_TYPE], [TASK_NO], [SEQ_NO]);

ALTER TABLE [dbo].[TASK_BINARY] ADD CONSTRAINT [FK_TASK_BINARY] FOREIGN KEY ([TASK_TYPE], [TASK_NO], [SEQ_NO]) REFERENCES [dbo].[TASK]([TYPE], [TASK_NO], [SEQ_NO]);
