CREATE TABLE [dbo].[CUSTOMER_GROUP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(30) DEFAULT  NULL,
    [BILL_TO_NAME] NVARCHAR(50) DEFAULT  NULL,
    [BILL_TO_ADDR_1] NVARCHAR(50) DEFAULT  NULL,
    [BILL_TO_ADDR_2] NVARCHAR(50) DEFAULT  NULL,
    [BILL_TO_ADDR_3] NVARCHAR(50) DEFAULT  NULL,
    [BILL_TO_CITY] NVARCHAR(30) DEFAULT  NULL,
    [BILL_TO_STATE] NVARCHAR(10) DEFAULT  NULL,
    [BILL_TO_ZIPCODE] NVARCHAR(10) DEFAULT  NULL,
    [BILL_TO_COUNTRY] NVARCHAR(50) DEFAULT  NULL,
    [BILL_TO_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [ALLOW_OVER_PAYMNT] NCHAR(1) DEFAULT  NULL,
    [ALLOW_ADJ_INVOICE] NCHAR(1) DEFAULT  NULL,
    [MODIFY_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[CUSTOMER_GROUP] ADD CONSTRAINT [PK_CUST_GROUP] PRIMARY KEY ([ID]);
