CREATE TABLE [dbo].[SCHEDULER_RUN_LOG] (
    [SCHEDULE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [COUNT] int DEFAULT ((0)) NOT NULL,
    [START_DATE] datetime DEFAULT  NOT NULL,
    [END_DATE] datetime DEFAULT  NOT NULL,
    [WORK_ORDERS] int DEFAULT ((0)) NOT NULL,
    [OPERATIONS] int DEFAULT ((0)) NOT NULL,
    [REQUIREMENTS] int DEFAULT ((0)) NOT NULL,
    [ERROR_COUNT] int DEFAULT ((0)) NOT NULL,
    [INFINITE_CAPACITY] NCHAR(1) DEFAULT  NOT NULL,
    [MATERIALS_CHECKED] NCHAR(1) DEFAULT  NOT NULL,
    [SERVICES_CHECKED] NCHAR(1) DEFAULT  NOT NULL,
    [RUN_ABORTED] NCHAR(1) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [HARD_RELEASE_DATE] NCHAR(1) DEFAULT  NULL,
    [CCR_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[SCHEDULER_RUN_LOG] ADD CONSTRAINT [PK_SCHEDULER_RUN_LOG] PRIMARY KEY ([SCHEDULE_ID], [COUNT]);
