CREATE TABLE [dbo].[WIP_ISSUE_DIST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [DIST_NO] smallint DEFAULT  NOT NULL,
    [ENTRY_NO] smallint DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [AMOUNT_TYPE] NCHAR(2) DEFAULT  NOT NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [POSTING_STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [BATCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [NATIVE] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[WIP_ISSUE_DIST] ADD CONSTRAINT [PK_WIP_ISSUE_DIST] PRIMARY KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [DIST_NO], [ENTRY_NO], [CURRENCY_ID]);

ALTER TABLE [dbo].[WIP_ISSUE_DIST] ADD CONSTRAINT [FK_WPIDST_BATCH] FOREIGN KEY ([SITE_ID], [BATCH_ID]) REFERENCES [dbo].[JOURNAL_BATCH]([SITE_ID], [ID]);

ALTER TABLE [dbo].[WIP_ISSUE_DIST] ADD CONSTRAINT [FKEY0005] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[WIP_ISSUE_DIST] ADD CONSTRAINT [FKEY0194] FOREIGN KEY ([GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[WIP_ISSUE_DIST] ADD CONSTRAINT [FKEY9410] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
