CREATE TABLE [dbo].[ADDRESS_POS_SETUP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [COUNTRY] NVARCHAR(50) DEFAULT  NOT NULL,
    [FIELD_NO] smallint DEFAULT  NOT NULL,
    [FIELD_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [TITLE] NVARCHAR(80) DEFAULT  NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [POSITION_NO] smallint DEFAULT  NULL,
    [VISIBLE] smallint DEFAULT  NULL,
    [PERCENTAGE] DECIMAL(5,2) DEFAULT  NULL,
    [DOWN_HEIGHT] DECIMAL(5,3) DEFAULT  NULL,
    [ACROSS_WIDTH] DECIMAL(5,3) DEFAULT  NULL
)

ALTER TABLE [dbo].[ADDRESS_POS_SETUP] ADD CONSTRAINT [PK_ADDRESS_POS_SETUP] PRIMARY KEY ([COUNTRY], [FIELD_NO], [FIELD_TYPE]);
