CREATE TABLE [dbo].[QUOTE_ORDER_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [QUOTE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [QUOTE_LINE_NO] smallint DEFAULT  NOT NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUST_ORDER_LINE_NO] smallint DEFAULT  NOT NULL,
    [QUOTE_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [CUST_ORDER_LINE_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [CUST_ORDER_LINE_UNIT_PRICE] DECIMAL(22,8) DEFAULT  NULL,
    [QUOTE_UNIT_PRICE] DECIMAL(22,8) DEFAULT  NULL,
    [CUST_ORDER_LINE_DISC_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [QUOTE_DISC_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [QUOTE_STATUS] NCHAR(1) DEFAULT  NULL,
    [QUOTE_CURRENCY_ID] NVARCHAR(15) DEFAULT  NULL,
    [CUST_ORDER_CURRENCY_ID] NVARCHAR(15) DEFAULT  NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [CUSTOMER_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [SERVICE_CHARGE_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[QUOTE_ORDER_LINE] ADD CONSTRAINT [PK_QOUTE_ORDER_LINE] PRIMARY KEY ([QUOTE_ID], [QUOTE_LINE_NO], [CUST_ORDER_ID], [CUST_ORDER_LINE_NO]);
