CREATE TABLE [dbo].[BANK_ADJ_CURR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BANK_ACCOUNT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ADJUSTMENT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[BANK_ADJ_CURR] ADD CONSTRAINT [PK_BANK_ADJ_CURR] PRIMARY KEY ([BANK_ACCOUNT_ID], [ADJUSTMENT_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[BANK_ADJ_CURR] ADD CONSTRAINT [FKEY9433] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[BANK_ADJ_CURR] ADD CONSTRAINT [FKEY9434] FOREIGN KEY ([BANK_ACCOUNT_ID], [ADJUSTMENT_ID]) REFERENCES [dbo].[BANK_ADJUSTMENT]([BANK_ACCOUNT_ID], [ADJUSTMENT_ID]);
