CREATE TABLE [dbo].[CUST_CONTACT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CONTACT_NO] smallint DEFAULT  NULL,
    [CONTACT_ID] NVARCHAR(25) DEFAULT  NOT NULL,
    [PRIMARY_CONTACT] NCHAR(1) DEFAULT ('N') NOT NULL
)

ALTER TABLE [dbo].[CUST_CONTACT] ADD CONSTRAINT [PK_CUST_CONTACT] PRIMARY KEY ([CUSTOMER_ID], [CONTACT_ID]);

ALTER TABLE [dbo].[CUST_CONTACT] ADD CONSTRAINT [FK_CUST_CONT_CONT] FOREIGN KEY ([CONTACT_ID]) REFERENCES [dbo].[CONTACT]([ID]);

ALTER TABLE [dbo].[CUST_CONTACT] ADD CONSTRAINT [FK_CUST_CONT_CUST] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);
