CREATE TABLE [dbo].[RMA_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RMA_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[RMA_BINARY] ADD CONSTRAINT [PK_RMA_BINARY] PRIMARY KEY ([RMA_ID], [TYPE]);

ALTER TABLE [dbo].[RMA_BINARY] ADD CONSTRAINT [FKEY9377] FOREIGN KEY ([RMA_ID]) REFERENCES [dbo].[RMA]([ID]);
