CREATE TABLE [dbo].[REQUIREMENT_SUM] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SPID] NVARCHAR(15) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [OPERATION_SEQ_NO] smallint DEFAULT  NOT NULL,
    [PIECE_NO] smallint DEFAULT  NOT NULL,
    [EST_MATERIAL_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [EST_LABOR_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [EST_BURDEN_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [EST_SERVICE_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [REM_MATERIAL_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [REM_LABOR_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [REM_BURDEN_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [REM_SERVICE_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[REQUIREMENT_SUM] ADD CONSTRAINT [PK_REQUIREMENTX] PRIMARY KEY ([SPID], [WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO], [PIECE_NO]);
