CREATE TABLE [dbo].[DOCUMENT_REF_WO] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [SEQUENCE_NO] smallint DEFAULT  NOT NULL,
    [PIECE_NO] smallint DEFAULT  NOT NULL,
    [DOCUMENT_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[DOCUMENT_REF_WO] ADD CONSTRAINT [PK_DOCUMENT_REF_WO] PRIMARY KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [SEQUENCE_NO], [PIECE_NO], [DOCUMENT_ID]);
