CREATE TABLE [dbo].[PORT_OF_TRANS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(25) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL
)

ALTER TABLE [dbo].[PORT_OF_TRANS] ADD CONSTRAINT [PK_PORT_OF_TRANS] PRIMARY KEY ([CODE]);
