CREATE TABLE [dbo].[BUFFER_PROFILE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [ITEM_TYPE] NCHAR(1) DEFAULT  NULL,
    [LEADTIME_CATEGORY] NCHAR(1) DEFAULT  NULL,
    [LEADTIME_GREEN_PCT] smallint DEFAULT  NULL,
    [LEADTIME_RED_PCT] smallint DEFAULT  NULL,
    [VARIABILITY_CATEGORY] NCHAR(1) DEFAULT  NULL,
    [VAR_RED_SAFETY_PCT] smallint DEFAULT  NULL,
    [USE_SIG_MOQ_GREEN] NCHAR(1) DEFAULT  NULL,
    [ORDER_SPIKE_THRESH] int DEFAULT  NULL,
    [ORDER_SPIKE_HORIZON] smallint DEFAULT  NULL,
    [ADU_HORIZON_FACTOR] DECIMAL(5,2) DEFAULT  NULL,
    [ADU_ALERT_THRESH] int DEFAULT  NULL,
    [ADU_ALERT_HORIZON] smallint DEFAULT  NULL,
    [ONHAND_ALERT_RED_PCT] smallint DEFAULT  NULL
)

ALTER TABLE [dbo].[BUFFER_PROFILE] ADD CONSTRAINT [PK_BUFFER_PROFILE] PRIMARY KEY ([ID]);
