CREATE TABLE [dbo].[EC_GROUP_USER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EC_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [GROUP_TYPE] NVARCHAR(2) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [IS_LEADER] NCHAR(1) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_SIGNOFF] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[EC_GROUP_USER] ADD CONSTRAINT [PK_EC_GROUP_USER] PRIMARY KEY ([EC_ID], [GROUP_TYPE], [USER_ID]);

ALTER TABLE [dbo].[EC_GROUP_USER] ADD CONSTRAINT [FK_EC_GROUP_USER] FOREIGN KEY ([EC_ID]) REFERENCES [dbo].[EC]([ID]);
