CREATE TABLE [dbo].[SIC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[SIC] ADD CONSTRAINT [PK_SIC] PRIMARY KEY ([CODE]);
