CREATE TABLE [dbo].[SK_PART_CONTROLLED_LIST] (
    [CONTROLLED_LIST] NVARCHAR(50) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(255) DEFAULT  NULL
)

ALTER TABLE [dbo].[SK_PART_CONTROLLED_LIST] ADD CONSTRAINT [PK_SK_PART_CONTROLLED_LIST] PRIMARY KEY ([CONTROLLED_LIST]);
