CREATE TABLE [dbo].[EXCEPTION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TYPE] NCHAR(2) DEFAULT  NOT NULL,
    [OWNER_ID] NVARCHAR(40) DEFAULT  NOT NULL,
    [EXCEPTION_ID] NVARCHAR(40) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT  NOT NULL,
    [NOTE] image DEFAULT  NULL
)

ALTER TABLE [dbo].[EXCEPTION] ADD CONSTRAINT [PK_EXCEPTION] PRIMARY KEY ([TYPE], [OWNER_ID], [EXCEPTION_ID], [CREATE_DATE]);
