CREATE TABLE [dbo].[SHIFT_DAY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SHIFT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SHIFT_CODE] smallint DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [SHIFT_START] datetime DEFAULT  NULL,
    [SHIFT_END] datetime DEFAULT  NULL,
    [MEAL_START] datetime DEFAULT  NULL,
    [MEAL_END] datetime DEFAULT  NULL,
    [MEAL_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [MEAL_MANUAL] NCHAR(1) DEFAULT ('') NOT NULL,
    [BREAK1_START] datetime DEFAULT  NULL,
    [BREAK1_END] datetime DEFAULT  NULL,
    [BREAK1_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [BREAK1_MANUAL] NCHAR(1) DEFAULT ('') NOT NULL,
    [BREAK2_START] datetime DEFAULT  NULL,
    [BREAK2_END] datetime DEFAULT  NULL,
    [BREAK2_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [BREAK2_MANUAL] NCHAR(1) DEFAULT ('') NOT NULL,
    [BREAK3_START] datetime DEFAULT  NULL,
    [BREAK3_END] datetime DEFAULT  NULL,
    [BREAK3_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [BREAK3_MANUAL] NCHAR(1) DEFAULT ('') NOT NULL,
    [PAID_BREAKS] NCHAR(1) DEFAULT  NULL,
    [PERIODS_PER_HOUR] int DEFAULT  NULL
)

ALTER TABLE [dbo].[SHIFT_DAY] ADD CONSTRAINT [PK_SHIFT_DAY] PRIMARY KEY ([SHIFT_ID], [SHIFT_CODE]);

ALTER TABLE [dbo].[SHIFT_DAY] ADD CONSTRAINT [FKEY0257] FOREIGN KEY ([SHIFT_ID]) REFERENCES [dbo].[SHIFT]([ID]);
