CREATE TABLE [dbo].[CASH_RECEIPT_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CHECK_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NULL,
    [REFERENCE] NVARCHAR(40) DEFAULT  NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [DISCOUNT_APPLIED] DECIMAL(23,8) DEFAULT  NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT  NOT NULL,
    [APPLIED_TYPE] NVARCHAR(1) DEFAULT  NULL,
    [MEMO_INVOICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [PCURR_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [PCURR_DISC_APPLIED] DECIMAL(23,8) DEFAULT  NULL,
    [INST_NO] smallint DEFAULT  NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [RECV_CUSTOMER_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CASH_RECEIPT_LINE] ADD CONSTRAINT [PK_CASH_RECEIPT_LINE] PRIMARY KEY ([CUSTOMER_ID], [CHECK_ID], [LINE_NO]);

ALTER TABLE [dbo].[CASH_RECEIPT_LINE] ADD CONSTRAINT [FK_CRL_RECV_CUST] FOREIGN KEY ([RECV_CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);

ALTER TABLE [dbo].[CASH_RECEIPT_LINE] ADD CONSTRAINT [FK_CSH_RCPT_LINE_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[CASH_RECEIPT_LINE] ADD CONSTRAINT [FKEY0237] FOREIGN KEY ([CUSTOMER_ID], [CHECK_ID]) REFERENCES [dbo].[CASH_RECEIPT]([CUSTOMER_ID], [CHECK_ID]);

ALTER TABLE [dbo].[CASH_RECEIPT_LINE] ADD CONSTRAINT [FKEY0283] FOREIGN KEY ([GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);
