CREATE TABLE [dbo].[SERVICE_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SERVICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SERVICE_BINARY] ADD CONSTRAINT [PK_SERVICE_BINARY] PRIMARY KEY ([SERVICE_ID], [TYPE]);

ALTER TABLE [dbo].[SERVICE_BINARY] ADD CONSTRAINT [FKEY0113] FOREIGN KEY ([SERVICE_ID]) REFERENCES [dbo].[SERVICE]([ID]);
