CREATE TABLE [dbo].[LABEL_FORMAT_FIELD] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [COLUMN_ID] NVARCHAR(70) DEFAULT  NOT NULL,
    [LABEL_FIELD] NVARCHAR(50) DEFAULT  NOT NULL,
    [LABEL_FORMAT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[LABEL_FORMAT_FIELD] ADD CONSTRAINT [PK_LABEL_FMT_FLD] PRIMARY KEY ([LABEL_FIELD], [LABEL_FORMAT_ID]);

ALTER TABLE [dbo].[LABEL_FORMAT_FIELD] ADD CONSTRAINT [FKEY9460] FOREIGN KEY ([LABEL_FORMAT_ID]) REFERENCES [dbo].[LABEL_FORMAT]([ID]);
