CREATE TABLE [dbo].[PERSON] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(50) DEFAULT  NULL,
    [IS_APPROVER] NCHAR(1) DEFAULT ('N') NOT NULL,
    [IS_BUYER] NCHAR(1) DEFAULT ('N') NOT NULL,
    [IS_PLANNER] NCHAR(1) DEFAULT ('N') NOT NULL,
    [IS_REQUESTER] NCHAR(1) DEFAULT ('N') NOT NULL
)

ALTER TABLE [dbo].[PERSON] ADD CONSTRAINT [PK_PERSON] PRIMARY KEY ([ID]);
