CREATE TABLE [dbo].[SKILLS_AUDIT_INTERN] (
    [CREATE_DATE] datetime DEFAULT  NULL,
    [USER_ID] VARCHAR(50) DEFAULT  NULL,
    [ACTION] VARCHAR(50) DEFAULT  NULL,
    [TABLE_NAME] VARCHAR(50) DEFAULT  NULL
)
