CREATE TABLE [dbo].[CURRENCY_ENTITY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ENTITY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TRACKING_CURRENCY] NCHAR(1) DEFAULT  NOT NULL,
    [RND_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [REAL_GN_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [REAL_LS_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [UNREAL_GN_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [UNREAL_LS_ACCT_ID] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[CURRENCY_ENTITY] ADD CONSTRAINT [PK_CURR_ENTITY] PRIMARY KEY ([ENTITY_ID], [CURRENCY_ID]);

ALTER TABLE [dbo].[CURRENCY_ENTITY] ADD CONSTRAINT [FK_CURR_ENTITY_TO_AE] FOREIGN KEY ([ENTITY_ID]) REFERENCES [dbo].[ACCOUNTING_ENTITY]([ID]);

ALTER TABLE [dbo].[CURRENCY_ENTITY] ADD CONSTRAINT [FK_CURR_ENTITY_TO_CURR] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[CURRENCY_ENTITY] ADD CONSTRAINT [FKEY9383] FOREIGN KEY ([RND_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[CURRENCY_ENTITY] ADD CONSTRAINT [FKEY9384] FOREIGN KEY ([REAL_GN_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[CURRENCY_ENTITY] ADD CONSTRAINT [FKEY9385] FOREIGN KEY ([REAL_LS_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[CURRENCY_ENTITY] ADD CONSTRAINT [FKEY9386] FOREIGN KEY ([UNREAL_GN_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[CURRENCY_ENTITY] ADD CONSTRAINT [FKEY9387] FOREIGN KEY ([UNREAL_LS_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);
