CREATE TABLE [dbo].[PROJ_SUMM_BURD_AMT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROJECT_SUMMARY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [COST_CATEGORY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[PROJ_SUMM_BURD_AMT] ADD CONSTRAINT [PK_PROJ_SUMM_BURD_AMT] PRIMARY KEY ([PROJECT_SUMMARY_ID], [COST_CATEGORY_ID]);

ALTER TABLE [dbo].[PROJ_SUMM_BURD_AMT] ADD CONSTRAINT [FK_PROJ_SUMM_BURD_AMT_00] FOREIGN KEY ([PROJECT_SUMMARY_ID]) REFERENCES [dbo].[PROJECT_SUMMARY]([ID]);

ALTER TABLE [dbo].[PROJ_SUMM_BURD_AMT] ADD CONSTRAINT [FK_PROJ_SUMM_BURD_AMT_01] FOREIGN KEY ([COST_CATEGORY_ID]) REFERENCES [dbo].[COST_CATEGORY]([ID]);
