CREATE TABLE [dbo].[EQUIP_CALENDAR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NULL,
    [DAY_OF_WEEK] smallint DEFAULT  NOT NULL,
    [START_OF_DAY] datetime DEFAULT  NOT NULL,
    [SHIFT_1] DECIMAL(5,3) DEFAULT  NOT NULL,
    [SHIFT_2] DECIMAL(5,3) DEFAULT  NOT NULL,
    [SHIFT_3] DECIMAL(5,3) DEFAULT  NOT NULL,
    [SHIFT_1_CAPACITY] smallint DEFAULT  NULL,
    [SHIFT_2_CAPACITY] smallint DEFAULT  NULL,
    [SHIFT_3_CAPACITY] smallint DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NULL
)
