CREATE TABLE [dbo].[SERVICE_DISPATCH] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PURC_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DISPATCHED_DATE] datetime DEFAULT  NULL,
    [PRINTED_DATE] datetime DEFAULT  NULL,
    [SHIP_TO_ADDR_NO] int DEFAULT  NULL,
    [SHIP_FROM_ADDR_NO] int DEFAULT  NULL,
    [FREE_ON_BOARD] NVARCHAR(25) DEFAULT  NULL,
    [SHIP_VIA] NVARCHAR(40) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [MARKED_FOR_PURGE] NCHAR(1) DEFAULT  NULL,
    [SHIP_REASON_CD] NVARCHAR(15) DEFAULT  NULL,
    [CARRIER_ID] NVARCHAR(15) DEFAULT  NULL,
    [FREIGHT_TERMS] NCHAR(1) DEFAULT  NULL,
    [DISPATCH_ADDR_ID] NVARCHAR(20) DEFAULT  NULL,
    [TARE_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [TOTAL_NET_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [TOTAL_GROSS_WEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SERVICE_DISPATCH] ADD CONSTRAINT [PK_SERVICE_DISPATCH] PRIMARY KEY ([ID]);
