CREATE TABLE [dbo].[LABEL_GROUP_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [LABEL_GROUP_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [LABEL_FORMAT_ID] NVARCHAR(30) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[LABEL_GROUP_LINE] ADD CONSTRAINT [PK_LABEL_GROUP_LINE] PRIMARY KEY ([LABEL_GROUP_ID], [LABEL_FORMAT_ID]);

ALTER TABLE [dbo].[LABEL_GROUP_LINE] ADD CONSTRAINT [FKEY0300] FOREIGN KEY ([LABEL_GROUP_ID]) REFERENCES [dbo].[LABEL_GROUP]([ID]);

ALTER TABLE [dbo].[LABEL_GROUP_LINE] ADD CONSTRAINT [FKEY0301] FOREIGN KEY ([LABEL_FORMAT_ID]) REFERENCES [dbo].[LABEL_FORMAT]([ID]);
