CREATE TABLE [dbo].[CUST_GROUP_RELATION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [GROUP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CUST_GROUP_RELATION] ADD CONSTRAINT [PK_CUST_GROUP_RELATION] PRIMARY KEY ([GROUP_ID], [CUSTOMER_ID]);
