CREATE TABLE [dbo].[SOA_DIMENSION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(100) DEFAULT  NOT NULL,
    [AGENCY_ID] NVARCHAR(10) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(64) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(250) DEFAULT  NULL,
    [STATUS] NVARCHAR(15) DEFAULT  NOT NULL,
    [EFFECTIVE_DATE] datetime DEFAULT  NULL,
    [EXPIRATION_DATE] datetime DEFAULT  NULL,
    [READ_ONLY] NCHAR(1) DEFAULT  NOT NULL,
    [SEQUENCE_NO] int DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[SOA_DIMENSION] ADD CONSTRAINT [PK_SOA_DIMENSION] PRIMARY KEY ([ID], [AGENCY_ID]);
