CREATE TABLE [dbo].[COST_SIMULATION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SIMULATION_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [PRV_MATERIAL_COST] DECIMAL(23,8) DEFAULT  NULL,
    [PRV_LABOR_COST] DECIMAL(23,8) DEFAULT  NULL,
    [PRV_BURDEN_COST] DECIMAL(23,8) DEFAULT  NULL,
    [PRV_SERVICE_COST] DECIMAL(23,8) DEFAULT  NULL,
    [PRV_FIXED_COST] DECIMAL(23,8) DEFAULT  NULL,
    [PRV_UNIT_PRICE] DECIMAL(22,8) DEFAULT  NULL,
    [TOT_PRV_COST] DECIMAL(23,8) DEFAULT  NULL,
    [SIM_MATERIAL_COST] DECIMAL(23,8) DEFAULT  NULL,
    [SIM_LABOR_COST] DECIMAL(23,8) DEFAULT  NULL,
    [SIM_BURDEN_COST] DECIMAL(23,8) DEFAULT  NULL,
    [SIM_SERVICE_COST] DECIMAL(23,8) DEFAULT  NULL,
    [SIM_FIXED_COST] DECIMAL(23,8) DEFAULT  NULL,
    [TOT_SIM_COST] DECIMAL(23,8) DEFAULT  NULL,
    [SIM_UNIT_PRICE] DECIMAL(22,8) DEFAULT  NULL,
    [SIM_UNIT_MKUP_AMT] DECIMAL(22,8) DEFAULT  NULL,
    [SIM_MATERIAL_PCT] DECIMAL(5,2) DEFAULT  NULL,
    [SIM_LABOR_PCT] DECIMAL(5,2) DEFAULT  NULL,
    [SIM_BURDEN_PCT] DECIMAL(5,2) DEFAULT  NULL,
    [SIM_SERVICE_PCT] DECIMAL(5,2) DEFAULT  NULL,
    [SIM_FIXED_PCT] DECIMAL(5,2) DEFAULT  NULL,
    [SIM_UNIT_PCT] DECIMAL(5,2) DEFAULT  NULL,
    [MARKUP_TYPE] NCHAR(1) DEFAULT  NULL,
    [PRV_CREATE_DATE] datetime DEFAULT  NULL,
    [SIM_CREATE_DATE] datetime DEFAULT  NOT NULL,
    [SIM_UNIT_MKUP_PCT] DECIMAL(5,2) DEFAULT  NULL,
    [PRV_PUR_BUR_PCT] DECIMAL(6,3) DEFAULT  NULL,
    [PRV_PUR_BUR_UNIT] DECIMAL(22,8) DEFAULT  NULL,
    [SIM_PUR_BUR_PCT] DECIMAL(6,3) DEFAULT  NULL,
    [SIM_PUR_BUR_UNIT] DECIMAL(22,8) DEFAULT  NULL,
    [SIM_PUR_BUR_UN_PCT] DECIMAL(5,2) DEFAULT  NULL
)

ALTER TABLE [dbo].[COST_SIMULATION] ADD CONSTRAINT [PK_COST_SIMULATION] PRIMARY KEY ([SIMULATION_ID], [PART_ID]);

ALTER TABLE [dbo].[COST_SIMULATION] ADD CONSTRAINT [FK_COST_SIMULATION_00] FOREIGN KEY ([SIMULATION_ID]) REFERENCES [dbo].[SIMULATION]([ID]);

ALTER TABLE [dbo].[COST_SIMULATION] ADD CONSTRAINT [FK_COST_SIMULATION_01] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);
