CREATE TABLE [dbo].[SERVICE_DISPATCHED] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TRANSACTION_ID] int DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [OPERATION_SEQ_NO] smallint DEFAULT  NOT NULL,
    [SERVICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PURC_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [PURC_ORDER_LINE_NO] smallint DEFAULT  NULL,
    [DISPATCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [DISPATCH_LINE_NO] smallint DEFAULT  NULL,
    [DISPATCHED_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[SERVICE_DISPATCHED] ADD CONSTRAINT [PK_SERVICE_DISPATCHED] PRIMARY KEY ([TRANSACTION_ID]);
