CREATE TABLE [dbo].[SHOP_GROUP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [GROUP_RESOURCE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SEQ_NO] smallint DEFAULT  NOT NULL,
    [SUB_RESOURCE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [EFFICIENCY_FACTOR] DECIMAL(15,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[SHOP_GROUP] ADD CONSTRAINT [PK_SHOP_GROUP] PRIMARY KEY ([GROUP_RESOURCE_ID], [SEQ_NO], [SUB_RESOURCE_ID]);

ALTER TABLE [dbo].[SHOP_GROUP] ADD CONSTRAINT [FKEY0123] FOREIGN KEY ([GROUP_RESOURCE_ID]) REFERENCES [dbo].[SHOP_RESOURCE]([ID]);

ALTER TABLE [dbo].[SHOP_GROUP] ADD CONSTRAINT [FKEY0124] FOREIGN KEY ([SUB_RESOURCE_ID]) REFERENCES [dbo].[SHOP_RESOURCE]([ID]);
