CREATE TABLE [dbo].[CREDIT_MEMO_APPLY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [MEMO_VOUCHER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [INV_VOUCHER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [APPLY_AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [APPLY_DATE] datetime DEFAULT  NULL,
    [INST_NO] smallint DEFAULT  NULL
)

ALTER TABLE [dbo].[CREDIT_MEMO_APPLY] ADD CONSTRAINT [FKEY0225] FOREIGN KEY ([INV_VOUCHER_ID]) REFERENCES [dbo].[PAYABLE]([VOUCHER_ID]);

ALTER TABLE [dbo].[CREDIT_MEMO_APPLY] ADD CONSTRAINT [FKEY0226] FOREIGN KEY ([MEMO_VOUCHER_ID]) REFERENCES [dbo].[PAYABLE]([VOUCHER_ID]);
