CREATE TABLE [dbo].[RCR_PAYABLE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [PAY_STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [TOTAL_AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [AUTHORIZED_PAYMENT] DECIMAL(23,8) DEFAULT  NULL,
    [TERMS_NET_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [TERMS_NET_DAYS] smallint DEFAULT  NULL,
    [TERMS_NET_DATE] datetime DEFAULT  NULL,
    [TERMS_DISC_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [TERMS_DISC_DAYS] smallint DEFAULT  NULL,
    [TERMS_DISC_DATE] datetime DEFAULT  NULL,
    [TERMS_DISC_PERCENT] DECIMAL(5,3) DEFAULT  NULL,
    [TERMS_DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [REPORT_1099_MISC] NCHAR(1) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PAYB_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [TRIGGER_FREQ] NCHAR(1) DEFAULT ('') NOT NULL,
    [TRIGGER_DAY] smallint DEFAULT  NULL,
    [TRIGGER_COUNT] smallint DEFAULT  NULL,
    [TRIGGER_MAX] smallint DEFAULT  NULL,
    [TRIGGER_LAST_DATE] datetime DEFAULT  NULL,
    [GROUP_ID] NVARCHAR(15) DEFAULT  NULL,
    [VAT_BOOK_CODE] NVARCHAR(5) DEFAULT  NULL,
    [WITHHOLDING_CODE] NVARCHAR(15) DEFAULT  NULL,
    [REMIT_ADDR_NO] int DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NULL,
    [TERMS_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [TERMS_DISC_BASIS] NVARCHAR(32) DEFAULT  NULL
)

ALTER TABLE [dbo].[RCR_PAYABLE] ADD CONSTRAINT [PK_RCR_PAYABLE] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[RCR_PAYABLE] ADD CONSTRAINT [FKEY0024] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[RCR_PAYABLE] ADD CONSTRAINT [FKEY0084] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);

ALTER TABLE [dbo].[RCR_PAYABLE] ADD CONSTRAINT [FKEY0279] FOREIGN KEY ([PAYB_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[RCR_PAYABLE] ADD CONSTRAINT [FKEY9632] FOREIGN KEY ([TERMS_ID]) REFERENCES [dbo].[TERMS]([ID]);
