CREATE TABLE [dbo].[CONTRACT_TYPE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [CONTRACT_CATEGORY] NCHAR(1) DEFAULT  NULL,
    [REVENUE_BASIS] NCHAR(1) DEFAULT  NULL,
    [BILLING_BASIS] NCHAR(1) DEFAULT  NULL,
    [FEE_BASIS] NCHAR(1) DEFAULT  NULL,
    [INVOICING_METHOD] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[CONTRACT_TYPE] ADD CONSTRAINT [PK_CONTRACT_TYPE] PRIMARY KEY ([CODE]);
