CREATE TABLE [dbo].[SERVICE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NULL,
    [VAT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [SERVICE_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [USAGE_UM] NVARCHAR(15) DEFAULT  NULL,
    [PLAN_TRANSIT_DAYS] smallint DEFAULT  NULL,
    [SCHEDULE_RANK] smallint DEFAULT  NULL,
    [RUN] DECIMAL(20,8) DEFAULT  NULL,
    [RUN_TYPE] NVARCHAR(15) DEFAULT  NULL,
    [LOAD_SIZE_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [MINIMUM_MOVE_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [LONG_DESCRIPTION] image DEFAULT  NULL,
    [INTRASTAT_INCLUDE] NCHAR(1) DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT  NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [BID_RATE_CATEGORY_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[SERVICE] ADD CONSTRAINT [PK_SERVICE] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[SERVICE] ADD CONSTRAINT [FKEY0077] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);
