CREATE TABLE [dbo].[UNP_MNT_ENGINEER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ALL_FLAG] NVARCHAR(1) DEFAULT  NULL,
    [KEY1_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [KEY2_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [KEY_TYPE] NVARCHAR(1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[UNP_MNT_ENGINEER] ADD CONSTRAINT [PK_UNP_MNT_ENG] PRIMARY KEY ([RESOURCE_ID], [KEY1_ID], [KEY2_ID], [KEY_TYPE]);

ALTER TABLE [dbo].[UNP_MNT_ENGINEER] ADD CONSTRAINT [FKEY9528] FOREIGN KEY ([RESOURCE_ID]) REFERENCES [dbo].[SHOP_RESOURCE]([ID]);
