CREATE TABLE [dbo].[RCR_GJ] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [TOTAL_DR_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [TOTAL_CR_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [POST_ALL_TRACKING] NCHAR(1) DEFAULT  NOT NULL,
    [POST_AS_NATIVE] NCHAR(1) DEFAULT  NOT NULL,
    [USER_EXCH_RATE] NCHAR(1) DEFAULT  NULL,
    [REVERSING] NCHAR(1) DEFAULT  NOT NULL,
    [AUTO_PROCESS] NCHAR(1) DEFAULT  NOT NULL,
    [TRIGGER_FREQ] NCHAR(1) DEFAULT  NOT NULL,
    [TRIGGER_DAY] smallint DEFAULT  NULL,
    [TRIGGER_MAX] smallint DEFAULT  NULL,
    [TRIGGER_COUNT] smallint DEFAULT  NULL,
    [TRIGGER_LAST_DATE] datetime DEFAULT  NULL,
    [GROUP_ID] NVARCHAR(15) DEFAULT  NULL,
    [LAST_EXECUTED_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[RCR_GJ] ADD CONSTRAINT [PK_RCR_GJ] PRIMARY KEY ([ID]);
