CREATE TABLE [dbo].[SUMMARY_CODE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SUMMARY_CODE] ADD CONSTRAINT [PK_SUMMARY_CODE] PRIMARY KEY ([CODE]);
