CREATE TABLE [dbo].[SHIPPER_LINK] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [BOL_ID] NVARCHAR(20) DEFAULT  NULL,
    [TARE_ID] NVARCHAR(30) DEFAULT  NULL,
    [PALLET_ID] NVARCHAR(30) DEFAULT  NULL,
    [CARTON_ID] NVARCHAR(30) DEFAULT  NULL,
    [CARTON_LINE_NO] smallint DEFAULT  NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [CUST_ORDER_LINE_NO] smallint DEFAULT  NULL,
    [CUST_ORDER_DEL_NO] smallint DEFAULT  NULL,
    [PACKLIST_ID] NVARCHAR(15) DEFAULT  NULL,
    [PACKLIST_LINE_NO] smallint DEFAULT  NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[SHIPPER_LINK] ADD CONSTRAINT [FK_SHIPPER_LINK_BOL] FOREIGN KEY ([BOL_ID]) REFERENCES [dbo].[BOL]([ID]);

ALTER TABLE [dbo].[SHIPPER_LINK] ADD CONSTRAINT [FKEY9571] FOREIGN KEY ([TARE_ID]) REFERENCES [dbo].[TARE]([ID]);

ALTER TABLE [dbo].[SHIPPER_LINK] ADD CONSTRAINT [FKEY9572] FOREIGN KEY ([PALLET_ID]) REFERENCES [dbo].[PALLET]([ID]);

ALTER TABLE [dbo].[SHIPPER_LINK] ADD CONSTRAINT [FKEY9573] FOREIGN KEY ([CARTON_ID], [CARTON_LINE_NO]) REFERENCES [dbo].[CARTON_LINE]([CARTON_ID], [LINE_NO]);

ALTER TABLE [dbo].[SHIPPER_LINK] ADD CONSTRAINT [FKEY9574] FOREIGN KEY ([CUST_ORDER_ID], [CUST_ORDER_LINE_NO]) REFERENCES [dbo].[CUST_ORDER_LINE]([CUST_ORDER_ID], [LINE_NO]);

ALTER TABLE [dbo].[SHIPPER_LINK] ADD CONSTRAINT [FKEY9575] FOREIGN KEY ([PACKLIST_ID], [PACKLIST_LINE_NO]) REFERENCES [dbo].[SHIPPER_LINE]([PACKLIST_ID], [LINE_NO]);
