CREATE TABLE [dbo].[LMC_MRP_BOM_LT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PARENT_PART_ID] VARCHAR(30) DEFAULT  NOT NULL,
    [CHILD_PART_ID] VARCHAR(30) DEFAULT  NOT NULL,
    [DIRECTION] CHAR(1) DEFAULT  NOT NULL,
    [DAYS_OFFSET] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[LMC_MRP_BOM_LT] ADD CONSTRAINT [PK_LMC_MRP_BOM_LT] PRIMARY KEY ([PARENT_PART_ID], [CHILD_PART_ID]);
