CREATE TABLE [dbo].[RESOURCE_SCHED] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SCHEDULE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RESOURCE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[RESOURCE_SCHED] ADD CONSTRAINT [PK_RESOURCE_SCHED] PRIMARY KEY ([SCHEDULE_ID], [RESOURCE_ID]);

ALTER TABLE [dbo].[RESOURCE_SCHED] ADD CONSTRAINT [FKEY0130] FOREIGN KEY ([RESOURCE_ID]) REFERENCES [dbo].[SHOP_RESOURCE]([ID]);

ALTER TABLE [dbo].[RESOURCE_SCHED] ADD CONSTRAINT [FKEY0185] FOREIGN KEY ([SCHEDULE_ID]) REFERENCES [dbo].[SCHEDULE]([ID]);
