CREATE TABLE [dbo].[EQUIP_PART_PRICE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(10) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [PRICE] DECIMAL(22,8) DEFAULT  NULL,
    [DISCOUNT] DECIMAL(14,4) DEFAULT  NULL
)

ALTER TABLE [dbo].[EQUIP_PART_PRICE] ADD CONSTRAINT [PK_EQ_PART_PRICE] PRIMARY KEY ([ID], [PART_ID]);

ALTER TABLE [dbo].[EQUIP_PART_PRICE] ADD CONSTRAINT [FKEY9511] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);
