CREATE TABLE [dbo].[PROCESS_ACTIVITY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TYPE] NVARCHAR(1) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DOCUMENT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DOCUMENT_LINE_NO] smallint DEFAULT  NOT NULL,
    [PROCESS_TYPE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DOCUMENT_TYPE] NVARCHAR(20) DEFAULT  NULL,
    [SEQUENCE_NO] smallint DEFAULT  NULL,
    [STANDARD_DAYS] DECIMAL(14,2) DEFAULT ((0)) NOT NULL,
    [ACTUAL_DAYS] DECIMAL(14,2) DEFAULT ((0)) NOT NULL,
    [STANDARD_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [ACTUAL_COST] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [START_DATE] datetime DEFAULT  NULL,
    [END_DATE] datetime DEFAULT  NULL,
    [PERCENT_COMPLETE] DECIMAL(14,2) DEFAULT ((0)) NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NULL
)

ALTER TABLE [dbo].[PROCESS_ACTIVITY] ADD CONSTRAINT [PK_PROCESS_ACTIVITY] PRIMARY KEY ([TYPE], [SITE_ID], [ID], [DOCUMENT_ID], [DOCUMENT_LINE_NO]);
