CREATE TABLE [dbo].[PROFILES] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[PROFILES] ADD CONSTRAINT [PK_PROFILES] PRIMARY KEY ([ID]);
