CREATE TABLE [dbo].[PORT_OF_ARRIVAL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(25) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL
)

ALTER TABLE [dbo].[PORT_OF_ARRIVAL] ADD CONSTRAINT [PK_PORT_OF_ARRIVAL] PRIMARY KEY ([CODE]);
