CREATE TABLE [dbo].[REPORT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [TITLE] NVARCHAR(80) DEFAULT  NULL,
    [GROUP_NAME] NVARCHAR(15) DEFAULT  NULL,
    [REPORT_FILE_NAME] NVARCHAR(8) DEFAULT  NULL,
    [COLUMN_COUNT] smallint DEFAULT  NOT NULL,
    [DIVISOR] DECIMAL(8,0) DEFAULT  NOT NULL,
    [DIVISOR_DESCR] NVARCHAR(40) DEFAULT  NULL,
    [SEND_BUDGETS] NCHAR(1) DEFAULT  NOT NULL,
    [CALENDAR_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [CALENDAR_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[REPORT] ADD CONSTRAINT [PK_REPORT] PRIMARY KEY ([ID]);
