CREATE TABLE [dbo].[VR_DATA_SRC_DRILLTO_PARAM] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DATA_SOURCE_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [DATA_SOURCE_COLUMN_NAME] NVARCHAR(80) DEFAULT  NOT NULL,
    [SEQUENCE_NO] int DEFAULT  NOT NULL,
    [PARAMETER_TYPE] NCHAR(1) DEFAULT ('C') NOT NULL,
    [PARAMETER_VALUE] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[VR_DATA_SRC_DRILLTO_PARAM] ADD CONSTRAINT [PK_VR_DATA_SRC_DRILLTO_PARAM] PRIMARY KEY ([DATA_SOURCE_ID], [DATA_SOURCE_COLUMN_NAME], [SEQUENCE_NO]);

ALTER TABLE [dbo].[VR_DATA_SRC_DRILLTO_PARAM] ADD CONSTRAINT [FK_VR_DRILLTO_TO_DS_COL] FOREIGN KEY ([DATA_SOURCE_ID], [DATA_SOURCE_COLUMN_NAME]) REFERENCES [dbo].[VR_DATA_SOURCE_COLUMN]([DATA_SOURCE_ID], [NAME]);
