CREATE TABLE [dbo].[MASTER_PROD_SCHED] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NOT NULL,
    [RANK] smallint DEFAULT  NULL
)

ALTER TABLE [dbo].[MASTER_PROD_SCHED] ADD CONSTRAINT [PK_MSTR_PROD_SCHD] PRIMARY KEY ([ID]);
