CREATE TABLE [dbo].[SLS_TAX_GRP_TAX] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SALES_TAX_GROUP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SALES_TAX_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SLS_TAX_GRP_TAX] ADD CONSTRAINT [PK_SLS_TAX_GRP_TAX] PRIMARY KEY ([SALES_TAX_GROUP_ID], [SALES_TAX_ID]);

ALTER TABLE [dbo].[SLS_TAX_GRP_TAX] ADD CONSTRAINT [FKEY0041] FOREIGN KEY ([SALES_TAX_GROUP_ID]) REFERENCES [dbo].[SALES_TAX_GROUP]([ID]);

ALTER TABLE [dbo].[SLS_TAX_GRP_TAX] ADD CONSTRAINT [FKEY0046] FOREIGN KEY ([SALES_TAX_ID]) REFERENCES [dbo].[SALES_TAX]([ID]);
