CREATE TABLE [dbo].[AIC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[AIC] ADD CONSTRAINT [PK_AIC] PRIMARY KEY ([CODE]);
