CREATE TABLE [dbo].[PHYS_COUNT_TAG] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PHYS_COUNT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TAG_NO] int DEFAULT  NOT NULL,
    [GROUP_NO] int DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [LOCATION_ID] NVARCHAR(15) DEFAULT  NULL,
    [COUNT_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [COUNT_USER_ID] NVARCHAR(20) DEFAULT  NULL,
    [RECOUNT_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [RECOUNT_USER_ID] NVARCHAR(20) DEFAULT  NULL,
    [COUNT_DATE] datetime DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [TRACE_ID] NVARCHAR(30) DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [WBS_CODE] NVARCHAR(30) DEFAULT  NULL,
    [PROJ_REF_SEQ_NO] smallint DEFAULT  NULL,
    [PROJ_REF_SUB_ID] NVARCHAR(3) DEFAULT  NULL,
    [DEPARTMENT_ID] NVARCHAR(15) DEFAULT  NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [ADJUST_QTY] DECIMAL(20,8) DEFAULT  NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[PHYS_COUNT_TAG] ADD CONSTRAINT [PK_PHYS_COUNT_TAG] PRIMARY KEY ([PHYS_COUNT_ID], [TAG_NO]);

ALTER TABLE [dbo].[PHYS_COUNT_TAG] ADD CONSTRAINT [FKEY0103] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);

ALTER TABLE [dbo].[PHYS_COUNT_TAG] ADD CONSTRAINT [FKEY0118] FOREIGN KEY ([WAREHOUSE_ID]) REFERENCES [dbo].[WAREHOUSE]([ID]);

ALTER TABLE [dbo].[PHYS_COUNT_TAG] ADD CONSTRAINT [FKEY0176] FOREIGN KEY ([PHYS_COUNT_ID]) REFERENCES [dbo].[PHYSICAL_COUNT]([ID]);
