CREATE TABLE [dbo].[TC_PROJECT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TC_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PROJECT_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[TC_PROJECT] ADD CONSTRAINT [PK_TC_PROJECT] PRIMARY KEY ([TC_ID], [PROJECT_ID]);
