CREATE TABLE [dbo].[CONTACT_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CONTACT_ID] NVARCHAR(25) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CONTACT_BINARY] ADD CONSTRAINT [PK_CONTACT_BINARY] PRIMARY KEY ([CONTACT_ID], [TYPE]);

ALTER TABLE [dbo].[CONTACT_BINARY] ADD CONSTRAINT [FKEYCONT_BIN_CONT] FOREIGN KEY ([CONTACT_ID]) REFERENCES [dbo].[CONTACT]([ID]);
