CREATE TABLE [dbo].[CARRIER] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [NAME] NVARCHAR(50) DEFAULT  NULL,
    [SHIPPER_ID] NVARCHAR(15) DEFAULT  NULL,
    [ROUTE] NVARCHAR(50) DEFAULT  NULL,
    [SHIPPER_INSTRUCT] NVARCHAR(250) DEFAULT  NULL,
    [COD_CHARGE] DECIMAL(23,8) DEFAULT  NULL,
    [ADDR_1] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_2] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_3] NVARCHAR(50) DEFAULT  NULL,
    [CITY] NVARCHAR(30) DEFAULT  NULL,
    [STATE] NVARCHAR(10) DEFAULT  NULL,
    [ZIPCODE] NVARCHAR(10) DEFAULT  NULL,
    [COUNTRY] NVARCHAR(50) DEFAULT  NULL,
    [CARRIER_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [VAT_REGISTRATION] NVARCHAR(25) DEFAULT  NULL,
    [PARCEL_ID] NVARCHAR(80) DEFAULT  NULL,
    [WEB_URL] NVARCHAR(255) DEFAULT  NULL
)

ALTER TABLE [dbo].[CARRIER] ADD CONSTRAINT [PK_CARRIER] PRIMARY KEY ([ID]);
