CREATE TABLE [dbo].[RMA_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RMA_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [ORG_ORDER_LINE_NO] smallint DEFAULT  NULL,
    [NEW_ORDER_LINE_NO] smallint DEFAULT  NULL,
    [QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [RECEIVED_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [SHIPPED_QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL,
    [PIECE_COUNT] DECIMAL(20,8) DEFAULT  NULL,
    [PIECES_RECEIVED] DECIMAL(20,8) DEFAULT  NULL,
    [PIECES_SHIPPED] DECIMAL(20,8) DEFAULT  NULL,
    [LENGTH] DECIMAL(14,4) DEFAULT  NULL,
    [WIDTH] DECIMAL(14,4) DEFAULT  NULL,
    [HEIGHT] DECIMAL(14,4) DEFAULT  NULL,
    [DIMENSIONS_UM] NVARCHAR(15) DEFAULT  NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NULL,
    [LINE_STATUS] NCHAR(1) DEFAULT ('A') NOT NULL,
    [QUOTE_LINE_NO] smallint DEFAULT  NULL,
    [UDF_LAYOUT_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_1] NVARCHAR(80) DEFAULT  NULL,
    [USER_2] NVARCHAR(80) DEFAULT  NULL,
    [USER_3] NVARCHAR(80) DEFAULT  NULL,
    [USER_4] NVARCHAR(80) DEFAULT  NULL,
    [USER_5] NVARCHAR(80) DEFAULT  NULL,
    [USER_6] NVARCHAR(80) DEFAULT  NULL,
    [USER_7] NVARCHAR(80) DEFAULT  NULL,
    [USER_8] NVARCHAR(80) DEFAULT  NULL,
    [USER_9] NVARCHAR(80) DEFAULT  NULL,
    [USER_10] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[RMA_LINE] ADD CONSTRAINT [PK_RMA_LINE] PRIMARY KEY ([RMA_ID], [LINE_NO]);

ALTER TABLE [dbo].[RMA_LINE] ADD CONSTRAINT [FKEY9379] FOREIGN KEY ([RMA_ID]) REFERENCES [dbo].[RMA]([ID]);
