CREATE TABLE [dbo].[PROGRAM_NAME] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [MENU_ID] NVARCHAR(40) DEFAULT  NOT NULL,
    [SEQ_NO] int DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(40) DEFAULT  NOT NULL,
    [SUB_HEADING] NCHAR(1) DEFAULT  NULL,
    [MENU_TEXT] NVARCHAR(80) DEFAULT  NULL,
    [TOOLTIP] NVARCHAR(40) DEFAULT  NULL,
    [HIDE_ENTRY] NCHAR(1) DEFAULT  NULL,
    [EXECUTE_COMMAND] NVARCHAR(250) DEFAULT  NULL,
    [ICON] NVARCHAR(40) DEFAULT  NULL
)

ALTER TABLE [dbo].[PROGRAM_NAME] ADD CONSTRAINT [PK_PROGRAM_NAME] PRIMARY KEY ([USER_ID], [MENU_ID], [SEQ_NO], [PROGRAM_ID]);
