CREATE TABLE [dbo].[TERRITORY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[TERRITORY] ADD CONSTRAINT [PK_TERRITORY] PRIMARY KEY ([CODE]);
