CREATE TABLE [dbo].[TEST_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TEST_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[TEST_BINARY] ADD CONSTRAINT [PK_TEST_BINARY] PRIMARY KEY ([TEST_ID], [TYPE]);

ALTER TABLE [dbo].[TEST_BINARY] ADD CONSTRAINT [FKEY0245] FOREIGN KEY ([TEST_ID]) REFERENCES [dbo].[TEST]([ID]);
