CREATE TABLE [dbo].[PURC_ORDER_RFQ] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PURC_ORD_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PURC_ORD_LINE_NO] smallint DEFAULT  NOT NULL,
    [PURC_RFQ_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PURC_RFQ_LINE_NO] smallint DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PURC_ORDER_RFQ] ADD CONSTRAINT [PK_PURC_ORDER_RFQ] PRIMARY KEY ([PURC_ORD_ID], [PURC_ORD_LINE_NO], [PURC_RFQ_ID], [PURC_RFQ_LINE_NO]);
