CREATE TABLE [dbo].[PACKAGE_TYPE_SYNC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EVENT_ID] int DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [PACKAGE_CODE] NVARCHAR(5) DEFAULT  NOT NULL,
    [EXCEPTION] NCHAR(1) DEFAULT  NOT NULL,
    [SUBSCRIPTIONS] int DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[PACKAGE_TYPE_SYNC] ADD CONSTRAINT [PK_PACKAGE_TYPE_SYNC] PRIMARY KEY ([EVENT_ID]);
