CREATE TABLE [dbo].[RECEIVABLE_INST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [INST_NO] smallint DEFAULT  NOT NULL,
    [DUE_DATE] datetime DEFAULT  NOT NULL,
    [TOTAL_AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [PAID_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [LAST_PAID_DATE] datetime DEFAULT  NULL,
    [ZERO_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[RECEIVABLE_INST] ADD CONSTRAINT [PK_RECEIVABLE_INST] PRIMARY KEY ([INVOICE_ID], [INST_NO]);

ALTER TABLE [dbo].[RECEIVABLE_INST] ADD CONSTRAINT [FK_RECEIVABLE_INST_00] FOREIGN KEY ([INVOICE_ID]) REFERENCES [dbo].[RECEIVABLE]([INVOICE_ID]);
