CREATE TABLE [dbo].[PURC_CATEGORY_TYPE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[PURC_CATEGORY_TYPE] ADD CONSTRAINT [PK_PURC_CATEGORY_TYPE] PRIMARY KEY ([CODE]);
