CREATE TABLE [dbo].[PART_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[PART_BINARY] ADD CONSTRAINT [PK_PART_BINARY] PRIMARY KEY ([PART_ID], [TYPE]);

ALTER TABLE [dbo].[PART_BINARY] ADD CONSTRAINT [FKEY0090] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);
