CREATE TABLE [dbo].[TRANS_CATEGORY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[TRANS_CATEGORY] ADD CONSTRAINT [PK_TRANS_CATEGORY] PRIMARY KEY ([ID]);
