CREATE TABLE [dbo].[APPLICATION_LINK] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [GROUP_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [GROUP_SEQ_NO] smallint DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(80) DEFAULT  NOT NULL,
    [LANGUAGE_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [ACCELERATOR] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[APPLICATION_LINK] ADD CONSTRAINT [PK_APPLICATION_LINK] PRIMARY KEY ([GROUP_ID], [GROUP_SEQ_NO], [PROGRAM_ID], [LANGUAGE_ID]);

ALTER TABLE [dbo].[APPLICATION_LINK] ADD CONSTRAINT [FKEY0248] FOREIGN KEY ([GROUP_ID], [LANGUAGE_ID]) REFERENCES [dbo].[APPLICATION_GROUP]([GROUP_ID], [LANGUAGE_ID]);

ALTER TABLE [dbo].[APPLICATION_LINK] ADD CONSTRAINT [FKEY0249] FOREIGN KEY ([PROGRAM_ID], [LANGUAGE_ID]) REFERENCES [dbo].[APPLICATION]([PROGRAM_ID], [LANGUAGE_ID]);
