CREATE TABLE [dbo].[INV_PIECES] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [LENGTH] DECIMAL(14,4) DEFAULT  NOT NULL,
    [WIDTH] DECIMAL(14,4) DEFAULT  NOT NULL,
    [HEIGHT] DECIMAL(14,4) DEFAULT  NOT NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LOCATION_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DIMENSIONS_UM] NVARCHAR(15) DEFAULT  NOT NULL,
    [QTY] DECIMAL(20,8) DEFAULT ((0)) NOT NULL
)

ALTER TABLE [dbo].[INV_PIECES] ADD CONSTRAINT [PK_INV_PIECES] PRIMARY KEY ([PART_ID], [LENGTH], [WIDTH], [HEIGHT], [WAREHOUSE_ID], [LOCATION_ID], [DIMENSIONS_UM]);
