CREATE TABLE [dbo].[CUST_WIP_VAS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WIP_VAS_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [STATUS] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[CUST_WIP_VAS] ADD CONSTRAINT [PK_CUST_WIP_VAS] PRIMARY KEY ([CUSTOMER_ID], [PART_ID], [WIP_VAS_ID]);
