CREATE TABLE [dbo].[PURC_REQUISITION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_ID] NVARCHAR(25) DEFAULT  NULL,
    [CONTACT_FIRST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_LAST_NAME] NVARCHAR(30) DEFAULT  NULL,
    [CONTACT_INITIAL] NVARCHAR(2) DEFAULT  NULL,
    [CONTACT_POSITION] NVARCHAR(50) DEFAULT  NULL,
    [CONTACT_HONORIFIC] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_SALUTATION] NVARCHAR(60) DEFAULT  NULL,
    [CONTACT_PHONE] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_FAX] NVARCHAR(20) DEFAULT  NULL,
    [CONTACT_EMAIL] NVARCHAR(100) DEFAULT  NULL,
    [CONTACT_MOBILE] NVARCHAR(20) DEFAULT  NULL,
    [PURC_REQ_ADDR_NO] int DEFAULT  NULL,
    [SHIPTO_ADDR_NO] int DEFAULT  NULL,
    [REQUISITION_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [DESIRED_RECV_DATE] datetime DEFAULT  NULL,
    [BUYER] NVARCHAR(20) DEFAULT  NULL,
    [PREPARER] NVARCHAR(20) DEFAULT  NULL,
    [REQUESTOR] NVARCHAR(20) DEFAULT  NULL,
    [ASSIGNED_TO] NVARCHAR(20) DEFAULT  NULL,
    [APP1_DATE] datetime DEFAULT  NULL,
    [APP2_DATE] datetime DEFAULT  NULL,
    [APP3_DATE] datetime DEFAULT  NULL,
    [APP4_DATE] datetime DEFAULT  NULL,
    [FREE_ON_BOARD] NVARCHAR(25) DEFAULT  NULL,
    [SHIP_VIA] NVARCHAR(40) DEFAULT  NULL,
    [SALES_TAX_GROUP_ID] NVARCHAR(15) DEFAULT  NULL,
    [STATUS] NCHAR(1) DEFAULT ('') NOT NULL,
    [SELL_RATE] DECIMAL(15,8) DEFAULT  NOT NULL,
    [BUY_RATE] DECIMAL(15,8) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TOTAL_AMT_ORDERED] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [MARKED_FOR_PURGE] NCHAR(1) DEFAULT ('') NOT NULL,
    [EXCH_RATE_FIXED] NCHAR(1) DEFAULT ('') NOT NULL,
    [SHIPTO_ID] NVARCHAR(20) DEFAULT  NULL,
    [SHIPFROM_ID] NVARCHAR(20) DEFAULT  NULL,
    [CARRIER_ID] NVARCHAR(20) DEFAULT  NULL,
    [TERMS_NET_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [TERMS_NET_DAYS] smallint DEFAULT  NULL,
    [TERMS_NET_DATE] datetime DEFAULT  NULL,
    [TERMS_DISC_DAYS] smallint DEFAULT  NULL,
    [TERMS_DISC_DATE] datetime DEFAULT  NULL,
    [TERMS_DISC_PERCENT] DECIMAL(5,3) DEFAULT  NULL,
    [TERMS_DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [TERMS_DISC_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [CATEGORY_TYPE] NVARCHAR(15) DEFAULT  NULL,
    [UDF_LAYOUT_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_1] NVARCHAR(80) DEFAULT  NULL,
    [USER_2] NVARCHAR(80) DEFAULT  NULL,
    [USER_3] NVARCHAR(80) DEFAULT  NULL,
    [USER_4] NVARCHAR(80) DEFAULT  NULL,
    [USER_5] NVARCHAR(80) DEFAULT  NULL,
    [USER_6] NVARCHAR(80) DEFAULT  NULL,
    [USER_7] NVARCHAR(80) DEFAULT  NULL,
    [USER_8] NVARCHAR(80) DEFAULT  NULL,
    [USER_9] NVARCHAR(80) DEFAULT  NULL,
    [USER_10] NVARCHAR(80) DEFAULT  NULL,
    [STATUS_EFF_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [TERMS_ID] NVARCHAR(15) DEFAULT  NULL,
    [CONTACT_PHONE_EXT] NVARCHAR(10) DEFAULT  NULL,
    [TERMS_DISC_BASIS] NVARCHAR(32) DEFAULT  NULL
)

ALTER TABLE [dbo].[PURC_REQUISITION] ADD CONSTRAINT [PK_PURC_REQISITION] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[PURC_REQUISITION] ADD CONSTRAINT [FK_PUR_REQ_CONT_ID] FOREIGN KEY ([CONTACT_ID]) REFERENCES [dbo].[CONTACT]([ID]);

ALTER TABLE [dbo].[PURC_REQUISITION] ADD CONSTRAINT [FK_PURC_REQUISITION_00] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[PURC_REQUISITION] ADD CONSTRAINT [FK_PURC_REQUISITION_01] FOREIGN KEY ([SHIPTO_ADDR_NO]) REFERENCES [dbo].[SHIPTO_ADDRESS]([ADDR_NO]);

ALTER TABLE [dbo].[PURC_REQUISITION] ADD CONSTRAINT [FK_PURC_REQUISITION_02] FOREIGN KEY ([VENDOR_ID]) REFERENCES [dbo].[VENDOR]([ID]);

ALTER TABLE [dbo].[PURC_REQUISITION] ADD CONSTRAINT [FK_PURC_REQUISITION_03] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[PURC_REQUISITION] ADD CONSTRAINT [FKEY9630] FOREIGN KEY ([TERMS_ID]) REFERENCES [dbo].[TERMS]([ID]);
