CREATE TABLE [dbo].[DBR_STATUS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CCR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [STATUS_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [STATUS_DATE] datetime DEFAULT  NOT NULL,
    [NUM_OPEN_ITEMS] int DEFAULT  NOT NULL,
    [NUM_BUFFER_INTRS] int DEFAULT  NULL,
    [NUM_EMERG_ZONE_INT] int DEFAULT  NOT NULL,
    [NUM_YELLO_ZONE_INT] int DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)
