CREATE TABLE [dbo].[JOURNAL_DIM] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PROCESS_TYPE] NVARCHAR(5) DEFAULT  NOT NULL,
    [SOURCE_ID] NVARCHAR(40) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ENTRY_NO] int DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [ACCT_YEAR] DECIMAL(4,0) DEFAULT  NOT NULL,
    [ACCT_PERIOD] DECIMAL(2,0) DEFAULT  NOT NULL,
    [BATCH_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [DEBIT_AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [CREDIT_AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [DOCUMENT_DATE] datetime DEFAULT  NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [TRANSACTION_ID] int DEFAULT  NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [PACKLIST_ID] NVARCHAR(15) DEFAULT  NULL,
    [PACKLIST_LINE_NO] smallint DEFAULT  NULL,
    [RECEIVER_ID] NVARCHAR(15) DEFAULT  NULL,
    [RECEIVER_LINE_NO] smallint DEFAULT  NULL,
    [PRODUCT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [DEPARTMENT_ID] NVARCHAR(15) DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [COMMODITY_CODE] NVARCHAR(15) DEFAULT  NULL,
    [SALESREP_ID] NVARCHAR(15) DEFAULT  NULL,
    [BUYER] NVARCHAR(20) DEFAULT  NULL
)

ALTER TABLE [dbo].[JOURNAL_DIM] ADD CONSTRAINT [PK_JOURNAL_DIM] PRIMARY KEY ([PROCESS_TYPE], [SOURCE_ID], [CURRENCY_ID], [ENTRY_NO], [SITE_ID]);

ALTER TABLE [dbo].[JOURNAL_DIM] ADD CONSTRAINT [FK_JOURN_DIM_ACCT] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[JOURNAL_DIM] ADD CONSTRAINT [FK_JOURN_DIM_CURR] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[JOURNAL_DIM] ADD CONSTRAINT [FK_JOURN_DIM_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
