CREATE TABLE [dbo].[GL_INTERFACE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL
)

ALTER TABLE [dbo].[GL_INTERFACE] ADD CONSTRAINT [PK_GL_INTERFACE] PRIMARY KEY ([ID]);
