CREATE TABLE [dbo].[VENDOR_WEEK] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [VENDOR_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SERVICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [DAY_OF_WEEK] smallint DEFAULT  NOT NULL,
    [DAY_PERCENT] smallint DEFAULT  NOT NULL
)
