CREATE TABLE [dbo].[TIMING] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [PROGRAM_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [PROGRAM_VERSION] NVARCHAR(10) DEFAULT  NULL,
    [START_TIME] datetime DEFAULT  NOT NULL,
    [SCREEN_TIME] NVARCHAR(15) DEFAULT  NULL,
    [POPULATE_TIME] NVARCHAR(15) DEFAULT  NULL,
    [SAVE_TIME] NVARCHAR(15) DEFAULT  NULL,
    [DELETE_TIME] NVARCHAR(15) DEFAULT  NULL,
    [USER_TIME] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[TIMING] ADD CONSTRAINT [PK_TIMING] PRIMARY KEY ([USER_ID], [PROGRAM_ID]);
