CREATE TABLE [dbo].[ISSUE_REASON] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[ISSUE_REASON] ADD CONSTRAINT [PK_ISSUE_REASON] PRIMARY KEY ([ID]);
