CREATE TABLE [dbo].[NOTIFICATION_SENDER_EMAIL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DOC_TYPE] NVARCHAR(15) DEFAULT  NOT NULL,
    [EMAIL_TYPE] NVARCHAR(15) DEFAULT  NOT NULL,
    [SENDER_EMAIL] NVARCHAR(2000) DEFAULT  NULL,
    [SENDER_EMAIL_PASSWORD] NVARCHAR(20) DEFAULT  NULL
)

ALTER TABLE [dbo].[NOTIFICATION_SENDER_EMAIL] ADD CONSTRAINT [PK_NOTIFICATION_SENDER_EMAIL] PRIMARY KEY ([DOC_TYPE], [EMAIL_TYPE]);
