CREATE TABLE [dbo].[USER_DIMENSION_SETUP] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [DIMENSION] smallint DEFAULT  NOT NULL,
    [DIMENSION_LABEL] NVARCHAR(25) DEFAULT  NULL
)

ALTER TABLE [dbo].[USER_DIMENSION_SETUP] ADD CONSTRAINT [PK_USER_DIMENSN_LABEL] PRIMARY KEY ([DIMENSION]);
