CREATE TABLE [dbo].[PLANNING_CALENDAR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CALENDAR_NO] int DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [BEGIN_DATE] datetime DEFAULT  NULL,
    [PLANNING_SIZE] int DEFAULT  NULL,
    [PLANNING_HORIZON] int DEFAULT  NULL,
    [RANGE_1_COUNT] int DEFAULT  NULL,
    [RANGE_1_SIZE] int DEFAULT  NULL,
    [RANGE_2_COUNT] int DEFAULT  NULL,
    [RANGE_2_SIZE] int DEFAULT  NULL,
    [RANGE_3_COUNT] int DEFAULT  NULL,
    [RANGE_3_SIZE] int DEFAULT  NULL
)

ALTER TABLE [dbo].[PLANNING_CALENDAR] ADD CONSTRAINT [PK_PLANNING_CALENDAR] PRIMARY KEY ([CALENDAR_NO]);
