CREATE TABLE [dbo].[V_HISTORY_TYPE] (
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(50) DEFAULT  NULL,
    [LAST_MODIFIED] datetime DEFAULT  NOT NULL,
    [LAST_USER] NVARCHAR(20) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT  NOT NULL,
    [CREATOR] NVARCHAR(20) DEFAULT  NULL,
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[V_HISTORY_TYPE] ADD CONSTRAINT [X_V_HISTORY_TYPE_0] PRIMARY KEY ([ID]);
