CREATE TABLE [dbo].[UNP_MNT_REM_CODE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL
)

ALTER TABLE [dbo].[UNP_MNT_REM_CODE] ADD CONSTRAINT [PK_UNP_MNT_REM_CD] PRIMARY KEY ([ID], [TYPE_ID]);
