CREATE TABLE [dbo].[CUSTOMER_ENTITY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ENTITY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CREDIT_STATUS] NCHAR(1) DEFAULT ('A') NOT NULL,
    [CREDIT_LIMIT_CTL] NCHAR(1) DEFAULT ('O') NOT NULL,
    [CREDIT_LIMIT] DECIMAL(23,8) DEFAULT  NULL,
    [RECV_AGE_LIMIT] smallint DEFAULT  NULL,
    [TOTAL_OPEN_ORDERS] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [TOTAL_OPEN_RECV] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [OPEN_ORDER_COUNT] int DEFAULT ((0)) NOT NULL,
    [OPEN_RECV_COUNT] int DEFAULT ((0)) NOT NULL,
    [CT_BEST_LOWER_PCT] int DEFAULT  NULL,
    [CT_GOOD_LOWER_PCT] int DEFAULT  NULL,
    [PT_DAYS] int DEFAULT  NULL,
    [PT_BEST_LOWER_PCT] int DEFAULT  NULL,
    [PT_GOOD_LOWER_PCT] int DEFAULT  NULL,
    [OLDEST_INV_TYPE] NCHAR(1) DEFAULT  NULL,
    [TOTAL_OPEN_SHIPPED] DECIMAL(23,8) DEFAULT ((0)) NOT NULL,
    [OPEN_OLDEST_RECV] datetime DEFAULT  NULL,
    [SHIP_CREDIT_LIMIT_CTL] NCHAR(1) DEFAULT ('C') NOT NULL,
    [CREATED_BY] NVARCHAR(20) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [MODIFIED_BY] NVARCHAR(20) DEFAULT  NULL,
    [MODIFY_DATE] datetime DEFAULT  NULL
)

ALTER TABLE [dbo].[CUSTOMER_ENTITY] ADD CONSTRAINT [PK_CUSTOMER_ENTITY] PRIMARY KEY ([ENTITY_ID], [CUSTOMER_ID]);

ALTER TABLE [dbo].[CUSTOMER_ENTITY] ADD CONSTRAINT [FK_CUSTOMER_ENTITY_TO_CUSTOMER] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);

ALTER TABLE [dbo].[CUSTOMER_ENTITY] ADD CONSTRAINT [FK_CUSTOMER_ENTITY_TO_ENTITY] FOREIGN KEY ([ENTITY_ID]) REFERENCES [dbo].[ACCOUNTING_ENTITY]([ID]);
