CREATE TABLE [dbo].[VAT_BOOK] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CODE] NVARCHAR(5) DEFAULT  NOT NULL,
    [YEAR] int DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(40) DEFAULT  NULL,
    [AR_INVOICES] NCHAR(1) DEFAULT ('') NOT NULL,
    [AR_MEMOS] NCHAR(1) DEFAULT ('') NOT NULL,
    [AP_INVOICES] NCHAR(1) DEFAULT ('') NOT NULL,
    [AP_MEMOS] NCHAR(1) DEFAULT ('') NOT NULL,
    [REPORT_TYPE] NCHAR(2) DEFAULT ('') NOT NULL,
    [ALPHA_PREFIX] NVARCHAR(4) DEFAULT  NULL,
    [START_NUMBER] int DEFAULT  NULL,
    [NEXT_NUMBER] int DEFAULT  NULL,
    [ALPHA_SUFFIX] NVARCHAR(4) DEFAULT  NULL,
    [LEADING_ZEROS] NCHAR(1) DEFAULT ('') NOT NULL,
    [DECIMAL_PLACES] smallint DEFAULT  NULL,
    [CURR_POSTING_DATE] datetime DEFAULT  NULL,
    [ENTITY_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[VAT_BOOK] ADD CONSTRAINT [PK_VAT_BOOK] PRIMARY KEY ([CODE], [YEAR], [ENTITY_ID]);
