CREATE TABLE [dbo].[SELECT_OPT_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUST_ORDER_LINE_NO] int DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [SEQ_NO] int DEFAULT  NOT NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL
)

ALTER TABLE [dbo].[SELECT_OPT_BINARY] ADD CONSTRAINT [PK_SELECT_OPT_BINARY] PRIMARY KEY ([CUST_ORDER_ID], [CUST_ORDER_LINE_NO], [TYPE], [SEQ_NO]);
