CREATE TABLE [dbo].[IBT_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [IBT_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[IBT_BINARY] ADD CONSTRAINT [PK_IBT_BINARY] PRIMARY KEY ([IBT_ID], [TYPE]);
