CREATE TABLE [dbo].[RCR_RECEIVABLE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [TOTAL_AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [TERMS_NET_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [TERMS_NET_DAYS] smallint DEFAULT  NULL,
    [TERMS_NET_DATE] datetime DEFAULT  NULL,
    [TERMS_DISC_TYPE] NCHAR(1) DEFAULT ('') NOT NULL,
    [TERMS_DISC_DAYS] smallint DEFAULT  NULL,
    [TERMS_DISC_DATE] datetime DEFAULT  NULL,
    [TERMS_DISC_PERCENT] DECIMAL(5,3) DEFAULT  NULL,
    [TERMS_DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RECV_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [TRIGGER_FREQ] NCHAR(1) DEFAULT ('') NOT NULL,
    [TRIGGER_DAY] smallint DEFAULT  NULL,
    [TRIGGER_COUNT] smallint DEFAULT  NULL,
    [TRIGGER_MAX] smallint DEFAULT  NULL,
    [TRIGGER_LAST_DATE] datetime DEFAULT  NULL,
    [GROUP_ID] NVARCHAR(15) DEFAULT  NULL,
    [VAT_BOOK_CODE] NVARCHAR(5) DEFAULT  NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [SALESREP_ID] NVARCHAR(15) DEFAULT  NULL,
    [TERMS_ID] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [TERMS_DISC_BASIS] NVARCHAR(32) DEFAULT  NULL
)

ALTER TABLE [dbo].[RCR_RECEIVABLE] ADD CONSTRAINT [PK_RCR_RECEIVABLE] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[RCR_RECEIVABLE] ADD CONSTRAINT [FKEY9366] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[RCR_RECEIVABLE] ADD CONSTRAINT [FKEY9367] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);

ALTER TABLE [dbo].[RCR_RECEIVABLE] ADD CONSTRAINT [FKEY9369] FOREIGN KEY ([RECV_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[RCR_RECEIVABLE] ADD CONSTRAINT [FKEY9587] FOREIGN KEY ([SALESREP_ID]) REFERENCES [dbo].[SALES_REP]([ID]);

ALTER TABLE [dbo].[RCR_RECEIVABLE] ADD CONSTRAINT [FKEY9627] FOREIGN KEY ([TERMS_ID]) REFERENCES [dbo].[TERMS]([ID]);
