CREATE TABLE [dbo].[REFERENCE_DESIGNATOR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [OPERATION_SEQ_NO] smallint DEFAULT  NOT NULL,
    [PIECE_NO] smallint DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [X_COORDINATE] NVARCHAR(15) DEFAULT  NULL,
    [Y_COORDINATE] NVARCHAR(15) DEFAULT  NULL,
    [DESCRIPTION] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[REFERENCE_DESIGNATOR] ADD CONSTRAINT [PK_REFERENCE_DESIGNATOR] PRIMARY KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO], [PIECE_NO], [ID]);
