CREATE TABLE [dbo].[SHIPPER_INVOICE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [PACKLIST_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NULL,
    [INVOICED_DATE] datetime DEFAULT  NULL,
    [INVOICE_CANDIDATE] NCHAR(1) DEFAULT ('N') NOT NULL,
    [DOC_FILE_PATH] NVARCHAR(255) DEFAULT  NULL,
    [DOCUMENT_ID] NVARCHAR(128) DEFAULT  NULL,
    [DISTRIBUTED_DATE] datetime DEFAULT  NULL,
    [DOC_TOTAL_AMOUNT] DECIMAL(23,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[SHIPPER_INVOICE] ADD CONSTRAINT [PK_SHIPPER_INVOICE] PRIMARY KEY ([PACKLIST_ID], [SITE_ID]);
