CREATE TABLE [dbo].[CUST_ADDRESS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ADDR_NO] int DEFAULT  NOT NULL,
    [NAME] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_1] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_2] NVARCHAR(50) DEFAULT  NULL,
    [ADDR_3] NVARCHAR(50) DEFAULT  NULL,
    [CITY] NVARCHAR(30) DEFAULT  NULL,
    [STATE] NVARCHAR(10) DEFAULT  NULL,
    [ZIPCODE] NVARCHAR(10) DEFAULT  NULL,
    [COUNTRY] NVARCHAR(50) DEFAULT  NULL,
    [CUST_ADDR_COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [DEF_SLS_TAX_GRP_ID] NVARCHAR(15) DEFAULT  NULL,
    [TAX_ID_NUMBER] NVARCHAR(25) DEFAULT  NULL,
    [TAX_EXEMPT] NCHAR(1) DEFAULT ('') NOT NULL,
    [SALESREP_ID] NVARCHAR(15) DEFAULT  NULL,
    [TERRITORY] NVARCHAR(15) DEFAULT  NULL,
    [SHIP_VIA] NVARCHAR(40) DEFAULT  NULL,
    [FREE_ON_BOARD] NVARCHAR(25) DEFAULT  NULL,
    [DISCOUNT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [ARRIVAL_CODE] NVARCHAR(25) DEFAULT  NULL,
    [TRANS_CODE] NVARCHAR(25) DEFAULT  NULL,
    [COUNTRY_ID] NVARCHAR(15) DEFAULT  NULL,
    [NATURE_OF_TRANS] int DEFAULT  NULL,
    [MODE_OF_TRANSPORT] int DEFAULT  NULL,
    [SIRET_NUMBER] DECIMAL(14,0) DEFAULT  NULL,
    [SHIPTO_ID] NVARCHAR(20) DEFAULT  NULL,
    [PRIORITY_CODE] NVARCHAR(15) DEFAULT  NULL,
    [FILL_RATE_TYPE] NCHAR(1) DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [COMPLIANCE_LABEL] NCHAR(1) DEFAULT  NULL,
    [CONSOLIDATE_ORDERS] NCHAR(1) DEFAULT  NULL,
    [VAT_REGISTRATION] NVARCHAR(25) DEFAULT  NULL,
    [DEF_LBL_FORMAT_ID] NVARCHAR(30) DEFAULT  NULL,
    [CARRIER_ID] NVARCHAR(15) DEFAULT  NULL,
    [ORDER_FILL_RATE] DECIMAL(5,2) DEFAULT ((0)) NOT NULL,
    [LANGUAGE_ID] NVARCHAR(2) DEFAULT  NULL,
    [USER_1] NVARCHAR(80) DEFAULT  NULL,
    [USER_2] NVARCHAR(80) DEFAULT  NULL,
    [USER_3] NVARCHAR(80) DEFAULT  NULL,
    [USER_4] NVARCHAR(80) DEFAULT  NULL,
    [USER_5] NVARCHAR(80) DEFAULT  NULL,
    [USER_6] NVARCHAR(80) DEFAULT  NULL,
    [USER_7] NVARCHAR(80) DEFAULT  NULL,
    [USER_8] NVARCHAR(80) DEFAULT  NULL,
    [USER_9] NVARCHAR(80) DEFAULT  NULL,
    [USER_10] NVARCHAR(80) DEFAULT  NULL,
    [UDF_LAYOUT_ID] NVARCHAR(80) DEFAULT  NULL,
    [GENERATE_ASN] NVARCHAR(1) DEFAULT  NULL,
    [HOLD_TRANSFER_ASN] NVARCHAR(1) DEFAULT  NULL,
    [CUSTOMS_DOC_PRINT] NVARCHAR(1) DEFAULT  NULL,
    [SUPPRESS_AR_PRINT] NVARCHAR(1) DEFAULT  NULL,
    [ACCEPT_830] NVARCHAR(1) DEFAULT  NULL,
    [ACCEPT_862] NVARCHAR(1) DEFAULT  NULL,
    [POOL_POINT_ID] NVARCHAR(20) DEFAULT  NULL,
    [POOL_CODE] NVARCHAR(20) DEFAULT  NULL,
    [SUPPLIER_ID] NVARCHAR(20) DEFAULT  NULL,
    [DOCK_CODE_FIELD] NVARCHAR(20) DEFAULT  NULL,
    [DUTY_BROKERAGE] NVARCHAR(20) DEFAULT  NULL,
    [MATERIAL_ISSUER] NVARCHAR(20) DEFAULT  NULL,
    [TRANS_METHOD_CODE] NVARCHAR(20) DEFAULT  NULL,
    [EQUIPMENT_DESCR] NVARCHAR(20) DEFAULT  NULL,
    [LADING_CODE] NVARCHAR(20) DEFAULT  NULL,
    [MODEL_YEAR] NVARCHAR(20) DEFAULT  NULL,
    [HANDLING_ID] NVARCHAR(20) DEFAULT  NULL,
    [ALLOW_CHARGE_NO] NVARCHAR(20) DEFAULT  NULL,
    [NON_RETURN_CODE] NVARCHAR(20) DEFAULT  NULL,
    [MIXED_CODE] NVARCHAR(20) DEFAULT  NULL,
    [TRADING_PARTNER] NVARCHAR(20) DEFAULT  NULL,
    [TRANSIT_TIME] DECIMAL(14,4) DEFAULT  NULL,
    [INTER_CONSIGNEE] NVARCHAR(20) DEFAULT  NULL,
    [CONSOL_SHIP_LINE] NCHAR(1) DEFAULT  NULL,
    [VAT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [VAT_OVERRIDE_SEQ] NVARCHAR(1) DEFAULT  NULL,
    [PALLET_DETAILS_REQ] NCHAR(1) DEFAULT  NULL,
    [MATCH_INV_TO_PACK] NCHAR(1) DEFAULT  NULL,
    [GENERATE_WSA] NCHAR(1) DEFAULT  NULL,
    [HOLD_TRANSFER_WSA] NCHAR(1) DEFAULT  NULL,
    [PRICE_GROUP] NVARCHAR(15) DEFAULT  NULL,
    [ACTIVE_FLAG] NCHAR(1) DEFAULT ('Y') NOT NULL,
    [DISPLAY_SEQ_NO] DECIMAL(7,3) DEFAULT ((9999)) NULL,
    [VAT_EXEMPT] NCHAR(1) DEFAULT ('N') NOT NULL
)

ALTER TABLE [dbo].[CUST_ADDRESS] ADD CONSTRAINT [PK_CUST_ADDRESS] PRIMARY KEY ([CUSTOMER_ID], [ADDR_NO]);

ALTER TABLE [dbo].[CUST_ADDRESS] ADD CONSTRAINT [FK_CUST_ADDR_CNTRY] FOREIGN KEY ([COUNTRY_ID]) REFERENCES [dbo].[COUNTRY]([ID]);

ALTER TABLE [dbo].[CUST_ADDRESS] ADD CONSTRAINT [FKEY0043] FOREIGN KEY ([DEF_SLS_TAX_GRP_ID]) REFERENCES [dbo].[SALES_TAX_GROUP]([ID]);

ALTER TABLE [dbo].[CUST_ADDRESS] ADD CONSTRAINT [FKEY0062] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);

ALTER TABLE [dbo].[CUST_ADDRESS] ADD CONSTRAINT [FKEY0070] FOREIGN KEY ([DISCOUNT_CODE]) REFERENCES [dbo].[CUSTOMER_DISCOUNT]([DISCOUNT_CODE]);

ALTER TABLE [dbo].[CUST_ADDRESS] ADD CONSTRAINT [FKEY0259] FOREIGN KEY ([SALESREP_ID]) REFERENCES [dbo].[SALES_REP]([ID]);

ALTER TABLE [dbo].[CUST_ADDRESS] ADD CONSTRAINT [FKEY9311] FOREIGN KEY ([ARRIVAL_CODE]) REFERENCES [dbo].[PORT_OF_ARRIVAL]([CODE]);

ALTER TABLE [dbo].[CUST_ADDRESS] ADD CONSTRAINT [FKEY9312] FOREIGN KEY ([TRANS_CODE]) REFERENCES [dbo].[PORT_OF_TRANS]([CODE]);

ALTER TABLE [dbo].[CUST_ADDRESS] ADD CONSTRAINT [FKEY9314] FOREIGN KEY ([NATURE_OF_TRANS]) REFERENCES [dbo].[NATURE_OF_TRANS]([CODE]);

ALTER TABLE [dbo].[CUST_ADDRESS] ADD CONSTRAINT [FKEY9315] FOREIGN KEY ([MODE_OF_TRANSPORT]) REFERENCES [dbo].[MODE_OF_TRANSPORT]([CODE]);

ALTER TABLE [dbo].[CUST_ADDRESS] ADD CONSTRAINT [FKEY9462] FOREIGN KEY ([DEF_LBL_FORMAT_ID]) REFERENCES [dbo].[LABEL_FORMAT]([ID]);
