CREATE TABLE [dbo].[SCHEDULE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(60) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT  NULL,
    [GLOBAL_START_DATE] datetime DEFAULT  NULL,
    [GLOBAL_END_DATE] datetime DEFAULT  NULL,
    [GLOBAL_COUNT] int DEFAULT  NULL,
    [SORT_START_DATE] datetime DEFAULT  NULL,
    [SORT_END_DATE] datetime DEFAULT  NULL,
    [SORT_COUNT] int DEFAULT  NULL,
    [OPERATIONS] int DEFAULT  NULL,
    [REQUIREMENTS] int DEFAULT  NULL,
    [WORK_ORDERS] int DEFAULT  NULL,
    [BOTTLENECK_ID] NVARCHAR(15) DEFAULT  NULL,
    [BOTTLENECK_DELAY] int DEFAULT  NULL,
    [DELAYED_OPERATIONS] int DEFAULT  NULL,
    [INFINITE_CAPACITY] NCHAR(1) DEFAULT ('') NOT NULL,
    [MATERIALS_CHECKED] NCHAR(1) DEFAULT ('') NOT NULL,
    [ACTIVE] NCHAR(1) DEFAULT ('') NOT NULL,
    [AS_OF_DATETIME] datetime DEFAULT  NULL,
    [SERVICES_CHECKED] NCHAR(1) DEFAULT ('') NOT NULL,
    [MASTER_SCHEDULE_ID] NVARCHAR(15) DEFAULT  NULL,
    [HARD_RELEASE_DATE] NCHAR(1) DEFAULT  NULL,
    [CCR_ID] NVARCHAR(15) DEFAULT  NULL,
    [IN_PROCESS] NCHAR(1) DEFAULT (N'N') NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [SCHEDULE_WHATIF_WO] NCHAR(1) DEFAULT ('N') NOT NULL,
    [PROBABILITY_THRESHOLD] smallint DEFAULT  NULL
)

ALTER TABLE [dbo].[SCHEDULE] ADD CONSTRAINT [PK_SCHEDULE] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[SCHEDULE] ADD CONSTRAINT [FK_SCHED_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);
