CREATE TABLE [dbo].[RATE_DETAIL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RATE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PERIOD_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [COST_CATEGORY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RATE] DECIMAL(15,8) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[RATE_DETAIL] ADD CONSTRAINT [PK_RATE_DETAIL] PRIMARY KEY ([RATE_ID], [SITE_ID], [PERIOD_ID], [COST_CATEGORY_ID]);

ALTER TABLE [dbo].[RATE_DETAIL] ADD CONSTRAINT [FK_RATE_DETAIL_00] FOREIGN KEY ([RATE_ID]) REFERENCES [dbo].[RATE]([ID]);

ALTER TABLE [dbo].[RATE_DETAIL] ADD CONSTRAINT [FK_RATE_DETAIL_01] FOREIGN KEY ([COST_CATEGORY_ID]) REFERENCES [dbo].[COST_CATEGORY]([ID]);
