CREATE TABLE [dbo].[ALLOCATION_DETAIL] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ALLOC_ID] NVARCHAR(5) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [NUM_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [NUM_SITE_ID] NVARCHAR(15) DEFAULT  NULL,
    [DIV_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [DIV_SITE_ID] NVARCHAR(15) DEFAULT  NULL,
    [PERCENT_1] DECIMAL(6,3) DEFAULT  NOT NULL,
    [PERCENT_2] DECIMAL(6,3) DEFAULT  NOT NULL,
    [ADDL_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [ADDL_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [DEBIT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [CREDIT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [TRANS_SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [CR_USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [CR_USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [CR_CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [CR_PRODUCT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [DR_USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [DR_USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [DR_CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NULL,
    [DR_PRODUCT_CODE] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[ALLOCATION_DETAIL] ADD CONSTRAINT [PK_ALLOCATION_DETAIL] PRIMARY KEY ([ALLOC_ID], [LINE_NO]);

ALTER TABLE [dbo].[ALLOCATION_DETAIL] ADD CONSTRAINT [FKEY0017] FOREIGN KEY ([NUM_SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[ALLOCATION_DETAIL] ADD CONSTRAINT [FKEY0018] FOREIGN KEY ([DIV_SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[ALLOCATION_DETAIL] ADD CONSTRAINT [FKEY0019] FOREIGN KEY ([TRANS_SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[ALLOCATION_DETAIL] ADD CONSTRAINT [FKEY0217] FOREIGN KEY ([ALLOC_ID]) REFERENCES [dbo].[ALLOCATION]([ID]);
