CREATE TABLE [dbo].[SHIPMENT_DIST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUST_ORDER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DIST_NO] smallint DEFAULT  NOT NULL,
    [ENTRY_NO] smallint DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [AMOUNT_TYPE] NCHAR(2) DEFAULT  NOT NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [POSTING_STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [BATCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [NATIVE] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[SHIPMENT_DIST] ADD CONSTRAINT [PK_SHIPMENT_DIST] PRIMARY KEY ([CUST_ORDER_ID], [DIST_NO], [ENTRY_NO], [CURRENCY_ID]);

ALTER TABLE [dbo].[SHIPMENT_DIST] ADD CONSTRAINT [FK_SHPDST_BATCH] FOREIGN KEY ([SITE_ID], [BATCH_ID]) REFERENCES [dbo].[JOURNAL_BATCH]([SITE_ID], [ID]);

ALTER TABLE [dbo].[SHIPMENT_DIST] ADD CONSTRAINT [FKEY0008] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[SHIPMENT_DIST] ADD CONSTRAINT [FKEY0153] FOREIGN KEY ([CUST_ORDER_ID]) REFERENCES [dbo].[CUSTOMER_ORDER]([ID]);

ALTER TABLE [dbo].[SHIPMENT_DIST] ADD CONSTRAINT [FKEY0196] FOREIGN KEY ([GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[SHIPMENT_DIST] ADD CONSTRAINT [FKEY9412] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
