CREATE TABLE [dbo].[LABEL_TYPE_VAR] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [LABEL_TYPE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [TABLE_LINKS] NVARCHAR(250) DEFAULT  NULL,
    [ID_ALIAS] NVARCHAR(10) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[LABEL_TYPE_VAR] ADD CONSTRAINT [PK_LABEL_TYPE_VAR] PRIMARY KEY ([ID], [LABEL_TYPE_ID], [ID_ALIAS]);

ALTER TABLE [dbo].[LABEL_TYPE_VAR] ADD CONSTRAINT [FKEY9458] FOREIGN KEY ([LABEL_TYPE_ID]) REFERENCES [dbo].[LABEL_TYPE]([ID]);
