CREATE TABLE [dbo].[SETUP_TYPE_ATTRIB] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SETUP_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [ATTRIBUTE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RANK] int DEFAULT  NULL,
    [SORT_KEY] NCHAR(1) DEFAULT  NOT NULL,
    [SORT_SEQUENCE] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[SETUP_TYPE_ATTRIB] ADD CONSTRAINT [PK_SETUP_TYPE_ATTRIB] PRIMARY KEY ([SETUP_ID], [ATTRIBUTE_ID]);
