CREATE TABLE [dbo].[RECV_LINE_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [INVOICE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [RECV_LINE_NO] smallint DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[RECV_LINE_BINARY] ADD CONSTRAINT [PK_RECV_LINE_BINARY] PRIMARY KEY ([INVOICE_ID], [RECV_LINE_NO], [TYPE]);

ALTER TABLE [dbo].[RECV_LINE_BINARY] ADD CONSTRAINT [FKEY0236] FOREIGN KEY ([INVOICE_ID], [RECV_LINE_NO]) REFERENCES [dbo].[RECEIVABLE_LINE]([INVOICE_ID], [LINE_NO]);
