CREATE TABLE [dbo].[SERIES_MODEL_PART] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [SERIES_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [MODEL_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [ENG_ID] NVARCHAR(3) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[SERIES_MODEL_PART] ADD CONSTRAINT [PK_SERIES_MODEL_PART] PRIMARY KEY ([SERIES_ID], [MODEL_ID], [SITE_ID]);

ALTER TABLE [dbo].[SERIES_MODEL_PART] ADD CONSTRAINT [FKEY0109] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);
