CREATE TABLE [dbo].[PROBLEM_CLASS] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL
)

ALTER TABLE [dbo].[PROBLEM_CLASS] ADD CONSTRAINT [PK_PROBLEM_CLASS] PRIMARY KEY ([ID]);
