CREATE TABLE [dbo].[UNITS_CONVERSION] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [FROM_UM] NVARCHAR(15) DEFAULT  NOT NULL,
    [TO_UM] NVARCHAR(15) DEFAULT  NOT NULL,
    [CONVERSION_FACTOR] DECIMAL(15,8) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[UNITS_CONVERSION] ADD CONSTRAINT [PK_UNITS_CONVERSION] PRIMARY KEY ([FROM_UM], [TO_UM]);

ALTER TABLE [dbo].[UNITS_CONVERSION] ADD CONSTRAINT [FKEY0030] FOREIGN KEY ([FROM_UM]) REFERENCES [dbo].[UNITS]([UNIT_OF_MEASURE]);
