CREATE TABLE [dbo].[SOA_DOC_SYNC] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EVENT_ID] int DEFAULT  NOT NULL,
    [PROC_TYPE] NVARCHAR(15) DEFAULT  NOT NULL,
    [TABLE_NAME] NVARCHAR(30) DEFAULT  NOT NULL,
    [KEY_VALUES] NVARCHAR(250) DEFAULT  NOT NULL,
    [ACTION_CODE] NVARCHAR(3) DEFAULT  NOT NULL,
    [STATUS] NVARCHAR(3) DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL
)

ALTER TABLE [dbo].[SOA_DOC_SYNC] ADD CONSTRAINT [PK_SOA_DOC_SYNC] PRIMARY KEY ([EVENT_ID]);
