CREATE TABLE [dbo].[INDIRECT_DIST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [TRANSACTION_ID] int DEFAULT  NOT NULL,
    [DIST_NO] smallint DEFAULT  NOT NULL,
    [ENTRY_NO] smallint DEFAULT  NOT NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [AMOUNT_TYPE] NCHAR(2) DEFAULT  NOT NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [POSTING_STATUS] NCHAR(1) DEFAULT  NOT NULL,
    [POSTING_DATE] datetime DEFAULT  NOT NULL,
    [BATCH_ID] NVARCHAR(15) DEFAULT  NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [CURRENCY_ID] NVARCHAR(15) DEFAULT ('') NOT NULL,
    [NATIVE] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[INDIRECT_DIST] ADD CONSTRAINT [PK_INDIRECT_DIST] PRIMARY KEY ([TRANSACTION_ID], [DIST_NO], [ENTRY_NO], [CURRENCY_ID]);

ALTER TABLE [dbo].[INDIRECT_DIST] ADD CONSTRAINT [FK_INDDST_BATCH] FOREIGN KEY ([SITE_ID], [BATCH_ID]) REFERENCES [dbo].[JOURNAL_BATCH]([SITE_ID], [ID]);

ALTER TABLE [dbo].[INDIRECT_DIST] ADD CONSTRAINT [FKEY0012] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[INDIRECT_DIST] ADD CONSTRAINT [FKEY0199] FOREIGN KEY ([GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[INDIRECT_DIST] ADD CONSTRAINT [FKEY9415] FOREIGN KEY ([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
