CREATE TABLE [dbo].[CUSTOMER_FORECAST] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [CUSTOMER_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [FORECAST_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [PART_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [REQUIRED_DATE] datetime DEFAULT  NOT NULL,
    [REQUIRED_QTY] DECIMAL(20,8) DEFAULT  NOT NULL,
    [CUSTOMER_PART_ID] NVARCHAR(30) DEFAULT  NULL,
    [CUSTOMER_PO_REF] NVARCHAR(40) DEFAULT  NULL,
    [USER_DATE] datetime DEFAULT  NULL,
    [WAREHOUSE_ID] NVARCHAR(15) DEFAULT  NULL,
    [SITE_ID] NVARCHAR(15) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[CUSTOMER_FORECAST] ADD CONSTRAINT [FK_CUST_FORECAST_TO_SITE] FOREIGN KEY ([SITE_ID]) REFERENCES [dbo].[SITE]([ID]);

ALTER TABLE [dbo].[CUSTOMER_FORECAST] ADD CONSTRAINT [FKEY9101] FOREIGN KEY ([PART_ID]) REFERENCES [dbo].[PART]([ID]);

ALTER TABLE [dbo].[CUSTOMER_FORECAST] ADD CONSTRAINT [FKEY9102] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER]([ID]);
