CREATE TABLE [dbo].[USER_MNU_AUTHORITY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [GROUP_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [LANGUAGE_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [PERMISSION] NCHAR(1) DEFAULT  NULL
)

ALTER TABLE [dbo].[USER_MNU_AUTHORITY] ADD CONSTRAINT [PK_USER_MNU_AUTHORITY] PRIMARY KEY ([USER_ID], [GROUP_ID], [LANGUAGE_ID]);
