CREATE TABLE [dbo].[RFQ_BINARY] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RFQ_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [BITS] image DEFAULT  NULL,
    [BITS_LENGTH] int DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[RFQ_BINARY] ADD CONSTRAINT [PK_RFQ_BINARY] PRIMARY KEY ([RFQ_ID], [TYPE]);

ALTER TABLE [dbo].[RFQ_BINARY] ADD CONSTRAINT [FKEY0250] FOREIGN KEY ([RFQ_ID]) REFERENCES [dbo].[REQUEST_FOR_QUOTE]([ID]);
