CREATE TABLE [dbo].[CURR_PRICE_INDEX] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [FROM_CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [TO_CURRENCY_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [EXCHANGE_RATE] DECIMAL(15,8) DEFAULT  NULL
)

ALTER TABLE [dbo].[CURR_PRICE_INDEX] ADD CONSTRAINT [PK_CURR_PRICE_INDEX] PRIMARY KEY ([FROM_CURRENCY_ID], [TO_CURRENCY_ID]);

ALTER TABLE [dbo].[CURR_PRICE_INDEX] ADD CONSTRAINT [FKEY9592] FOREIGN KEY ([FROM_CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);

ALTER TABLE [dbo].[CURR_PRICE_INDEX] ADD CONSTRAINT [FKEY9593] FOREIGN KEY ([TO_CURRENCY_ID]) REFERENCES [dbo].[CURRENCY]([ID]);
