CREATE TABLE [dbo].[RCR_RECV_LINE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [RCR_RECEIVABLE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [LINE_NO] smallint DEFAULT  NOT NULL,
    [REFERENCE] NVARCHAR(40) DEFAULT  NULL,
    [QTY] DECIMAL(20,8) DEFAULT  NULL,
    [AMOUNT] DECIMAL(23,8) DEFAULT  NOT NULL,
    [VAT_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [VAT_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [VAT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [COMM] DECIMAL(6,3) DEFAULT  NULL,
    [GL_ACCOUNT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [VAT_CODE] NVARCHAR(15) DEFAULT  NULL,
    [VAT_RCV_PERCENT] DECIMAL(6,3) DEFAULT  NULL,
    [VAT_RCV_AMOUNT] DECIMAL(23,8) DEFAULT  NULL,
    [VAT_RCV_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL,
    [vat_category] NVARCHAR(15) DEFAULT  NULL,
    [COMMISSION_PCT] DECIMAL(6,3) DEFAULT  NULL,
    [USER_DIMENSION_1] NVARCHAR(15) DEFAULT  NULL,
    [USER_DIMENSION_2] NVARCHAR(15) DEFAULT  NULL,
    [PRODUCT_CODE] NVARCHAR(15) DEFAULT  NULL
)

ALTER TABLE [dbo].[RCR_RECV_LINE] ADD CONSTRAINT [PK_RCR_RECV_LINE] PRIMARY KEY ([RCR_RECEIVABLE_ID], [LINE_NO]);

ALTER TABLE [dbo].[RCR_RECV_LINE] ADD CONSTRAINT [FKEY9368] FOREIGN KEY ([RCR_RECEIVABLE_ID]) REFERENCES [dbo].[RCR_RECEIVABLE]([ID]);

ALTER TABLE [dbo].[RCR_RECV_LINE] ADD CONSTRAINT [FKEY9370] FOREIGN KEY ([GL_ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[RCR_RECV_LINE] ADD CONSTRAINT [FKEY9581] FOREIGN KEY ([vat_category]) REFERENCES [dbo].[VAT_CATEGORY]([ID]);
