CREATE TABLE [dbo].[WORKORD_MILESTONE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [WORKORDER_TYPE] NCHAR(1) DEFAULT  NOT NULL,
    [WORKORDER_BASE_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [WORKORDER_LOT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SPLIT_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [WORKORDER_SUB_ID] NVARCHAR(3) DEFAULT  NOT NULL,
    [MILESTONE_ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [MAT_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [LAB_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [BUR_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [SER_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NOT NULL
)

ALTER TABLE [dbo].[WORKORD_MILESTONE] ADD CONSTRAINT [PK_WORKORD_MILESTONE] PRIMARY KEY ([WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [MILESTONE_ID]);

ALTER TABLE [dbo].[WORKORD_MILESTONE] ADD CONSTRAINT [FKEY9108] FOREIGN KEY ([MAT_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[WORKORD_MILESTONE] ADD CONSTRAINT [FKEY9109] FOREIGN KEY ([LAB_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[WORKORD_MILESTONE] ADD CONSTRAINT [FKEY9110] FOREIGN KEY ([BUR_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);

ALTER TABLE [dbo].[WORKORD_MILESTONE] ADD CONSTRAINT [FKEY9111] FOREIGN KEY ([SER_GL_ACCT_ID]) REFERENCES [dbo].[ACCOUNT]([ID]);
