CREATE TABLE [dbo].[ADJ_REASON] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(15) DEFAULT  NOT NULL,
    [DESCRIPTION] NVARCHAR(80) DEFAULT  NULL,
    [ADJ_GL_ACCT_ID] NVARCHAR(30) DEFAULT  NULL
)

ALTER TABLE [dbo].[ADJ_REASON] ADD CONSTRAINT [PK_ADJ_REASON] PRIMARY KEY ([ID]);
