CREATE TABLE [dbo].[TARE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [ID] NVARCHAR(30) DEFAULT  NOT NULL,
    [BOL_ID] NVARCHAR(20) DEFAULT  NULL
)

ALTER TABLE [dbo].[TARE] ADD CONSTRAINT [PK_TARE] PRIMARY KEY ([ID]);

ALTER TABLE [dbo].[TARE] ADD CONSTRAINT [FK_TARE_BOL] FOREIGN KEY ([BOL_ID]) REFERENCES [dbo].[BOL]([ID]);
