CREATE TABLE [dbo].[VMDI_TABLE] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [LAYOUT_KEY] NCHAR(3) DEFAULT  NOT NULL,
    [LAYOUT_VERSION] NCHAR(4) DEFAULT  NOT NULL,
    [LAYOUT_DIRECTION] NCHAR(1) DEFAULT  NOT NULL,
    [SEGMENT_TYPE] NCHAR(3) DEFAULT  NOT NULL,
    [TABLE_NAME] NVARCHAR(18) DEFAULT  NOT NULL,
    [JOIN] NVARCHAR(250) DEFAULT  NULL,
    [PRIMARY_KEY] NVARCHAR(250) DEFAULT  NULL
)

ALTER TABLE [dbo].[VMDI_TABLE] ADD CONSTRAINT [PK_VMDI_TABLE] PRIMARY KEY ([LAYOUT_KEY], [LAYOUT_VERSION], [LAYOUT_DIRECTION], [SEGMENT_TYPE], [TABLE_NAME]);

ALTER TABLE [dbo].[VMDI_TABLE] ADD CONSTRAINT [FKEY9103] FOREIGN KEY ([LAYOUT_KEY], [LAYOUT_VERSION], [LAYOUT_DIRECTION]) REFERENCES [dbo].[VMDI_LAYOUT]([KEY], [VERSION], [DIRECTION]);
