CREATE TABLE [dbo].[EVENT_DETECT] (
    [ROWID] int IDENTITY(1,1) DEFAULT  NOT NULL,
    [EVENT_ID] int DEFAULT  NOT NULL,
    [CREATE_DATE] datetime DEFAULT (getdate()) NOT NULL,
    [EVENT_TYPE] NCHAR(1) DEFAULT  NULL,
    [EVENT_BASE_ID] NVARCHAR(30) DEFAULT  NULL,
    [EVENT_LOT_ID] NVARCHAR(5) DEFAULT  NULL,
    [EVENT_SPLIT_ID] NVARCHAR(3) DEFAULT  NULL,
    [USER_ID] NVARCHAR(20) DEFAULT  NOT NULL,
    [STATUS] NCHAR(1) DEFAULT  NULL,
    [ERROR_MSG] NVARCHAR(250) DEFAULT  NULL
)
